export default {
  interactions: [{
    text: {
      en: 'Welcome to the best goods around! You aren’t going to find a better deal than what I have for you; however, I hear that there is a special shop with fantastic items unlike anything I’ve ever seen. In the meanwhile, I have some spare coins and spare goods. Would you like to sell anything?',
      da: 'Velkommen til de bedste varer i området! Du vil ikke finde en bedre handel end hvad jeg har for dig; men, jeg hører, at der er en speciel butik med fantastiske ting, ting som jeg ikke selv kunne forestille mig. I mellemtiden har jeg nogle ekstra mønter og ting til overs. Vil du sælge noget?',
      ru: 'Добро пожаловать! Тут вы найдете лучшие товары на этом миру! Хоть у меня и есть отличный товар, я слыхал о магазине с таинственными и мощными предметами, такие который я не когда не видел в своё жизни. Ну, а пока, у меня есть немного денег и немного товара, вы хотите что-то продать или купить?',
      sv: 'Välkommen till affären med de bästa grejerna i stan! Du kommer inte att hitta bättre erbjudanden! Dock så har jag hört talas om en specialaffär med helt fantastiska föremål, vars make aldrig skådats . Aja, jag har några mynt och föremål över. Vill du sälja någonting?',
      es: '¡Bienvenido a los mejores productos! No vas a encontrar una oferta mejor que la que tengo para ti; Sin embargo, escuché que hay una tienda especial con artículos fantásticos diferentes a todo lo que he visto. Mientras tanto, tengo algunas monedas de repuesto y productos de repuesto. ¿Te gustaría vender algo?',
      hi: 'चारों ओर सबसे अच्छा सामान के लिए आपका स्वागत है! मेरे पास आपके लिए जो कुछ भी है, उससे बेहतर सौदा खोजने के लिए आप नहीं जा रहे हैं; हालाँकि, मैं सुनता हूँ कि कुछ भी नहीं देखा है के विपरीत शानदार वस्तुओं के साथ एक विशेष दुकान है। इस बीच, मेरे पास कुछ अतिरिक्त सिक्के और अतिरिक्त सामान हैं। क्या आप कुछ भी बेचना चाहेंगे?',
      ko: '최고의 제품에 오신 것을 환영합니다! 당신은 내가 당신을 위해 가지고있는 것보다 나은 거래를 찾지 않을 것입니다. 그러나, 나는 이제까지 보았던 무엇이든지와 다른 훌륭한 항목과 함께 특별한 상점이 있다는 것을 들었다. 그 사이에, 나는 여분의 동전과 여분의 물건을 가지고있다. 아무것도 팔고 싶습니까?',
      ht: 'Byenveni nan pi bon machandiz yo alantou! Ou pa pral jwenn yon pi bon kontra pase sa mwen gen pou ou; sepandan, mwen tande ke gen yon magazen espesyal ak atik kokenn kontrèman ak nenpòt bagay mwen te janm wè. Pandan se tan a, mwen gen kèk pyès monnen ak pyès de rezèv. Èske ou ta renmen vann anyen?',
      cs: 'Vítejte u nejlepšího zboží v okolí! Nebudete najít lepší řešení než to, co mám pro vás; Slyšel jsem však, že existuje speciální obchod s fantastickými předměty na rozdíl od všeho, co jsem kdy viděl. Mezitím mám nějaké náhradní mince a náhradní zboží. Chcete něco prodat?',
      tl: 'Maligayang pagdating sa pinakamahusay na mga kalakal sa paligid! Hindi ka makakahanap ng isang mas mahusay na deal kaysa sa kung ano ang mayroon ako para sa iyo; Gayunpaman, naririnig ko na mayroong isang espesyal na tindahan na may hindi kapani-paniwala na mga bagay na hindi katulad ng anumang nakita ko kailanman. Samantala, mayroon akong mga ekstrang barya at ekstrang paninda. Nais mo bang magbenta ng anupaman?',
      ja: '周りの最高の商品へようこそ！あなたは私があなたのために持っているものより良い取引を見つけるつもりはありません。しかし、私が今まで見たことのないものとは違って、素晴らしいアイテムが並ぶ特別な店があると聞きます。その間に、予備のコインと予備の商品があります。何か販売しますか？',
      el: 'Καλώς ήρθατε στα καλύτερα αγαθά γύρω! Δεν πρόκειται να βρείτε μια καλύτερη συμφωνία από ό, τι έχω για σας. Ωστόσο, ακούω ότι υπάρχει ένα ειδικό κατάστημα με φανταστικά αντικείμενα σε αντίθεση με οτιδήποτε έχω δει ποτέ. Εν τω μεταξύ, έχω κάποια εφεδρικά νομίσματα και εφεδρικά αγα. θάΘα θέλατε να πουλήσετε τίποτα?',
      bg: 'Добре дошли в най-добрите стоки наоколо! Вие няма да намерите по-добра сделка от това, което имам за вас; обаче чувам, че има специален магазин с фантастични артикули, за разлика от всичко, което някога съм виждал. Междувременно имам резервни монети и резервни стоки. Обичате ли да продавате нещо?',
      de: 'Willkommen bei den besten Waren, die es gibt! Du wirst kein besseres Angebot finden als das, was ich für dich habe; aber ich höre, dass es einen speziellen Laden mit fantastischen Gegenständen gibt, wie ich sie noch nie gesehen habe. In der Zwischenzeit habe ich einige Ersatzmünzen und Ersatzwaren. Möchtest du etwas verkaufen?',
      fr: 'Bienvenue chez le commerçant avec les meilleurs produits du marché! Vous ne trouverez pas de meilleures offres que ce que j\'ai pour vous ; cependant, j\'ai entendu dire qu\'il y a un magasin spécial avec des articles fantastiques comme je n\'en ai jamais vu. En attendant, j\'ai des pièces et des biens de rechange. Voudriez-vous vendre quelque chose?',
      pt: 'Seja bem-vindo aos melhores produtos nas redondezas! Você não vai encontrar um negócio melhor do que o que eu tenho para você, no entanto, eu ouço que há uma loja especial com itens fantásticos ao contrário de qualquer coisa que eu já vi. Enquanto isso, eu tenho algumas moedas de sobra e bens de reposição. Quer vender alguma coisa?',
      nl: 'Welkom bij de beste goederen die er zijn! U zult geen betere deal vinden dan wat ik voor u heb, maar ik hoor dat er een speciale winkel is met fantastische artikelen die anders zijn dan wat ik ooit heb gezien. Intussen heb ik nog wat reserve munten en reserve goederen. Wilt u iets verkopen?',
      it: 'Benvenuti ai migliori prodotti in circolazione! Non troverete un\'offerta migliore di quella che ho per voi; tuttavia, ho sentito dire che c\'è un negozio speciale con articoli fantastici come non ho mai visto. Nel frattempo, ho delle monete e dei prodotti di ricambio. Volete vendere qualcosa',
      pl: 'Witamy w najlepszych towarach w okolicy! Nie znajdziesz lepszej oferty niż ta, którą dla ciebie mam, ale słyszę, że istnieje specjalny sklep z fantastycznymi przedmiotami, w przeciwieństwie do czegokolwiek, co kiedykolwiek widziałem. W międzyczasie mam zapasowe monety i zapasowe towary. Czy lubisz coś sprzedawać?',
      ro: 'Bine ai venit la cele mai bune obiecte din împrejurimi! Nu vei găsi o afacere mai bună decât ceea ce am eu pentru tine; cu toate acestea, am auzit că există un magazin special cu elemente fantastice, diferite de orice am văzut vreodată. Între timp, am niște monede și bunuri de rezervă. Îți place să vinzi ceva?',
      zh: '歡迎來到各地最好的商品！ 你不會找到比我給你更好的交易; 然而，我聽說有一個特別的商店，有很棒的物品，不像我見過的任何東西。 與此同時，我有一些備用硬幣和備用貨物。 你想要賣些什麼嗎？',
      hu: 'Üdvözlöm! Itt találja a legjobb árukat a környéken! Ennél jobb üzletet sehol máshol nem fog látni a világon, de úgy halottam, hogy létezik egy nagyon különleges bazár olyan tárgyakkal, amilyeneket én még soha életemben nem láttam. De addig is, nálam találsz némi pénzt és egy kevés tartalék árut. Szeretnél bármit is eladni?'
    },

    choices: [{
      en: 'Show me your wares.',
      ru: 'Покажи мне свои товары.',
      hu: 'Mutasd az áruidat',
      pt: 'Mostra-me os teus produtos.',
      fr: 'Montrez moi vos articles',
      nl: 'Laat mij uw waren zien'
    }]
  }],

  header: {
    en: 'Sell your items.',
    de: 'Verkaufen Sie Ihre Objekte.',
    sv: 'Sälj dina föremål.',
    it: 'Vendi i tuoi oggetti.',
    fr: 'Vendre vos objets.',
    ru: 'Продать свои вещи.',
    bg: 'Продайте предметите си.',
    cs: 'Prodávejte své zboží.',
    pl: 'Sprzedawaj swoje przedmioty.',
    es: 'Vende tus articulos.',
    hi: 'अपने आइटम बेचें',
    ko: '상품 판매',
    ht: 'Vann atik ou yo.',
    tl: 'Ibenta ang iyong mga item.',
    ja: 'あなたの商品を売る。',
    el: 'Πουλήστε τα στοιχεία σας.',
    pt: 'Venda os seus itens.',
    nl: 'Verkoop je waren.',
    da: 'Sælg dine varer.',
    ro: 'Vinde-ți obiectele.',
    zh: '賣出你的物品。',
    hu: 'Itt add el az árudat.'
  },

  info: {
    en: 'To sell an item, shift-right-click it or drag it into the trader window.',
    ru: 'Чтобы продать вещь, нажмите на него правой кнопкой мыши или перетащите в окно торговца.',
    bg: 'За да продадете вещ, щракнете с десния бутон върху него или го плъзнете в прозореца на търговеца.',
    cs: 'Chcete-li položku prodat, klikněte na ni pravým tlačítkem myši nebo ji přetáhněte do okna obchodníka.',
    pt: 'Para vender um item, clique direito ou arraste-o para a janela de negociação.',
    it: 'Per vendere un punto, clicca destro o trascinalo nella finestra del trader.',
    pl: 'Aby sprzedać przedmiot, kliknij go prawym przyciskiem myszy lub przeciągnij do okna inwestora.',
    es: 'Para vender un artículo, haga clic derecho o arrástrelo a la ventana del comerciante.',
    hi: 'किसी आइटम को बेचने के लिए, उसे राइट क्लिक करें या उसे ट्रेडर विंडो में खींचें।',
    ko: '항목을 판매하려면 항목을 마우스 오른쪽 단추로 클릭하거나 상인 창으로 끌어다 놓으십시오.',
    ht: 'Vann yon atik, klike sou li dwat oswa trennen l nan fenèt machann vann.',
    tl: 'Upang magbenta ng isang item, i-right click ito o i-drag ito sa window ng negosyante.',
    ja: 'アイテムを売るには、アイテムを右クリックするか、またはトレーダーウィンドウにドラッグします。',
    el: 'Για να πουλήσετε ένα στοιχείο, κάντε δεξί κλικ ή σύρετέ το στο παράθυρο του εμπόρου.',
    de: 'Um einen Gegenstand zu verkaufen, klicken Sie ihn mit der rechten Maustaste an oder ziehen Sie ihn in das Händlerfenster.',
    sv: 'För att sälja ett sak högerklickar du på det eller drar det i handelsfönstret.',
    fr: 'Pour vendre un objet, cliquez dessus avec le bouton droit de la souris ou faites-le glisser dans la fenêtre du commerçant.',
    nl: 'Om een artikel te verkopen, klik er met de rechtermuisknop op of sleep het naar het handelaarsvenster.',
    da: 'For at sælge et emne skal du højreklikke på det eller trække det i handlervinduet.',
    ro: 'Pentru a vinde un element, faceți clic-dreapta sau trageți-l în fereastra comerciantului.',
    zh: '要賣物品，在物品上按右鍵或把它拖入到交易窗口中。',
    tr: 'Bir eşyayı satmak için Shift\'e basılı tutarak eşyaya sağ tıklayın veya eşyayı takas penceresine sürükleyip bırakın.',
    hu: 'Hogy eladj egy tárgyat, shift + jobbkattints rá, vagy húzd ide a Trader ablakba.'
  },

  // Include punctuation and space.
  price: {
    en: 'Selling price: ',
    ru: 'Цена продажи: ',
    de: 'Verkaufspreis: ',
    fr: 'Prix de vente: ',
    bg: 'Продажна цена: ',
    cs: 'Prodejní cena: ',
    pl: 'Cena sprzedaży: ',
    es: 'Precio de venta: ',
    hi: 'विक्रय मूल्य: ',
    ko: '판매 가격: ',
    ht: 'Vann pri: ',
    tl: 'Pagbebenta ng presyo: ',
    ja: '販売価格： ',
    el: 'Τιμή πωλήσεως: ',
    sv: 'Säljande pris: ',
    pt: 'Preço de venda: ',
    nl: 'Verkoopprijs: ',
    ro: 'Prețul de vânzare: ',
    it: 'Prezzo di vendita: ',
    da: 'Salgspris: ',
    zh: '售價： ',
    tr: 'Satış ücreti: ',
    hu: 'Eladási ár: '
  },

  buy: {
    en: 'Are you interested in anything? Click an item to buy it.',
    de: 'Interessierst du dich für etwas? Klicken Sie auf einen Gegenstand, um ihn zu kaufen.',
    ru: 'Вам что-нибудь интересно? Кликните на предмет, чтобы купить его.',
    es: '¿Estás interesado en algo? Haga clic en un artículo para comprarlo.',
    fr: 'Quelque chose vous intéresse ? Cliquez sur un article pour l\'acheter.',
    pt: 'Estás interessado em alguma coisa? Clique num item para comprá-lo.',
    nl: 'Bent u in iets geïnteresseerd? Klik op een item om het te kopen.',
    it: 'Sei interessato a qualcosa? Clicca su un oggetto per comprarlo.',
    pl: 'Interesuje cię coś? Kliknij przedmiot, aby go kupić.',
    sv: 'Är du intresserad av något? Klicka på en sak för att köpa den.',
    ko: '관심이 있습니까? 항목을 클릭하여 구입하십시오.',
    hi: 'क्या आप किसी चीज में रुचि रखते हैं? इसे खरीदने के लिए किसी आइटम पर क्लिक करें।',
    ht: 'Èske w enterese nan anyen? Klike sou yon atik pou achte l.',
    tl: 'Interesado ka ba sa anumang bagay? Mag-click sa isang bagay upang bilhin ito.',
    cs: 'Zajímá vás něco? Kliknutím na předmět ji koupíte.',
    el: 'Ενδιαφέρεστε για οτιδήποτε; Κάντε κλικ σε ένα στοιχείο για να το αγοράσετε.',
    bg: 'Интересувате ли се от нещо? Кликнете върху бележка, за да го купите.',
    ja: '何か興味がありますか？購入するにはアイテムをクリックしてください。',
    da: 'Er du interesseret i noget? Klik på en genstand for at købe den.',
    zh: '有感興趣的東西嗎？点击商品即可購買。',
    tr: 'İlginizi çeken bir şeyler var mı? Bir eşyayı almak isterseniz üstüne tıklayın.',
    hu: 'Látsz valamit, amit érdekesnek találsz? Kattints egy tárgyra hogy megvásárold.'
  }
}
