export default {

  logout: {
    en: 'Log Out',
    el: 'Αποσύνδεση',
    ru: 'Выйти',
    bg: 'Изход',
    hi: 'बाहर आए',
    es: 'Cerrar Sesión',
    de: 'Abmelden',
    fr: 'Déconnexion',
    ko: '로그아웃',
    tr: 'Çıkış Yap',
    nl: 'Uitloggen',
    pt: 'Terminar Sessão',
    pl: 'Wyloguj się',
    ht: 'Dekonekte',
    ro: 'Deconectare',
    zh: '登出',
    hu: 'Kijelentkezés',
    bn: 'লগ আউট',
    vi: 'Đăng xuất',
    cs: 'Odhlásit se',
    sr: 'Одјави се',
    it: 'Disconnetti',
    ja: 'ログアウト'
  },

  home: {
    en: 'Home',
    el: 'Αρχική σελίδα',
    ru: 'Главная страница',
    bg: 'Главна страница',
    hi: 'मुख्य स्क्रीन',
    es: 'Inicio',
    de: 'Startseite',
    fr: 'Accueil',
    ko: '홈페이지',
    tr: 'Anasayfa',
    nl: 'Thuis',
    pt: 'Início',
    ro: 'Acasă',
    zh: '主頁',
    hu: 'Főoldal',
    pl: 'Start',
    bn: 'মূল স্ক্রীন',
    vi: 'Trang chủ',
    cs: 'Domů',
    sr: 'Почетна',
    it: 'Inizio',
    ja: 'ホーム'
  }
}
