export default {

  // Character selection

  select: {
    title: {
      en: 'Select Character',
      sv: 'Välj Karaktär',
      ru: 'Выберите Персонажа',
      fr: 'Sélectionnez le Héros',
      hi: 'स्वरूप चुने',
      es: 'Seleccione Carácter',
      de: 'Charakter Auswählen',
      ko: '캐릭터 선택',
      tr: 'Karakter Seç',
      bg: 'Изберете Герой',
      cs: 'Zvolte Hrdina',
      el: 'Επιλέξτε χαρακτήρας',
      ja: 'キャラクターを選択',
      tl: 'Piliin ang Character',
      it: 'Seleziona Carattere',
      pl: 'Wybierz Postać',
      nl: 'Selecteer Karakter',
      pt: 'Selecione um Personagem',
      ht: 'Chwazi Karaktè',
      ro: 'Selectează Caracterul',
      da: 'Vælg Tegn',
      zh: '選人物'
    },

    create: {
      en: 'Click to create character',
      sv: 'Klicka för att skapa karaktär',
      ru: 'Нажмите, чтобы создать персонажа',
      hi: 'स्वरूप बानाने के लिए क्लिक करे',
      es: 'Pulsar para crear un carácter',
      de: 'Klicke, um einen Charakter zu machen', // TODO: shorten
      fr: 'Cliquez pour créer le personnage',
      ko: '캐릭터를 만들려면 클릭하십시오',
      tr: 'Karakter yaratmak için tıkla',
      bg: 'Кликнете, за да създадете герой',
      cs: 'Kliknutím vytvoříte hrdina',
      el: 'Κάντε κλικ για να κάνετε χαρακτήρα',
      ja: 'クリックしてキャラクターを作成',
      tl: 'I-click upang lumikha ng character',
      it: 'Clicca per creare il personaggio',
      pl: 'Kliknij, aby utworzyć postać',
      nl: 'Klik om karakter te creëren',
      pt: 'Clique para criar um personagem',
      ht: 'Klike sou yo kreye karaktè',
      ro: 'Click pentru a crea un caracter',
      da: 'Klik for at vælge helt',
      zh: '點擊以創建角色'
    },

    enterWorld: {
      en: 'Enter World',
      sv: 'Ange Världen',
      ru: 'Войти в мир',
      fr: 'Entrer le Monde',
      hi: 'प्रवेश करे',
      es: 'Entrar en el Mundo',
      de: 'Tritt ein in die Welt',
      ko: '세계에 들어가기',
      tr: 'Dünyaya Gir',
      bg: 'Bлезте в света',
      cs: 'Vstupte do světa',
      el: 'Εισάγετε τον κόσμο',
      ja: '世界に入る',
      tl: 'Ipasok ang World',
      it: 'Entra nel Mondo',
      pl: 'Wejdź do świata',
      nl: 'Betreed de Wereld',
      pt: 'Entrar no Mundo',
      ht: 'Antre Lemonn',
      ro: 'Intră în Lume',
      da: 'Indtast Verden',
      zh: '進入世界'
    },

    emptySlot: {
      en: 'Empty',
      sv: 'Tom plats',
      ru: 'Пусто',
      hi: 'रिक्त',
      es: 'Vacío',
      de: 'Leer',
      fr: 'Vide',
      ko: '빈 슬롯',
      tr: 'Boş',
      bg: 'Празен',
      cs: 'Prázdný',
      el: 'Αδειάζω',
      ja: '空きスロット',
      tl: 'Wala',
      it: 'Slot vuoto',
      pl: 'Pusty',
      nl: 'Leeg',
      pt: 'Vazio',
      ht: 'Vide',
      ro: 'Gol',
      da: 'Tom',
      zh: '空的'
    },

    error: {
      en: 'Network Error',
      sv: 'Nätverksfel',
      ru: 'Проблема с Сетью',
      fr: 'Problème de Réseau',
      hi: 'नेट्वर्क में खराबी',
      es: 'Error de Red',
      de: 'Netzwerkfehler',
      ko: '네트워크 오류',
      tr: 'Ağ Hatası',
      bg: 'Мрежова Грешка',
      cs: 'Chyba Sítě',
      el: 'Σφάλμα δικτύου',
      ja: 'ネットワークエラー',
      tl: 'Error sa Network',
      it: 'Errore di Rete',
      pl: 'Błąd Sieci',
      nl: 'Netwerkfout',
      pt: 'Erro de Rede',
      ht: 'Rezo Erè',
      ro: 'Eroare de Rețea',
      da: 'Netværksfejl',
      zh: '網絡錯誤'
    }
  },

  // Character creation
  create: {
    title: {
      en: 'Character Creation',
      sv: 'Skapa Karaktär',
      ru: 'Создание Персонажа',
      fr: 'Création du Personnage',
      hi: 'स्वरूप निर्माण',
      es: 'Creación de Carácter',
      de: 'Charaktererstellung',
      ko: '캐릭터 생성',
      tr: 'Karakter Yaratma',
      bg: 'Създаване на Герой',
      cs: 'Tvorba Znaků',
      el: 'Δημιουργία χαρακτήρων',
      ja: 'キャラクター作成',
      tl: 'Paglikha ng Karakter',
      it: 'Creazione del Personaggio',
      pl: 'Tworzenie Postaci',
      nl: 'Karakter Creatie',
      pt: 'Criação de Personagens',
      ht: 'Kreyasyon Karaktè',
      ro: 'Creare de Personaje',
      da: 'Oprettelse af Helt',
      zh: '角色創造'
    },

    pressIcon: {
      en: 'Press an icon for a brief description.',
      sv: 'Tryck på en ikon för en kort beskrivning.',
      ru: 'Нажмите на иконку, чтобы увидеть краткое описание.',
      fr: 'Cliquez sur une icône pour une brève description',
      hi: 'संक्षिप्त विवरण के लिए तस्वीर पर क्लिक करे।',
      es: 'Pulse un icono para obtener una breve descripción.',
      de: 'Drücken Sie ein Symbol für eine Kurzbeschreibung.',
      ko: '간단한 설명을 보려면 아이콘을 누르십시오',
      tr: 'Kısa bir açıklama için bir ikona bas',
      bg: 'Натиснете икона за кратко описание',
      cs: 'Pro stručný popis stiskněte ikonu',
      el: 'Πατήστε ένα εικονίδιο για μια σύντομη περιγραφή',
      ja: 'アイコンを押すと簡単な説明が表示されます',
      tl: 'Pindutin ang isang icon para sa maikling paglalarawan',
      it: 'Premi unicona per una breve descrizione',
      pl: 'Naciśnij ikonę, aby uzyskać krótki opis',
      nl: 'Druk op een icoon voor een korte beschrijving.',
      pt: 'Pressione um ícone para uma breve descrição.',
      ht: 'Peze yon icon pou yon deskripsyon tou kout.',
      ro: 'Apăsați o pictogramă pentru o scurtă descriere.',
      da: 'Tryk på et ikon for en kort beskrivelse.',
      zh: '按圖標可獲得簡要說明。'
    },

    selectClass: {
      en: 'Select a Class',
      sv: 'Välj en Klass',
      ru: 'Выберите Класс',
      hi: 'श्रेणी चुने',
      es: 'Seleccione una Clase',
      de: 'Wählen Sie eine Klasse',
      fr: 'Sélectionnez une Classe',
      ko: '클래스 선택',
      tr: 'Bir sınıf Seç',
      bg: 'Изберете клас',
      cs: 'Vyberte Třídu',
      el: 'Επιλέξτε μια τάξη',
      ja: 'クラスを選択',
      tl: 'Pumili ng Klase',
      it: 'Seleziona una Classe',
      pl: 'Wybierz Klasę',
      nl: 'Selecteer een Klasse',
      pt: 'Selecione uma Classe',
      ht: 'Chwazi yon Klas',
      ro: 'Alegeți o Clasă',
      da: 'Vælg en Klasse',
      zh: '選擇角色職業'
    },

    selectFaction: {
      en: 'Select a Faction',
      sv: 'Välj en Fraktion',
      ru: 'Выберите фракцию',
      fr: 'Sélectionnez une Faction',
      hi: 'वंश चुने',
      es: 'Seleccione una Facción',
      de: 'Wählen Sie eine Fraktion aus',
      ko: '진영을 선택하십시오',
      tr: 'Bir Grup seç',
      bg: 'Изберете фракция',
      cs: 'Vyberte Frakci',
      el: 'Επιλέξτε μια παράταξη',
      ja: '派閥を選択',
      tl: 'Pumili ng isang pangkatin',
      it: 'Seleziona una Fazione',
      pl: 'Wybierz Frakcję',
      nl: 'Selecteer een Factie',
      pt: 'Selecione uma Facção',
      ht: 'Chwazi yon Faksyon',
      ro: 'Alegeți o Facțiune',
      da: 'Vælg en Fraktion',
      zh: '選擇派系'
    },

    enterName: {
      en: 'Enter a name',
      sv: 'Aige ett namn',
      ru: 'Введите имя',
      fr: 'Entrez un nom',
      hi: 'नाम डाले',
      es: 'Ingresa un nombre',
      de: 'Geben Sie einen Namen ein', // TODO: shorten
      ko: '이름 입력',
      tr: 'Bir isim gir',
      bg: 'Въведете име',
      cs: 'Zadejte název',
      el: 'Γράψτε ένα όνομα',
      ja: '名前を入力してください',
      tl: 'Ilagay ang pangalan',
      it: 'Inserisci un nome',
      pl: 'Wpisz imię',
      nl: 'Voer een naam in',
      pt: 'Digite um nome',
      ht: 'Mete yon non',
      ro: 'Introduceți un nume',
      da: 'Indtast et navn',
      zh: '選擇名稱'
    },

    nameReq: {
      en: 'Your name can only contain characters a-Z, and numbers 0-9, without any spaces. Up to 16 characters.',
      sv: 'Ditt namn kan bara använda sig karaktärerna a-Z, och nummer 0-9, utan mellanslag. Max 16 karaktärer.',
      ru: 'Ваше имя может состоять только из букв латинского алфавита a-Z и цифр 0-9, без пробелов. Максимум 16 символов.',
      fr: 'Votre nom ne peut contenir que des caractères de A à Z, des chiffres entre 0 et 9, sans aucun espace, et jusqu\'à 16 caractères.',
      hi: 'आपके नाम में केवल a-Z अक्षर और 0-9 अंक हो सकते है| अधिकतम 16 अक्षर।',
      es: 'Su nombre sólo puede contener los caracteres de la a-Z, y los números del 0 al 9, sin espacios. Hasta 16 caracteres.',
      de: 'Dein Name darf nur die Zeichen a-Z und die Zahlen 0-9 ohne Leerzeichen enthalten. Bis zu 16 Zeichen.',
      ko: '이름에는 공백없이 a-Z와 0-9의 문자 만 사용할 수 있습니다. 최대 16 자.',
      tr: 'İsminiz boşluk bırakmadan yalnızca a-Z karakterlerini ve 0-9 arasındaki sayıları içerebilir. 16 karaktere kadar.',
      bg: 'Вашето име може да съдържа само знаци a-Z и цифри 0-9, без никакви интервали. До 16 знака.',
      cs: 'Vaše jméno může obsahovat pouze znaky a-Z a čísla 0-9, bez mezer. Až 16 znaků.',
      el: 'To όνομά σας μπορεί να περιέχει μόνο χαρακτήρες a-Z και αριθμούς 0-9, χωρίς κενά. Έως 16 χαρακτήρες.',
      ja: 'あなたの名前はスペースなしで文字a-Zと数字0-9を含むことができます。 16文字まで',
      tl: 'Ang iyong pangalan ay maaari lamang maglaman ng mga character a-Z, at numero 0-9, nang walang anumang mga puwang. Hanggang sa 16 na mga character.',
      it: 'Il tuo nome può contenere solo caratteri a-Z e numeri da 0 a 9, senza spazi. Fino a 16 caratteri.',
      pl: 'Twoje imię może zawierać tylko znaki a-Z i cyfry 0-9, bez spacji. Do 16 znaków.',
      nl: 'Uw naam kan alleen de tekens a-Z bevatten, en cijfers 0-9, zonder spaties. Tot 16 tekens.',
      pt: 'O seu nome só pode conter caracteres de a-Z, e números 0-9, sem espaços. Até 16 caracteres.',
      ht: 'Non ou ka sèlman gen karaktè a-Z, ak nimewo 0-9, san okenn espas. Jiska 16 karaktè.',
      ro: 'Numele tău poate conține doar caractere a-Z, și numere 0-9, fără spații. Până la 16 caractere.',
      da: 'Dit navn kan kun indeholde tegn a-Z og tal 0-9 uden mellemrum. Op til 16 tegn.',
      zh: '你的名字只能包含字符a-Z和數字0-9，不能包含任何空格。 最多16個字符。'
    }
  },

  // Character deletion
  delete: {
    // It places the characters name after the string, e.g. 'Delete Battlebubbles'
    title: {
      en: 'Delete',
      sv: 'Radera',
      ru: 'Удалить',
      hi: 'मिटा दे',
      es: 'Borrar',
      de: 'Löschen',
      fr: 'Supprimer',
      ko: '캐릭터 삭제',
      tr: 'Sil',
      bg: 'Изтрий',
      cs: 'Smazat',
      el: 'Διαγράφω',
      ja: '削除する',
      tl: 'Tanggalin',
      it: 'Elimina',
      pl: 'Kasować',
      nl: 'Verwijder',
      pt: 'Eliminar',
      ht: 'Efase',
      ro: 'Șterge',
      da: 'Slet',
      zh: '刪除'
    },

    info: {
      en: 'To delete, type the character\'s name. Your character can not be restored.',
      sv: 'För att ta bort, skriv in karaktärens namn. Din karaktär tas bort för alltid.',
      ru: 'Чтобы удалить, введите имя персонажа. Ваш персонаж не может быть восстановлен.',
      hi: 'मिटाने के लिए अपने स्वरुप का नाम दाले। आपका स्वरूप पुनर नहीं मिल पाएगा।',
      es: 'Para eliminar, escriba el nombre del caracter. Tu carácter no puede ser restaurado.',
      de: 'Geben Sie zum Löschen deines character\'s den Namen ein. Dein Charakter kann nicht wiederhergestellt werden.',
      fr: 'Pour supprimer, saisissez le nom du personnage. Votre personnage ne pourra pas être restauré.',
      ko: '삭제하려면 캐릭터의 이름을 입력하십시오. 당신의 캐릭터는 회복 될 수 없습니다.',
      tr: 'Silmek için karakterin adını yazın. Silinen karakter geri getirilemez.',
      bg: 'За да изтриете, въведете името на вашият герой. Вашият герой не може да бъде възстановен.',
      cs: 'Chcete-li odstranit, zadejte název znaku. Vaše postava nemůže být obnovena.',
      el: 'Για να διαγράψετε, πληκτρολογήστε το όνομα του χαρακτήρα. Ο χαρακτήρας σας δεν μπορεί να αποκατασταθεί.',
      ja: '削除するには、文字の名前を入力します。あなたの性格は回復できません。',
      tl: 'Upang tanggalin, i-type ang pangalan ng character. Ang iyong karakter ay hindi maibabalik.',
      it: 'Per cancellare, digita il nome del personaggio. Il tuo personaggio non può essere ripristinato.',
      pl: 'Aby usunąć, wpisz nazwę postaci. Twoja postać nie może zostać przywrócona.',
      nl: 'Om te verwijderen typt u de naam van het karakter in. Uw karakter kan niet worden hersteld.',
      pt: 'Para apagar, digite o nome do personagem. Seu personagem não pode ser restaurado.',
      ht: 'Efase, tape non karaktè a. Karaktè ou pa kapab retabli.',
      ro: 'Pentru a șterge, tastați numele caracterului. Personajul tău nu va putea fi restaurat',
      da: 'For at slette skal du indtaste tegnets navn. Din karakter kan ikke gendannes.',
      zh: '要刪除，請鍵入角色的名稱。 你的角色無法恢復。'
    },

    placeholder: {
      en: 'Are you sure?',
      sv: 'Är du säker?',
      ru: 'Вы уверены?',
      fr: 'Êtes-vous sûr?',
      hi: 'पक्की तौर पर?',
      es: '¿Estás seguro?',
      de: 'Bist du sicher?',
      ko: '확실합니까?',
      tr: 'Emin misin?',
      bg: 'Сигурен ли си?',
      cs: 'Jsi si jistá?',
      el: 'Είσαι σίγουρος?',
      ja: '本気ですか？',
      tl: 'Sigurado ka ba?',
      it: 'Sei sicuro?',
      pl: 'Jesteś pewny?',
      nl: 'Weet u het zeker?',
      pt: 'Tens a certeza?',
      ht: 'Èske w sèten?',
      ro: 'Ești sigur?',
      da: 'Er du sikker?',
      zh: '你確定嗎？'
    }
  }
}
