export default {

  logout: {
    en: 'Log Out',
    ru: 'Выйти',
    hi: 'बाहर आए',
    es: 'Cerrar Sesion',
    de: 'Abmelden',
    fr: 'Déconnexion',
    ko: '로그 아웃',
    bg: 'Изход',
    cs: 'Odhlásit se',
    el: 'Αποσυνδέση',
    ja: 'ログアウト',
    sv: 'Logga ut',
    tl: 'Mag-log Out',
    tr: 'Çıkış Yap',
    nl: 'Uitloggen',
    pt: 'Sair',
    pl: 'Wyloguj się',
    ht: 'Dekonekte',
    ro: 'Deconectare',
    da: 'Afslut',
    zh: '登出'
  },

  home: {
    en: 'Home',
    ru: 'Домой',
    hi: 'मुख्य स्क्रीन',
    es: 'Inicio',
    de: 'Startseite',
    fr: 'Accueil',
    ko: '홈페이지',
    bg: 'Домой',
    cs: 'Domov',
    el: 'σπιτάκι',
    ja: 'ホームページ',
    sv: 'Hemsida',
    tl: 'Bahay',
    tr: 'Anasayfa',
    nl: 'Thuis',
    pt: 'Início',
    pl: 'Domu',
    ht: 'Paj lakay',
    ro: 'Acasă',
    da: 'Gå hjem',
    zh: '主頁'
  }
}
