export default {
  whisper: {
    en: 'Whisper',
    el: 'Ψίθυρος',
    ru: 'Шептать',
    hi: 'फुसफुसाऐ',
    es: 'Susurro',
    de: 'Flüstern',
    fr: 'Chuchoter',
    tr: 'Fısıltı',
    nl: 'Fluisteren',
    pt: 'Sussurro',
    ro: 'Șoaptă',
    hu: 'Suttogás',
    zh: '耳語',
    pl: 'Szept',
    bn: 'ফিসফিসানি',
    vi: 'Thì thầm',
    cs: 'Šepot',
    sr: 'Шапући',
    it: 'Sussurro',
    ko: '귓말',   
    ja: 'ひそひそ話'
  },

  types: [
    {
      en: 'Exp Gain',
      el: 'Απόκτηση εμπειρίας',
      ru: 'Получение опыта',
      de: 'Exp erhalten',
      fr: 'Gain d\'xp',
      es: 'Exp ganada',
      pt: 'Exp Ganho',
      tr: 'Exp Kazanımı',
      nl: 'Exp Gekregen',
      hu: 'EXP Jutalom',
      zh: 'Exp 獲得',
      pl: 'Zdobywanie Doświadczenia',
      bn: 'Exp লাভ',
      vi: 'Kinh nghiệm nhận được',
      cs: 'Získání zkušeností',
      sr: 'EXP Добитак',
      it: 'Guadagno di Exp',
      ko: '경험치',
      ja: 'Exp 獲得'
    },
    {
      en: 'Target Change',
      el: 'Αλλαγή στόχου',
      de: 'Ziel gewechselt',
      ru: 'Смена цели',
      fr: 'Changement de Cible',
      es: 'Cambio de Objetivo',      
      pt: 'Mudança de Alvo',
      nl: 'Verander Doelwit',
      hu: 'Célpont Megváltoztatása',
      zh: '目標變更',
      pl: 'Zmiana celu',
      bn: 'লক্ষ্য পরিবর্তন',
      vi: 'Mục tiêu thay đổi',
      cs: 'Změna cíle',
      sr: 'Промена мете', 
      it: 'Cambio di Target',
      tr: 'Hedef Değişimi',
      ko: '목표 변경',
      ja: 'ターゲット変更'
    },
    {
      en: 'Cast',
      el: 'Χτυπήματα',
      de: 'Zauber',
      ru: 'Произношение заклинаний',
      fr: 'Cast',
      es: 'Invocar',
      pt: 'Lançar',
      nl: 'Uitspreken',
      hu: 'Előhívás',
      zh: '施法',
      pl: 'Rzucenie czaru',
      bn: 'নিক্ষেপ',
      vi: 'Thi triển',
      cs: 'Čarování',
      sr: 'Бацити',
      it: 'Invocare',
      tr: 'Büyü',
      ko: '발동하다',
      ja: 'キャスト'
    },
    {
      en: 'Damage',
      el: 'Ζημιά',
      de: 'Schaden',
      ru: 'Урон',
      fr: 'Damage',
      es: 'Daño',
      pt: 'Dano',
      tr: 'Hasar',
      nl: 'Schade',
      hu: 'Sebzés',
      zh: '傷害',
      pl: 'Obrażenia',
      bn: 'ক্ষতি',
      vi: 'Sát thương',
      cs: 'Poškození',
      sr: 'Штета',
      it: 'Danno',
      ko: '피해량',
      ja: 'ダメージ'
    },
    {
      en: 'Heal',
      el: 'Γιατριά',
      ru: 'Исцеление',
      fr: 'Heal',
      de: 'Heilung',
      es: 'Curar',
      pt: 'Curar',
      tr: 'İyileşme',
      nl: 'Genezen',
      hu: 'Gyógyítás',
      zh: '補血',
      pl: 'Leczenie',
      bn: 'চিকিৎসা',
      vi: 'Hồi máu',
      cs: 'Vyléčení',
      sr: 'Оздравити',
      it: 'Cura',
      ko: '치유',
      ja: 'ヒール'
    },
    {
      en: 'Death',
      el: 'Θάνατος',
      de: 'Tod',
      ru: 'Смерть',
      fr: 'Death',
      es: 'Muerto',
      pt: 'Morte',
      tr: 'Ölüm',
      nl: 'Dood',
      hu: 'Halál',
      zh: '死亡',    
      pl: 'śmierć',
      bn: 'মৃত্যু',
      vi: 'Chết',
      cs: 'Smrt',
      sr: 'Смрт',
      it: 'Morte',
      ko: '사망',  
      ja: '死亡'
    },
    {
      en: 'Level Up',
      el: 'Απόκτηση επιπέδου',
      de: 'Level aufgestiegen',
      ru: 'Повышения уровня',
      fr: 'Level Up',
      es: 'Nivel Incrementado',
      pt: 'Subir de nível',
      nl: 'Level Omhoog',
      hu: 'Szintlépés',
      zh: '升等',
      pl: 'Zdobyto poziom',
      bn: 'লেভেল আপ',
      vi: 'Lên cấp',
      cs: 'Zvýšení úrovně',
      sr: 'Нови ниво',
      it: 'Nuovo Livello',
      tr: 'Seviye Atlama',
      ko: '레벨 업',
      ja: 'レベルアップ'
    },
    {
      en: 'Items',
      el: 'Αντικείμενα',
      de: 'Gegenstände',
      ru: 'Предметы',
      fr: 'Items',
      es: 'Objetos',
      pt: 'Items',
      nl: 'Voorwerpen',
      hu: 'Tárgyak',
      zh: '升等',
      pl: 'Przedmioty',
      bn: 'আইটেমস',
      vi: 'Vật phẩm',
      cs: 'Předměty',
      sr: 'Предмети',
      it: 'Oggetti',
      tr: 'Eşyalar',
      ko: '아이템',
      ja: 'アイテム'
    },
    {
      en: 'Auction',
      el: 'Δημοπρασία',
      de: 'Auktion',
      ru: 'Аукцион',
      fr: 'Enchères',
      es: 'Subasta',
      pt: 'Leilão',
      nl: 'Veiling',
      hu: 'Aukció',
      zh: '拍賣',
      ko: '경매',
      pl: 'Aukcja',
      bn: 'নিলাম',
      vi: 'Nhà đấu giá',
      cs: 'Předměty',
      sr: 'Аукција',
      it: 'Vendita all \'asta',
      tr: 'Açık Arttırma',
      ko: '경매',
      ja: '競売'
    },
    {
      en: 'Pick Gold',
      el: 'Απόκτηση χρυσού',
      de: 'Gold aufgehoben',
      ru: 'Сбор золота',
      fr: 'Gold Ramassé',
      es: 'Recoger Oro',
      pt: 'Pegar Ouro',
      nl: 'Goud Oprapen',
      hu: 'Felvett Arany',
      zh: '採金',
      pl: 'Zbierz złoto',
      bn: 'টাকা তোলা',
      vi: 'Nhặt vàng',
      cs: 'Zvednout zlato',
      sr: 'Покупи злато',
      it: 'Colleziona l\'oro',
      tr: 'Altını Topla',
      ko: '골드를 줍기',
      ja: 'ゴールド獲得'
    },
    {
      en: 'Spent Gold',
      el: 'Ξόδεμα χρυσού',
      de: 'Gold ausgegeben',
      ru: 'Трата золота',
      fr: 'Gold Utilisé',
      es: 'Oro gastado',
      pt: 'Ouro gasto',
      nl: 'Goud Besteden',
      hu: 'Elköltött Arany',
      zh: '花金',
      pl: 'Wydane złoto',
      bn: 'টাকা ব্যয় করা',
      vi: 'Vàng đã dùng',
      cs: 'Utratit zlato',
      sr: 'Потрошено злато',
      it: 'Spendi l\'oro',
      tr: 'Altın Harca',
      ko: '골드를 쓰다',
      ja: 'ゴールド支払'
    },
    {
      en: 'Fame Gain',
      el: 'Απόκτηση φήμης',
      de: 'Ruhm erhalten',
      ru: 'Получение славы',
      fr: 'Gain de Gloire',
      es: 'Fama ganada',
      pt: 'Fama ganha',
      tr: 'Şöhret Kazancı',
      nl: 'Beroemdheid Gekregen',
      hu: 'Dicsőség Jutalom',
      zh: '獲得聲譽',
      pl: 'Zdobyta Sława',
      bn: 'Fame লাভ',
      vi: 'Danh vọng nhận được',
      cs: 'Získání slávy',
      sr: 'Добитак славе',
      it: 'Guadagno della Fama',
      ko: '명성을 얻다',
      ja: '名声獲得'
    }
  ]
}
