export default {
  whisper: {
    en: 'Whisper',
    ru: 'Шептать',
    hi: 'फुसफुसाऐ',
    es: 'Susurro',
    de: 'Flüstern',
    fr: 'Chuchoter',
    ko: '속삭임',
    tr: 'Fısıltı',
    nl: 'Fluisteren',
    pt: 'Sussurro',
    ro: 'Șoaptă',
    hu: 'Suttogás',
    zh: '耳語',
    pl: 'Szept'
  },

  types: [
    {
      en: 'Exp Gain',
      ru: 'Получение опыта',
      de: 'Exp erhalten',
      fr: 'Gain d\'xp',
      es: 'Exp ganado',
      pt: 'Exp Ganho',
      tr: 'Exp Kazanımı',
      nl: 'Exp Gekregen',
      hu: 'EXP Jutalom',
      zh: 'Exp 獲得',
      pl: 'Zdobywanie Doświadczenia'
    },
    {
      en: 'Target Change',
      de: 'Ziel gewechselt',
      ru: 'Смена цели',
      fr: 'Changement de Cible',
      es: 'Cambio de Objetivo',
      pt: 'Mudança de Alvo',
      nl: 'Verander Doelwit',
      hu: 'Célpont Megváltoztatása',
      zh: '目標變更',
      pl: 'Zmiana celu'
    },
    {
      en: 'Cast',
      de: 'Zauber',
      ru: 'Произношение заклинаний',
      fr: 'Cast',
      es: 'Invocar',
      pt: 'Lançar',
      nl: 'Uitspreken',
      hu: 'Előhívás',
      zh: '施法',
      pl: 'Rzucenie czaru'
    },
    {
      en: 'Damage',
      de: 'Schaden',
      ru: 'Урон',
      fr: 'Damage',
      es: 'Daño',
      pt: 'Dano',
      tr: 'Hasar',
      nl: 'Schade',
      hu: 'Sebzés',
      zh: '傷害',
      pl: 'Obrażenia'
    },
    {
      en: 'Heal',
      ru: 'Исцеление',
      fr: 'Heal',
      de: 'Heilung',
      es: 'Curar',
      pt: 'Curar',
      tr: 'İyileşme',
      nl: 'Genezen',
      hu: 'Gyógyítás',
      zh: '補血',
      pl: 'Leczenie'
    },
    {
      en: 'Death',
      de: 'Tod',
      ru: 'Смерть',
      fr: 'Death',
      es: 'Muerto',
      pt: 'Morte',
      tr: 'Ölüm',
      nl: 'Dood',
      hu: 'Halál',
      zh: '死亡',
      pl: 'śmierć'
    },
    {
      en: 'Level Up',
      de: 'Level aufgestiegen',
      ru: 'Повышения уровня',
      fr: 'Level Up',
      es: 'Nivel subido',
      pt: 'Subir de nível',
      nl: 'Level Omhoog',
      hu: 'Szintlépés',
      zh: '升等',
      pl: 'Zdobyto poziom'
    },
    {
      en: 'Items',
      de: 'Gegenstände',
      ru: 'Предметы',
      fr: 'Items',
      es: 'Items',
      pt: 'Items',
      nl: 'Voorwerpen',
      hu: 'Tárgyak',
      zh: '升等',
      pl: 'Przedmioty'
    },
    {
      en: 'Auction',
      de: 'Auktion',
      ru: 'Аукцион',
      fr: 'Enchères',
      es: 'Subasta',
      pt: 'Leilão',
      nl: 'Veiling',
      hu: 'Aukció',
      zh: '拍賣',
      pl: 'Aukcja'
    },
    {
      en: 'Pick Gold',
      de: 'Gold aufgehoben',
      ru: 'Сбор золота',
      fr: 'Gold Ramassé',
      es: 'Oro recogido',
      pt: 'Pegar Ouro',
      nl: 'Goud Oprapen',
      hu: 'Felvett Arany',
      zh: '採金',
      pl: 'Zbierz złoto'
    },
    {
      en: 'Spent Gold',
      de: 'Gold ausgegeben',
      ru: 'Трата золота',
      fr: 'Gold Utilisé',
      es: 'Oro gastado',
      pt: 'Ouro gasto',
      nl: 'Goud Besteden',
      hu: 'Elköltött Arany',
      zh: '花金',
      pl: 'Wydane złoto'
    },
    {
      en: 'Fame Gain',
      de: 'Ruhm erhalten',
      ru: 'Получение славы',
      fr: 'Gain de Gloire',
      es: 'Fama ganada',
      pt: 'Fama ganha',
      tr: 'Şöhret Kazancı',
      nl: 'Beroemdheid Gekregen',
      hu: 'Dicsőség Jutalom',
      zh: '獲得聲譽',
      pl: 'Zdobyta Sława'
    }
  ]
}
