export default {
  whisper: {
    en: 'Whisper',
    ru: 'Шептать',
    hi: 'फुसफुसाऐ',
    es: 'Susurro',
    de: 'Flüstern',
    fr: 'Chuchoter',
    ko: '속삭임',
    tr: 'Fısıltı',
    nl: 'Fluisteren',
    pt: 'Sussurro',
    ro: 'Șoaptă',
    hu: 'Suttogás',
    zh: '耳語',
    pl: 'Szept',
    bn: 'ফিসফিসানি',
    vi: 'Thì thầm'
  },

  types: [
    {
      en: 'Exp Gain',
      ru: 'Получение опыта',
      de: 'Exp erhalten',
      fr: 'Gain d\'xp',
      es: 'Exp ganada',
      pt: 'Exp Ganho',
      tr: 'Exp Kazanımı',
      nl: 'Exp Gekregen',
      hu: 'EXP Jutalom',
      zh: 'Exp 獲得',
      pl: 'Zdobywanie Doświadczenia',
      bn: 'Exp লাভ',
      vi: 'Kinh nghiệm nhận được'
    },
    {
      en: 'Target Change',
      de: 'Ziel gewechselt',
      ru: 'Смена цели',
      fr: 'Changement de Cible',
      es: 'Cambio de Objetivo',
      pt: 'Mudança de Alvo',
      nl: 'Verander Doelwit',
      hu: 'Célpont Megváltoztatása',
      zh: '目標變更',
      pl: 'Zmiana celu',
      bn: 'লক্ষ্য পরিবর্তন',
      vi: 'Mục tiêu thay đổi'
    },
    {
      en: 'Cast',
      de: 'Zauber',
      ru: 'Произношение заклинаний',
      fr: 'Cast',
      es: 'Invocar',
      pt: 'Lançar',
      nl: 'Uitspreken',
      hu: 'Előhívás',
      zh: '施法',
      pl: 'Rzucenie czaru',
      bn: 'নিক্ষেপ',
      vi: 'Thi triển'
    },
    {
      en: 'Damage',
      de: 'Schaden',
      ru: 'Урон',
      fr: 'Damage',
      es: 'Daño',
      pt: 'Dano',
      tr: 'Hasar',
      nl: 'Schade',
      hu: 'Sebzés',
      zh: '傷害',
      pl: 'Obrażenia',
      bn: 'ক্ষতি',
      vi: 'Sát thương'
    },
    {
      en: 'Heal',
      ru: 'Исцеление',
      fr: 'Heal',
      de: 'Heilung',
      es: 'Curar',
      pt: 'Curar',
      tr: 'İyileşme',
      nl: 'Genezen',
      hu: 'Gyógyítás',
      zh: '補血',
      pl: 'Leczenie',
      bn: 'চিকিৎসা',
      vi: 'Hồi máu'
    },
    {
      en: 'Death',
      de: 'Tod',
      ru: 'Смерть',
      fr: 'Death',
      es: 'Muerto',
      pt: 'Morte',
      tr: 'Ölüm',
      nl: 'Dood',
      hu: 'Halál',
      zh: '死亡',
      pl: 'śmierć',
      bn: 'মৃত্যু',
      vi: 'Chết'
    },
    {
      en: 'Level Up',
      de: 'Level aufgestiegen',
      ru: 'Повышения уровня',
      fr: 'Level Up',
      es: 'Nivel Incrementado',
      pt: 'Subir de nível',
      nl: 'Level Omhoog',
      hu: 'Szintlépés',
      zh: '升等',
      pl: 'Zdobyto poziom',
      bn: 'লেভেল আপ',
      vi: 'Lên cấp'
    },
    {
      en: 'Items',
      de: 'Gegenstände',
      ru: 'Предметы',
      fr: 'Items',
      es: 'Objetos',
      pt: 'Items',
      nl: 'Voorwerpen',
      hu: 'Tárgyak',
      zh: '升等',
      pl: 'Przedmioty',
      bn: 'আইটেমস',
      vi: 'Vật phẩm'
    },
    {
      en: 'Auction',
      de: 'Auktion',
      ru: 'Аукцион',
      fr: 'Enchères',
      es: 'Subasta',
      pt: 'Leilão',
      nl: 'Veiling',
      hu: 'Aukció',
      zh: '拍賣',
      pl: 'Aukcja',
      bn: 'নিলাম',
      vi: 'Nhà đấu giá'
    },
    {
      en: 'Pick Gold',
      de: 'Gold aufgehoben',
      ru: 'Сбор золота',
      fr: 'Gold Ramassé',
      es: 'Recoger Oro',
      pt: 'Pegar Ouro',
      nl: 'Goud Oprapen',
      hu: 'Felvett Arany',
      zh: '採金',
      pl: 'Zbierz złoto',
      bn: 'টাকা তোলা',
      vi: 'Nhặt vàng'
    },
    {
      en: 'Spent Gold',
      de: 'Gold ausgegeben',
      ru: 'Трата золота',
      fr: 'Gold Utilisé',
      es: 'Oro gastado',
      pt: 'Ouro gasto',
      nl: 'Goud Besteden',
      hu: 'Elköltött Arany',
      zh: '花金',
      pl: 'Wydane złoto',
      bn: 'টাকা ব্যয় করা',
      vi: 'Vàng đã dùng'
    },
    {
      en: 'Fame Gain',
      de: 'Ruhm erhalten',
      ru: 'Получение славы',
      fr: 'Gain de Gloire',
      es: 'Fama ganada',
      pt: 'Fama ganha',
      tr: 'Şöhret Kazancı',
      nl: 'Beroemdheid Gekregen',
      hu: 'Dicsőség Jutalom',
      zh: '獲得聲譽',
      pl: 'Zdobyta Sława',
      bn: 'Fame লাভ',
      vi: 'Danh vọng nhận được'
    }
  ]
}
