export default {

  manager: {
      en: 'Clan Manager',
      ru: 'Клан Менеджер',
      fr: 'Gestionnaire du clan', // TODO: shorten
      hi: 'दल प्रबंधक',
      es: 'Clan Gerente', // TODO: shorten
      de: 'Clan-Manager',
      tr: 'Klan Yönetimi',
      bg: 'Мениджър на клана', // TODO: shorten
      ph: 'Clan Manager',
      bg: 'Мениджър на клана',
      el: 'Clan Manager',
      cs: 'Clan Manager',
      el: 'Clan Manager',
      it: 'Clan Manager',
      ja: 'クランマネージャー',
      pl: 'Menedżer klanu',
      pt: 'Gerente do Clã',
      ph: 'Clan Manager',
      sv: 'Clan Manager',
      ht: 'Manadjè klan',
      nl: 'Clanmanager',
      ko: '씨족 메뉴'
  },

  leave: {
      en: 'Leave Clan',
      ru: 'Покинуть Клан',
      fr: 'Quitter le clan',
      hi: 'दल छोड़े',
      es: 'Salir Clan', // TODO: shorten
      de: 'Clan verlassen',
      tr: 'Klandan Ayrıl',
      bg: 'Напусни Clan',
      ph: 'Iwanan mo ang grupo',
      bg: 'Напусни Clan',
      el: 'Αφήστε τη Clan',
      cs: 'Opustit klan',
      el: 'Αφήστε τη Clan',
      it: 'Abbandona il clan', // TODO: shorten
      ja: 'クランを脱退',
      pl: 'Opuść Klan',
      pt: 'Saia do clã',
      ph: 'Iwanan mo ang grupo', // TODO: shorten
      sv: 'Lämna Clan',
      ht: 'Kite Clan',
      nl: 'Verlofclan',
      ko: '씨족 을 나가기'
  },

  heading: {
      en: 'Clan',
      ru: 'Клан',
      fr: 'Clan',
      hi: 'दल',
      es: 'Clan',
      de: 'Clan',
      tr: 'Klan',
      bg: 'клан',
      cs: 'Klan',
      el: 'Φυλή',
      ph: 'Clan',
      bg: 'клан',
      el: 'Φυλή',
      it: 'Clan',
      ja: '族',
      pl: 'Klan',
      pt: 'Clã',
      ph: 'Clan',
      sv: 'Klan',
      ht: 'Clan',
      nl: 'Clan',
      ko: '씨족'
  },

  createheading: {
      en: 'Create Clan',
      ru: 'Создать Клан',
      fr: 'Créer un clan',
      hi: 'दल बनाए',
      es: 'Crear un clan',
      de: 'Clan anlegen',
      tr: 'Klan yarat',
      bg: 'Създайте клана',
      cs: 'Vytvořit klan',
      el: 'Δημιουργία Clan',
      it: 'Create Clan',
      ph: 'Lumikha ng Clan',
      bg: 'Създайте клана',
      el: 'Δημιουργία Clan',
      ja: 'クランを作成',
      pl: 'Utwórz klan',
      pt: 'Criar clã',
      ph: 'Lumikha ng Clan',
      sv: 'Skapa Clan',
      ht: 'Kreye Clan',
      nl: 'Creërenclan',
      ko: '씨족 을 만들기'
  },

  createinfo: {
      en: 'To create a clan you need',
      ru: 'Для создания клана вам нужно',
      fr: 'Pour créer un clan, on requiert',
      hi: 'दल बनाने के लिए आपको ज़रूरत है',
      es: 'Para crear un clan, necesita',
      de: 'Um einen Clan zu erstellen, brauchst du',
      ph: 'Upang lumikha ng isang lahi na kailangan mo',
      bg: 'За да създадете нужда от клан',
      el: 'Για να δημιουργήσετε μια οικογένεια που χρειάζεστε',
      tr: 'Klan yaratmak için ihtiyacın olan',
      bg: 'За да създадете нужда от клан',
      cs: 'Chcete-li vytvořit klan, který potřebujete',
      el: 'Για να δημιουργήσετε μια οικογένεια που χρειάζεστε',
      it: 'Per creare un clan che ti serve',
      ja: 'クランを作成するにはあなたが必要です',
      pl: 'Aby stworzyć potrzebny klan',
      pt: 'Para criar um clã você precisa',
      ph: 'Upang lumikha ng isang lahi na kailangan mo',
      sv: 'För att skapa en klan behöver du',
      ht: 'Pou kreye yon klan ou bezwen',
      nl: 'Om een clan te creëren heb je het volgende nodig',
      ko: '씨족 을 만들고 싶으면...'
  },

  createname: {
      en: 'Clan name',
      ru: 'имя клана',
      fr: 'Nom du clan',
      hi: 'दल का नाम',
      es: 'Clan nombre', // TODO: shorten
      de: 'Clan-Name',
      tr: 'Klan adı',
      bg: 'Име на клана',
      cs: 'Klanové jméno',
      ph: 'Pangalan ng isang lipi',
      bg: 'Име на клана',
      el: 'Όνομα Φίλου',
      el: 'Όνομα Φίλου',
      it: 'Nome del clan',
      ja: '氏名',
      pl: 'Nazwa klanu',
      pt: 'Nome do clã',
      ph: 'Pangalan ng isang lipi', // TODO: shorten
      sv: 'Klan namn',
      ht: 'Non klan',
      nl: 'Clannaam',
      ko: '씨족 이름'
  },

  createtag: {
      en: 'Clan tag',
      ru: 'Тег клана',
      fr: 'Tag du clan',
      hi: 'दल टैग',
      es: 'Clan seña', // TODO: shorten
      de: 'Clan-Tag',
      tr: 'Klan etiketi',
      ph: 'Clan tag',
      bg: 'Клан',
      el: 'Ετικέτα Clan',
      bg: 'Ден на клана',
      ph: 'Lumikha',
      bg: 'създавам',
      el: 'Δημιουργώ',
      cs: 'Den klanů',
      el: 'Ημέρα του γάμου', // TODO: shorten
      it: 'Clan tag',
      ja: '族の日',
      pl: 'Dzień klanu',
      pt: 'Dia do clã',
      ph: 'Araw ng lahi',
      sv: 'Clan tag',
      ht: 'Tag klan',
      nl: 'Clanlabel',
      ko: '씨족 꼬리표'
  },

  createbutton: {
      en: 'Create',
      ru: 'Создать',
      fr: 'Créer',
      ph: 'Sige',
      bg: 'добре',
      el: 'εντάξει',
      hi: 'निर्माण करे',
      es: 'Crear',
      de: 'Erstellen',
      tr: 'Yarat',
      bg: 'създавам',
      cs: 'Vytvořit',
      el: 'Δημιουργώ',
      it: 'Creare',
      ja: '作成する',
      pl: 'Stwórz',
      pt: 'Crio',
      ph: 'Lumikha',
      sv: 'Skapa',
      ht: 'Kreye',
      nl: 'Creëren',
      ko: '만들기'
  }
}
