export default {

  leave: {
    en: 'Leave Clan',
    ru: 'Покинуть Клан',
    fr: 'Quitter le Clan',
    hi: 'दल छोड़े',
    es: 'Salir de Clan',
    de: 'Clan Verlassen',
    tr: 'Klandan Ayrıl',
    bg: 'Напусни Клан',
    cs: 'Opustit Кlan',
    el: 'Αφήστε τη Φυλή',
    it: 'Tradire il Clan',
    ja: 'クランを脱退',
    pl: 'Opuść Klan',
    pt: 'Sair do Clã',
    tl: 'Iwanan ang Lahi',
    sv: 'Lämna Clan',
    ht: 'Kite Clan',
    nl: 'Verlofclan',
    ko: '씨족 을 나가기',
    ro: 'Părăsește Clanul',
    da: 'Forlad Clan',
    zh: '離開公會',
    hu: 'Klán Elhagyása'
  },

  heading: {
    en: 'Clan',
    ru: 'Клан',
    fr: 'Clan',
    hi: 'दल',
    es: 'Clan',
    de: 'Clan',
    tr: 'Klan',
    bg: 'Клан',
    cs: 'Klan',
    el: 'Φυλή',
    it: 'Clan',
    ja: '族',
    pl: 'Klan',
    pt: 'Clã',
    tl: 'Clan',
    sv: 'Klan',
    ht: 'Clan',
    nl: 'Clan',
    ko: '씨족',
    ro: 'Clan',
    da: 'Klan',
    zh: '公會',
    hu: 'Klán'
  },

  createheading: {
    en: 'Create Clan',
    ru: 'Создать Клан',
    fr: 'Créer un Clan',
    hi: 'दल बनाए',
    es: 'Crear un Clan',
    de: 'Clan Erstellen',
    tr: 'Klan Oluştur',
    bg: 'Създайте Клан',
    cs: 'Vytvořit Кlan',
    el: 'Δημιουργία Clan',
    it: 'Create Clan',
    ja: 'クランを作成',
    pl: 'Utwórz Кlan',
    pt: 'Criar Clã',
    tl: 'Lumikha ng Clan',
    sv: 'Skapa Clan',
    ht: 'Kreye Clan',
    nl: 'Creërenclan',
    ko: '씨족 을 만들기',
    ro: 'Creează un Clan',
    da: 'Opret Clan',
    zh: '創建公會',
    hu: 'Klán Létrehozása'
  },

  createname: {
    en: 'Clan Name',
    ru: 'Имя Клана',
    fr: 'Nom du Clan',
    hi: 'दल का नाम',
    es: 'Nombre del Clan',
    de: 'Clan-Name',
    tr: 'Klan Adı',
    bg: 'Име на Клана',
    cs: 'Klanové Jméno',
    el: 'Όνομα Φίλου',
    it: 'Nome del Clan',
    ja: '氏名',
    pl: 'Nazwa Кlanu',
    pt: 'Nome do Clã',
    tl: 'Pangalan ng clan', // TODO: shorten
    sv: 'Klan Namn',
    ht: 'Non Кlan',
    nl: 'Clannaam',
    ko: '씨족 이름',
    ro: 'Numele Clanului',
    da: 'Klan Navn',
    zh: '公會名稱',
    hu: 'Klán Neve'
  },

  createtag: {
    en: 'Clan Tag',
    ru: 'Tag Клана',
    fr: 'Tag du Clan',
    hi: 'दल Tag',
    es: 'Clan Tag',
    de: 'Clan-Tag',
    tr: 'Klan Tag\'ı',
    bg: 'Tag на Клана',
    cs: 'Tag Кlanů',
    el: 'Tag Φυλή',
    it: 'Tag di Clan',
    ja: '族 Tag',
    pl: 'Tag Кlanu',
    pt: 'Tag do Clã',
    tl: 'Clan Tag',
    sv: 'Klan Tag',
    ht: 'Tag Кlan',
    nl: 'Clan Tag',
    ko: '씨족 Tag',
    ro: 'Clan Tag',
    da: 'Klan Tag',
    zh: '公會標籤',
    hu: 'Klán Címkéje'
  },

  createbutton: {
    en: 'Create',
    ru: 'Создать',
    fr: 'Créer',
    hi: 'निर्माण करे',
    es: 'Crear',
    de: 'Erstellen',
    tr: 'Oluştur',
    bg: 'Създай',
    cs: 'Vytvořit',
    el: 'Δημιουργώ',
    it: 'Creare',
    ja: '作成する',
    pl: 'Stwórz',
    pt: 'Criar',
    tl: 'Lumikha',
    sv: 'Skapa',
    ht: 'Kreye',
    nl: 'Creëren',
    ko: '만들기',
    ro: 'Creează',
    da: 'Skab',
    zh: '創建',
    hu: 'Létrehozás'
  },

  roles: [
    { $$: 'Member' },
    { $$: 'Assistant' },
    { $$: 'Officer' },
    { $$: 'Owner' }
  ]
}
