export default {
  death: {
    en: 'You have died.',
    el: 'Έχεις πεθάνει',
    ru: 'Вы умерли.',
    hi: 'आप मर चुके हैं',
    es: 'Has muerto.',
    de: 'Du bist gestorben.',
    fr: 'Vous êtes mort.',
    ko: '사망했습니다.',
    tr: 'Öldün.',
    nl: 'Je bent gestorven.',
    pt: 'Você morreu.',
    ro: 'Tu ai murit.',
    zh: '你死了。',
    hu: 'Meghaltál',
    pl: 'Zginąłeś',
    bn: 'আপনি মারা গেছেন',
    vi: 'Bạn đã chết',
    sr: 'Умро си.',
    it: 'Sei morto.',
    ja: '死んでしまった。',
    cs: 'Zemřel jsi'
  },

  deathmsg: {
    en: 'Press the button to be resurrected at the nearest conjurer.',
    el: 'Πάτησε το κουμπί για να αναστηθείς στον κοντινότερο Θαυματοποιό.',
    ru: 'Нажмите кнопку, чтобы воскреснуть у ближайшего Заклинателя.',
    hi: 'निकटतम संयोजक पर पुनर्जीवित होने के लिए बटन दबाएं।',
    es: 'Presiona este botón para ser resucitado en el invocador más cercano.',
    de: 'Drücke den Knopf, um beim nächsten Beschwörer wiederbelebt zu werden.',
    fr: 'Appuyez sur le bouton pour être ressuscité chez le prestidigitateur le plus proche.',
    ko: '버튼을 누르면 가장 가까운 conjurer에서 리스폰됩니다.',
    tr: 'En yakın hokkabazda diriltilmek için düğmeye basın.',
    nl: 'Druk op de knop om op te staan bij de dichtstbijzijnde goochelaar.',
    pt: 'Pressione o botão para ser ressuscitado no conjurador mais próximo.',
    ro: 'Apăsați butonul pentru a fi înviat la cea mai apropiată Conjurer.',
    zh: '按下按鈕在最近的魔術師處復活。',
    hu: 'Nyomd meg a gombot hogy felgyógyítsanak a legközelebbi Conjurernél',
    pl: 'Wciśnij przycisk aby zostać wskrzeszonym przy najbliższym Conjurer',
    bn: 'নিকটতম কনজিউরারে পুনরুত্থিত হতে বাটনে চাপুন',
    vi: 'Nhấn nút để hồi sinh tại điểm gần nhất',
    sr: 'Притисните дугме да би сте васкрсли до најблизег Conjurer-a.',
    it: 'Premi il pulsante per risorgere dal Conjurer più vicino.',
    ja: 'ボタンを押すと近くの祈祷師へリスポーンします。',
    cs: 'Stisknutím tlačítka budete vzkříšeni u nejbližšího kouzelníka'
  },

  // 'Resurrect' is used in many translations/languages.
  respawn: {
    en: 'Respawn',
    el: 'Ανάστηση',
    ru: 'Воскреснуть',
    hi: 'अपने आप को जीवित करें',
    es: 'Resucitar',
    de: 'Wiederbeleben',
    fr: 'Ressusciter',
    ko: '리스폰',
    nl: 'Wederopstand',
    pt: 'Ressuscitar',
    ro: 'Înviați',
    zh: '重生',
    hu: 'Feltámadás',
    pl: 'Respawn',
    bn: 'পুনর্জীবন',
    vi: 'Hồi sinh',
    sr: 'Васкрсни',
    it: 'Respawn',
    tr: 'Yeniden Doğ',
    ja: 'リスポーン',
    cs: 'Respawn' // translate  Resurrect is 'Vzkřísit', but Respawn doesnt have right translate in czech, so i would like to let it call 'respawn'

  }
}
