export default {
  death: {
    en: 'You have died.',
    ru: 'Вы умерли.',
    hi: 'आप मर चुके हैं',
    es: 'Has muerto.',
    it: 'Sei morto.',
    de: 'Du bist gestorben.',
    fr: 'Vous êtes morts.',
    ko: '당신은 죽었습니다',
    bg: 'Ти си умрял.',
    cs: 'Zemřel jsi.',
    el: 'Έχεις πεθάνει.',
    ja: 'あなたは死んだ。',
    sv: 'Du har dött.',
    tl: 'Namatay ka na.',
    tr: 'Öldün.',
    nl: 'Je bent gestorven.',
    pt: 'Você morreu.',
    pl: 'Umarłeś.',
    ht: 'Ou te mouri.',
    ro: 'Tu ai murit.',
    da: 'Du er død.',
    zh: '你死了。',
    hu: 'Meghaltál'
  },

  deathmsg: {
    en: 'Press the button to be resurrected at the nearest conjurer.',
    ru: 'Нажмите кнопку, чтобы воскреснуть у ближайшего фокусника.',
    hi: 'निकटतम संयोजक पर पुनर्जीवित होने के लिए बटन दबाएं।',
    es: 'Presiona el botón para ser resucitado en el mago más cercano.',
    it: 'Premere il pulsante per essere resuscitato dal mago più vicino.',
    de: 'Drücke die Taste, die beim nächsten Zauberer wieder auferstehen soll.',
    fr: 'Appuyez sur le bouton pour être ressuscité chez le prestidigitateur le plus proche.',
    ko: '버튼을 눌러 가장 가까운 conjurer에게 부활 시키십시오.',
    bg: 'Натиснете бутона, който ще се възкреси в най-близкия фокусник.',
    cs: 'Stiskněte tlačítko pro vzkříšení u nejbližšího kouzelníka.',
    el: 'Πατήστε το κουμπί για να αναστηθεί στο πλησιέστερο μάγουλο.',
    ja: 'ボタンを押すと最寄りの保険会社に復活します。',
    sv: 'Tryck på knappen för att återuppstå vid närmaste konjurer.',
    tl: 'Pindutin ang pindutan upang mabuhay na muli sa pinakamalapit na salamangkero.',
    tr: 'En yakın hokkabazda diriltilmek için düğmeye basın.',
    nl: 'Druk op de knop om op te staan bij de dichtstbijzijnde goochelaar.',
    pt: 'Pressione o botão para ser ressuscitado no conjurador mais próximo.',
    pl: 'Naciśnij przycisk, aby zostać wskrzeszony u najbliższego zaklinacza.',
    ht: 'Peze bouton an pou li resisite nan aparèy ki pi pre a.',
    ro: 'Apăsați butonul pentru a fi înviat la cea mai apropiată conjurer.',
    da: 'Tryk på knappen for at blive opstandet hos nærmeste konjurer.',
    zh: '按下按钮可以找最近的魔术师处复活',
    hu: 'Nyomd meg a gombot hogy felgyógyítsanak a legközelebbi Conjurernél'
  },

  // 'Resurrect' is used in many translations/languages.
  respawn: {
    en: 'Respawn',
    ru: 'Воскреснуть',
    hi: 'अपने आप को जीवित करें',
    es: 'Resucítate',
    it: 'Risorgere',
    de: 'Erwecke dich wieder',
    fr: 'Ressuscitez',
    ko: '자신을 부활 시키십시오.',
    bg: 'Възкресете',
    cs: 'Vzkřís',
    el: 'Αναζωογονήστε τον εαυτό σας',
    ja: '自分を復活させる',
    sv: 'Återuppliva',
    tl: 'Buhayin Mo ang Iyong Sarili',
    nl: 'Wederopstand',
    pt: 'Ressuscitar',
    pl: 'Wskrześ',
    ht: 'Resisite',
    ro: 'Înviați',
    da: 'Genoplive',
    zh: '复活',
    hu: 'Feltámadás'
  }
}
