export default {
  // Simple basic UI elements that pop up everywhere
  ok: {
    en: 'Okay',
    el: 'ΟΚ',
    ru: 'Хорошо',
    de: 'Okay',
    hi: 'ठीक',
    fr: 'OK',
    es: 'Bien',
    tr: 'Tamam',
    nl: 'Okee',
    pt: 'Claro',
    ko: '오케이',
    ro: 'Okay',
    zh: '好的',
    hu: 'Rendben',
    pl: 'OK',
    bn: 'ঠিক আছে',
    vi: 'Đồng ý',
    sr: 'Добро',
    it: 'Ok',
    ja: '決定'
  },

  back: {
    en: 'Back',
    el: 'Πίσω',
    ru: 'Назад',
    hi: 'पिछला',
    fr: 'Retour',
    de: 'Zurück',
    es: 'Regresar',
    nl: 'Terug',
    tr: 'Geri',
    pt: 'Voltar',
    ko: '뒤로',
    ro: 'Înapoi',
    zh: '回',
    hu: 'Vissza',
    pl: 'Cofnij',
    bn: 'আগে',
    vi: 'Trở về',
    sr: 'Назад',
    it: 'Indietro',
    ja: '戻る'
  },

  accept: {
    en: 'Accept',
    el: 'Αποδοχή',
    ru: 'Принять',
    hi: 'स्वीकार है',
    fr: 'Accepter',
    de: 'Akzeptieren',
    es: 'Aceptar',
    nl: 'Aanvaarden',
    tr: 'Kabul Et',
    pt: 'Aceitar',
    ko: '동의',
    ro: 'Acceptă',
    zh: '允许',
    hu: 'Elfogadás',
    pl: 'Akceptuj',
    bn: 'গ্রায্য',
    vi: 'Chấp nhận',
    sr: 'Прихвати',
    it: 'Accetta',
    ja: '承認'
  },

  cancel: {
    en: 'Cancel',
    el: 'Ακύρωση',
    ru: 'Отмена',
    nl: 'Annuleren',
    tr: 'İptal Et',
    fr: 'Annuler',
    es: 'Cancelar',
    pt: 'Cancelar',
    de: 'Abbrechen',
    ro: 'Anulează',
    ko: '취소',
    hi: 'कैंसल',
    zh: '取消',
    hu: 'Mégsem',
    pl: 'Anuluj',
    bn: 'বাতিল',
    vi: 'Hủy bỏ',
    sr: 'Откажи',
    it: 'Annullare',
    ja: 'キャンセル'
  },

  decline: {
    en: 'Decline',
    el: 'Απόρριψη',
    ru: 'Отказать',
    hi: 'मना करें',
    fr: 'Refuser',
    de: 'Ablehnen',
    es: 'Rechazar',
    nl: 'Afwijzen',
    tr: 'Reddet',
    pt: 'Rejeitar',
    ko: '쇠퇴',
    ro: 'Refuză',
    zh: '拒绝',
    hu: 'Elutasítás',
    pl: 'Anuluj',
    bn: 'অগ্রায্য',
    vi: 'Từ chối',
    sr: 'Одбиј',
    it: 'Declina',
    ja: '拒否'
  },

  close: {
    en: 'Close',
    el: 'Κλείσιμο',
    ru: 'Закрыть',
    hi: 'बंद करे',
    fr: 'Fermer',
    de: 'Schließen',
    es: 'Cerrar',
    nl: 'Dichtbij',
    tr: 'Kapat',
    pt: 'Fechar',
    ko: '닫기',
    ro: 'Închide',
    zh: '关',
    hu: 'Bezárás',
    pl: 'Zamknij',
    bn: 'বন্ধ',
    vi: 'Đóng',
    sr: 'Затвори',
    it: 'Chiudi',
    ja: '閉じる'
  }
}
