export default {
  // Simple basic UI elements that pop up everywhere
  ok: {
    en: 'Okay',
    sv: 'Okej',
    ru: 'Окей',
    de: 'Okay',
    hi: 'ठीक',
    fr: 'OK',
    es: 'Bien',
    tr: 'Tamam',
    nl: 'Okee',
    pt: 'Claro',
    pl: 'Dobrze',
    ht: 'Dakò',
    ko: '오케이',
    it: 'Okay',
    cs: 'Dobře',
    ja: 'はい',
    bg: 'Добре',
    el: 'εντάξει',
    tl: 'Sige',
    ro: 'Okay',
    da: 'Okay',
    zh: '好的',
    hu: 'Rendben'
  },

  back: {
    en: 'Back',
    sv: 'Bakåt',
    ru: 'Назад',
    hi: 'पिछला',
    fr: 'Retour',
    de: 'Zurück',
    es: 'Regresar',
    nl: 'Terug',
    tr: 'Geri',
    pt: 'Voltar',
    pl: 'Wstecz',
    ht: 'Tounen',
    ko: '뒤로',
    it: 'Dietro',
    cs: 'Zadní',
    ja: 'バック',
    bg: 'Oбратно',
    el: 'Πίσω',
    tl: 'Bumalik',
    ro: 'Înapoi',
    da: 'Tilbage',
    zh: '回',
    hu: 'Vissza'
  },

  accept: {
    en: 'Accept',
    sv: 'Acceptera',
    ru: 'Принять',
    hi: 'स्वीकार है',
    fr: 'Accepter',
    de: 'Akzeptieren',
    es: 'Aceptar',
    nl: 'Aanvaarden',
    tr: 'Kabul Et',
    pt: 'Aceitar',
    pl: 'Zaakceptować',
    ht: 'Aksepte',
    ko: '동의',
    it: 'Accettare',
    cs: 'Akceptovat',
    ja: '受け入れる',
    bg: 'Приемам',
    el: 'Αποδέχομαι',
    tl: 'Tanggapin',
    ro: 'Acceptă',
    da: 'Acceptere',
    zh: '允许',
    hu: 'Elfogadás'
  },

  cancel: {
    en: 'Cancel',
    ru: 'Отменить',
    nl: 'Annuleren',
    tr: 'İptal Et',
    fr: 'Annuler',
    es: 'Cancelar',
    pt: 'Cancelar',
    it: 'Annulla',
    pl: 'Odwołaj',
    de: 'Abbrechen',
    ro: 'Anulează',
    el: 'Ματαίωση',
    tl: 'Kanselahin',
    bg: 'Отказ',
    cs: 'Zrušení',
    ht: 'Anile',
    ko: '취소',
    ja: 'キャンセル',
    hi: 'कैंसल',
    sv: 'Annullera',
    da: 'Afbestille',
    zh: '取消',
    hu: 'Mégsem'
  },

  decline: {
    en: 'Decline',
    sv: 'Nedgång',
    ru: 'Отказать',
    hi: 'मना करें',
    fr: 'Refuser',
    de: 'Ablehnen',
    es: 'Rechazar',
    nl: 'Afwijzen',
    tr: 'Reddet',
    pt: 'Rejeitar',
    pl: 'Upadek',
    ht: 'Refize',
    ko: '쇠퇴',
    it: 'Diminuzione',
    cs: 'Pokles',
    ja: '断る',
    bg: 'Отказвам',
    el: 'Πτώση',
    tl: 'Tanggihan',
    ro: 'Refuză',
    da: 'Nedgang',
    zh: '拒绝',
    hu: 'Elutasítás'
  },

  close: {
    en: 'Close',
    sv: 'Stänga',
    ru: 'Закрыть',
    hi: 'बंद करे',
    fr: 'Fermer',
    de: 'Schließen',
    es: 'Cerrar',
    nl: 'Dichtbij',
    tr: 'Kapat',
    pt: 'Fechar',
    pl: 'Blisko',
    ht: 'Close',
    ko: '닫기',
    it: 'Chiudi',
    cs: 'Zavřít',
    ja: '閉じる',
    bg: 'Затвори',
    el: 'Κοντά',
    tl: 'Isara',
    ro: 'Închide',
    da: 'Luk',
    zh: '关',
    hu: 'Bezárás'
  }
}
