export default {

  name: {
    en: 'Inventory',
    el: 'Τσάντα',
    ru: 'Инвентарь',
    hi: 'वस्तुसूची',
    es: 'Inventario',
    de: 'Inventar',
    fr: 'Inventaire',
    nl: 'Inventaris',
    pt: 'Inventário',
    tr: 'Enventer',
    ko: '목록',
    ro: 'inventar',
    zh: '库存',
    hu: 'Hátizsák',
    pl: 'Ekwipunek',
    vi: 'Hành trang',
    sr: 'Инвентар',
    it: 'Inventario'
  },

  pick: {
    en: 'You have picked up $1.',
    el: 'Απόκτησες το $1.',
    nl: 'Je hebt opgepikt $1.',
    es: 'Has recogido $1.',
    pt: 'Você pegou $1.',
    de: 'Du hast $1 aufgesammelt.',
    ro: 'Ai luat $1.',
    fr: 'Vous avez ramassé $1.',
    ru: 'Вы подобрали $1.',
    hi: 'आपने $1 उठा लिया',
    ko: '당신은 $1 를 선택했습니다',
    zh: '你捡到了$1。',
    hu: 'Fölvetted: $1',
    pl: 'Podniesiono $1.',
    vi: 'Bạn nhặt được $1.',
    sr: 'Покупио си $1.',
    it: 'Hai raccolto $1.',
    tr: 'Yerden $1 aldın.'
  },

  throw: {
    en: 'You threw away $1.',
    el: 'Πέταξες το $1.',
    ru: 'Вы выбросили $1.',
    ro: 'Ai aruncat $1.',
    es: 'Has tirado $1.',
    fr: 'Vous avez jeté $1.',
    de: 'Du hast $1 weggeworfen.',
    pt: 'Deitaste fora a $1.',
    ko: '너는 버렸어 $1',
    nl: 'Je hebt $1 weggegooid.',
    tr: '$1 \'i attın.',
    hi: 'आपने $1 को फेंक दिया',
    zh: '你丢了$1。',
    hu: 'Eldobtad: $1',
    pl: 'Wyrzucono: $1.',
    vi: 'Bạn đã vứt đi $1.',
    it: 'Hai gettato via $1.',
    sr: 'Бацио си $1.'
    tr: 'Yere $1 attın.'
  },

  full: {
    en: 'Your inventory is full.',
    el: 'Η τσάντα σου είναι γεμάτη.',
    nl: 'Uw inventaris is vol.',
    es: 'Tu inventario está lleno.',
    pt: 'O seu inventário está cheio.',
    de: 'Dein Inventar ist voll.',
    ro: 'Inventarul tău este plin.',
    fr: 'Votre inventaire est plein.',
    ru: 'В инвентаре нет места.',
    hi: 'आपकी वस्तुसूचि भर गयी है',
    ko: '인벤토리가 가득 찼습니다',
    zh: '你的库存满了。',
    hu: 'A hátizsákod tele van.',
    pl: 'Twój ekwipunek jest pełen.',
    vi: 'Hành trang của bạn đã đầy',
    it: 'Il tuo inventario è pieno',
    sr: 'Твој инвентар је пун.',
    tr: 'Enventerin dolu'
  },

  sold: {
    en: 'You have sold $1.',
    el: 'Πούλησες το $1.',
    nl: 'U heeft verkocht $1.',
    es: 'Has vendido $1.',
    pt: 'Você vendeu $1.',
    de: 'Du hast $1 verkauft.',
    ro: 'Ai vândut $1.',
    fr: 'Vous avez vendu $1.',
    ru: 'Вы продали $1.',
    hi: 'आपने $1 बेच दिया',
    ko: '$1 에',
    zh: '你卖了 $1。',
    hu: 'Eladtad: $1',
    pl: 'Sprzedano $1.',
    vi: 'Bạn đã bán $1.',
    it: 'Hai venduto $1.',
    sr: 'Продао си $1.',
    tr: '$1 sattın.'
  },

  receive: {
    en: 'You have received $1',
    el: 'Έχεις λάβει $1',
    de: 'Du hast $1 erhalten.',
    ru: 'Вы получили $1.',
    fr: 'Vous avez reçu $1.',
    nl: 'Je hebt 1 dollar ontvangen.',
    pt: 'Você recebeu $1.',
    es: 'Has recibido $1.',
    hi: 'आपको $1 प्राप्त हुआ है',
    ko: '$1 를 받았습니다',
    ro: 'Ați primit $1.',
    zh: '你收到 $1。',
    hu: 'Kaptál: $1',
    pl: 'Otrzymano $1.',
    vi: 'Bạn vừa nhận được $1.',
    it: 'Hai ricevuto $1.',
    sr: 'Добио си $1.'
    tr: '$1 elde ettin.'
  },

  drop: {
    en: 'Drop item',
    el: 'Πέταμα αντικειμένου',
    ru: 'Выбросить предмет',
    hi: 'वस्तु गिरा दे',
    es: 'Tirar objeto',
    de: 'Item fallen lassen',
    fr: 'Déposer l\'item',
    nl: 'Laat vallen',
    pt: 'Soltar item',
    tr: 'Eşyayı bırak',
    ko: '아이템 놓기',
    ro: 'Aruncă obiectul',
    zh: '丢装备',
    hu: 'Tárgy eldobása',
    pl: 'Wyrzuć przedmiot',
    vi: 'Vứt vật phẩm',
    it: 'Rilascia l\'oggetto',
    sr: 'Баци предмет'
  },

  equip: {
    en: 'Equip item',
    el: 'Εξόπλιση αντικειμένου',
    ru: 'Экипировать снаряжение',
    hi: 'वस्तु पहन लें',
    es: 'Equipar objeto',
    pt: 'Equipar item',
    ko: '장비 아이템',
    de: 'Item ausrüsten',
    fr: 'Equipez l\'item',
    nl: 'Rust uw item uit',
    ro: 'Echipează obiectul',
    zh: '上装备',
    hu: 'Felfegyverkezés',
    pl: 'Wyposaż przedmiot',
    vi: 'Trang bị vật phẩm',
    it: 'Equipaggia l\'oggetto',
    sr: 'Опреми предмет',
    tr: 'Eşyayı kuşan'
  },

  use: {
    en: 'Use item',
    el: 'Χρήση αντικειμένου',
    ru: 'Использовать',
    hi: 'इस्तमाल करे',
    ro: 'Utilizează',
    es: 'Usar objeto',
    fr: 'Utiliser l\'item',
    de: 'Item benutzen',
    pt: 'Usar item',
    ko: '항목 사용',
    nl: 'Gebruik item',
    tr: 'Eşyayı kullan',
    zh: '用物品',
    hu: 'Használat',
    pl: 'Użyj przedmiot',
    vi: 'Sử dụng vật phẩm',
    it: 'Usa l\'oggetto',
    sr: 'Употреби предмет'
  },

  copyitemid: {
    en: 'Copy item ID',
    ru: 'Скопировать ID предмета',
    el: 'Αντιγραφή ID αντικειμένου',
    hu: 'Azonosító másolása',
    pt: 'Copiar ID do item',
    tr: 'Eşya ID\'sini kopyala'
  },

  sell: {
    en: 'Sell item',
    el: 'Πώληση αντικειμένου',
    ru: 'Продать предмет',
    hu: 'Eladás',
    pt: 'Vender item',
    tr: 'Eşya sat'
  },

  splithalf: {
    en: 'Split half',
    el: 'Χωρισμός στο μισό',
    ru: 'Разделить пополам',
    fr: 'Partager en deux',
    pt: 'Dividir ao meio',
    hu: 'Kettéosztás',
    de: 'Stapel teilen',
    es: 'Partir a la mitad',
    pl: 'Rozdziel na pół',
    vi: 'Chia đôi',
    it: 'Dividi a metà',
    sr: 'Поделити на пола',
    tr: 'İkiye böl'
  },

  splitone: {
    en: 'Split one',
    el: 'Διαχωρισμός ενός',
    ru: 'Отделить один',
    fr: 'Retirer un item',
    pt: 'Retirar um',
    hu: 'Egy elvétele',
    de: 'Aufteilen',
    es: 'Separar uno',
    pl: 'Wydziel jeden',
    vi: 'Tách làm một',
    it: 'Dividine uno',
    sr: 'Поделити један',
    tr: 'Bir tane ayır'
  },

  spend: {
    en: 'You have spent $1.',
    el: 'Έχεις ξόδέξει $1.',
    ru: 'Вы потратили $1.',
    es: 'Has gastado $1.',
    fr: 'Vous avez dépensé $1.',
    de: 'Du hast $1 ausgegeben.',
    pt: 'Você gastou $1.',
    ko: '$1 동전을 보냈습니다',
    nl: 'U heeft $1 uitgegeven.',
    tr: '$1 para harcadınız.',
    hi: 'आपने $1 सिक्के खर्च कर दिए हैं',
    ro: 'Ai cheltuit $1.',
    zh: '你花了$1。',
    hu: 'Elköltöttél $1',
    pl: 'Wydano $1.',
    vi: 'Bạn đã dành $1',
    it: 'Hai speso $1',
    sr: 'Ти си потрошио $1.',
    tr: '$1 harcadın.'
  },

  death: {
    en: 'You died and lost $1.',
    el: 'Πέθανες και έχασες $1.',
    ru: 'Вы умерли и потеряли $1.',
    es: 'Has muerto y perdiste $1.',
    fr: 'Vous êtes mort et avez perdu $1.',
    de: 'Du bist gestorben und hast $1 verloren.',
    pt: 'Você morreu e perdeu $1.',
    ko: '$1 개의 동전을 잃고 잃어 버렸습니다',
    nl: 'Je stierf en verloor $1.',
    tr: 'Öldün ve $1 para kaybettin.',
    hi: 'आप मारे गए और $1 सिक्के खो दिए',
    ro: 'Ai murit și ai pierdut $1.',
    zh: '你死了，掉了 $1。',
    hu: 'Meghaltál és elvesztetted: $1',
    pl: 'Podczas śmierci stracono $1.',
    vi: 'Bạn đã chết và mất $1',
    it: 'Sei morto e hai perso $1',
    sr: 'Преминули сте и изгубили $1.'
  },

  bindlevel: [
    {$$: 'Tradable'},
    {$$: 'Account bound'},
    {$$: 'Character bound'}
  ]
}
