export default {

  search: {
    en: 'Search',
    nl: 'Zoeken',
    ru: 'Поиск',
    de: 'Suche',
    tl: 'Paghahanap',
    pt: 'Pesquisar',
    it: 'Ricerca',
    fr: 'Recherche',
    es: 'Buscar',
    pl: 'Wyszukiwanie',
    el: 'Ψάξιμο',
    bg: 'Търсене',
    cs: 'Vyhledávání',
    ht: 'Rechèch',
    ko: '수색',
    ja: 'サーチ',
    ro: 'Caută',
    hi: 'खोजे',
    da: 'Søg',
    sv: 'Sök',
    zh: '搜索',
    hu: 'Keresés'
  },

  filtermine: {
    en: 'My items only',
    nl: 'Alleen mijn voorwerpen',
    de: 'Nur meine items',
    ru: 'Только мои предметы',
    tl: 'Aking mga item lamang',
    pt: 'Apenas os meus itens',
    it: 'Solo i miei oggetti',
    pl: 'Tylko moje rzeczy',
    fr: 'Uniquement mes objets',
    es: 'Sólo mis objetos',
    el: 'Τα στοιχεία μου μόνο',
    bg: 'Само моите предмети',
    cs: 'Pouze mé položky',
    ht: 'Objè mwen sèlman',
    ko: '내 항목들 만',
    ja: '私の商品のみ',
    ro: 'Doar obiectele mele',
    hi: 'मेरी वस्तुएं',
    da: 'Kun mine genstand',
    sv: 'Endast mina föremål',
    zh: '只要我的装备',
    hu: 'Csak az én tárgyaim'
  },

  buy: {
    en: 'Buy Item',
    nl: 'Voorwerp Kopen',
    de: 'Item Kaufen',
    ru: 'Купить предмет',
    tl: 'Bumili ng Item',
    pt: 'Comprar Item',
    it: 'Comprare L\'oggetto',
    es: 'Comprar Objeto',
    fr: 'Acheter L\'objet',
    pl: 'Obiekt Zakupu',
    el: 'Αγοράστε Αντικείμενο',
    bg: 'Купете предмет',
    cs: 'Koupit Předmět',
    ht: 'Achte Objè',
    ko: '물건을 사다',
    ja: '商品を購入',
    ro: 'Cumpără Obiectul',
    hi: 'वस्तु खरीदे',
    da: 'Køb Genstand',
    sv: 'Köp Föremål',
    zh: '买装备',
    hu: 'Vásárlás'
  },

  post: {
    en: 'Post Item',
    ru: 'Отправить Предмет',
    nl: 'Plaatsen Voorwerp',
    es: 'Enviar Objeto',
    fr: 'Soumettre L\'objet',
    de: 'Item Senden',
    pt: 'Publicar Item',
    ko: '개체 보내기',
    pl: 'Prześlij Obiekt',
    sv: 'Skicka objekt',
    tr: 'Nesne Gönder',
    ht: 'Voye Objè',
    it: 'Invia L\'oggetto',
    hi: 'बाज़ार में डालें',
    tl: 'Ipadala ang Bagay',
    el: 'Στείλετε Αντικειμένου',
    bg: 'Изпрати Предмет',
    cs: 'Poslat Předmět',
    ja: 'オブジェクトを送信',
    da: 'Send Genstand',
    ro: 'Postează Obiectul',
    hu: 'Áruba bocsátás'
  },

  delist: {
    en: 'Delist Item',
    nl: 'Verwijderd Voorwerp',
    de: 'Verkauf Abbrechen',
    ru: 'Исключить Предмет',
    tl: 'Ibukod ang Item',
    pt: 'Excluir Objeto',
    it: 'Rimuovere L\'oggetto',
    pl: 'Usuń Obiekt',
    fr: 'Enlever l\'objet des enchères',
    es: 'Eliminar Objeto',
    el: 'Διαγραφή στοιχείου',
    bg: 'Изключване на Предмет',
    cs: 'Položka Delist',
    ht: 'De-lis Objè',
    ko: '항목 삭제',
    ja: 'アイテムを無効にする',
    ro: 'Scoate Obiectul',
    hi: 'बाज़ार से हटाएं',
    da: 'Fjern Genstand fra liste',
    sv: 'Delista-Objektet',
    hu: 'Tárgy visszavétele'
  },

  // Include the space and punctuation
  price: {
    en: 'Price: ',
    nl: 'Prijs: ',
    de: 'Preis: ',
    ru: 'Цена: ',
    tl: 'Presyo: ',
    pt: 'Preço: ',
    it: 'Prezzo: ',
    es: 'Precio: ',
    pl: 'Cena: ',
    fr: 'Prix: ',
    el: 'Τιμή: ',
    bg: 'Цена: ',
    cs: 'Cena: ',
    ht: 'Pri: ',
    ko: '가격: ',
    ja: '価格: ',
    ro: 'Preț: ',
    hi: 'कीमत: ',
    da: 'Pris: ',
    sv: 'Pris: ',
    zh: '价格: ',
    hu: 'Ár: '
  },

  // Include the space and punctuation
  fee: {
    en: 'Fee: ',
    de: 'Gebühr: ',
    nl: 'Honorarium: ',
    ru: 'Плата: ',
    tl: 'Bayad: ',
    pt: 'Taxa: ',
    it: 'Tassa: ',
    fr: 'Frais de vente: ',
    es: 'Tarifa: ',
    pl: 'Opłata: ',
    el: 'Τέλη: ',
    bg: 'Такса: ',
    cs: 'Poplatek: ',
    ht: 'Frè: ',
    ko: '비용: ',
    ja: '費用: ',
    ro: 'Taxă: ',
    hi: 'कीमत: ',
    da: 'Skat: ',
    sv: 'Avgift: ',
    zh: '费用: ',
    hu: 'Költség: '
  },

  dragitem: {
    en: 'Drag item into slot',
    nl: 'Slepen het voorwerp in de sleuf',
    de: 'Zieh ein Item hier rein',
    ru: 'Перетащите предмет в слот',
    tl: 'I-drag ang item sa puwang',
    pt: 'Arraste o item para o slot',
    it: 'Trascinare l\'oggetto nella fessura',
    pl: 'Przeciągnij obiekt do szczeliny czytnika',
    es: 'Arrastre el objeto a la ranura',
    fr: 'Glisser l\'objet dans l\'emplacement',
    el: 'Σύρετε το αντικείμενο σε υποδοχή',
    bg: 'Плъзнете предмет в слот',
    cs: 'Přetáhněte položku do slotu',
    ht: 'Drag objè nan plas',
    ko: '항목을 슬롯으로 드래그하십시오.',
    ja: 'アイテムをスロットにドラッグ',
    ro: 'Pune obiectul la locul lui',
    hi: 'वस्तु खीच कर खांचे में डाल दे',
    da: 'Træk genstand i slot',
    sv: 'Dra objektet till platsen',
    hu: 'Húzd a tárgyat az ablakba'
  },

  auctionpost: {
    en: 'You have posted $1 for sale',
    es: 'Ha contabilizado $1 para la venta',
    fr: 'Vous avez mis $1 en vente',
    de: 'Sie haben $1 zum Verkauf angeboten',
    pt: 'Você colocou $1 para leilão',
    ru: 'Вы выставили $1 на продажу',
    ko: '판매용으로 $1 를 게시했습니다',
    nl: 'U heeft $1 te koop aangeboden',
    pl: 'Wysłałeś $1 na sprzedaż',
    sv: 'Du har skrivit $1 till salu',
    tr: 'Satılık $1 gönderdiniz',
    ht: 'Ou te afiche $1 pou vann',
    it: 'Hai inviato $1 in vendita',
    hi: 'आपने $1 को विक्रय के लिए उपलब्ध कर दिया है',
    tl: 'Nag-post ka ng $1 para sa pagbebenta',
    el: 'Έχετε δημοσιεύσει $1 προς πώληση',
    bg: 'Публикували сте $1 за продажба',
    cs: 'Zveřejnili jste $1 na prodej',
    ja: 'あなたは販売のために $1 を投稿しました',
    ro: 'Ai postat $1 pentru vânzare',
    da: 'Du har indsendt $1 til salg',
    hu: 'Eladásra bocsátottad: $1'
  },

  // Do not translate "Stash".
  auctioncancel: {
    en: 'Item delisted and sent to Stash',
    ru: 'Предмет снят с продажи и отправлен в ваш Stash',
    nl: 'Item verwijderd en naar de Stash verzonden',
    de: 'Verkauf abgebrochen und Item in den Stash geschickt',
    pt: 'Item retirado do leilão e enviado para o Stash',
    it: 'Articolo cancellato e inviato a Stash',
    fr: 'Objet retiré des enchères et envoyé dans la Stash',
    pl: 'Przedmiot usunięty z wykazu i wysłany do Stash.',
    es: 'Artículo retirado de la lista y enviado a su Stash',
    tl: 'Inalis ang item at ipinadala sa Stash',
    el: 'Το στοιχείο αποσυντεθεί και αποστέλλεται στο στήθος',
    bg: 'Предмет се изтегля от продажба и се поставя в Stash',
    cs: 'Položka byla odstraněna a odeslána na Stazh',
    ht: 'Atik de-yo ki nan lis ak voye nan Stash',
    ko: '상장 폐지 된 물품',
    ja: '上場廃止されたアイテム',
    ro: 'Obiect delistat și pus la Stash',
    hi: 'वस्तु को बाज़ार से हटाकर आपके स्टैश में भेज दिया गया है',
    da: 'Genstand afnoteret og sendt til Stash',
    sv: 'Föremål listades och skickades till Stash',
    hu: 'A tárgyat nem vásárolták meg, és a Stash fiókodba került.'
  },

  // Do not translate "Stash".
  auctionbuy: {
    en: 'Item purchased for $g$1 and sent to your Stash',
    ru: 'Предмет, купленный за $g$1 и отправлен в ваш Stash',
    es: 'Artículo comprado por $g$1 y enviado a su Stash',
    fr: 'Article acheté pour $g$1 et envoyé dans votre Stash',
    de: 'Item, der für $g$1 gekauft und an Stash geschickt wurde',
    pt: 'Item comprado por $g$1 e enviado para o seu Stash',
    nl: 'Item gekocht voor $g$1 en verzonden naar uw Stash',
    pl: 'Przedmiot zakupiony za $g$1 i wysłany do twojego Stash',
    sv: 'Produkt som köpts för $g$1 och skickas till din Stash',
    ht: 'Atik achte pou $g$1 epi li voye bay Stash ou',
    it: 'Oggetto acquistato per $g$1 e inviato al tuo Stash',
    tl: 'Ang item na binili para sa $g$1 at ipinadala sa iyong Stash',
    el: 'Στοιχείο που αγοράσατε για $g$1 νομίσματα και απεστάλητε στο στήθος σας',
    bg: 'Позиция, закупена за $g$1 и изпратена до вашия Stash',
    cs: 'Zboží zakoupené za $g$1 a zaslané do vašeho Stash',
    ja: '$g$1 枚のコインで購入し、あなたの隠し場所に送られるアイテム',
    ko: '$g$1 동전으로 구입하여 은닉 한 물품',
    ro: 'Obiect cumpărat pentru $g$1 și trimis în Stash tău',
    hi: 'अपने $g$1 सिक्कों में वस्तु खरीद ली है और उसे आपके स्टैश में भेज दिया गया है',
    da: 'Vare købt til $g$1 og sendt til din Stash',
    hu: 'A tárgyat megvásárolták $g$1 áron, ami a Stash fiókodba került.'
  },

  sell: {
    en: 'You have sold $1 for $2',
    nl: 'U heeft verkocht $1 aan $2',
    es: 'Ha vendido $1 por $2',
    pt: 'Você vendeu $1 por $2',
    it: 'Hai venduto $1 per $2',
    pl: 'Sprzedałeś $1 za $2',
    de: 'Du hast $1 für $2 verkauft',
    ro: 'Ai vândut $1 pentru $2',
    fr: 'Vous avez vendu $1 pour $2',
    ru: 'Вы продали $1 за $2',
    hi: 'आपने $2 को $1 के लिए बेच दिया',
    bg: 'Продадохте $1 за $2',
    cs: 'Prodali jste $1 pro $2',
    el: 'Πουλήσατε $1 για $2',
    ja: 'あなたは売りました $1 の間 $2',
    tl: 'Binebenta mo na $1 Para sa $2',
    ht: 'Ou te vann $1 pou $2',
    ko: '$1 에 $1 를 판매했습니다',
    sv: 'Du har sålt $1 för $2',
    da: 'Du har solgt $1 til $2',
    hu: 'Eladtad: $1, $2 áron.'
  }
}
