export default {

  search: {
    en: 'Search',
    nl: 'Zoeken',
    ru: 'Поиск',
    de: 'Suche',
    tl: 'Paghahanap',
    pt: 'Busca',
    it: 'Ricerca',
    fr: 'Recherche',
    es: 'Buscar',
    pl: 'Wyszukiwanie',
    el: 'Ψάξιμο',
    bg: 'Търсене',
    cs: 'Vyhledávání',
    ht: 'Rechèch',
    ko: '수색',
    ja: 'サーチ',
    ro: 'Caută'
  },

  filtermine: {
    en: 'My items only',
    nl: 'Alleen mijn Voorwerpen',
    de: 'Nur meine Items',
    ru: 'Только мои предметы',
    tl: 'Aking mga item lamang',
    pt: 'Apenas os meus itens',
    it: 'Solo i miei articoli',
    pl: 'Tylko moje rzeczy',
    fr: 'Uniquement mes objets',
    es: 'Sólo mis Objetos',
    el: 'Τα στοιχεία μου μόνο',
    bg: 'Само моите елементи',
    cs: 'Pouze mé položky',
    ht: 'Objè mwen sèlman',
    ko: '내 항목 만',
    ja: '私の商品のみ',
    ro: 'Doar Obiectele Mele'
  },

  buy: {
    en: 'Buy Item',
    nl: 'Voorwerp Kopen',
    de: 'Item kaufen',
    ru: 'Купить предмет',
    tl: 'Bumili ng Item',
    pt: 'Comprar Objeto',
    it: 'Comprare l\'oggetto',
    es: 'Comprar Objeto',
    fr: 'Acheter l\'objet',
    pl: 'Obiekt zakupu',
    el: 'Αγοράστε Αντικείμενο',
    bg: 'Купете предмет',
    cs: 'Koupit předmět',
    ht: 'Achte Objè',
    ko: '물건을 사다',
    ja: '商品を購入',
    ro: 'Cumpără Obiectul'
  },

  post: {
    en: 'Post Item',
    ru: 'Отправить предмет',
    nl: 'Plaatsen Voorwerp',
    es: 'Enviar Objeto',
    fr: 'Soumettre l\'objet',
    de: 'Item senden',
    pt: 'Enviar Objeto',
    ko: '개체 보내기',
    pl: 'Prześlij Obiekt',
    sv: 'Skicka objekt',
    tr: 'Nesne Gönder',
    ht: 'Voye objè',
    it: 'Invia l\'oggetto',
    hi: 'वस्तु भेजें',
    tl: 'Ipadala ang Bagay',
    el: 'Στείλετε Αντικειμένου',
    bg: 'Изпрати предмет',
    cs: 'Poslat předmět',
    ja: 'オブジェクトを送信'
  },

  delist: {
    en: 'Delist Item',
    nl: 'Verwijderd Voorwerp',
    de: 'Verkauf abbrechen',
    ru: 'Исключить предмет',
    tl: 'Ibukod ang item',
    pt: 'Objeto de exclusão',
    it: 'Rimuovere l\'oggetto',
    pl: 'Usuń Obiekt',
    fr: 'Enlever l\'objet des enchères',
    es: 'Eliminar elemento',
    el: 'Διαγραφή στοιχείου',
    bg: 'Изключване на предмет',
    cs: 'Položka Delist',
    ht: 'De-lis Objè',
    ko: '항목 삭제',
    ja: 'アイテムを無効にする',
    ro: 'Scoate Obiectul'
  },

  // Include the space and punctuation
  price: {
    en: 'Price: ',
    nl: 'Prijs: ',
    de: 'Preis: ',
    ru: 'Цена: ',
    tl: 'Presyo: ',
    pt: 'Preço: ',
    it: 'Prezzo: ',
    es: 'Precio: ',
    pl: 'Cena: ',
    fr: 'Prix: ',
    el: 'Τιμή: ',
    bg: 'Цена: ',
    cs: 'Cena: ',
    ht: 'Pri: ',
    ko: '가격: ',
    ja: '価格: ',
    ro: 'Preț: '
  },

  // Include the space and punctuation
  fee: {
    en: 'Fee: ',
    de: 'Gebühr: ',
    nl: 'Honorarium: ',
    ru: 'Плата: ',
    tl: 'Bayad: ',
    pt: 'Taxa: ',
    it: 'Tassa: ',
    fr: 'Frais de vente: ',
    es: 'Tarifa: ',
    pl: 'Opłata: ',
    el: 'Τέλη: ',
    bg: 'Такса: ',
    cs: 'Poplatek: ',
    ht: 'Frè: ',
    ko: '보수: ',
    ja: '費用: ',
    ro: 'Taxă: '
  },

  dragitem: {
    en: 'Drag item into slot',
    nl: 'Slepen het voorwerp in de sleuf',
    de: 'Zieh ein Item hier rein',
    ru: 'Перетащите предмет в слот',
    tl: 'I-drag ang item sa puwang',
    pt: 'Arraste o objeto para a ranhura',
    it: 'Trascinare l\'oggetto nella fessura',
    pl: 'Przeciągnij obiekt do szczeliny czytnika',
    es: 'Arrastre el objeto a la ranura',
    fr: 'Glisser l\'objet dans l\'emplacement',
    el: 'Σύρετε το αντικείμενο σε υποδοχή',
    bg: 'Плъзнете предмет в слот',
    cs: 'Přetáhněte položku do slotu',
    ht: 'Drag objè nan plas',
    ko: '항목을 슬롯으로 드래그하십시오.',
    ja: 'アイテムをスロットにドラッグ',
    ro: 'Pune obiectul la locul lui'
  },

  auctionpost: {
    en: 'You have posted $1 for sale',
    es: 'Ha contabilizado $1 para la venta',
    fr: 'Vous avez mis $1 en vente',
    de: 'Sie haben $1 zum Verkauf angeboten',
    pt: 'Você enviei $1 para venda',
    ru: 'Вы выставили $1 на продажу',
    ko: '판매용으로 $1 를 게시했습니다',
    nl: 'U heeft $1 te koop aangeboden',
    pl: 'Wysłałeś $1 na sprzedaż',
    sv: 'Du har skrivit $1 till salu',
    tr: 'Satılık $1 gönderdiniz',
    ht: 'Ou te afiche $1 pou vann',
    it: 'Hai inviato $1 in vendita',
    hi: 'आपने $1 को विक्रय के लिए उपलब्ध कर दिया है',
    tl: 'Nag-post ka ng $1 para sa pagbebenta',
    el: 'Έχετε δημοσιεύσει $1 προς πώληση',
    bg: 'Публикували сте $1 за продажба',
    cs: 'Zveřejnili jste $1 na prodej',
    ja: 'あなたは販売のために $1 を投稿しました',
    ro: 'Ai postat $1 pentru vânzare'
  },

  auctioncancel: {
    en: 'Item delisted and sent to stash',
    ru: 'Предмет снят с продажи и положен в ваш сундук',
    nl: 'Item verwijderd en naar de stash verzonden',
    de: 'Verkauf abgebrochen und Item in den Speicher geschickt',
    pt: 'Item retirado da lista e enviado para o esconderijo',
    it: 'Articolo cancellato e inviato a magazzino',
    fr: 'Objet retiré des enchères et envoyé dans la planque',
    pl: 'Przedmiot usunięty z wykazu i wysłany do przechowania.',
    es: 'Artículo retirado de la lista y enviado a esconder',
    tl: 'Inalis ang item at ipinadala sa itago',
    el: 'Το στοιχείο αποσυντεθεί και αποστέλλεται στο στήθος',
    bg: 'Предмет е изтрит и изпратен на скривалище',
    cs: 'Položka byla odstraněna a odeslána',
    ht: 'Atik de-yo ki nan lis ak voye nan stash',
    ko: '상장 폐지 된 물품',
    ja: '上場廃止されたアイテム',
    ro: 'Obiect delistat și pus la păstrare'
  },

  auctionbuy: {
    en: 'Item purchased for $1 coins and sent to your Stash',
    ru: 'Предмет, купленный за $1, отправлен в ваш сундук',
    es: 'Artículo comprado por $1 monedas y enviado a su Stash',
    fr: 'Article acheté pour $1 pièces et envoyé dans votre planque',
    de: 'Artikel, der für $1 Münzen gekauft und an Ihr Versteck geschickt wurde',
    pt: 'Item comprado por $1 moedas e enviado para o seu Cesto',
    nl: 'Item gekocht voor $1 munten en verzonden naar uw Stash',
    pl: 'Przedmiot zakupiony za $1 monet i wysłany do Twojego magazynu',
    sv: 'Produkt som köpts för $1 mynt och skickas till din Stash',
    ht: 'Atik achte pou pyès monnen $1 epi li voye bay Stash ou',
    it: 'Oggetto acquistato per $1 monete e inviato al tuo Stash',
    hi: '$1 के लिए अपने वस्तु खरीद लिया है और उसे आपके स्टैश में भेज दिया गया है',
    tl: 'Ang item na binili para sa $1 barya at ipinadala sa iyong Stash',
    el: 'Στοιχείο που αγοράσατε για $1 νομίσματα και απεστάλητε στο Stash σας',
    bg: 'Позиция, закупена за $1 монети и изпратена до вашия Stash',
    cs: 'Zboží zakoupené za $1 mincí a zaslané do vašeho Stash',
    ja: '$1 枚のコインで購入し、あなたの隠し場所に送られるアイテム',
    ko: '$1 동전으로 구입하여 은닉 한 물품',
    ro: 'Obiect cumpărat pentru $1 monede și trimis în inventarul tău'
  },

  sell: {
    en: 'You have sold $1 for $2',
    nl: 'U heeft verkocht $1 aan $2',
    es: 'Usted ha vendido $1 por $2',
    pt: 'Você vendeu $1 por $2',
    it: 'Hai venduto $1 per $2',
    pl: 'Sprzedałeś $1 za $2',
    de: 'Du hast $1 für $2 verkauft',
    ro: 'Ai vândut $1 pentru $2',
    fr: 'Vous avez vendu $1 pour $2',
    ru: 'Вы продали $1 за $2',
    hi: 'आपने $1 के लिए $2 बेच दिया है',
    bg: 'Продадохте $1 за $2',
    cs: 'Prodali jste $1 pro $2',
    el: 'Πουλήσατε $1 για $2',
    ja: 'あなたは売りました $1 の間 $2',
    tl: 'Binebenta mo na $1 Para sa $2',
    ht: 'Ou te vann $1 pou $2',
    ko: '$1 에 $1 를 판매했습니다',
    sv: 'Du har sålt $1 för $2'
  }

}
