export default {

  /* ! Note: !
    Do not translate the word "Party", to ensure consistent player communication
  */

  invite: {
    en: 'Party invite',
    ru: 'Пригласить в party',
    it: 'invito Party',
    pt: 'convidar Party',
    nl: 'uitnodigen Party',
    pl: 'zaproszenie Party',
    de: 'Party einladung',
    fr: 'Invitation à une party',
    ht: 'Party envite',
    es: 'Party Invita',
    tr: 'Party davet et',
    cs: 'Pozvat party',
    ja: 'Party への招待',
    hi: 'Party आमंत्रण',
    sv: 'Party inbjudan',
    ko: 'Party 초대',
    bg: 'Покана за група',
    el: 'Πρόσκληση party',
    tl: 'Party imbitahan',
    ro: 'Invitație la party'
  },

  kick: {
    en: 'Party kick',
    ru: 'Выгнать',
    it: 'calcione Party',
    pt: 'chute Party',
    pl: 'kop Party',
    es: 'Sacar del Party',
    de: 'Treten',
    fr: 'Coup de pied',
    ht: 'Choute',
    nl: 'Paty uitgooien',
    tr: 'Partyden at',
    cs: 'Strana kop',
    ja: 'Partyキック',
    hi: 'Party लात',
    sv: 'Party spark',
    ko: 'Party 킥',
    bg: 'Изритай от група',
    el: 'λάκτισμα party',
    tl: 'Party sipa',
    ro: 'Dă afară'
  },

  leave: {
    en: 'Leave party',
    it: 'andarsene Party',
    pt: 'sair Party',
    nl: 'verlof Party',
    pl: 'wyjechać Party',
    de: 'Party Verlassen',
    fr: 'Party de départ',
    ht: 'Kite party',
    ru: 'Выйти',
    es: 'Salir del Party',
    tr: 'Party ayrıl',
    cs: 'Nechte stranou',
    ja: 'Partyのままに',
    hi: 'छोड़ना party',
    sv: 'Lämna arty',
    ko: 'party 나가기',
    bg: 'Излизане от група',
    el: 'Αφήστε party',
    tl: 'Iwanan ang party',
    ro: 'Părăsește party'
  },

  create: {
    en: 'Create party',
    ru: 'Создать party',
    it: 'Crea party',
    pt: 'Criar party',
    nl: 'Een party creëren',
    pl: 'Utwórz party',
    de: 'Party Erstellen',
    fr: 'Créer une party',
    ht: 'Kreye party',
    es: 'Crear party',
    tr: 'Party oluştur',
    cs: 'Vytvořit párty',
    ja: 'Partyを作成',
    hi: 'सर्जन करना party',
    sv: 'Skapa party',
    ko: 'party 만들기',
    bg: 'Създаване на група',
    el: 'Δημιουργία party',
    tl: 'Lumikha ng party',
    ro: 'Creează party'
  },

  onInvite: {
    en: '$1 has invited you to join their party.',
    de: '$1 hat dich eingeladen, an ihrer party teilzunehmen.',
    fr: '$1 vous invite à vous joindre à leur party.',
    ht: '$1 envite ou nan party yo.',
    ru: '$1 пригласил вас в party',
    es: '$1 te ha invitado a juntar a su Party.',
    nl: '$1 heeft je uitgenodigd vergezel hun party.',
    tr: '$1 seni party davet etti.',
    it: '$1 ti ha invitato a unirti alla loro festa.',
    pt: 'O $1 convidou-te para te juntares à festa deles.',
    pl: '$1 zaprosiło cię do przyłączenia się do ich partii.',
    cs: '$1 vás pozval, abyste se připojili k jejich straně.',
    ja: '$ 1があなたを彼らのPartyに招待しています。',
    hi: '$1 उनके party में शामिल होने के लिए आमंत्रित किया है।',
    sv: '$1 har bjudit in dig att gå med i deras party.',
    ko: '$1 님이 party 에 가입하도록 초대했습니다.',
    bg: '$1 ви покани да се присъедините към група.',
    el: 'Το $1 σας έχει προσκαλέσει να συμμετάσχετε στο party τους.',
    tl: 'Inanyayahan ka ng $1 na sumali sa kanilang party.',
    ro: '$1 te-a invitat să te alături party-ului'
  },

  // members, as in "12 members in party"
  members: {
    en: 'Members',
    de: 'Mitglieder',
    hi: 'सदस्य',
    it: 'Membri',
    pl: 'Członkowie',
    pt: 'Membros',
    fr: 'Membres',
    ru: 'Члены',
    nl: 'Leden',
    es: 'Miembros',
    tr: 'Üye',
    cs: 'Členové',
    ja: 'メンバー',
    ht: 'Manm yo',
    sv: 'Medlemmar',
    ko: '회원',
    bg: 'члена',
    el: 'Μέλη',
    tl: 'Mga Miyembro',
    ro: 'Membrii'
  },

  link: {
    en: 'Invitation link',
    hi: 'आमंत्रण लिंक',
    it: 'Invito Link',
    fr: 'Lien d\'invitation',
    de: 'Einladungslink',
    ru: 'Пригласительная ссылка',
    nl: 'Uitnodigingslink',
    es: 'Invitación enlace',
    tr: 'Davet linki',
    pt: 'Link para o convite',
    pl: 'Zaproszenie do składania wniosków',
    cs: 'Pozvánka',
    ja: '招待状リンク',
    ht: 'Lyen envitasyon',
    sv: 'Inbjudnings länk',
    ko: '초대 링크',
    bg: 'Линк за покана',
    el: 'Σύνδεσμος πρόσκλησης',
    tl: 'Link ng Imbitasyon',
    ro: 'Link-ul invitației'
  },

  onLink: {
    en: 'Send this link to other players! This will allow them to join your party.',
    ru: 'Отправьте эту ссылку другим игрокам! Это позволит им присоединиться к вашей party.',
    fr: 'Envoyez ce lien à d\'autres joueurs ! Cela leur permettra de se joindre à votre parti.',
    hi: 'अन्य खिलाड़ियों के लिए इस लिंक भेजें! इससे उन्हें अपनी पार्टी में शामिल होने की अनुमति देगा।',
    pl: 'Wyślij ten link do innych graczy! To pozwoli im dołączyć do twojej partii.',
    pt: 'Envie este link para outros jogadores! Isto permitirá que eles se juntem à sua festa.',
    it: 'Invia questo link ad altri giocatori! Questo permetterà loro di unirsi alla tua festa.',
    de: 'Sende diesen Link an andere Spieler! Dies wird es ihnen ermöglichen, sich deiner Gruppe anzuschließen.',
    nl: 'Stuur deze link naar andere spelers! Dit zal hen in staat stellen om zich aan te sluiten bij je party.',
    es: '¡Envíta este enlace a otros jugadores! Esto los permitirá a juntar en to party.',
    tr: 'Bu bağlantıyı diğer oyunculara gönder! Bu onların partyne katılmasını sağlayacak.',
    cs: 'Pošlete tento odkaz ostatním hráčům!  To jim umožní připojit se k vaší straně.',
    ja: '他のプレイヤーにこのリンクを送ってください！これにより、彼らはあなたのPartyに参加することができます。',
    ht: 'Voye lyen sa a bay lòt jwè yo! Sa a pral pèmèt yo rantre nan pati ou.',
    sv: 'Skicka den här länken till andra spelare! Detta gör att de kan ansluta sig till din party.',
    ko: '이 링크를 다른 플레이어에게 보내십시오! 그러면 party 에 가입 할 수 있습니다.',
    bg: 'Изпратете този линк на други играчи! Това ще им позволи да се присъединят към вашата група.',
    el: 'Στείλτε αυτό το σύνδεσμο σε άλλους παίκτες! Αυτό θα τους επιτρέψει να ενταχθούν στο party σας.',
    tl: 'Ipadala ang link na ito sa ibang mga manlalaro! Ito ay magpapahintulot sa kanila na sumali sa iyong party.',
    ro: 'Trimi-te acest link altor jucători! Le va permite să se alăture party-ului tău.'
  },

  copyLink: {
    /*
      PLEASE dont translate this literally, its very likely each language
      has their own version of expressing this. Google it if you are unsure :)
    */
    en: 'Copy to Clipboard',
    ru: 'Копировать в буфер',
    es: 'Copia a su Portapapele',
    de: 'In die Zwischenablage kopieren',
    fr: 'Copier dans le presse',
    tr: 'Bağlantıyı kopyala',
    nl: 'Kopieer naar klembord',
    it: 'Copia negli Appunti',
    pt: 'Copiar para Área de transferência',
    pl: 'Skopiować do schowka.',
    cs: 'Zkopírovat do schránky',
    ja: 'クリップボードにコピー',
    hi: 'क्लिपबोर्ड पर कॉपी करें',
    ht: 'Kopi nan clipboard',
    sv: 'Kopiera till Urklipp',
    ko: '클립 보드에 복사',
    bg: 'Копирай',
    el: 'Αντιγραφή στο πρόχειρο',
    tl: 'Kopyahin sa clipboard',
    ro: 'Copiați în clipboard'
  }
}
