export default {

  /* ! Note: !
    Do not translate the word "Party", to ensure consistent player communication
  */

  invite: {
    en: 'Party invite',
    ru: 'Пригласить в party',
    it: 'invito Party',
    pt: 'convidar Party',
    nl: 'uitnodigen Party',
    pl: 'zaproszenie Party',
    de: 'Party einladung',
    fr: 'Inviter à rejoindre une Party',
    ht: 'Party envite',
    es: 'Invitación a Party',
    tr: 'Party davet et',
    cs: 'Pozvat Party',
    ja: 'Party への招待',
    hi: 'Party में आमंत्रण',
    sv: 'Party Inbjudan',
    ko: 'Party 초대',
    bg: 'Покана за Party',
    el: 'Πρόσκληση Party',
    tl: 'Party Imbitahan',
    ro: 'Invitație la Party',
    da: 'Invitere til Party'
  },

  // DO NOT translate Party
  kick: {
    en: 'Party kick',
    ru: 'Выгнать',
    it: 'Calcione Party',
    pt: 'chute Party',
    pl: 'Kop Party',
    es: 'Sacar del Party',
    de: 'Treten',
    fr: 'Virer de la Party"',
    ht: 'Party Choute',
    nl: 'Paty uitgooien',
    tr: 'Party at',
    cs: 'Party kop',
    ja: 'Partyキック',
    hi: 'Party से निकाले',
    sv: 'Party spark',
    ko: 'Party 킥',
    bg: 'Изритай от Party',
    el: 'λάκτισμα party',
    tl: 'Party sipa',
    ro: 'Lovitură de Party',
    da: 'Kick ud af Party'
  },

  // DO NOT translate Party
  leave: {
    en: 'Leave Party',
    it: 'andarsene Party',
    pt: 'sair Party',
    nl: 'verlof Party',
    pl: 'wyjechać Party',
    de: 'Party Verlassen',
    fr: 'Quitter la Party',
    ht: 'Kite Party',
    ru: 'Выйти',
    es: 'Salir del Party',
    tr: 'Party ayrıl',
    cs: 'Opustit Party',
    ja: 'Partyのままに',
    hi: 'Party छोड़ दे',
    sv: 'Lämna Larty',
    ko: 'Party 나가기',
    bg: 'Излизане от Party',
    el: 'Αφήστε Party',
    tl: 'Iwanan ang Party',
    ro: 'Părăsește Party',
    da: 'Forlad Party'
  },

  // DO NOT translate Party
  create: {
    en: 'Create Party',
    ru: 'Создать Party',
    it: 'Crea Party',
    pt: 'Criar Party',
    nl: 'Een Party creëren',
    pl: 'Utwórz Party',
    de: 'Party Erstellen',
    fr: 'Créer une Party',
    ht: 'Kreye Party',
    es: 'Crear un Party',
    tr: 'Party oluştur',
    cs: 'Vytvořit Party',
    ja: 'Partyを作成',
    hi: 'नई Party बनाए',
    sv: 'Skapa Party',
    ko: 'Party 만들기',
    bg: 'Създаване на Party',
    el: 'Δημιουργία Party',
    tl: 'Lumikha ng Party',
    ro: 'Creează Party',
    da: 'Opret Party'
  },

  // DO NOT translate Party
  onInvite: {
    en: '$1 has invited you to join their Party.',
    de: '$1 hat dich eingeladen, an ihrer Party teilzunehmen.',
    fr: '$1 vous invite à vous joindre à leur Party.',
    ht: '$1 envite ou nan Party yo.',
    ru: '$1 пригласил вас в Party',
    es: '$1 te ha invitado a juntar a su Party.',
    nl: '$1 heeft je uitgenodigd vergezel hun Party.',
    tr: '$1 seni Party davet etti.',
    it: '$1 ti ha invitato a unirti alla loro Party.',
    pt: 'O $1 convidou-te para te juntares à Party deles.',
    pl: '$1 zaprosiło cię do przyłączenia się do ich partii.',
    cs: '$1 vás pozval, abyste se připojili k jejich Party.',
    ja: '$ 1があなたを彼らのPartyに招待しています。',
    hi: '$1 उनकेPartyमें शामिल होने के लिए आपको आमंत्रित किया है।',
    sv: '$1 har bjudit in dig att gå med i deras Party.',
    ko: '$1 님이 Party 에 가입하도록 초대했습니다.',
    bg: '$1 ви покани да се присъедините към Party.',
    el: 'Το $1 σας έχει προσκαλέσει να συμμετάσχετε στο Party τους.',
    tl: 'Inanyayahan ka ng $1 na sumali sa kanilang Party.',
    ro: '$1 te-a invitat să te alături Party-ului',
    da: '$1 har inviteret dig til at deltage i deres Party.'
  },

  // nearby, as in "12 members nearby"
  nearby: {
    en: 'nearby',
    ru: 'поблизости',
    de: 'in der Nähe',
    es: 'cercanas',
    fr: 'proximité',
    bg: 'наблизо',
    cs: 'v okolí',
    el: 'κοντά',
    sv: 'i närheten',
    tl: 'na partido',
    tr: 'Yakında',
    nl: 'in de buurt',
    pt: 'nas proximidades',
    pl: 'w pobliżu',
    ro: 'din apropiere',
    da: 'i nærheden',
    ja: 'あなたの近くに',
    hi: 'आपके करीब',
    ht: 'tou pre ou'
  },

  link: {
    en: 'Invitation link',
    hi: 'आमंत्रण लिंक',
    it: 'Invito Link',
    fr: 'Lien d\'invitation',
    de: 'Einladungslink',
    ru: 'Пригласительная ссылка',
    nl: 'Uitnodigingslink',
    es: 'Enlace de invitación ',
    tr: 'Davet linki',
    pt: 'Link para o convite',
    pl: 'Link zaproszenia',
    cs: 'Pozvánka',
    ja: '招待状リンク',
    ht: 'Lyen envitasyon',
    sv: 'Inbjudnings länk',
    ko: '초대 링크',
    bg: 'Линк за покана',
    el: 'Σύνδεσμος πρόσκλησης',
    tl: 'Link ng Imbitasyon',
    ro: 'Link-ul invitației',
    da: 'Invitation Link'
  },

  // DO NOT translate Party
  onLink: {
    en: 'Send this link to other players! This will allow them to join your Party.',
    ru: 'Отправьте эту ссылку другим игрокам! Это позволит им присоединиться к вашей Party.',
    fr: 'Envoyez ce lien à d\'autres joueurs ! Cela leur permettra de se joindre à votre Party.',
    hi: 'इस लिंक को अन्य खिलाड़ियों को भेजें! इससे वे आपके Part में शामिल हो सकेंगे।',
    pl: 'Wyślij ten link do innych graczy! To pozwoli im dołączyć do twojej Party',
    pt: 'Envie este link para outros jogadores! Isto permitirá que eles se juntem à sua Party.',
    it: 'Invia questo link ad altri giocatori! Questo permetterà loro di unirsi alla tua Party.',
    de: 'Sende diesen Link an andere Spieler! Dies wird es ihnen ermöglichen, sich deiner Party anzuschließen.',
    nl: 'Stuur deze link naar andere spelers! Dit zal hen in staat stellen om zich aan te sluiten bij je Party.',
    es: '¡Envía este enlace a otros jugadores! Esto los permitirá a juntar en tu Party.',
    tr: 'Bu bağlantıyı diğer oyunculara gönder! Bu onların Party katılmasını sağlayacak.',
    cs: 'Pošlete tento odkaz ostatním hráčům! To jim umožní připojit se k vaší Party.',
    ja: '他のプレイヤーにこのリンクを送ってください！これにより、彼らはあなたのPartyに参加することができます。',
    ht: 'Voye lyen sa a bay lòt jwè yo! Sa a pral pèmèt yo rantre nan Party ou.',
    sv: 'Skicka den här länken till andra spelare! Detta gör att de kan ansluta sig till din Party.',
    ko: '이 링크를 다른 플레이어에게 보내십시오! 그러면 party 에 가입 할 수 있습니다.',
    bg: 'Изпратете този линк на други играчи! Това ще им позволи да се присъединят към вашата Party.',
    el: 'Στείλτε αυτό το σύνδεσμο σε άλλους παίκτες! Αυτό θα τους επιτρέψει να ενταχθούν στο Party σας.',
    tl: 'Ipadala ang link na ito sa ibang mga manlalaro! Ito ay magpapahintulot sa kanila na sumali sa iyong Party.',
    ro: 'Trimi-te acest link altor jucători! Le va permite să se alăture Party-ului tău.',
    da: 'Send dette link til andre spillere! Dette vil give dem mulighed for at deltage i din Party.'
  },

  copyLink: {
    /*
      PLEASE dont translate this literally, its very likely each language
      has their own version of expressing this. Google it if you are unsure :)
    */
    en: 'Copy to Clipboard',
    ru: 'Копировать в буфер',
    es: 'Copia a su Portapapeles',
    de: 'In die Zwischenablage kopieren',
    fr: 'Copier le lien',
    tr: 'Bağlantıyı kopyala',
    nl: 'Kopieer naar klembord',
    it: 'Copia negli Appunti',
    pt: 'Copiar para Área de transferência',
    pl: 'Skopiować do schowka.',
    cs: 'Kopírovat do vyrovnávací paměti',
    ja: 'クリップボードにコピー',
    hi: 'क्लिपबोर्ड पर कॉपी करें',
    ht: 'Kopi nan tanpon',
    sv: 'Kopiera till Urklipp',
    ko: '클립 보드에 복사',
    bg: 'Копиране в буфер',
    el: 'Αντιγραφή στο πρόχειρο',
    tl: 'Kopyahin sa clipboard',
    ro: 'Copiați în clipboard',
    da: 'Kopier til buffer'
  }
}
