export default {

  name: {
    en: 'Settings',
    el: 'Ρυθμίσεις',
    ru: 'Настройки',
    hi: 'सेटिंग्स',
    es: 'Configuración',
    de: 'Einstellungen',
    fr: 'Paramètres',
    nl: 'Instellingen',
    tr: 'Ayarlar',
    pt: 'Configurações',
    ko: '설정',
    ro: 'Setări',
    zh: '设置',
    hu: 'Beállítások',
    pl: 'Ustawienia',
    vi: 'Cài đặt',
    sr: 'Подешавања',
    it: 'Impostazioni',
    ja: '設定'
  },

  // ---- Controls
  controls: {
    en: 'Controls',
    el: 'Controls',
    ru: 'Управление',
    hi: 'नियंत्रण',
    es: 'Controles',
    de: 'Steuerung',
    fr: 'Contrôles',
    tr: 'Kontroller',
    nl: 'Bediening',
    pt: 'Controlos',
    ko: '통제 수단',
    ro: 'Controale',
    zh: '控制',
    hu: 'Irányítás',
    pl: 'Sterowanie',
    vi: 'Điều khiển',
    sr: 'Контроле',
    it: 'Controlli',
    ja: '操作'
  },

  keybindings: {
    en: 'Key bindings',
    el: 'Πλήκτρα',
    de: 'Tastenbelegung',
    ru: 'Привязки клавиш',
    pt: 'Combinações de teclas',
    fr: 'Assignation des touches',
    nl: 'Knop verbindingen',
    hu: 'Billentyűparancsok',
    es: 'Atajos de teclado',
    zh: '鍵盤設定',
    pl: 'Ustawienia klawiszy',
    vi: 'Gán phím',
    it: 'Configurazione tasti',
    sr: 'Конфигурација контрола',
    tr: 'Tuş atamaları',
    ja: 'キー割り当て'
  },

  camera: {
    en: 'Camera',
    el: 'Κάμερα',
    es: 'Cámara',
    de: 'Kamera',
    fr: 'Caméra',
    ru: 'Камера',
    pl: 'Kamera',
    sr: 'Камера',
    it: 'Telecamera',
    hu: 'Kamera',
    pt: 'Câmera',
    tr: 'Kamera',
    ja: 'カメラ'
  },

  mousesensitivity: {
    en: 'Sensitivity',
    el: 'Ευαισθησία',
    es: 'Sensibilidad',
    de: 'Empfindlichkeit',
    fr: 'Sensibilité',
    ru: 'Чувствительность',
    pl: 'Czułość',
    vi: 'Độ nhạy chuột',
    sr: 'Сензитивност',
    it: 'Sensibilità',
    hu: 'Érzékenység',
    pt: 'Sensibilidade',
    tr: 'Hassasiyet',
    ja: 'マウス感度'
  },

  invertmousex: {
    en: 'Invert horizontally',
    el: 'Οριζόντια αντιστροφή',
    es: 'Invertir horizontalmente',
    de: 'X-Achse umkehren',
    fr: 'Inverser horizontalement',
    ru: 'Инвертировать горизонтально',
    pl: 'Inwersja pozioma',
    vi: 'Đảo ngược theo chiều ngang',
    sr: 'Обрни хоризонтално',
    it: 'Inverti orizzontalmente',
    hu: 'Vízszintes tükrözés',
    pt: 'Inverter horizontalmente',
    tr: 'Yatay ters çevir',
    ja: '左右反転'
  },

  invertmousey: {
    en: 'Invert vertically',
    el: 'Κάθετη αντιστροφή',
    es: 'Invertir verticalmente',
    de: 'Y-Achse umkehren',
    fr: 'Inverser verticalement',
    ru: 'Инвертировать вертикально',
    pl: 'Inwersja pionowa',
    vi: 'Đảo ngược theo chiều dọc',
    sr: 'Обрни вертикално',
    it: 'Inverti verticalmente',
    hu: 'Függőleges tükrözés',
    pt: 'Inverter verticalmente',
    tr: 'Dikey ters çevir',
    ja: '上下反転'
  },

  pointerlock: {
    en: 'Hide mouse during rotation',
    el: 'Απόκρυψη ποντικιού κατά την περιστροφή',
    de: 'Maus bei Rotation verstecken',
    ru: 'Скрыть мышь во время вращения камеры',
    pt: 'Ocultar o rato durante a rotação.',
    fr: 'Cacher la souris pendant les rotations',
    nl: 'Verstop rechter muis knop tijdens rotatie',
    hu: 'Egérmutató elrejtése forgáskor',
    es: 'Ocultar el puntero durante la rotación',
    zh: '旋轉中隱藏滑鼠',
    pl: 'Schowaj myszkę podczas obrotu',
    vi: 'Ẩn chuột khi xoay',
    sr: 'Сакриј миш током ротације',
    it: 'Nascondi il mouse durante le rotazioni',
    tr: 'Döndürme sırasında fareyi gizle',
    ja: '操作中にカーソル非表示'
  },

  lockedcamera: {
    en: 'Locked camera',
    el: 'Κλειδωμένη κάμερα',
    ru: 'Заблокированная камера',
    hi: 'कैमरा लॉक',
    es: 'Cámara fija',
    de: 'Kamera-Sperre',
    fr: 'Caméra verrouillée',
    tr: 'Kilitli kamera',
    nl: 'Gesloten camera',
    pt: 'Câmera bloqueada',
    ko: '잠긴 카메라',
    ro: 'Blochează camera',
    zh: '锁定相机',
    hu: 'Rögzített kamera',
    pl: 'Zablokowana kamera',
    vi: 'Khóa Camera',
    sr: 'Фиксна камера',
    it: 'Telecamera fissa',
    ja: 'カメラを固定'
  },

  // ---- Graphics
  graphics: {
    en: 'Graphics',
    el: 'Γραφικά',
    ru: 'Графика',
    hi: 'ग्राफ़िक्स',
    es: 'Gráficos',
    de: 'Grafik',
    fr: 'Graphiques',
    nl: 'Grafischen',
    tr: 'Grafikler',
    pt: 'Gráficos',
    ko: '제도법',
    ro: 'Grafică',
    zh: '图像',
    hu: 'Grafika',
    pl: 'Grafika',
    vi: 'Đồ họa',
    sr: 'Графика',
    it: 'Grafica',
    ja: 'グラフィック'
  },

  viewrange: {
    en: 'View range',
    el: 'Απόσταση θέασης',
    ru: 'Дальность прорисовки',
    de: 'Sichtweite',
    nl: 'Weergavebereik',
    pt: 'Distância de visão',
    ro: 'Câmp vizual',
    es: 'Rango de visión',
    hi: 'नज़र सीमा',
    fr: 'Distance d\'affichage',
    tr: 'Görüş mesafesi',
    ko: '범위보기',
    zh: '远景范围',
    hu: 'Látótávolság',
    pl: 'Zasięg widzenia',
    vi: 'Khoảng cách nhìn',
    it: 'Distanza visiva',
    sr: 'Дистанца погледа',
    ja: '描画範囲'
  },

  resolution: {
    en: 'Resolution',
    el: 'Ανάλυση',
    ru: 'Разрешение',
    hi: 'रेसोलूशन',
    es: 'Resolución',
    de: 'Auflösung',
    fr: 'Résolution',
    nl: 'Resolutie',
    tr: 'Çözünürlük',
    pt: 'Resolução',
    ko: '게임의 해상도',
    ro: 'Rezoluție',
    zh: '解析度',
    hu: 'Felbontás',
    pl: 'Rozdzielczość',
    vi: 'Độ phân giải',
    sr: 'Резолуција',
    it: 'Risoluzione',
    ja: '解像度'
  },

  postprocessing: {
    en: 'Post-processing',
    el: 'Post-processing',
    de: 'Nachbearbeitung',
    ru: 'Постобработка',
    tr: 'Detaylandırma',
    fr: 'Post-traitement',
    pt: 'Pós-processamento.',
    nl: 'Nawerking',
    hu: 'Utófeldolgozás',
    es: 'Post-procesamiento',
    pl: 'Post-processing',
    vi: 'Hậu xử lý',
    it: 'Post-processing',
    sr: 'Пост обрада',
    ja: 'ジャギー抑制'
  },

  skilleffects: {
    en: 'Skill Effects',
    el: 'Εφέ Ξορκιών',
    ru: 'Визуальные эффекты навыков',
    hi: 'स्किल दिखावट',
    es: 'Efectos de Habilidades',
    de: 'Fertigkeitseffekte',
    fr: 'Effets des Compétences',
    nl: 'Vaardigheidseffecten',
    tr: 'Yetenek Efektleri',
    pt: 'Efeitos de Habilidade',
    ko: '기술 효과',
    ro: 'Efectele Abilităților',
    zh: '技能影响',
    hu: 'Képesség effektek',
    pl: 'Efekty umiejętności',
    vi: 'Hiệu ứng kỹ năng',
    it: 'Effetti delle Skills',
    sr: 'Ефекти вештина',
    ja: 'スキル演出'
  },

  shadows: {
    en: 'Shadows',
    el: 'Σκιές',
    ru: 'Тени',
    de: 'Schatten',
    fr: 'Ombres',
    pt: 'Sombras',
    nl: 'Schaduwen',
    hu: 'Árnyékok',
    zh: '影子',
    es: 'Sombras',
    pl: 'Cienie',
    vi: 'Đổ bóng',
    sr: 'Сенке',
    it: 'Ombre',
    tr: 'Gölgeler',
    ja: '影'
  },

  ssao: {
    en: 'Ambient Occlusion',
    el: 'Ambient Occlusion',
    ru: 'Окружающая окклюзия',
    fr: 'Occlusion Ambiante',
    pt: 'Oclusão Ambiental',
    nl: 'Omgevingsocclusie',
    hu: 'Környezet okklúzió',
    es: 'Oclusión Ambiental',
    pl: 'Okluzja otoczenia',
    de: 'Umgebungsverdeckung',
    vi: 'Môi trường xung quanh',
    it: 'Occlusione Ambientale',
    sr: 'Оклузија околине',
    tr: 'Çevresel Perdeleme',
    ja: '環境閉塞'
  },

  grass: {
    en: 'Grass',
    el: 'Γρασίδι',
    de: 'Gras',
    ru: 'Трава',
    fr: 'Herbe',
    pt: 'Grama',
    nl: 'Gras',
    hu: 'Fű',
    es: 'Hierba',
    zh: '草',
    pl: 'Trawa',
    vi: 'Cây cỏ',
    sr: 'Трава',
    it: 'Erba',
    tr: 'Çim',
    ja: '草'
  },

  clouds: {
    en: 'Clouds',
    el: 'Σύννεφα',
    de: 'Wolken',
    ru: 'Облака',
    fr: 'Nuages',
    pt: 'Nuvens',
    nl: 'Wolken',
    hu: 'Felhők',
    es: 'Nubes',
    zh: '云',
    pl: 'Chmury',
    vi: 'Mây',
    sr: 'Облаци',
    it: 'Nuvole',
    tr: 'Çimler',
    ja: '雲'
  },

  particles: {
    en: 'Particles',
    el: 'Particles',
    de: 'Partikel',
    ru: 'Частицы',
    fr: 'Particules',
    pt: 'Partículas',
    nl: 'Deeltjes',
    hu: 'Részecskék',
    es: 'Partículas',
    zh: '粒子',
    pl: 'Cząsteczki',
    vi: 'Hạt chi tiết',
    it: 'Particelle',
    sr: 'Ефекти',
    tr: 'Parçacıklar',
    ja: 'パーティクル'
  },

  detailprops: {
    en: 'Detail props',
    el: 'Λεπτομέρειες',
    de: 'Details',
    ru: 'Детализация',
    nl: 'Detail Voorwerpen',
    hu: 'Részletes objektumok',
    es: 'Detalles de accesorios',
    zh: '細節道具',
    fr: 'Objets détaillés',
    pl: 'Szczegóły',
    vi: 'Chi tiết',
    it: 'Dettagli',
    sr: 'Детаљи предмета',
    pt: 'Detalhes das props.',
    tr: 'Nesne detayları',
    ja: '建造物の詳細'
  },

  // ---- Audio
  audio: {
    en: 'Audio',
    el: 'Ήχος',
    ru: 'Звук',
    de: 'Ton',
    nl: 'Geluid',
    pt: 'Áudio',
    ro: 'Audio',
    es: 'Audio',
    hi: 'आवाज़',
    fr: 'Audio',
    tr: 'Ses',
    ko: '오디오',
    zh: '音频',
    hu: 'Hang',
    pl: 'Audio',
    vi: 'Âm thanh',
    sr: 'Звук',
    it: 'Audio',
    ja: 'オーディオ'
  },

  sfxvolume: {
    en: 'SFX Volume',
    el: 'Ένταση SFX',
    ru: 'Громкость спецэффектов',
    de: 'Effekt-Lautstärke',
    nl: 'SFX Volume',
    pt: 'Volume de SFX',
    ro: 'Volum SFX',
    es: 'Volumen SFX',
    hi: 'इफैक्ट्स की आवाज़',
    fr: 'Volume des effets sonores',
    tr: 'SFX Ses Gücü',
    ko: 'SFX 볼륨',
    hu: 'Effektek hangereje',
    pl: 'Poziom dźwięków',
    vi: 'Âm lượng SFX',
    sr: 'SFX гласноћа',
    it: 'SFX Volume',
    ja: '効果音'
  },
  ambiencevolume: {
    en: 'Ambience Volume',
    el: 'Ένταση ατμόσφαιρας',
    ru: 'Громкость окружения',
    hu: 'Környezet hangereje',
    pt: 'Som ambiente',
    tr: 'Ambiyans sesi',
    ja: '環境音'
  },
  musicvolume: {
    en: 'Music Volume',
    el: 'Ένταση μουσικής',
    de: 'Musik-Lautstärke',
    ru: 'Громкость музыки',
    fr: 'Volume des Musiques',
    es: 'Volumen de la música',
    pl: 'Poziom muzyki',
    vi: 'Âm lượng nhạc',
    sr: 'Гласноћа музике',
    it: 'Volume Musica',
    hu: 'Zene hangereje',
    pt: 'Volume da música',
    tr: 'Müzik sesi',
    ja: '音楽'
  },
  // ---- Chat
  chat: {
    en: 'Chat',
    el: 'Συνομιλία',
    ru: 'Чат',
    hi: 'चैट',
    es: 'Chat',
    de: 'Chat',
    fr: 'Chat',
    nl: 'Chat',
    tr: 'sohbet',
    pt: 'Chat',
    ko: '잡담',
    ro: 'Chat',
    hu: 'Cset',
    zh: '聊天室',
    pl: 'Czat',
    vi: 'Chat',
    sr: 'Чет',
    it: 'Chat',
    ja: 'チャット'
  },

  chatbubbles: {
    en: 'Show chat bubbles',
    el: 'Εμφάνιση φουσκών συνομιλίας',
    de: 'Sprechblasen anzeigen',
    ru: 'Показавать сообщения над игроком',
    fr: 'Afficher les bulles de chat',
    pt: 'Mostrar bolhas de chat',
    nl: 'Laat chat bubbels zien',
    hu: 'Csetbuborékok mutatása',
    zh: '顯示聊天氣泡',
    es: 'Mostrar burbujas de chat',
    pl: 'Chmurki czatu',
    vi: 'Hiển thị bong bóng chat',
    sr: 'Прикажи чет',
    it: 'Mostra le chat bubbles',
    tr: 'Sohbet balonlarını göster',
    ja: 'チャットをキャラクター上に表示'
  },

  combatlog: {
    en: 'Combat Log',
    el: 'Καταγραφή μάχης',
    de: 'Kampf-Log',
    ru: 'Лог боя',
    nl: 'Gevechts log',
    hu: 'Harci kisnapló',
    es: 'Registro de combate',
    zh: '戰鬥表',
    fr: 'Journal de Combat',
    pl: 'Log Walki',
    vi: 'Nhật ký combat',
    it: 'registro dei combattimenti',
    sr: 'Борбени чет',
    pt: 'Log de combate',
    tr: 'Savaş Günlüğü',
    ja: '戦闘ログ'
  },

  // ---- User interface
  interface: {
    en: 'Interface',
    el: 'Διεπαφή',
    ru: 'Интерфейс',
    de: 'Oberfläche',
    pt: 'Interface',
    nl: 'Interface',
    ro: 'Interfață',
    es: 'Interfaz',
    hi: 'अन्तराफलक',
    fr: 'Interface',
    tr: 'Arayüz',
    ko: '인터페이스',
    hu: 'Felület',
    zh: '界面',
    pl: 'Interfejs',
    vi: 'Giao diện',
    sr: 'Интерфејс',
    it: 'Interfaccia',
    ja: 'インターフェース'
  },

  language: {
    en: 'Language',
    el: 'Γλώσσα',
    ru: 'Язык',
    de: 'Sprache',
    nl: 'Taal',
    pt: 'Idioma',
    ro: 'Limbă',
    es: 'Idioma',
    hi: 'भाषा',
    fr: 'Langue',
    tr: 'Dil',
    ko: '언어',
    hu: 'Nyelv',
    zh: '語言',
    pl: 'Język',
    vi: 'Ngôn ngữ',
    sr: 'Језик',
    it: 'Linguaggio',
    ja: '言語'
  },

  invwidth: {
    en: 'Inventory width',
    el: 'Πλάτος τσάντας',
    ru: 'Ширина инвентаря',
    de: 'Inventar-Breite',
    nl: 'Inventarisbreedte',
    pt: 'Largura do inventário',
    ro: 'Lățimea inventarului',
    es: 'Ancho del inventario',
    hi: 'वस्तुसूची की चौड़ाई',
    fr: 'Largeur de l\'inventaire',
    ko: '인벤토리 너비',
    hu: 'Hátizsák szélesség',
    pl: 'Szerokość ekwipunku',
    vi: 'Độ dài hành trang',
    sr: 'Ширина инвентара',
    it: 'Larghezza inventario',
    tr: 'Enventar genişliği',
    ja: 'インベントリの行'
  },

  // Do NOT translate "Stash"
  stashwidth: {
    en: 'Stash width',
    el: 'Πλάτος Stash',
    es: 'Ancho del Stash',
    ru: 'Ширина Stash',
    fr: 'Largeur de Stash',
    hu: 'Stash szélesség',
    de: 'Stash-Breite',
    pl: 'Szerokość Stash',
    vi: 'Độ dài Stash',
    sr: 'Ширина Stash-а',
    it: 'Larghezza Stash',
    pt: 'Tamanho do baú',
    tr: 'Stash genişliği',
    ja: 'Stashの行'
  },

  // Do NOT translate "Stash"
  stashheight: {
    en: 'Stash height',
    el: 'Ύψος Stash',
    es: 'Capacidad del stash',
    ru: 'Высота Stash',
    fr: 'Hauteur de Stash',
    hu: 'Stash magasság',
    de: 'Stash-Höhe',
    pl: 'Wysokość Stash',
    vi: 'Độ rộng Stash',
    sr: 'Висина Stash-а',
    it: 'Altezza Stash',
    pt: 'Altura do baú',
    tr: 'Stash yüksekliği',
    ja: 'Stashの列'
  },

  tutorial: {
    en: 'Tutorial',
    el: 'Οδηγός για αρχάριους',
    ru: 'Обучение',
    hi: 'शिक्षण',
    es: 'Tutorial',
    de: 'Tutorial',
    fr: 'Tutoriel',
    nl: 'Handleiding',
    tr: 'Öğretici',
    pt: 'Tutorial',
    ko: '지도 시간',
    ro: 'Tutorial',
    hu: 'Bemutató',
    zh: '講解',
    pl: 'Samouczek',
    vi: 'Hướng dẫn',
    sr: 'Туторијал',
    it: 'Tutorial',
    ja: 'チュートリアル'
  },

  resettutorial: {
    en: 'Reset tutorial',
    el: 'Μηδενισμός οδηγού για αρχάριους',
    ru: 'Начать обучение снова',
    hi: 'शिक्षण रीसेट',
    es: 'Reiniciar el tutorial',
    de: 'Tutorial zurücksetzen',
    fr: 'Réinitialiser le tutoriel',
    nl: 'Reset handleiding',
    tr: 'Öğreticiyi sıfırla',
    pt: 'Recomeçar o tutorial',
    ko: '재설정 자습서',
    ro: 'Resetează tutorialul',
    hu: 'Bemutató újrakezdése',
    zh: '重置講解',
    pl: 'Zresetuj samouczek',
    vi: 'Cài đặt lại hướng dẫn',
    sr: 'Понови туторијал',
    it: 'Ripristina tutorial',
    ja: 'チュートリアルを初期化'
  },

  disabletutorial: {
    en: 'Disable tutorial',
    el: 'Απενεργοποίηση οδηγού για αρχάριους',
    de: 'Tutorial deaktivieren',
    ru: 'Отключить обучение',
    tr: 'Öğreticiyi kapat',
    fr: 'Désactiver le tutoriel',
    pt: 'Desativar o tutorial',
    nl: 'Handleiding uitschakelen',
    hu: 'Bemutató elrejtése',
    es: 'Deshabilitar el tutorial',
    zh: '禁用講解',
    pl: 'Wyłącz samouczek',
    vi: 'Vô hiệu hóa hướng dẫn',
    sr: 'Искључи туторијал',
    it: 'Disabilita il tutorial',
    ja: 'チュートリアルを無効化'
  },

  // ---- map
  maplowqual: {
    en: 'Low quality mode',
    el: 'Λειτουργία χαμηλής ποιότητας',
    de: 'Niedrige Qualität',
    ru: 'Режим низкого качества',
    hu: 'Alacsony minőségű mód',
    pt: 'Modo de qualidade baixa',
    fr: 'Mode basse qualité',
    nl: 'Lage kwaliteit modus',
    es: 'Modo de baja calidad',
    zh: '低畫質模式',
    pl: 'Niska jakość',
    vi: 'Chế độ chất lượng thấp',
    sr: 'Мод лошијег квалитета',
    it: 'Modalità bassa qualità',
    tr: 'Düşük kalite modu',
    ja: '低品質モード'
  },

  mapshowmonsters: {
    en: 'Show monsters',
    el: 'Εμφάνιση τεράτων',
    ru: 'Показывать монстров',
    hu: 'Szörnyek mutatása',
    pt: 'Mostrar monstros',
    fr: 'Afficher les monstres',
    nl: 'Laat monsters zien',
    es: 'Mostrar monstruos',
    zh: '顯示怪物',
    de: 'Monster sichtbar',
    pl: 'Widoczność potworów',
    vi: 'Hiển thị quái vật',
    sr: 'Приказуј чудовишта',
    it: 'Mostra i mostri',
    tr: 'Canavarları göster',
    ja: 'モンスターを表示'
  }
}
