export default {

  settings: {
      en: 'settings',
      ru: 'Настройки',
      hi: 'सेटिंग्स',
      es: 'configuración',
      de: 'Einstellungen',
      fr: 'paramétrage',
      nl: 'instellingen',
      tr: 'ayarlar',
      ph: 'mga setting',
      bg: 'настройки',
      el: 'Ρυθμίσεις',
      pt: 'Ajustes',
      pl: 'nastawy',
      ht: 'ajisteman',
      it: 'impostazioni',
      ko: '설정',
      cs: 'nastavení',
      ja: '設定',
      sv: 'inställningar'
  },

  // controls section of settings menu
  controls: {
      en: 'controls',
      ru: 'Управление',
      hi: 'कंट्रोल्स',
      es: 'controles',
      de: 'Kontrollen',
      fr: 'commandes',
      tr: 'kontroller',
      nl: 'bediening',
      pt: 'controles',
      pl: 'kontrole',
      ht: 'kontwòl yo',
      it: 'regolazione',
      ko: '통제 수단',
      cs: 'řízení',
      ph: 'mga kontrol',
      bg: 'контроли',
      el: 'ελέγχους',
      ja: 'コントロール',
      sv: 'kontrollinstrument'
  },

  lockedcamera: {
      en: 'Locked camera',
      ru: 'Заблокировать камеру',
      hi: 'कैमरा लॉक',
      es: 'Cámara fija',
      de: 'Gesperrte Kamera',
      fr: 'Caméra verrouillée',
      tr: 'Kilitli kamera',
      nl: 'Gesloten camera',
      pt: 'câmera bloqueada',
      pl: 'Zamknięta kamera',
      ph: 'Naka-lock na camera',
      bg: 'Заключена камера',
      el: 'Κλειδωμένη κάμερα',
      ht: 'Kamera fèmen',
      it: 'telecamera bloccata',
      ko: '잠긴 카메라',
      cs: 'Zamknutá kamera',
      ja: 'ロックカメラ',
      sv: 'Låst kamera'
  },

  graphics: {
      en: 'graphics',
      ru: 'Графика',
      hi: 'ग्राफ़िक्स',
      es: 'gráficos',
      de: 'Grafiken',
      fr: 'schémas',
      nl: 'grafischen',
      tr: 'grafikler',
      ph: 'graphics',
      bg: 'графики',
      el: 'γραφικών',
      pt: 'gráficos',
      pl: 'grafika',
      ht: 'grafik',
      it: 'grafica',
      ko: '제도법',
      cs: 'grafika',
      ja: 'グラフィックス',
      sv: 'grafik'
  },

  resolution: {
      en: 'Resolution',
      ru: 'Разрешение',
      hi: 'रेसोलूशन',
      es: 'Resolución',
      de: 'Auflösung',
      ph: 'Resolution',
      bg: 'Резолюция',
      el: 'Ανάλυση',
      fr: 'Résolution',
      nl: 'Resolution',
      tr: 'Çözünürlük',
      pt: 'Resolução',
      pl: 'Rozdzielczość',
      ht: 'Rezolisyon an',
      it: 'delibera',
      ko: '게임의 해상도',
      cs: 'Rozlišení',
      ja: '解決',
      sv: 'mötesbeslut'
  },

  skilleffects: {
      en: 'Skill effects',
      ru: 'Эффекты навыков',
      hi: 'स्किल दिखावट',
      es: 'Efectos de habilidades',
      de: 'Fertigkeitseffekte',
      fr: 'Effets de compétences',
      nl: 'Vaardigheidseffecten',
      ph: 'Mga epekto sa kasanayan',
      bg: 'Ефекти на уменията',
      el: 'Επιπτώσεις δεξιοτήτων',
      tr: 'Yetenek efektleri',
      pt: 'Efeitos de habilidade',
      pl: 'Efekty umiejętności',
      ht: 'Efè Konpetans',
      it: 'effetti di abilità',
      ko: '기술 효과',
      cs: 'Dovednostní efekty',
      ja: 'スキル効果',
      sv: 'Färdighetseffekter'
  },

  shadow: {
      en: 'Shadow quality',
      ru: 'Качество тени',
      hi: 'परछाईं क्वालिटी',
      es: 'Calidad de sombra',
      de: 'Schattenqualität',
      fr: 'Qualité de l\'ombre',
      ph: 'Kalidad ng anino',
      bg: 'Качество на сенките',
      el: 'Ποιότητα σκιάς',
      nl: 'Schaduwkwaliteit',
      tr: 'Gölge kalitesi',
      pt: 'Qualidade de sombras',
      pl: 'Jakość cienia',
      ht: 'Kalite lonbraj',
      it: 'Qualità dell\'ombra',
      ko: '그림자',
      cs: 'Kvalita stínu',
      ja: 'シャドウ品質',
      sv: 'Skuggkvalitet'
  },

  grassamount: {
      en: 'Grass amount',
      ru: 'Количество травы',
      hi: 'घास की मात्रा',
      es: 'Cantidad de pasto',
      de: 'Grasmenge',
      fr: 'Quantité d\'herbe',
      ph: 'Halaga ng Grass',
      bg: 'Количество трева',
      el: 'Χόρτο ποσό',
      nl: 'Grasbedrag',
      tr: 'Çim miktarı',
      pt: 'Quantidade de grama',
      pl: 'Ilość trawy',
      ht: 'Zèb kantite lajan',
      it: 'Quantità d\'erba',
      ko: '잔디 양',
      cs: 'Množství trávy',
      ja: '草量',
      sv: 'Gräsbelopp'
  },

  chat: {
      en: 'chat',
      ru: 'Чат',
      hi: 'चैट',
      es: 'Chat',
      de: 'Chat',
      fr: 'clavardage',
      nl: 'praten',
      tr: 'sohbet',
      pt: 'bate-papo',
      ph: 'chat',
      bg: 'чат',
      el: 'κουβέντα',
      pl: 'pogawędka',
      ht: 'chat',
      it: 'chiacchierata',
      ko: '잡담',
      cs: 'chatu',
      ja: 'チャット',
      sv: 'chatt'
  },

  chatwidth: {
      en: 'Chat width',
      ru: 'Ширина чата',
      hi: 'चैट की चौडाई',
      es: 'Ancho del chat',
      de: 'Chatbreite',
      fr: 'Largeur du chat',
      nl: 'Chatbreedte',
      tr: 'Chat genişliği',
      pt: 'Largura do chat',
      ph: 'Lapad ng chat',
      bg: 'Ширина на чата',
      el: 'Συνομιλία πλάτος',
      pl: 'Szerokość rozmowy',
      ht: 'Lajè chat',
      it: 'Larghezza della chat',
      ko: '잡담 폭',
      cs: 'Šířka chatu',
      ja: 'チャット幅',
      sv: 'Chatt bredd'
  },

  chatheight: {
      en: 'Chat height',
      ru: 'Высота чата',
      hi: 'चैट की लम्बाई',
      es: 'Altura del chat',
      de: 'Chathöhe',
      fr: 'Hauteur de clavardage',
      nl: 'Chathoogte',
      tr: 'Chat yükskliği',
      pt: 'Altura do chat',
      pl: 'Wysokość rozmowy',
      ph: 'Taas ng chat',
      bg: 'Височина на чата',
      el: 'Ύψος συνομιλίας',      ht: 'Wotè chat',
      it: 'Altezza della chat',
      ko: '잡담 노피',
      cs: 'Výška chatu',
      ja: 'チャットの高さ',
      sv: 'Chathöjd'
  },

  tutorial: {
      en: 'tutorial',
      ru: 'Учебник',
      hi: 'शिक्षण',
      es: 'tutorial',
      de: 'Tutorial',
      fr: 'didacticiel',
      nl: 'handleiding',
      tr: 'öğretici',
      pt: 'tutorial',
      ph: 'pagtuturo',
      bg: 'настойнически',
      el: 'φροντιστήριο',
      pl: 'przewodnik',
      ht: 'leson patikilye',
      it: 'tutorial',
      ko: ' 지도 시간',
      cs: 'výuku',
      ja: 'チュートリアル',
      sv: 'handledning'
  },

  reset: {
      en: 'Reset tutorial',
      ru: 'Начать учебник заново',
      hi: 'शिक्षण रीसेट',
      es: 'Reiniciar tutorial',
      de: 'Tutorial zurücksetzen',
      fr: 'Réinitialiser le tutoriel',
      ph: 'I-reset ang tutorial
      bg: 'Нулиране на урока
      el: 'Επαναφορά του σεμιναρίου',
      nl: 'Gereset les',
      tr: 'Öğreticiyi sıfırla',
      pt: 'tutorial de reset',
      pl: 'resetowanie samouczka',
      ht: 'Reset tutorial',
      it: 'Ripristina tutorial',
      ko: '재설정 자습서',
      cs: 'Obnovit výuku',
      ja: 'チュートリアルをリセット',
      sv: 'Återställ handledningen'
  }
}
