export default {

  name: {
    en: 'Settings',
    ru: 'Настройки',
    hi: 'सेटिंग्स',
    es: 'Configuración',
    de: 'Einstellungen',
    fr: 'Paramètres',
    nl: 'Instellingen',
    tr: 'Ayarlar',
    pt: 'Configurações',
    pl: 'Nastawy',
    ht: 'Ajisteman',
    it: 'Impostazioni',
    ko: '설정',
    cs: 'Nastavení',
    ja: '設定',
    sv: 'Inställningar',
    bg: 'Настройки',
    el: 'Ρυθμίσεις',
    tl: 'Mga setting',
    ro: 'Setări',
    da: 'Indstillinger',
    zh: '设置',
    hu: 'Beállítások'
  },

  // ---- Controls
  controls: {
    en: 'Controls',
    ru: 'Управление',
    hi: 'नियंत्रण',
    es: 'Controles',
    de: 'Kontrollen',
    fr: 'Contrôles',
    tr: 'Kontroller',
    nl: 'Bediening',
    pt: 'Controlos',
    pl: 'Sterownica',
    ht: 'Kontwòl yo',
    it: 'Regolazione',
    ko: '통제 수단',
    cs: 'Řízení',
    ja: 'コントロール',
    sv: 'Kontroll',
    bg: 'Контроли',
    el: 'διακόπτης',
    tl: 'Mga kontrol',
    ro: 'Controale',
    da: 'Controls',
    zh: '控制',
    hu: 'Irányítás'
  },

  keybindings: {
    en: 'Key bindings',
    ru: 'Привязки клавиш',
    pt: 'Combinações de teclas',
    fr: 'Assignation des touches',
    nl: 'Knop verbindingen',
    hu: 'Billentyűparancsok',
    es: 'Atajos de teclado'
  },

  pointerlock: {
    en: 'Hide mouse during rotation',
    ru: 'Скрыть мышь во время вращения',
    pt: 'Ocultar o rato durante a rotação.',
    fr: 'Cacher la souris pendant les rotations',
    nl: 'Verstop rechter muis knop tijdens rotatie',
    hu: 'Egérmutató elrejtése forgáskor',
    es: 'Ocultar el mouse durante la rotación'
  },

  lockedcamera: {
    en: 'Locked camera',
    ru: 'Заблокированная камера',
    hi: 'कैमरा लॉक',
    es: 'Cámara fija',
    de: 'Gesperrte Kamera',
    fr: 'Caméra verrouillée',
    tr: 'Kilitli kamera',
    nl: 'Gesloten camera',
    pt: 'Câmera bloqueada',
    pl: 'Zamknięta kamera',
    ht: 'Kamera fèmen',
    it: 'Telecamera bloccata',
    ko: '잠긴 카메라',
    cs: 'Zamknutá kamera',
    ja: 'ロックカメラ',
    sv: 'Låst kamera',
    bg: 'Заключена камера',
    el: 'Κλειδωμένη κάμερα',
    tl: 'Naka-lock na camera',
    ro: 'Blochează camera',
    da: 'Låst kamera',
    zh: '锁定相机',
    hu: 'Lezárt kamera'
  },

  // ---- Graphics
  graphics: {
    en: 'Graphics',
    ru: 'Графика',
    hi: 'ग्राफ़िक्स',
    es: 'Gráficos',
    de: 'Grafik',
    fr: 'Graphiques',
    nl: 'Grafischen',
    tr: 'Grafikler',
    pt: 'Gráficos',
    pl: 'Grafika',
    ht: 'Grafik',
    it: 'Grafica',
    ko: '제도법',
    cs: 'Grafika',
    ja: 'グラフィックス',
    sv: 'Grafik',
    bg: 'Графика',
    el: 'Γραφικών',
    tl: 'Grapika',
    ro: 'Grafică',
    da: 'Grafik',
    zh: '图像',
    hu: 'Grafika'
  },

  viewrange: {
    en: 'View range',
    ru: 'Дальность прорисовки',
    de: 'Sichtweite',
    nl: 'Weergavebereik',
    pt: 'Distância de visão',
    pl: 'Zakres widoków',
    it: 'Visualizza la gamma',
    ro: 'Câmp vizual',
    es: 'Ver rango',
    sv: 'Visa intervall',
    el: 'Προβολή εύρους',
    bg: 'Преглед на обхвата',
    cs: 'Zobrazit rozsah',
    hi: 'नज़र सीमा',
    fr: 'Champ de vision',
    tr: 'Görüş mesafesi',
    ht: 'Je ranje',
    ko: '범위보기',
    ja: '表示範囲',
    tl: 'Tingnan ang saklaw',
    da: 'Omfang af synet',
    zh: '远景范围',
    hu: 'Látótávolság'
  },

  resolution: {
    en: 'Resolution',
    ru: 'Разрешение',
    hi: 'रेसोलूशन',
    es: 'Resolución',
    de: 'Auflösung',
    fr: 'Résolution',
    nl: 'Resolutie',
    tr: 'Çözünürlük',
    pt: 'Resolução',
    pl: 'Rozdzielczość',
    ht: 'Rezolisyon an',
    it: 'Delibera',
    ko: '게임의 해상도',
    cs: 'Rozlišení',
    ja: '解決',
    sv: 'Upplösning',
    bg: 'Резолюция',
    el: 'Ανάλυση',
    tl: 'Resolution',
    ro: 'Rezoluție',
    da: 'Løsning',
    zh: '解析度',
    hu: 'Felbontás'
  },

  postprocessing: {
    en: 'Post-processing',
    de: 'Nachbearbeitung',
    ru: 'Постобработка',
    tr: 'Detaylandırma',
    fr: 'Post-traitement',
    pt: 'Pós-processamento.',
    nl: 'Nawerking',
    hu: 'Elő-tömörítés',
    es: 'Publicar-procesamiento'
  },

  skilleffects: {
    en: 'Skill Effects',
    ru: 'Эффекты Навыков',
    hi: 'स्किल दिखावट',
    es: 'Efectos de Habilidades',
    de: 'Fertigkeitseffekte',
    fr: 'Effets de Habiletés',
    nl: 'Vaardigheidseffecten',
    tr: 'Yetenek Efektleri',
    pt: 'Efeitos de Habilidade',
    pl: 'Efekty Umiejętności',
    ht: 'Efè Konpetans',
    it: 'Effetti di Abilità',
    ko: '기술 효과',
    cs: 'Dovednostní Efekty',
    ja: 'スキル効果',
    sv: 'Färdighetseffekter',
    bg: 'Ефекти',
    el: 'Επιπτώσεις δεξιοτήτων',
    tl: 'Mga epekto sa kasanayan',
    ro: 'Efectele Abilităților',
    da: 'Færdighedseffekter',
    zh: '技能影响',
    hu: 'Képesség effektusok'
  },

  shadows: {
    en: 'Shadows',
    ru: 'Тени',
    fr: 'Ombres',
    pt: 'Sombras',
    nl: 'Schaduwen',
    hu: 'Árnyékok'
  },

  ssao: {
    en: 'Ambient Occlusion',
    ru: 'Окружающая Окклюзия',
    fr: 'Occlusion Ambiante',
    pt: 'Oclusão Ambiental',
    nl: 'Omgevingsocclusie',
    hu: 'Környezet okklúzió',
    es: 'Oclusión Ambiental'
  },

  grass: {
    en: 'Grass',
    ru: 'Трава',
    fr: 'Herbe',
    pt: 'Grama',
    nl: 'Gras',
    hu: 'Fű',
    es: 'Hierba'
  },

  clouds: {
    en: 'Clouds',
    ru: 'Облака',
    fr: 'Nuages',
    pt: 'Nuvens',
    nl: 'Wolken',
    hu: 'Felhők',
    es: 'Nubes'
  },

  particles: {
    en: 'Particles',
    ru: 'Частицы',
    fr: 'Particules',
    pt: 'Partículas',
    nl: 'Deeltjes',
    hu: 'Effekt-részecskék',
    es: 'Partículas'
  },

  detailprops: {
    en: 'Detail props',
    ru: 'Детальные пропи',
    nl: 'Detail Voorwerpen',
    hu: 'Részletes objektumok',
    es: 'Accesorios de detalle'
  },

  // ---- Audio
  audio: {
    en: 'Audio',
    ru: 'Звук',
    de: 'Ton',
    nl: 'Geluid',
    pt: 'Áudio',
    pl: 'Dźwięk',
    it: 'Audio',
    ro: 'Audio',
    es: 'Audio',
    sv: 'Ljud',
    el: 'Ήχος',
    bg: 'звуков',
    cs: 'Вук',
    hi: 'आवाज़',
    fr: 'Audio',
    tr: 'Ses',
    ht: 'Audio',
    ko: '오디오',
    ja: 'オーディオ',
    tl: 'Audio',
    da: 'Lyd',
    zh: '音频',
    hu: 'Hang'
  },

  sfxvolume: {
    en: 'SFX Volume',
    ru: 'Громкость Эффектов',
    de: 'SFX Lautstärke',
    nl: 'SFX Volume',
    pt: 'Volume de SFX',
    pl: 'Objętość SFX',
    it: 'Volume SFX',
    ro: 'Volum SFX',
    es: 'Volumen SFX',
    sv: 'SFX-volym',
    el: 'Ενταση SFX',
    bg: 'гръмкостта SFX',
    cs: 'Objem SFX',
    hi: 'इफैक्ट्स की आवाज़',
    fr: 'Volume des effets sonores',
    tr: 'SFX Ses Gücü',
    ht: 'Volim SFX',
    ko: 'SFX 볼륨',
    ja: 'SFXボリューム',
    tl: 'Dami ng SFX',
    da: 'Volumen af SFX',
    hu: 'SFX-hangerő '
  },

  // ---- Chat
  chat: {
    en: 'Chat',
    ru: 'Чат',
    hi: 'चैट',
    es: 'Chat',
    de: 'Chat',
    fr: 'Chat',
    nl: 'Chat',
    tr: 'sohbet',
    pt: 'Chat',
    pl: 'pogawędka',
    ht: 'Chat',
    it: 'Chiacchierata',
    ko: '잡담',
    cs: 'Chatu',
    ja: 'チャット',
    sv: 'Chatt',
    bg: 'чат',
    el: 'κουβέντα',
    tl: 'Chat',
    ro: 'Chat',
    da: 'Chat',
    hu: 'Cset'
  },

  chatbubbles: {
    en: 'Show chat bubbles',
    ru: 'Показавать чат пузеры',
    fr: 'Afficher les bulles de chat',
    pt: 'Mostrar bolhas de chat',
    nl: 'Laat chat bubbels zien',
    hu: 'Csetbuborékok mutatása'
  },

  combatlog: {
    en: 'Combat Log',
    ru: 'Боевой лог',
    nl: 'Gevechts log',
    hu: 'Harci kisnapló',
    es: 'Registro de combate'
  },

  // ---- User interface
  interface: {
    en: 'Interface',
    ru: 'Интерфейс',
    de: 'Interface',
    pt: 'Interface',
    pl: 'Interfejs',
    nl: 'Interface',
    it: 'interfaccia',
    ro: 'Interfață',
    es: 'Interfaz',
    sv: 'Gränssnitt',
    el: 'Διεπαφή',
    bg: 'интерфейс',
    cs: 'Rozhraní',
    hi: 'अन्तराफलक',
    fr: 'Interface',
    tr: 'Arayüzey',
    ht: 'Entèfas',
    ko: '인터페이스',
    ja: 'インタフェース',
    tl: 'Interface',
    da: 'Grænseflade',
    hu: 'Felület'
  },

  language: {
    en: 'Language',
    ru: 'Язык',
    de: 'Sprache',
    nl: 'Taal',
    pt: 'Idioma',
    pl: 'Język',
    it: 'Lingua',
    ro: 'Limbă',
    es: 'Idioma',
    sv: 'Språk',
    el: 'Γλώσσα',
    bg: 'език',
    cs: 'Jazyk',
    hi: 'भाषा',
    fr: 'Langue',
    tr: 'Dil',
    ht: 'Lang',
    ko: '언어',
    ja: '言語',
    tl: 'Wika',
    da: 'Sprog',
    hu: 'Nyelv'
  },

  invwidth: {
    en: 'Inventory width',
    ru: 'Ширина инвентаря',
    de: 'Inventar Breite',
    nl: 'Inventarisbreedte',
    pt: 'Largura do inventário',
    pl: 'Szerokość inwentarza',
    it: 'Larghezza dell\'inventario',
    ro: 'Lățimea inventarului',
    es: 'Ancho de inventario',
    sv: 'Inventariebredd',
    el: 'Εύρος αποθέματος',
    bg: 'Ширина инвентаря',
    cs: 'Šířka inventáře',
    hi: 'वस्तुसूची की चौड़ाई',
    fr: 'Largeur de l\'inventaire',
    tl: 'Lapad ng Imbentaryo',
    da: 'Lagerbredde',
    ko: '인벤토리 너비',
    ht: 'Lajè Envantè',
    ja: '在庫の幅',
    hu: 'Hátizsák szélesség'
  },

  tutorial: {
    en: 'Tutorial',
    ru: 'Обучение',
    hi: 'शिक्षण',
    es: 'Tutorial',
    de: 'Tutorial',
    fr: 'Tutoriel',
    nl: 'Handleiding',
    tr: 'Öğretici',
    pt: 'Tutorial',
    pl: 'Przewodnik',
    ht: 'Leson patikilye',
    it: 'Tutorial',
    ko: '지도 시간',
    cs: 'Výuku',
    ja: 'チュートリアル',
    sv: 'Handledning',
    bg: 'Учение',
    el: 'φροντιστήριο',
    tl: 'Pagtuturo',
    ro: 'Tutorial',
    da: 'Tutorial',
    hu: 'Bemutató'
  },

  resettutorial: {
    en: 'Reset tutorial',
    ru: 'Начать обучение заново',
    hi: 'शिक्षण रीसेट',
    es: 'Reiniciar tutorial',
    de: 'Tutorial zurücksetzen',
    fr: 'Réinitialiser le tutoriel',
    nl: 'Reset handleiding',
    tr: 'Öğreticiyi sıfırla',
    pt: 'Recomeçar o tutorial',
    pl: 'resetowanie samouczka',
    ht: 'Reset tutorial',
    it: 'Ripristina tutorial',
    ko: '재설정 자습서',
    cs: 'Obnovit výuku',
    ja: 'チュートリアルをリセット',
    sv: 'Återställ handledningen',
    bg: 'Нулиране на урока',
    el: 'επαναφορά φροντιστήριο',
    tl: 'i-reset ang tutorial',
    ro: 'Resetează tutorialul',
    da: 'Nulstil tutorial',
    hu: 'Bemutató újrakezdése'
  },

  disabletutorial: {
    en: 'Disable tutorial',
    ru: 'Отключить обучения',
    tr: 'Öğreticiyi kapat',
    fr: 'Désactiver le tutoriel',
    pt: 'Desativar o tutorial',
    nl: 'Handleiding uitschakelen',
    hu: 'Bemutató elrejtése',
    es: 'Desactivar tutorial'
  },

  // ---- map
  maplowqual: {
    en: 'Low quality mode',
    ru: 'Режим низкого качества',
    hu: 'Alacsony minőségű mód',
    pt: 'Modo de qualidade baixa',
    fr: 'Mode basse qualité',
    nl: 'Lage kwaliteit modus',
    es: 'Modo de baja calidad'
  },

  mapshowmonsters: {
    en: 'Show monsters',
    ru: 'Показывать монстров',
    hu: 'Szörnyek mutatása',
    pt: 'Mostrar monstros',
    fr: 'Afficher les monstres',
    nl: 'Laat monsters zien',
    es: 'Mostrar monstruos'
  }
}
