export default {

  waitunstash: {
    en: 'You have to wait until you can retrieve this item.',
    de: 'Du musst noch etwas warten, bis du dieses Item nehmen kannst.',
    ru: 'Вы должны подождать перед тем как вы можете получить этот предмет',
    tl: 'Kailangan mong maghintay hanggang sa maari mong ma-retreive ang item na ito.',
    pt: 'Você tem que esperar até que você possa recuperar este item.',
    it: 'Devi aspettare di poter recuperare questo articolo.',
    pl: 'Musisz poczekać, aż będziesz mógł odzyskać ten przedmiot.',
    fr: 'Vous devez attendre jusqu\'à ce que vous puissiez récupérer cet objet"',
    es: 'Tiene que esperar hasta que pueda recuperar este elemento.',
    nl: 'Je moet wachten tot je dit item kan terugvinden.',
    sv: 'Du måste vänta innan du kan hämta det här föremålet.',
    bg: 'Трябва да изчакате докато изтеглите този елемент.',
    cs: 'Musíte počkat, dokud tuto položku nelze načíst.',
    ko: '이 항목을 가져올 때까지 기다려야합니다.',
    ja: 'このアイテムを取得できるようになるまで待つ必要があります。',
    hi: 'आपको इस आइटम को पुनः प्राप्त करने तक इंतजार करना होगा।',
    ro: 'Trebuie să aștepți până să poți recupera acest obiect.',
    ht: 'Ou dwe rete jiskaske ou ka rekipere atik sa a.',
    el: 'Πρέπει να παρακολουθείτε μέχρι να μπορείτε να ανακτήσετε αυτό το στοιχείο.',
    da: 'Du skal til, indtil du kan hente denne vare.'
  },

  withdraw: {
    en: 'Withdraw',
    nl: 'Terugtrekken',
    de: 'Abheben',
    ru: 'Забрать',
    tl: 'Mag-withdraw',
    es: 'Retirar',
    fr: 'Retirer',
    pt: 'Retirar',
    it: 'Ritirare',
    pl: 'Wycofanie',
    sv: 'Retirera',
    ro: 'Retrage',
    hi: 'निकालना',
    ko: '빼다',
    tr: 'Çekil',
    ht: 'Retire',
    cs: 'Ustoupit',
    ja: '撤回',
    el: 'Αποσύρω',
    bg: 'Теглене',
    da: 'Træk'
  },

  stash: {
    en: 'Move to stash',
    de: 'Bewegung zur Brust',
    ru: 'Положить в сундук',
    pt: 'Mover para o esconderijo',
    it: 'Spostare a nascondiglio',
    pl: 'Przenieś się do skrytki',
    fr: 'Aller dans la planque',
    es: 'Mover a su alijo',
    nl: 'Verhuizen naar opslagplaats',
    ko: '은신처로 이동하십시오',
    sv: 'Flytta till skattkista',
    ht: 'Deplase nan catcher',
    hi: 'स्टैश में भेजें',
    tl: 'Ilipat sa itago',
    el: 'Μετακίνηση στο θησαυρός',
    bg: 'Преместване в скривалище',
    cs: 'Přesuňte se na skrýš',
    ja: '隠し場所に移動',
    ro: 'Mută în ascunzătoare.',
    da: 'Flyt til stash'
  },

  stashed: {
    en: '$1 has been moved to your stash',
    de: '$1 wurde in deinen Speicher verschoben',
    ru: '$1 Было перенесено в сундук',
    pt: '$1 foi transferido para o seu esconderijo',
    it: '$1 e\' stato spostato nella tua scorta',
    pl: '$1 został przeniesiony do twojego magazynu',
    fr: '$1 a été transféré dans votre planque',
    es: '$1 ha sido movido al alijo',
    nl: '$1 is verplaatst naar je voorraad',
    hi: '$1 को स्टैश में भेज दिया गया है',
    tl: 'Ang $1 ay inilipat sa iyong itago',
    sv: '$1 har flyttats till din stash',
    ro: '$1 a fost mutat în ascunzătoare',
    ht: '$1 te deplase nan catcher ou',
    cs: '$1 byl přesunut na vaši skrýš',
    ja: '$1 はあなたの隠し場所に移動しました',
    el: '$1 έχει μεταφερθεί στη θέση σας',
    bg: '$1 е преместен в скривалището ви',
    da: '$1 er flyttet til din stash',
    ko: '$1 가 숨겨지기로 옮겼습니다.'
  }

}
