export default {

  waitunstash: {
    en: 'You have to wait until you can retrieve this item.',
    de: 'Du musst noch etwas warten, bis du dieses Item nehmen kannst.',
    ru: 'Вы должны подождать перед тем как вы можете получить этот предмет.',
    tl: 'Kailangan mong maghintay hanggang sa maari mong ma-retreive ang item na ito.',
    pt: 'Você tem de esperar até que possa recuperar este item.',
    it: 'Devi aspettare di poter recuperare questo articolo.',
    pl: 'Musisz poczekać, aż będziesz mógł odzyskać ten przedmiot.',
    fr: 'Vous devez attendre jusqu\'à ce que vous puissiez récupérer cet objet',
    es: 'Tiene que esperar hasta que pueda recuperar este elemento.',
    nl: 'Je moet wachten tot je dit item kan terugvinden.',
    sv: 'Du måste vänta innan du kan hämta det här föremålet.',
    bg: 'Трябва да изчакате докато изтеглите този елемент.',
    cs: 'Musíte počkat, dokud tuto položku nelze načíst.',
    ko: '이 항목을 가져올 때까지 기다려야합니다.',
    ja: 'このアイテムを取得できるようになるまで待つ必要があります。',
    hi: 'आपको इस आइटम को पुनः प्राप्त करने तक इंतजार करना होगा।',
    ro: 'Trebuie să aștepți până să poți recupera acest obiect.',
    ht: 'Ou dwe rete jiskaske ou ka rekipere atik sa a.',
    el: 'Πρέπει να παρακολουθείτε μέχρι να μπορείτε να ανακτήσετε αυτό το στοιχείο.',
    da: 'Du skal til, indtil du kan hente denne vare.',
    zh: '您必须等到可以取回这个装备。',
    hu: 'Várnod kell még hogy visszaszerezhesd ezt a tárgyat.'
  },

  withdraw: {
    en: 'Withdraw',
    nl: 'Terugtrekken',
    de: 'Abheben',
    ru: 'Забрать',
    tl: 'Mag-withdraw',
    es: 'Retirar',
    fr: 'Retirer',
    pt: 'Retirar',
    it: 'Ritirare',
    pl: 'Wycofanie',
    sv: 'Retirera',
    ro: 'Retrage',
    hi: 'निकालना',
    ko: '빼다',
    tr: 'Çekil',
    ht: 'Retire',
    cs: 'Ustoupit',
    ja: '撤回',
    el: 'Αποσύρω',
    bg: 'Теглене',
    da: 'Træk',
    zh: '退出',
    hu: 'Pénz Kivétele'
  },

  // Do not translate "Stash".
  stash: {
    en: 'Move to Stash',
    de: 'Bewegung zur Stash',
    ru: 'Положить в Stash',
    pt: 'Mover para o baú',
    it: 'Spostare a Stash',
    pl: 'Przenieś się do Stash',
    fr: 'Aller dans la Stash',
    es: 'Mover a su Stash',
    nl: 'Verhuizen naar Stash',
    ko: '은신처로 이동하십시오',
    sv: 'Flytta till Stash',
    ht: 'Deplase nan Stash',
    hi: 'स्टैश में भेजें',
    tl: 'Ilipat sa Stash',
    el: 'Μετακίνηση στο θησαυρός',
    bg: 'Преместване в Stash',
    cs: 'Přesuňte se na Stash',
    ja: '隠し場所に移動',
    ro: 'Mută în Stash.',
    da: 'Flyt til Stash',
    zh: '转到保管',
    hu: 'Stash küldés'
  },

  // Do not translate "Stash".
  stashed: {
    en: '$1 has been moved to your Stash.',
    de: '$1 wurde in deinen Stash verschoben.',
    ru: '$1 Было перенесено в Stash.',
    pt: '$1 foi transferido para o seu Stash.',
    it: '$1 e\' stato spostato nella tua Stash.',
    pl: '$1 został przeniesiony do twojego Stash.',
    fr: '$1 a été transféré dans votre Stash.',
    es: '$1 ha sido movido al Stash.',
    nl: '$1 is verplaatst naar je Stash.',
    hi: '$1 को स्टैश में भेज दिया गया है',
    tl: 'Ang $1 ay inilipat sa iyong itago.',
    sv: '$1 har flyttats till din Stash.',
    ro: '$1 a fost mutat în Stash.',
    ht: '$1 te deplase nan Stash ou.',
    cs: '$1 byl přesunut na vaši Stash.',
    ja: '$1 はあなたの隠し場所に移動しました',
    el: '$1 έχει μεταφερθεί στη θέση σας.',
    bg: '$1 е преместен в Stash ви.',
    da: '$1 er flyttet til din Stash.',
    ko: '$1 가 숨겨지기로 옮겼습니다.',
    zh: '$1 被转移到了你的保管',
    hu: 'A Stash fiókodba került: $1'
  }

}
