// Work in progress, do not translate
export default {
  msg: [
    {en: 'Welcome! Press <kbd>W A S D</kbd> or <kbd>⭠ ⭢ ⭡ ⭣</kbd> to move.'},
    {en: 'Great job! Now, <kbd>left/right click</kbd> and drag your mouse to rotate the camera.'},
    {en: 'I can tell you will be good at this. To prepare you for combat, I will explain some basic UI elements.'},
    {en: 'This is your unit frame. You can see your own health and mana here.'},
    {en: 'Move out of the base and target a monster by clicking it with your mouse.'},
    {en: 'This monster is now your target. Any offensive spells you cast will be directed at your target.'},
    {en: 'You can attack by pressing the keys indicated on your skillbar. Press <kbd>1</kbd> on your keyboard to attack the monster!'},
    {en: 'Perfect! Keep it up and deal with the monster!'},
    {en: 'Nice job. You have been rewarded with experience points.'},
    {en: 'Collect enough experience points and you will level up.'},
    {en: 'Monsters can leave items and gold on the ground. Find an item! (Not gold)'},
    {en: 'You have picked up an item. Open your inventory (<kbd>B</kbd>) to see it.'},
    {en: 'Congratulations. You have opened the inventory. Here is your item.'},
    {en: 'Find a piece of equipment you can wear, right click it, and press "Equip item".'},
    {en: 'You have equipped the item. Open your character panel (<kbd>C</kbd>).'},
    {en: 'You can see all equipped items in your character panel.'},
    {en: 'Next, try to level up by killing monsters.'},
    {en: 'You have leveled up and earned stat points. Open your character panel (<kbd>C</kbd>) again.'},
    {en: 'Stat points can be used to increase your primary stats. Hover over the buttons to preview their effects, then use your stat points.'},
    {en: 'Next, we will teach you how to learn new skills. First, level up until you unlock a new skill.'},
    {en: 'A new skill is available. You need to use books to learn new skills.'},
    {en: 'Collect some items and coins. You need 32 coins for your first book. You can sell items to the trader as well.'},
    {en: 'You have enough coins. Go back to your base, and  talk to the trader (purple NPC with a backpack) to buy your new skill book. '},
    {en: 'The trader sells skill books, potions, and mounts. Right-click the book to buy it.'},
    {en: 'Once you have the book, open your inventory, right-click the book and press <kbd>Learn skill</kbd> to learn it.'},
    {en: 'Skillful. Close the Trader Window, then open your skill panel (<kbd>K</kbd>) to see an overview of your skills.'},
    {en: 'Here you can see your skills. Hover over them for additional information. Skills usually require one Skill point, which you earn once every two levels'},
    {en: 'You can click and drag a skill icon into your skillbar. We already did it for you, but try it anyways!'},
    {en: 'You have learned a lot. You\'re almost ready to start your adventure.'},
    {en: 'Hordes is all about working in a party with other players. A party can help you level up.'},
    {en: 'A party of players will share experience and items, allowing them to be faster than solo players.'},
    {en: 'You can create or find a party with the party interface. Click on <kbd>Find Party</kbd> to automatically search one.'},
    {en: 'You can also invite players to your party by right-clicking on their unitframe, or using the command <kbd>/partyinvite</kbd>.'},
    {en: 'Partying will also allow you to share fame points in PVP combat.'},
    {en: 'Players of the other faction can be killed to earn fame and items (such as the crown) for your character.'},
    {en: 'You can also sell items to other players. You can visit the Merchant to do so.'},
    {en: 'Any items you buy at the merchant will be sent to your stash - a storage for your items and gold. It is a brown box located next to the merchant.'},
    {en: 'You will find runes when slaying monsters. Runes will allow you to upgrade your items. Visit the blacksmith to do so.'},
    {en: 'Coordination with players is important. You can use <kbd>/global</kbd>, <kbd>/party</kbd>, <kbd>/faction</kbd> and <kbd>/clan</kbd>. Press Enter to chat.'},
    {en: 'Type in your greatest battle shout. Then press enter to send your love letter to the world.'},
    {en: 'One last thing. See that cogwheel in the upper right corner? The game settings.'},
    {en: 'You can change many things here, such as the controls, language, or reducing the graphics.'},
    {en: 'Alright, close the settings again.'},
    {en: 'That\'s it. You did it. You are ready to slay. Your faction depends on you.'},
    {en: 'Good luck, champion.'}
  ]
}
