// Work in progress, do not translate
export default {
  msg: [
    {en: 'Welcome! Press <kbd>W A S D</kbd> or <kbd>⭠ ⭢ ⭡ ⭣</kbd> to move.'},
    {en: 'Great job! Now, <kbd>left/right click</kbd> and drag your mouse to rotate the camera.'},
    {en: 'To prepare you for combat, I will explain the UI elements.'},
    {en: 'This is your unit frame. You can see your own health and mana here.'},
    {en: 'Move forward and find a monster, then target it by clicking it with your mouse or pressing <kbd>TAB</kbd>.'},
    {en: 'This monster is now your target. Any spells you cast will be directed at your target.'},
    {en: 'You can attack by pressing the keys on your skillbar. Press <kbd>1</kbd> on your keyboard to attack the monster!'},
    {en: 'Perfect! Keep it up and deal with the monster!'},
    {en: 'Nice job. You have been rewarded with experience points.'},
    {en: 'Collect enough experience points and you will level up.'},
    {en: 'You can press <kbd>Shift</kbd> to see items and coins on the ground. Pick up an item! '},
    {en: 'You have picked up an item. Open your inventory (<kbd>B</kbd>) to see it.'},
    {en: 'Here you can see your items. The inventory size depends on the bag you have equipped.'},
    {en: 'You can equip items by right clicking them and selecting "Equip item".'},
    {en: 'Open your character panel (<kbd>C</kbd>).'},
    {en: 'You can see all equipped items in your character panel.'},
    {en: 'Next, try to level up by killing monsters.'},
    {en: 'You have leveled up and earned stat points. Open your character panel (<kbd>C</kbd>) again.'},
    {en: 'Stat points can be used to increase your primary stats. Hover over the buttons to preview their effects, then use your stat points.'},
    {en: 'Next, we will teach you how to learn new skills. First, level up to level 3 to unlock a new skill.'},
    {en: 'A new skill is available. You need to use books to learn new skills.'},
    {en: 'Collect some items and coins. You need 32 coins for your first book. You can sell items to the trader as well.'},
    {en: 'You have enough coins. Go back to your base, and  talk to the trader (purple NPC with a backpack) to buy your new skill book. '},
    {en: 'The trader sells skill books, potions, and mounts. Right-click the book to buy it.'},
    {en: 'Once you have the book, open your inventory, right-click the book and press <kbd>Learn skill</kbd> to learn it.'},
    {en: 'Close the Trader Window, then open your skill panel (<kbd>K</kbd>) to see an overview of your skills.'},
    {en: 'Here you can see your skills. Hover over them for additional information. Skills usually require one skill point, which you earn once every two levels'},
    {en: 'You can click and drag a skill into your skillbar. We already did it for you!'},
    {en: 'You have learned a lot. You\'re almost ready to start your adventure.'},
    {en: 'Hordes is all about working in a party with other players. A party can help you level up.'},
    {en: 'A party of players will share experience and items, allowing them to progress faster than solo players.'},
    {en: 'You can create or find a party with the party interface. Click on <kbd>Find Party</kbd> to automatically search one.'},
    {en: 'You can also invite players to your party by right-clicking on their unitframe, or using the command <kbd>/partyinvite</kbd>.'},
    {en: 'Partying will also allow you to share fame points in PVP combat.'},
    {en: 'Players of the other faction can be killed to earn fame and items (such as the crown) for your character.'},
    {en: 'You can also sell items to other players. You can visit the Merchant to do so.'},
    {en: 'Any items you buy at the merchant will be sent to your stash - a storage for your items and gold. It is a brown box located next to the merchant.'},
    {en: 'You will find runes when slaying monsters. Runes will allow you to upgrade your items. Visit the blacksmith to do so.'},
    {en: 'Coordination with players is important. You can use <kbd>/global</kbd>, <kbd>/party</kbd>, <kbd>/faction</kbd> and <kbd>/clan</kbd>. Press Enter to chat.'},
    {en: 'Type in your greatest battle shout. Then press enter to send your love letter to the world.'},
    {en: 'See the cogwheel in the upper right corner? Open your game settings.'},
    {en: 'You can change many things here, such as the controls, language, or reducing the graphics.'},
    {en: 'Alright, close the settings again.'},
    {en: 'That\'s it. You did it. You are ready to slay. Your faction depends on you.'},
    {en: 'Good luck, champion.'},
    {en: 'Congratulations on Lv. 25! You can now enter Headless Landing, a new world. Speak to the Conjurer in your base.'}
  ]
}
