export default {
  guided: {
    approachMonster: {
      en: 'Approach a monster',
      de: 'Geh zu einem Monster',
      ru: 'Подойди к монстру',
      zh: '接近一隻怪物',
      pt: 'Vá até o monstro',
      es: 'Acércate a un monstruo',
      fr: 'Approche du monstre',
      ro: 'Apropie-te de un monstru',
      it: 'Avvicinati a un mostro',
      nl: 'Benader een monster',
      vi: 'Tiến lại gần một quái vật',
      hu: 'Menj egy szörnyhöz',
      cs: 'Jdi k příšeře',
      pl: 'Podejdź do potwora'
    },
    targetMonster: {
      en: 'Target the monster',
      de: 'Wähle das Monster',
      ru: 'Выбери монстра',
      zh: '選取怪物',
      pt: 'Selecione o monstro',
      es: 'Selecciona el monstruo',
      fr: 'Cible le monstre',
      ro: 'Țintește monstrul',
      it: 'Seleziona il mostro',
      nl: 'Selecteer het monster',
      vi: 'Chọn quái vật',
      hu: 'Jelöld ki a szörnyet',
      cs: 'Zaměř příšeru',
      pl: 'Wybierz potwora'
    },
    castSkill: {
      en: 'Cast skill',
      de: 'Benutze einen Skill',
      ru: 'Примени навык',
      zh: '施放技能',
      pt: 'Use uma habilidade',
      es: 'Lanza una habilidad',
      fr: 'Lance une compétence',
      ro: 'Folosește o abilitate',
      it: 'Usa un\'abilità',
      nl: 'Gebruik een vaardigheid',
      vi: 'Dùng kỹ năng',
      hu: 'Használj képességet',
      cs: 'Použij dovednost',
      pl: 'Użyj umiejętności'
    },
    pickupWeapon: {
      en: 'Pick up the weapon',
      de: 'Waffe aufheben',
      ru: 'Подбери оружие',
      zh: '撿起武器',
      pt: 'Pegue a arma',
      es: 'Recoge el arma',
      fr: 'Ramasse l\'arme',
      ro: 'Ridică arma',
      it: 'Raccogli l\'arma',
      nl: 'Pak het wapen op',
      vi: 'Nhặt vũ khí',
      hu: 'Vedd fel a fegyvert',
      cs: 'Seber zbraň',
      pl: 'Podnieś broń'
    },
    showItemLabels: {
      en: 'Show items',
      de: 'Items anzeigen',
      ru: 'Покажи предметы',
      zh: '顯示物品',
      pt: 'Mostrar itens',
      es: 'Mostrar objetos',
      fr: 'Voir les objets',
      ro: 'Arată obiecte',
      it: 'Mostra oggetti',
      nl: 'Toon items',
      vi: 'Hiện vật phẩm',
      hu: 'Tárgyak mutatása',
      cs: 'Zobraz předměty',
      pl: 'Pokaż przedmioty'
    },
    moveCloser: {
      en: 'Move closer',
      de: 'Geh näher ran',
      ru: 'Подойди ближе',
      zh: '再靠近一點',
      pt: 'Aproxime-se',
      es: 'Acércate más',
      fr: 'Rapproche-toi',
      ro: 'Apropie-te',
      it: 'Avvicinati',
      nl: 'Kom dichterbij',
      vi: 'Đến gần hơn',
      hu: 'Menj közelebb',
      cs: 'Pojď blíž',
      pl: 'Podejdź bliżej'
    },
    openInventory: {
      en: 'Open inventory',
      de: 'Inventar öffnen',
      ru: 'Открой инвентарь',
      zh: '開啟物品欄',
      pt: 'Abra o inventário',
      es: 'Abre el inventario',
      fr: 'Ouvre l\'inventaire',
      ro: 'Deschide inventarul',
      it: 'Apri l\'inventario',
      nl: 'Open de inventaris',
      vi: 'Mở hành trang',
      hu: 'Nyisd ki a hátizsákot',
      cs: 'Otevři inventář',
      pl: 'Otwórz ekwipunek'
    },
    openCharacter: {
      en: 'Open character',
      de: 'Charakter öffnen',
      ru: 'Открой окно персонажа',
      zh: '開啟人物面板',
      pt: 'Abra a ficha',
      es: 'Abre la ficha',
      fr: 'Ouvre la fiche',
      ro: 'Deschide panoul',
      it: 'Apri la scheda',
      nl: 'Open personage',
      vi: 'Mở bảng nhân vật',
      hu: 'Nyisd meg a panelt',
      cs: 'Otevři panel postavy',
      pl: 'Otwórz panel postaci'
    },
    equipWeapon: {
      en: 'Equip the weapon',
      de: 'Waffe ausrüsten',
      ru: 'Экипируй оружие',
      zh: '裝備武器',
      pt: 'Equipe a arma',
      es: 'Equipa el arma',
      fr: 'Équipe l\'arme',
      ro: 'Echipează arma',
      it: 'Equipaggia l\'arma',
      nl: 'Rust het wapen uit',
      vi: 'Trang bị vũ khí',
      hu: 'Szereld fel a fegyvert',
      cs: 'Nasaď zbraň',
      pl: 'Załóż broń'
    },
    reachLevel: {
      en: 'Reach level $1',
      de: 'Erreiche Level $1',
      ru: 'Достигни уровня $1',
      zh: '達到 $1 級',
      pt: 'Alcance o nível $1',
      es: 'Alcanza el nivel $1',
      fr: 'Atteins le niveau $1',
      ro: 'Atinge nivelul $1',
      it: 'Raggiungi il livello $1',
      nl: 'Bereik level $1',
      vi: 'Đạt cấp $1',
      hu: 'Érd el a(z) $1. szintet',
      cs: 'Dosáhni úrovně $1',
      pl: 'Osiągnij poziom $1'
    },
    spendStats: {
      en: 'Spend all stat points',
      de: 'Verteile alle Stat-Punkte',
      ru: 'Распредели все статы',
      zh: '分配所有屬性點',
      pt: 'Gaste todos os pontos',
      es: 'Gasta todos los puntos',
      fr: 'Dépense tous tes points',
      ro: 'Distribuie toate punctele',
      it: 'Usa tutti i punti',
      nl: 'Besteed alle statpunten',
      vi: 'Dùng hết điểm tiềm năng',
      hu: 'Oszd el minden pontod',
      cs: 'Rozděl všechny staty',
      pl: 'Rozdaj wszystkie staty'
    },
    closeCharacter: {
      en: 'Close character',
      de: 'Charakter schließen',
      ru: 'Закрой окно персонажа',
      zh: '關閉人物面板',
      pt: 'Feche a ficha',
      es: 'Cierra la ficha',
      fr: 'Ferme la fiche',
      ro: 'Închide panoul',
      it: 'Chiudi la scheda',
      nl: 'Sluit personage',
      vi: 'Đóng bảng nhân vật',
      hu: 'Zárd be a karakterpanelt',
      cs: 'Zavři panel postavy',
      pl: 'Zamknij panel postaci'
    },
    closeInventory: {
      en: 'Close inventory',
      de: 'Inventar schließen',
      ru: 'Закрой инвентарь',
      zh: '關閉物品欄',
      pt: 'Feche o inventário',
      es: 'Cierra el inventario',
      fr: 'Ferme l\'inventaire',
      ro: 'Închide inventarul',
      it: 'Chiudi l\'inventario',
      nl: 'Sluit de inventaris',
      vi: 'Đóng hành trang',
      hu: 'Zárd be a hátizsákot',
      cs: 'Zavři inventář',
      pl: 'Zamknij ekwipunek'
    },
    collectCoins: {
      en: 'Collect coins',
      de: 'Sammle Münzen',
      ru: 'Собирай монеты',
      zh: '收集金幣',
      pt: 'Colete moedas',
      es: 'Recoge monedas',
      fr: 'Ramasse des pièces',
      ro: 'Colectează monede',
      it: 'Raccogli monete',
      nl: 'Verzamel munten',
      vi: 'Thu thập vàng',
      hu: 'Gyűjts érméket',
      cs: 'Sbírej mince',
      pl: 'Zbieraj monety'
    },
    talkTrader: {
      en: 'Talk to your class trader',
      de: 'Sprich mit dem Händler',
      ru: 'Поговори с торговцем',
      zh: '與職業商人交談',
      pt: 'Fale com o comerciante',
      es: 'Habla con el mercader',
      fr: 'Parle au marchand',
      ro: 'Vorbește cu negustorul',
      it: 'Parla al mercante',
      nl: 'Praat met de handelaar',
      vi: 'Nói với thương nhân lớp',
      hu: 'Beszélj a kereskedővel',
      cs: 'Promluv s obchodníkem',
      pl: 'Rozmawiaj z handlarzem'
    },
    buyBook: {
      en: 'Buy the skill book',
      de: 'Skillbuch kaufen',
      ru: 'Купи книгу способности',
      zh: '購買技能書',
      pt: 'Compre o livro',
      es: 'Compra el libro',
      fr: 'Achète le livre',
      ro: 'Cumpără cartea',
      it: 'Compra il libro abilità',
      nl: 'Koop vaardigheidsboek',
      vi: 'Mua sách kỹ năng',
      hu: 'Vedd meg a könyvet',
      cs: 'Kup knihu dovednosti',
      pl: 'Kup księgę umiejętności'
    },
    learnSkill: {
      en: 'Learn the skill',
      de: 'Skill lernen',
      ru: 'Изучи способность',
      zh: '學習技能',
      pt: 'Aprenda a habilidade',
      es: 'Aprende la habilidad',
      fr: 'Apprends la compétence',
      ro: 'Învață abilitatea',
      it: 'Impara l\'abilità',
      nl: 'Leer de vaardigheid',
      vi: 'Học kỹ năng',
      hu: 'Tanuld meg a képességet',
      cs: 'Nauč se dovednost',
      pl: 'Naucz się umiejętności'
    },
    useBook: {
      en: 'Use the skill book',
      de: 'Skillbuch benutzen',
      ru: 'Используй книгу',
      zh: '使用技能書',
      pt: 'Use o livro de habilidade',
      es: 'Usa el libro de habilidad',
      fr: 'Utilise le livre',
      ro: 'Folosește cartea',
      it: 'Usa il libro abilità',
      nl: 'Gebruik het boek',
      vi: 'Dùng sách kỹ năng',
      hu: 'Használd a könyvet',
      cs: 'Použij knihu dovednosti',
      pl: 'Użyj księgi umiejętności'
    },
    closeTrader: {
      en: 'Close shop',
      de: 'Händler schließen',
      ru: 'Закрой магазин',
      zh: '關閉商店',
      pt: 'Feche a loja',
      es: 'Cierra la tienda',
      fr: 'Ferme la boutique',
      ro: 'Închide magazinul',
      it: 'Chiudi il negozio',
      nl: 'Sluit de winkel',
      vi: 'Đóng cửa hàng',
      hu: 'Zárd be a boltot',
      cs: 'Zavři obchod',
      pl: 'Zamknij sklep'
    },
    openSkills: {
      en: 'Open skills',
      de: 'Skills öffnen',
      ru: 'Открой способности',
      zh: '開啟技能面板',
      pt: 'Abra as habilidades',
      es: 'Abre las habilidades',
      fr: 'Ouvre les compétences',
      ro: 'Deschide abilitățile',
      it: 'Apri le abilità',
      nl: 'Open de vaardigheden',
      vi: 'Mở bảng kỹ năng',
      hu: 'Nyisd ki a képességeket',
      cs: 'Otevři dovednosti',
      pl: 'Otwórz umiejętności'
    },
    activateSkill: {
      en: 'Activate the skill',
      de: 'Skill aktivieren',
      ru: 'Активируй способность',
      zh: '啟用技能',
      pt: 'Ative a habilidade',
      es: 'Activa la habilidad',
      fr: 'Active la compétence',
      ro: 'Activează abilitatea',
      it: 'Attiva l\'abilità',
      nl: 'Activeer de vaardigheid',
      vi: 'Kích hoạt kỹ năng',
      hu: 'Aktiváld a képességet',
      cs: 'Aktivuj dovednost',
      pl: 'Aktywuj umiejętność'
    },
    confirmSkills: {
      en: 'Confirm skills',
      de: 'Skills bestätigen',
      ru: 'Подтверди способности',
      zh: '確認技能',
      pt: 'Confirme as habilidades',
      es: 'Confirma las habilidades',
      fr: 'Valide les compétences',
      ro: 'Confirmă abilitățile',
      it: 'Conferma le abilità',
      nl: 'Bevestig skills',
      vi: 'Xác nhận kỹ năng',
      hu: 'Erősítsd meg',
      cs: 'Potvrď dovednosti',
      pl: 'Potwierdź umiejętności'
    },
    placeSkill: {
      en: 'Place the skill here',
      de: 'Skill hier ablegen',
      ru: 'Помести навык сюда',
      zh: '將技能放在這裡',
      pt: 'Coloque a habilidade',
      es: 'Coloca la habilidad aquí',
      fr: 'Place la compétence ici',
      ro: 'Pune abilitatea aici',
      it: 'Posiziona qui l\'abilità',
      nl: 'Plaats vaardigheid hier',
      vi: 'Đặt kỹ năng vào đây',
      hu: 'Helyezd ide a képességet',
      cs: 'Umísti dovednost sem',
      pl: 'Umieść umiejętność tutaj'
    },
    pickupSkill: {
      en: 'Pick up the skill',
      de: 'Skill nehmen',
      ru: 'Возьми способность',
      zh: '選取技能',
      pt: 'Pegue a habilidade',
      es: 'Selecciona la habilidad',
      fr: 'Choisis la compétence',
      ro: 'Selectează abilitatea',
      it: 'Seleziona l\'abilità',
      nl: 'Pak de vaardigheid op',
      vi: 'Chọn kỹ năng',
      hu: 'Vedd fel a képességet',
      cs: 'Uchop dovednost',
      pl: 'Chwyć umiejętność'
    },
    closeSkills: {
      en: 'Close skills',
      de: 'Skills schließen',
      ru: 'Закрой способности',
      zh: '關閉技能面板',
      pt: 'Feche as habilidades',
      es: 'Cierra las habilidades',
      fr: 'Ferme les compétences',
      ro: 'Închide abilitățile',
      it: 'Chiudi le abilità',
      nl: 'Sluit de vaardigheden',
      vi: 'Đóng bảng kỹ năng',
      hu: 'Zárd be a képességeket',
      cs: 'Zavři dovednosti',
      pl: 'Zamknij umiejętności'
    },
    selectSelf: {
      en: 'Select yourself',
      de: 'Wähle dich',
      ru: 'Выбери себя',
      zh: '選取自己',
      pt: 'Selecione-se',
      es: 'Selecciónate',
      fr: 'Sélectionne-toi',
      ro: 'Selectează-te',
      it: 'Selezionati',
      nl: 'Selecteer jezelf',
      vi: 'Chọn bản thân',
      hu: 'Jelöld ki magad',
      cs: 'Vyber sebe',
      pl: 'Wybierz siebie'
    },
    useNewSkill: {
      en: 'Use your new skill',
      de: 'Benutze den neuen Skill',
      ru: 'Примени новый навык',
      zh: '使用新技能',
      pt: 'Use sua nova habilidade',
      es: 'Usa tu nueva habilidad',
      fr: 'Utilise le nouveau talent',
      ro: 'Folosește noua abilitate',
      it: 'Usa la tua nuova abilità',
      nl: 'Gebruik de nieuwe skill',
      vi: 'Dùng kỹ năng mới',
      hu: 'Használd az új skillt',
      cs: 'Použij novou dovednost',
      pl: 'Użyj nowej umiejętności'
    },
    talkQuestGiver: {
      en: 'Talk to the quest giver',
      de: 'Sprich mit dem NPC',
      ru: 'Поговори с NPC',
      zh: '與任務發布者交談',
      pt: 'Fale com o NPC',
      es: 'Habla con el NPC',
      fr: 'Parle au PNJ',
      ro: 'Vorbește cu NPC-ul',
      it: 'Parla al mandante',
      nl: 'Praat met de questgever',
      vi: 'Nói với NPC nhiệm vụ',
      hu: 'Beszélj a küldetésadóval',
      cs: 'Promluv se zadavatelem',
      pl: 'Porozmawiaj z zadawcą'
    },
    acceptQuest: {
      en: 'Accept the quest',
      de: 'Quest annehmen',
      ru: 'Прими квест',
      zh: '接受任務',
      pt: 'Aceite a missão',
      es: 'Acepta la misión',
      fr: 'Accepte la quête',
      ro: 'Acceptă misiunea',
      it: 'Accetta la missione',
      nl: 'Accepteer de quest',
      vi: 'Nhận nhiệm vụ',
      hu: 'Fogadd el a küldetést',
      cs: 'Přijmi úkol',
      pl: 'Przyjmij zadanie'
    },
    findQuest: {
      en: 'Find the quest target',
      de: 'Questziel finden',
      ru: 'Найди цель квеста',
      zh: '尋找任務目標',
      pt: 'Encontre o objetivo da missão',
      es: 'Encuentra el objetivo',
      fr: 'Trouve l’objectif de quête',
      ro: 'Găsește obiectivul misiunii',
      it: 'Trova l’obiettivo',
      nl: 'Vind het questdoel',
      vi: 'Tìm mục tiêu nhiệm vụ',
      hu: 'Keresd meg a küldetés célját',
      cs: 'Najdi cíl úkolu',
      pl: 'Znajdź cel zadania'
    },
    click: {
      en: 'Click',
      de: 'Klick',
      ru: 'Нажать',
      zh: '點擊',
      pt: 'Clique',
      es: 'Clic',
      fr: 'Clic',
      ro: 'Clic',
      it: 'Clic',
      nl: 'Klik',
      vi: 'Nhấp',
      hu: 'Klikk',
      cs: 'Klik',
      pl: 'Kliknij'
    },
    rightClick: {
      en: 'Right-click',
      de: 'Rechtsklick',
      ru: 'ПКМ',
      zh: '按右鍵',
      pt: 'Clique direito',
      es: 'Clic derecho',
      fr: 'Clic droit',
      ro: 'Clic dreapta',
      it: 'Clic destro',
      nl: 'Rechtsklik',
      vi: 'Nhấp chuột phải',
      hu: 'Jobb klikk',
      cs: 'Pravý klik',
      pl: 'Kliknij prawym'
    },
    longPress: {
      en: 'Hold',
      de: 'Halten',
      ru: 'Удержать',
      zh: '長按',
      pt: 'Segure',
      es: 'Mantén',
      fr: 'Maintiens',
      ro: 'Ține apăsat',
      it: 'Tieni premuto',
      nl: 'Houd vast',
      vi: 'Nhấn giữ',
      hu: 'Tartsd nyomva',
      cs: 'Podrž',
      pl: 'Przytrzymaj'
    }
  }
}
