export default [
  {
    name       : {$$: 'Simple Wristbands' },
    description: {
      en: 'Cheap leather bands bought by an ambitious farmer.',
      ru: 'Дешевые кожаные ремешки, купленный амбициозным фермером.',
      es: 'Bandas de cuero baratas, compradas por un granjero ambicioso.',
      fr: 'Bandes en cuir bon marché acheté par un agriculteur ambitieux.',
      de: 'Billige Lederbänder, welche von einem ehrgeizigen Bauern gekauft wurde.',
      pt: 'Bandas de couro barato comprada por um fazendeiro ambicioso.',
      ko: '야심 찬 농부가 사들인 저렴한 가죽 밴드.',
      nl: 'Goedkope lederen bands gekocht door een ambitieuze boer.',
      pl: 'Tanie skórzane opaski kupiona przez ambitnego rolnika.',
      sv: 'Billiga läderband köpta av en ärelysten bonde.',
      ht: 'Gwoupman kwi bon mache te achte pa yon kiltivatè anbisye.',
      it: 'Cinturino in pelle a buon mercato comprato da un ambizioso contadino.',
      hi: 'एक महत्वाकांक्षी किसान द्वारा खरीदे गए सस्ते चमड़े के बैंड।',
      tl: 'Murang katad na mga banda na binili ng isang ambitious magsasaka.',
      el: 'Φτηνές δερμάτινες ζώνες που αγοράζονται από έναν φιλόδοξο αγρότη.',
      bg: 'Евтини кожени ленти, купена от амбициозен фермер.',
      cs: 'Levné kožené kapely koupil ambiciózní farmář.',
      ja: '野心的な農民によって買われた安い革バンド。',
      ro: 'Brățări de piele ieftină cumpărată de un fermier ambițios.',
      da: 'Billige læderbånd købt af en ambitiøs landmand.'
    }
  },

  {
    name       : {$$: 'Makeshift Armbands' },
    description: {
      en: 'Skilled hands made an intricate job at making these homemade cuffs.',
      ru: 'Опытные руки сделали сложную работу по изготовлению этих самодельных наручников.',
      es: 'Las manos expertas hicieron un trabajo complejo al hacer estos puños hechos en casa.',
      fr: 'Des mains habiles ont fait un travail complexe pour fabriquer ce brassard fait maison.',
      de: 'Geschickte Hände machten einen komplizierten Job bei der Herstellung dieser hausgemachten Manschetten.',
      pt: 'Mãos habilidosas faziam um trabalho complicado ao fazer esses punhos caseiros.',
      ko: '숙련 된 손은 수제 수갑을 만드는 데 복잡한 일을했습니다.',
      nl: 'Bekwame handen maakten een ingewikkelde klus bij het maken van deze zelfgemaakte manchetten.',
      pl: 'Wykwalifikowane ręce wykonały zawiłe zadanie przy wykonywaniu tych domowych mankietów.',
      sv: 'Skickligt hantverk ligger bakom dessa hemmagjorda armskydd.',
      tl: 'Ang mga skilled kamay ay gumawa ng isang masalimuot na trabaho sa paggawa ng mga homemade cuffs.',
      ht: 'Men kalifye te fè yon travay konplike nan fè pwaye endijèn sa yo.',
      it: 'Mani esperte hanno fatto un intricato lavoro nel realizzare questi polsini fatti in casa.',
      hi: 'कुशल हाथों ने इन होममेड कफ बनाने में एक जटिल काम किया।',
      cs: 'Kvalifikované ruce dělaly složitou práci při výrobě těchto domácích manžet.',
      el: 'Τα εξειδικευμένα χέρια έκαναν μια περίπλοκη δουλειά στην κατασκευή αυτών των σπιτικών μανικιών.',
      bg: 'Умели ръце направиха сложна работа, за да направят тези домашни маншети.',
      ja: '熟練した手はこれらの自家製の袖口を作ることにおいて複雑な仕事をしました。',
      ro: 'Niște mâini dibace au făcut o muncă complicată pentru realizarea acestor manșete de casă.',
      da: 'Færdige hænder gjorde et indviklet job ved at lave disse hjemmelavede manchetter.'
    }
  },

  {
    name       : {$$: 'Leather Armlets' },
    description: {
      en: 'Stiff, make your arms sore.',
      ru: 'Такие тугие, что твои руки начинают болеть.',
      es: 'Rígido, haz que te duela el brazo.',
      fr: 'Rigide, rend le bras douloureux.',
      de: 'Fest, mach deinen Hände wund.',
      pt: 'Rígido, dói-te no braço.',
      ko: '딱딱하고 팔을 아프게하십시오.',
      nl: 'Stijf, maak je arm pijnlijk.',
      pl: 'Sztywniak, bolit cię cała ręka.',
      sv: 'Styv, gör din vapen öm.',
      tl: 'Matigas ang ginagawa ng iyong braso.',
      ht: 'Sere sou tèlman bagay ke men ou kòmanse vin anfle.',
      it: 'Rigido, ti fa male al braccios.',
      hi: 'कठोर, अपनी बाहों को गाढ़ा करें।',
      cs: 'Ztuhlé, dělá svou ruki bolavou.',
      el: 'Σφίξτε τα χέρια σας.',
      bg: 'Скръв, направи ръцете си възпалени.',
      ja: '硬直して、腕を痛めます。',
      ro: 'Rigid, îți inflamează brațele.',
      da: 'Stiv, gør dine arme ømme.'
    }
  },

  {
    name       : {$$: 'Bone Bracelets' },
    description: {
      en: 'Elegant cuffs made from the tusks of the last mammoth.',
      ru: 'Элегантные наручники, сделаные из бивней последнего мамонта.',
      es: 'Unos puños elegantes creados con el comillo del mamut final.',
      fr: 'Menottes élégant fait à partir des défenses du dernier mammouth.',
      de: 'Elegante Manschetten aus den Stoßzähnen des letzten Mammuts.',
      pt: 'Elegantes algemas feitas das presas do último mamute.',
      ko: '마지막 매머드의 엄니부터 만들어진 우아한 커프스.',
      nl: 'Elegante manchetten gemaakt van de slagtanden van de laatste mammoet.',
      pl: 'Elegancki mankiety wykonany z kości ostatniego mamuta.',
      sv: 'Elegant manschetter gjord av tusenskönor från den sista mammoten.',
      tl: 'Elegante band na ginawa mula sa mga ngipin ng huling mammoth.',
      ht: 'Elegant pwaye nan defans ki sot pase yo mamout la.',
      it: 'Elegante polsini realizzato con le zanne dell ultimo mammut.',
      hi: 'अंतिम मैमथ के टस्क से बने सुरुचिपूर्ण कफ।',
      cs: 'Elegantní manžety vyrobená z kel posledního mamuta.',
      el: 'Κομψές μανσέτες από τα χέρια του τελευταίου μαμούθ.',
      bg: 'Елегантни маншети, направен от бивните на последния мамут.',
      ja: '最後のマンモスの牙から作られたエレガントな袖口。',
      ro: 'Manșetă elegantă confecționată din colții ultimului mamut.',
      da: 'Elegante manchetter lavet af tommelfingeren fra den sidste mammut.'
    }
  },

  {
    name       : {$$: 'Iron Vambraces' },
    description: {
      en: 'Heavy on your arms... worth the protection.',
      ru: 'Тяжёлые... но дают хорошую защиту.',
      es: 'Pesado en sus brazos... pero vale la protección.',
      fr: 'Pèse lourd sur votre bras... ça en vaut la protection.',
      de: 'Schwer auf den Händen... den Schutz wert.',
      pt: 'Pesado no braço...mas vale a pena a protecção.',
      ko: '팔에는 무겁지만... 보호가 그만한 가치가있다.',
      nl: 'Zwaar op je arm... de bescherming waard.',
      pl: 'Ciężko na twojej ręce... warte ochrony.',
      sv: 'Tung på armen ... värt skydd.',
      tl: 'Malakas sa iyong braso ... nagkakahalaga ng proteksyon.',
      tr: 'Kolunda ağır durur... koruma için değer.',
      ht: 'Lou... men vo defans yo.',
      it: 'Pesante sul braccio... vale la pena proteggerlo.',
      el: 'Βαρύ στο χέρι σου... αξίζει την προστασία.',
      bg: 'Тежка на ръце ти... си струваше защитата.',
      hi: 'हाथ पर भारी... पर सुरक्षा ज़रूर देता है।.',
      cs: 'Těžká na paži ... stojí za to.',
      ja: 'あなたの腕に重い...保護に値する。',
      ro: 'Grea pe braț... dar merită protecția.',
      da: 'Tung på dine arme... værd at beskytte.'
    }
  },

  {
    name       : {$$: 'Imbued Bracers' },
    description: {
      en: 'Dull metal bracer, handy for night time raiding.',
      ru: 'Тусклый металлический браслет, удобный для ночных рейдов.',
      es: 'Perfecto para correr en la noche, el color del metal está apagado.',
      fr: 'Brassard en métal terne, idéal pour les raids nocturnes.',
      de: 'Matte Metallarmschiene, praktisch für nächtliche Raubzüge.',
      pt: 'Braçadeira de metal aborrecida, útil para raides nocturnos.',
      ko: '무딘 금속 브레이 서, 야간의 습격에 편리합니다.',
      nl: 'Dof metalen bracer, handig voor nachtelijke overvallen.',
      sv: 'Dull metall bracer, praktisk för natten raiding.',
      tr: 'Donuk metal tutucu, gece baskını için kullanışlı.',
      pl: 'Nudny metalowy biustonosz, przydatny podczas nocnych nalotów.',
      tl: 'Mapurol na metal bracer na madaling gamitin para sa pag-atake ng gabi.',
      ht: 'Dim metal braslè, pratik pou atak lannwit.',
      it: 'Braccialetto in metallo opaco, comodo per i raid notturni.',
      hi: 'धातु का कुठिंत बाज़ूबंद, रात में हमला करने के लिए किफायती।.',
      cs: 'šikovný pro noční nájezdy.',
      el: 'Ελαφριές μεταλλικές λαβές εύχρηστες για νυχτερινές επιδρομές.',
      bg: 'Тъпа метална четка, удобна за нощно нападение.',
      ja: '夜間の襲撃に便利な鈍い金属製の装具。',
      ro: 'Manșetă anostă din metal, la îndemână pentru raidurile pe timp de noapte.',
      da: 'Kedelig metal bracer, praktisk til nat-time raiding.'
    }
  },

  {
    name       : {$$: 'Ember Cuffs' },
    description: {
      en: 'Scaled bracer, makes your arm resemble that of a dragon.',
      ru: 'Чешуйчатый наруч, делает вашу руку похоже на лапу дракона.',
      es: 'Muñequera escamosa, hace que su brazo aperece como un dragón.',
      fr: 'Brassard en écailles, qui fait ressembler votre bras à celui d\'un dragon.',
      de: 'Schuppiger Armschutz, lässt deine Arme an die eines Drachens erinnern.',
      pt: 'Braçadeira escamada, faz com que os teus braços se pareçam com os de um dragão.',
      ko: '스케일 된 브레이서는 팔을 용과 비슷하게 만듭니다.',
      nl: 'Geschaald bracer, maakt je armen lijken op die van een draak.',
      pl: 'Skalowany aparat ortodontyczny, sprawia, że twoje ramiona przypominajš smoka.',
      sv: 'Skalad bracer, gör att dina armar liknar den hos en drake.',
      tl: 'Ang pinaliit na bracer ay gumagawa ng iyong braso na katulad ng isang dragon.',
      tr: 'Ölçekli kol bağı, kollarınızı bir ejderhanınkine benzetir.',
      ht: 'Yon gwoup ponyèt pwopòsyonèl fè men ou sanble yon dragon an.',
      it: 'Il reggiseno in scala, ti fa assomigliare il braccio a quello di un drago.',
      hi: 'इस बाज़ुबंद से आपका हाथ बिल्कुल ड्रेगन की तरह लगेगा।',
      cs: 'Šupinatý šprýmař, tvá ruka se podobá tomu draka.',
      el: 'Κολλημένος κηδεμόνας κάνει το χέρι σου να μοιάζει με εκείνο ενός δράκου',
      bg: 'Мащабирането на ръката ви прилича на тази на дракон.',
      ja: '縮れたブレースはあなたの腕をドラゴンのそれに似せます。',
      ro: 'Manșetă acoperită cu solzi, îți face brațul să semene cu al unui dragon.',
      da: 'Skalet bracer, gør din arm lig den af en drage.'
    }
  },

  {
    name       : {$$: 'Mirrored Armlets' },
    description: {
      en: 'Blind your foes with a magical shine off a devious magicians mirror...',
      ru: 'Ослепляют ваших врагов блеском искривлённого магического зеркала...',
      es: 'Cega a sus enemigos con un brillo mágico de un espejo de mago astuto...',
      fr: 'Aveugle vos ennemis avec l\'éclat magique du miroir d\'un magicien sournois...',
      de: 'Blendet deine Feinde mit einem magischen Glanz von einem teuflischen Magierspiegel...',
      pt: 'Cega os teus inimigos com um brilho mágico de um espelho de um feiticeiro diabólico...',
      ko: '마법사애 거울이 부터있는 팔찌. 적의눈을 부시게 한다.',
      nl: 'Verblindt je vijanden met een magische glans van een slinkse goochelspiegel...',
      pl: 'Oślepia wrogów magicznym blaskiem od zdradzieckiego lusterka magów...',
      tl: 'Blinds iyong mga foes sa isang mahiwagang shine off ang isang palihis salamin magicians ...',
      sv: 'Blindar dina fiender med en magisk glans av en djävulsk trollkarlspegel...',
      tr: 'Düşmanlarınızı büyülü bir sihirbazın aynasından büyüleyen sihirli bir parıltıyla kör ediyor...',
      ht: 'Pèsyèn lènmi ou yo ak briye nan yon glas sere maji...',
      it: 'Acceca i tuoi nemici con una magica lucentezza da uno specchio di maghi subdoli...',
      hi: 'एक कुटिल जादूगर के आईने से उछलने वाली जादूई चमक आपके दुश्मनों को अंधा कर देगी।',
      cs: 'Slepí své nepřátele magickým zábleskem ze zlého kouzelnického zrcadla...',
      el: 'Τυφλώνει τους εχθρούς σου με μια μαγική λάμψη από έναν κακό καθρέφτη μάγων...',
      bg: 'Заслепява враговете си с магически блясък, отблъскващ отвратителен магьосник...',
      ja: '馬鹿げた魔術師の鏡からあなたの敵を魔法のように輝かせて盲目にします...',
      ro: 'Orbește adversarii cu o strălucire magică a unei oglinzi deviante a magicienilor.',
      da: 'Blind dine fjender med en magisk glans ud af et uhyggeligt tryllekunstner spejl ...'
    }
  },

  {
    name       : {$$: 'Golem Fragments' },
    description: {
      en: 'The ancient golems left remnants of their passing, which you unscrupulously have decided to wear on your arm.',
      ru: 'Древние големы оставили остатки своих похождений, которые вы бессовестно решили надеть на руку.',
      es: 'Los golems antiguos dejaron restos de su paso, que sin escrúpulos ha decido llevar en su brazo.',
      fr: 'Les géants anciens ont laissé des restes de leur passage, que vous avez sans scrupule décidé de porter sur votre bras.',
      de: 'Die alten Golems hinterließen Überreste ihres Ablebens, die du skrupellos auf deinem Arm getragen hast.',
      pt: 'Os antigos gigantes deixaram vestígios de sua passagem, que você, sem escrúpulos, decidiu usar em seu braço.',
      ko: '고대의 골렘들은 남은 자들을 떠났고, 당신은 부주의 한 태도로 팔에 끼기로 결정했습니다.',
      nl: 'De oude reuzen lieten restanten van hun overlijden achter, die je zonder scrupules op je arm hebt gedragen.',
      pl: 'Starożytnych gigantów zostawili po sobie resztki swojego odejścia, które bez skrupułów zdecydowaliście się nosić na ramieniu.',
      sv: 'De gamla golemerna lämnade resterna av deras passerar, som du skarpt har bestämt dig för att bära på din arm.',
      tr: 'Eski golemler, acımasızca kolunuza takmaya karar verdiğiniz pasajlarının kalıntılarını bıraktılar.',
      tl: 'Ang mga sinaunang golems ay iniwan ang mga labi ng kanilang pagpasa, na kung saan ikaw ay walang alinlangan ay nagpasiya na magsuot sa iyong braso.',
      ht: 'Golems yo ansyen kite sold nan pase yo, ki ou san skripil te deside mete sou bra ou.',
      it: 'I guardiani arcaici hanno lasciato i resti del loro passaggio, che avete deciso senza scrupoli di indossare sul vostro braccio.',
      hi: 'प्राचीन गोले ने उनके गुजरने के अवशेषों को छोड़ दिया, जिसे आपने अनजाने में अपनी बांह पर पहनने का फैसला किया है।',
      cs: 'Starověcí golemové zanechali pozůstatky svého průchodu, které jste bezohledně rozhodli nosit na paži.',
      el: 'Οι αρχαίοι golems άφησαν υπολείμματα από το πέρασμα τους, τα οποία εσείς ασυνείδητα έχετε αποφασίσει να φορέσετε στο χέρι σας.',
      bg: 'Древните големи оставиха остатъци от своето минаване, които безскрупулно сте решили да носите на ръката си.',
      ja: '古代のゴーレムは彼らの追い越しの残骸を残しました、あなたは不注意にあなたの腕に身に着けることに決めました。',
      ro: 'Golemii străvechi au lăsat rămășițe în urma lor, pe care tu, fără scrupule, ai decis să le porți pe braț.',
      da: 'De gamle golems forlod resterne af deres forbigående, som du uforskammeligt har besluttet at bære på din arm.'
    }
  },

  {
    name       : {$$: 'Coldforged Bracers' },
    description: {
      en: 'The deceptively light steel offers chilling protection against sneaky blows.',
      ru: 'Обманчиво легкая сталь предлагает охлаждающую защиту от подлых ударов.',
      fr: 'L\'acier léger et trompeur offre la protection contre les coups sournois.',
      es: 'El acero es engañosamente ligero y te ofrece protección frígido contra golpes furtivos.',
      de: 'Der trügerisch leichte Stahl bietet Kühlungsschutz gegen raffinierte Schläge.',
      pt: 'O aço enganosamente leve oferece proteção contra golpes furtivos.',
      ko: '믿을 수 없을만큼 가벼운 강철은 비열한 타격에 대한 차가운 보호를 제공합니다.',
      tl: 'Ang deceptively light steel ay nag-aalok ng pagpapanatiling proteksyon laban sa malupit na mga suntok.',
      nl: 'Het bedrieglijk lichte staal biedt koele bescherming tegen stiekeme klappen.',
      pl: 'Zwodniczo lekka stal oferuje ochronę przed podstępnymi uderzeniami.',
      sv: 'Det bedrägligt lätta stålet ger kylande skydd mot smutsiga slag.',
      tr: 'Aldatıcı hafif çelik, sinsi darbelere karşı soğutma koruması sunar.',
      ht: 'Engredyan asye limyè ofri refwadisman pwoteksyon kont kou lach.',
      it: 'L\'acciaio ingannevolmente leggero offre una protezione frigorifera contro i colpi subdoli.',
      hi: 'हलका-सा लगने वाला ये धातु भारी-भरकम रक्षण देता है।',
      cs: 'Klamně lehká ocel nabízí ochranu proti záludným úderům.',
      el: 'Ο απατηλά ελαφρύς χάλυβας προσφέρει προστασία ψύξης ενάντια στα κρυφά χτυπήματα',
      bg: 'Измамно леката стомана предлага охлаждаща защита срещу подъл удар.',
      ja: '一見軽い鋼は卑劣な打撃に対する低温保護を提供します。',
      ro: 'Oțelul înșelător de ușor oferă protecție revigorantă împotriva loviturilor viclene.',
      da: 'Det bedragerisk lette stål giver chillende beskyttelse imod snigende slag.'
    }
  },

  {
    name       : {$$: 'Blackstars' },
    description: {
      en: 'Stars are not often black, yet this fragment has a... deep... deep darkness.',
      ru: 'Звезды не часто черны, но этот фрагмент имеет... глубокую... глубокую тьму.',
      es: 'Normalmente, las estrellas no son negras, pero eso trozo tiene un intenso... intenso... oscuridad.',
      fr: 'Les étoiles ne sont pas souvent noires, mais ce fragment a une... très... très profonde obscurité.',
      de: 'Sterne sind nicht oft schwarz, aber dieses Fragment hat eine... tiefe... tiefe... tiefe Dunkelheit.',
      pt: 'As estrelas não são normalmente negras, mas este fragmento tem uma... profunda... profunda escuridão.',
      ko: '별은 종종 검은 색이 아니지만이 조각은 깊고... 또깊은 어둠이 있습니다.',
      tl: 'Ang mga bituin ay hindi madalas na itim ngunit ang fragment na ito ay may ... malalim ... malalim na kadiliman.',
      nl: 'Sterren zijn niet vaak zwart, maar toch heeft dit fragment een... diepe... diepe duisternis.',
      pl: 'Gwiazdy nie są często czarne, ale ten fragment ma... głęboką... głęboką ciemność.',
      sv: 'Tjärnor är inte ofta svarta, men detta fragment har en... djup... djup mörker.',
      tr: 'Yıldızlar genellikle siyah değildir, ancak bu parçanın derin ... derin bir karanlığı vardır.',
      ht: 'Zetwal yo pa souvan nwa, men fragman sa a gen ... gwo twou ... fon fènwa.',
      it: 'Le stelle non sono spesso nere, eppure questo frammento ha un... profondo buio profondo.',
      hi: 'सितारे अक्सर काले नहीं हैं, पर ये टुकड़ा...घना...घना काला है।',
      cs: 'Hvězdy nejsou často černé, ale tento fragment má hlubokou temnotu.',
      el: 'Τα αστέρια δεν είναι συχνά μαύρα αλλά το κομμάτι αυτό έχει... βαθύ σκοτάδι.',
      bg: 'Звездите често не са черни, но този фрагмент има... дълбока... дълбока тъмнина.',
      ja: '多くの場合、星は黒ではありませんが、この断片は...濃い...濃い暗さを持っています。',
      ro: 'Stelele nu sunt deseori negre, totuși acest fragment are o... adâncă... adâncă întunecime.',
      da: 'Stjerner er ikke ofte svarte, men dette fragment har et ... dybt ... dybt mørke.'
    }
  },

  {
    name       : {$$: 'Mobiuses' },
    description: {
      en: 'Reforged, lost, found, stolen, hidden for eras without end.',
      ru: 'Перекован, потерян, найден, украден, спрятан на века без конца.',
      es: 'Roto, rehecho, recubierto, robado, perdido por eras sin fin.',
      fr: 'Reforgé, perdu, trouvé, volé, caché depuis la nuit des temps.',
      de: 'Aufgearbeitet, verloren, gefunden, gestohlen, versteckt für unendliche Zeiten.',
      pt: 'Reforjado, perdido, encontrado, roubado, escondido por eras sem fim.',
      ko: '개조되고, 분실되고, 발견되고, 도난되고, 끝없는시간동안 숨겨젔다.',
      nl: 'Hervormd, verloren, gevonden, gestolen, verborgen voor tijdperken zonder einde.',
      tr: 'Yeniden dövülmüş, kaybolmuş, bulunmuş, sonu olmayan çağlardır gizlenmiş.',
      pl: 'Przeformułowane, zagubione, znalezione, skradzione, ukryte na całe epoki bez końca.',
      ht: 'Reforbe, pèdi, yo jwenn, yo vòlè li, kache pou syèk san fen.',
      tl: 'Reforged nawalang nakitang ninakaw na nakatago para sa panahon nang walang katapusan.',
      it: 'Riformato, perso, trovato, rubato, nascosto per epoche senza fine.',
      hi: 'वापस बनाया गया, खो दिया, मिल गया, चुरा लिया, और युगों युगों तक छिपाया है इसे।',
      cs: 'Reforged, ztracený, nalezený, ukradený, ukrytý pro éry bez konce.',
      el: 'Αναπροσανατολιστεί χαθεί βρεθεί κλαπεί κρυφτεί για τις εποχές χωρίς τέλος',
      bg: 'Открадната загуба, намерена открадната за епохи без край.',
      ja: '失われた遺失物は、終わりのない時代に隠されて盗まれました。',
      sv: 'Smidda, förlorade, hittade, stol, gömd för eroder utan slut.',
      ro: 'Refăurite, pierdute, găsite, furate, ascunse pentru ere fără sfârșit.',
      da: 'Reforged, lost, fundet, stjålet, skjult for epoker uden ende.'
    }
  },

  {
    name       : {$$: 'Guardians' },
    description: {
      en: 'This item was forged on a full moon when mysterious incantations were heard in the whispers of the dark. Some say that it was Anubis himself speaking with the dead.',
      ru: 'Этот предмет был выкован в полнолуние, когда в темноте раздавался шепот таинственных заклинаний. Некоторые говорят, что это был сам Анубис, говорящий с мертвыми.',
      es: 'Este artículo fue forjado en luna llena cuando se escucharon encantamientos misteriosos en los susurros de la oscuridad. Algunos dicen que fue Anubis mismo quien habló con los muertos.',
      fr: 'Cet objet a été forgé lors d\'une pleine lune quand des incantations mystérieuses ont été entendues dans les murmures de l\'obscurité. Certains disent que c\'était Anubis lui-même parlant avec les morts',
      de: 'Dieser Gegenstand wurde bei Vollmond geschmiedet, als im Flüstern der Dunkelheit mysteriöse Beschwörungen zu hören waren. Einige sagen, dass es Anubis selbst war, der mit den Toten sprach.',
      pt: 'Este item foi forjado numa lua cheia quando encantamentos misteriosos foram ouvidos nos sussurros da escuridão. Alguns dizem que foi o próprio Anubis falando com os mortos.',
      ko: '이 아이템은 어둠의 속삭임에서 신비한 주문을 들었을 때 보름달에 위조되었습니다. 어떤 사람들은 아누비스 자신이 죽은 자들과 이야기했다고합니다.',
      nl: 'Dit voorwerp werd gesmeed op volle maan toen mysterieuze bezweringen in het gefluister van de duisternis werden gehoord. Sommigen zeggen dat het Anubis zelf was die met de doden sprak.',
      pl: 'Ten przedmiot został wykuty w czasie pełni księżyca, gdy w szeptach ciemności usłyszano tajemnicze zaklęcia. Niektórzy mówią, że to sam Anubis mówił ze zmarłymi.',
      sv: 'Det här objektet smiddes på en fullmåne när mystiska incantations hördes i mörkets viskningar. Vissa säger att det var Anubis själv som talade med de döda.',
      tr: 'Bu eşya, karanlığın fısıltılarında gizemli sihirli sözler duyulduğunda, dolunayda dövüldü. Bazıları bunun ölülerle konuşan Anubis\'in kendisi olduğunu söylüyor.',
      tl: 'Ang item na ito ay ginawa sa isang buong buwan kapag mahiwaga incantations ay narinig sa whispers ng madilim. Sinasabi ng ilan na si Anubis mismo ay nakikipag-usap sa mga patay.',
      ht: 'Atik sa a te fòje nan lalin lan plen lè òneman misterye te tande nan yon murmures nan fènwa. Gen kèk ki di ke li te Anubi tèt li, pale ak moun ki mouri yo.',
      it: 'Questo oggetto è stato forgiato su una luna piena quando misteriosi incantesimi sono stati ascoltati nei sussurri del buio. Alcuni dicono che sia stato Anubi stesso a parlare con i morti.',
      hi: 'पूर्णीमा की रात में अंधेरी आवाज़ो में जब रहस्यमई मत्र सुने गए थे, तब इस वस्तु को बनाया गया था। कुछ कहते है कि आवाज़ों में भगवान अनूबिस खुद मुर्दों से बात कर रहे थे।',
      cs: 'Tento předmět byl kovaný na úplňku, když se v šepotu temnoty ozvalo tajemné zaklínadlo. Někteří říkají, že to byl Anubis sám mluvit s mrtvými.',
      ja: 'このアイテムは、暗闇のささやきの中で不思議な呪文が聞かれたときに満月に作られました。アヌビス自身が死者と話していたと言う人もいます。',
      el: 'Αυτό το στοιχείο ήταν σφυρηλατημένο σε πανσέληνο όταν ακούστηκαν μυστηριώδεις φωνές με τους ψίθυρους του σκοτάδι. Κάποιοι λένε ότι ο ίδιος ο Anubis μίλησε με τους νεκρούς.',
      bg: 'Този предмет беше изкован на пълнолуние, когато се чуваха тайнствени заклинания в шепота на тъмнината. Някои казват, че самият Анубис говори с мъртвите.',
      ro: 'Acest obiect a fost făurit sub lună plină când incantații misterioase au fost auzite în șoaptele nopții. Câțiva oameni spun că a fost chiar Anubis vorbind cu morții.',
      da: 'Denne genstand blev smedet på en fuldmåne, da mystiske incantations blev hørt i mørket hvisker. Nogle siger, at det var Anubis selv, der talte med de døde.'
    }
  }

]
