export default [
  {
    name       : {$$: 'Potato Sack' },
    description: {
      en: 'Sack stiff with starch making you feel dirty and disheveled.',
      ru: 'Грубый накрахмаленный мешок заставляет чувствовать вас грязным и взъерошенным.',
      es: 'Saco rígido con almidón que te hace sentir sucio y despeinado.',
      de: 'Sack steif mit Stärke, so dass Sie sich schmutzig und zerzaust fühlen.',
      fr: 'Sac rigide avec de l\'amidon qui vous donne l\'impression d\'être sale et ébouriffé.',
      pt: 'Saco rígido com amido que te faz sentir sujo e desgrenhado.',
      nl: 'Zak stijf met zetmeel waardoor je je vies en in de war voelt.',
      hi: 'बनाने आप गंदे और अस्त-व्यस्त लग रहा है स्टार्च के साथ कठोर पद से हटाने।',
      tl: 'Sack matigas na may arina paggawa ng pakiramdam mo marumi at sira.',
      el: 'Σκουπίστε σφικτά με άμυλο, κάνοντας να νιώσετε βρώμικος και ξεθωριασμένος.',
      bg: 'Уплътнява се с нишесте, за да се почувствате мръсни и разрошени.',
      pl: 'Worek sztywny ze skrobią sprawia, że czujesz się brudny i rozczochrany.',
      it: 'Sacco rigido con amido che ti fa sentire sporco e spettinato.',
      ht: 'Sak rèd ak lanmidon fè ou santi ou sal ak dezord.',
      tr: 'Bu çuvalla beraber insan kendini darmadağın ve saçma hissediyor.',
      cs: 'Pytel tuhý se škrobem, takže se cítíte špinavý a rozcuchaný.',
      ja: 'でんぷんを使って固い袋に入れ、汚れや乱れを感じさせます。',
      sv: 'Sack stiv med stärkelse som gör att du känner dig smutsig och rufsig.',
      ko: '자루에 녹말이 묻어있어 더럽고 흐트러진 느낌을줍니다.',
      ro: 'Sac rigid cu amidon, te face să te simți murdar și ciufulit.',
      da: 'Sække stiv med stivelse, så du bliver beskidte og pjusket.'
    }
  },

  {
    name       : {$$: 'Faded Garment' },
    description: {
      en: 'Leather shirt, faded from wear and tear.',
      ru: 'Кожаная рубашка, выцветшая из-за износа.',
      es: 'Camisa de cuero, desteñida por el desgaste.',
      de: 'Lederhemd, verblasst durch Abnutzung.',
      fr: 'Chemise en cuir, décolorée par l\'usure.',
      pt: 'Camisa de couro, descolorada de desgaste.',
      nl: 'Leren hemd, vervaagd van slijtage.',
      hi: 'चमड़ा शर्ट, टूट-फूट से फीका।',
      el: 'Το δερμάτινο πουκάμισο ξεθωριάστηκε από τη φθορά.',
      bg: 'Кожената риза избледня от износване.',
      pl: 'Skórzana koszula, wyblakła od zużycia.',
      tl: 'Ang katad na kamelyo ay nawala mula sa pagkasira at pagkasira.',
      it: 'Camicia in pelle, sbiadita dall\'usura.',
      ht: 'Chemiz kwi, ta vle chanje koulè soti nan mete ak chire.',
      tr: 'Aşınma ve yıpranma nedeniyle solmuş deri gömlek.',
      cs: 'Kožená košile, vybledlá od opotřebení.',
      ja: '革のシャツは消耗から消えていった。',
      sv: 'Lädertröja, bleknad från slitage.',
      ko: '마모로 인해 퇴색 한 가죽 셔츠.',
      ro: 'Cămașă de piele, decolorată de la uzură.',
      da: 'Læder skjorte, falmet fra slid.'
    }
  },

  {
    name       : {$$: 'Adventurer\'s Tunic' },
    description: {
      en: 'Knobbly soft iron tunic, passed on from many generations of adventurers passing over these lands.',
      ru: 'Изогнутая мягкая железная туника, переданная от многих поколений искателей приключений, проходящих по этим землям.',
      es: 'Túnica de hierro blando y nudoso, transmitida por muchas generaciones de aventureros que pasan por estas tierras.',
      de: 'Knorrige Weicheisen-Tunika, die von vielen Generationen von Abenteurern überliefert wurde, die diese Länder durchquerten.',
      fr: 'Tunique en fer doux et noueux, transmise de génération en génération par les aventuriers de passage sur ces terres.',
      pt: 'Uma túnica de ferro macia e manhosa, passada de muitas gerações de aventureiros que passaram por essas terras.',
      nl: 'Knobbelig zacht ijzeren tuniek, doorgegeven van vele generaties avonturiers die over deze landen trekken.',
      hi: 'नरम लोहे का अंगरखा, साहसी इन भूमि के ऊपर से गुजर की कई पीढ़ियों से पारित कर दिया।',
      el: 'Έλαμπτος μαλακός σιδερένιος χιτώνας πέρασε από πολλές γενιές τυχοδιωκτών που πέρασαν από αυτές τις χώρες.',
      bg: 'Невероятно мека железна туника, пренесена от много поколения авантюристи, преминаващи през тези земи.',
      tl: 'Ang malambot na tunika na bakal na mula sa maraming henerasyon ng mga adventurer na dumadaan sa mga lupaing ito.',
      pl: 'Knobbly soft iron tunika, przekazywana od wielu pokoleń poszukiwaczy przygód przechodzących przez te ziemie.',
      it: 'Una sapiente tunica in ferro dolce, tramandata da molte generazioni di avventurieri che hanno attraversato queste terre.',
      ht: 'Tunik manchbly fè, pase nan anpil jenerasyon nan avanturyé pase sou tè sa yo.',
      tr: 'Topuzlu yumuşak demir tunik, bu toprakların üzerinden geçen birçok maceracıdan günümüze kadar geldi.',
      cs: 'Rázně měkká železná tunika, předaná z mnoha generací dobrodruhů, kteří jdou přes tyto země.',
      ja: 'これらの土地を通り過ぎる何世代にもわたる冒険家から、たぶん柔らかい鉄のチュニックが受け継がれました。',
      sv: 'Mjuk järn tunika, vidarebefordrad från många generationer av äventyrare som passerar över dessa länder.',
      ko: '노블 블리 소프트 아이언 튜닉, 많은 세대의 모험가가이 땅을지나갑니다.',
      ro: 'Tunică de fier fină și colțuroasă, transmisă de multe generații de aventurieri care trec prin aceste ținuturi.',
      da: 'Knudret blød jern tunika, videreført fra mange generationer af eventyrere, der passerer over disse lande.'
    }
  },

  {
    name       : {$$: 'Leather Jerkin' },
    description: {
      en: 'This fabric isn\'t much, but it might stop an arrow or two.',
      ru: 'Эта ткань не очень, но она может остановить стрелу или две.',
      es: 'Este tejido no es mucho, pero puede detener una flecha o dos.',
      de: 'Dieser Stoff ist nicht viel, aber er könnte einen oder zwei Pfeile aufhalten.',
      fr: 'Ce tissu n\'est pas grand-chose, mais il pourrait arrêter une flèche ou deux.',
      pt: 'Este tecido não é lá grande coisa, mas pode parar uma flecha ou duas.',
      nl: 'Deze stof is niet veel, maar het zou een paar pijlen kunnen stoppen.',
      tl: 'Ang tela na ito ay hindi magkano ngunit maaaring itigil ang isang arrow o dalawa.',
      hi: 'यह कपड़े बहुत ज्यादा नहीं है, लेकिन यह एक तीर या दो बंद हो सकता है।',
      pl: 'Ten materiał to niewiele, ale może zatrzymać strzałę lub dwie.',
      it: 'Questo tessuto non è molto, ma potrebbe fermare una o due frecce.',
      el: 'Αυτό το ύφασμα δεν είναι πολύ, αλλά μπορεί να σταματήσει ένα βέλος ή δύο.',
      bg: 'Тази тъкан не е много, но може да спре стрелка или две.',
      ht: 'Sa a twal se pa anpil, men li ta ka sispann yon flèch oswa de.',
      tr: 'Bir kumaştan fazlası değil, belki bir iki ok durdurabilir.',
      cs: 'Tato tkanina není moc, ale mohla by zastavit šíp nebo dvě.',
      ja: 'この布はあまりありませんが、それは矢印1、2を止めるかもしれません。',
      sv: 'Det här tyget är inte mycket, men det kan sluta med en pil eller två.',
      ko: '이 직물은 그다지 많지는 않지만 두세 개의 화살이 멈출 수 있습니다.',
      ro: 'Materialul acesta nu e cine știe ce, dar ar putea opri o săgeată sau două.',
      da: 'Dette stof er ikke meget, men det kan stoppe en pil eller to.'
    }
  },

  {
    name       : {$$: 'Scaled Chestguard' },
    description: {
      en: 'Hard suit made from scales taken from a mighty dragon that once roamed these lands.',
      ru: 'Жесткий костюм из чешуи, взятой у могучего дракона, когда-то бродившего по этим землям.',
      es: 'Traje duro hecho de escamas tomadas de un poderoso dragón que una vez deambulaba por estas tierras.',
      de: 'Ein Hardkostüm aus Schuppen eines mächtigen Drachens, der einst durch dieses Land streift.',
      fr: 'Costume dur fait d\'écailles prises d\'un puissant dragon qui errait autrefois sur ces terres.',
      pt: 'Um fato duro feito de escamas tiradas de um poderoso dragão que percorreu estas terras.',
      nl: 'Hard pak gemaakt van schubben van een machtige draak die ooit in dit land rondzwierf.',
      tl: 'Hard suit na ginawa mula sa mga kaliskis kinuha mula sa isang makapangyarihang dragon na minsan roamed ang mga lupain.',
      hi: 'हार्ड एक शक्तिशाली अजगर है कि एक बार इन भूमि रोमिंग से लिया तराजू से बने सूट।',
      pl: 'Twardy garnitur wykonany ze skal wziętych od potężnego smoka, który kiedyś poruszał się po tych ziemiach.',
      it: 'Tuta rigida fatta di bilance prese da un potente drago che una volta vagando per queste terre.',
      el: 'Σκληρό κοστούμι κατασκευασμένο από ζυγαριές που τραβήχτηκαν από έναν ισχυρό δράκο που κάποτε γύριζε αυτά τα εδάφη.',
      bg: 'Твърд костюм, изработен от везни, взети от един могъщ дракон, който някога е бродил по тези земи.',
      ht: 'Kostim difisil te fè soti nan kal pwason sot pran nan yon dragon vanyan sòlda ki yon fwa ere tè sa yo.',
      tr: 'Bir zamanlar bu topraklarda dolaşan güçlü bir ejderhadan alınan pullarla yapılmış sert bir elbise.',
      cs: 'Tvrdý oblek vyrobený z šupin odebraných z mocného draka, který se kdysi potuloval po těchto zemích.',
      ja: 'かつてこれらの土地を歩き回っていた強力なドラゴンから取った鱗で作られたハードスーツ。',
      sv: 'Hård kostym gjord av vågar som tagits från en mäktig drake som en gång strövade över dessa länder.',
      ko: '한때이 땅을 배회 한 강력한 용에서 가져온 비늘로 만든 단단한 옷.',
      ro: 'Costum tare făcut din solzii luați de la un dragon puternic ce odată cutreiera aceste tărâmuri.',
      da: 'Hård kjole lavet af skalaer taget fra en mægtig drage, der engang roamede disse lande.'
    }
  },

  {
    name       : {$$: 'Sky Mail' },
    description: {
      en: 'Rumours say it\'s made from clouds...',
      ru: 'Слухи говорят, что она сделана из облаков...',
      es: 'Los rumores dicen que está hecho de las nubes...',
      de: 'Gerüchte besagen, dass es aus den Wolken gemacht wurde...',
      fr: 'Les rumeurs disent que ce manteau est fait à partir des nuages...',
      pt: 'Os rumores dizem que é feito de nuvens...',
      tl: 'Sinasabi ng mga alingawngaw na ginawa mula sa mga ulap ...',
      nl: 'Geruchten zeggen dat het gemaakt is van wolken...',
      hi: 'अफवाहें इसकी बादलों से बना कहते हैं ...',
      pl: 'Plotki mówią, że zrobione z chmur...',
      it: 'Voci dicono che è fatto di nuvole...',
      el: 'Φήμες λένε ότι έγιναν από σύννεφα...',
      bg: 'Слуховете казват, че са направени от облаци...',
      ht: 'Rimè di ke li te fè soti nan nyaj...',
      tr: 'Buluttan yapıldığına dair dedikodular var...',
      cs: 'Pověsti říkají, že jsou vyrobeny z mraků...',
      ja: 'うわさは雲から作られたと言う...',
      sv: 'Rykten säger att den är gjord av moln...',
      ko: '소문은 구름으로 만든다고 ...',
      ro: 'Zvonurile spun că e făcută din nori...',
      da: 'Ryger siger, at det er lavet af skyer...'
    }
  },

  {
    name       : {$$: 'Shadow Cloak' },
    description: {
      en: 'The wearer blends in nicely with the shadows... or so the thieves think.',
      ru: 'Носитель отлично сливается с тенью... или так думают воры.',
      es: 'El portador se mezcla bien entre las sombras... o es lo que piensan los ladrones.',
      de: 'Der Träger fügt sich gut in den Schatten ein.... so denken die Diebe.',
      fr: 'Le porteur se fond bien dans l\'ombre... c\'est du moins ce que pensent les voleurs.',
      pt: 'O utilizador mistura-se bem com as sombras... ou assim pensam os ladrões.',
      nl: 'De drager gaat mooi op in de schaduwen.... zo denken de dieven.',
      hi: 'पहनने वाला छाया के साथ अच्छी तरह से में मिश्रित ... या तो चोरों लगता है।',
      tl: 'Nagsuot ang nagsuot ng mabuti sa mga anino ... o kaya sa tingin ng mga magnanakaw.',
      pl: 'Użytkownik ładnie wtapia się w cienie.... albo tak myślą złodzieje.',
      el: 'Ο χρήστης μοιάζει με τις σκιές ... ή έτσι σκέφτονται οι κλέφτες.',
      bg: 'Носителят се слива добре със сенките ... или така крадците мислят.',
      it: 'Chi lo indossa si fonde bene con le ombre...... o così pensano i ladri.',
      ht: 'Utilisateurs la melanje nan joliman ak lonbraj yo ... oswa konsa ansasen yo panse.',
      tr: 'Kullanıcı gölgelerle güzelce karışır ... ya da hırsızlar öyle sanıyor.',
      cs: 'Nositelka se pěkně mísí se stíny ... nebo tak si zloději myslí.',
      ja: '着用者は影とうまく溶け込みます...あるいは泥棒は考えます。',
      sv: 'Bäraren blandar sig snyggt med skuggorna ... eller så tjuvarna tänker.',
      ko: '착용자는 그림자와 잘 어울립니다 ... 또는 도둑들이 생각합니다.',
      ro: 'Purtătorul se amestecă frumos printre umbre... sau așa cred hoții.',
      da: 'Brugeren passer godt sammen med skyggerne... eller så tøverne tænker.'
    }
  },

  {
    name       : {$$: 'Runic Halfplate' },
    description: {
      en: 'Forged by unknown magicians, you wear a dark and powerful chestplate.',
      ru: 'Выкованный неизвестными магами, вы носите темный и мощный нагрудник.',
      es: 'Forjado por magos desconocidos, llevas una placa de pecho oscura y poderosa.',
      de: 'Geschmiedet von unbekannten Magiern, trägst du einen dunklen und kraftvollen Brustschild.',
      fr: 'Forgé par des magiciens inconnus, vous portez un plastron d\'un métal sombre et puissant.',
      pt: 'Forjado por magos desconhecidos, você veste uma couraça escura e poderosa.',
      nl: 'Gesmeed door onbekende tovenaars, draag je een donker en krachtig borstplaatje.',
      hi: 'अज्ञात जादूगर द्वारा जाली, आप एक गहरी अंधेरे और शक्तिशाली छाती प्लेट पहनते हैं।',
      pl: 'Wykute przez nieznanych magów, nosisz ciemną i potężną płytę piersiową.',
      tl: 'Peke sa pamamagitan ng hindi kilalang mga magicians magsuot ka ng isang malalim na madilim at malakas na wallplate.',
      el: 'Σφυρηλατημένοι από άγνωστους μάγους φορούν μια βαθιά σκοτεινή και ισχυρή στήθος-πλάκα.',
      bg: 'Изковани от неизвестни магьосници, носите дълбок и мощен гръден плот.',
      it: 'Forgiato da maghi sconosciuti, si indossa un scuro e potente pettorale.',
      ht: 'Fòje pa majisyen unknown, ou mete yon gwo twou san piyè pwatrin nwa ak pwisan.',
      tr: 'Bilinmeyen bir büyücü tarafından dövülmüş. Derin karanlık ve güçlü bir zırh.',
      cs: 'Kované neznámými kouzelníky, nosíte temný a silný hrudník.',
      ja: '未知の魔術師によって鍛えられて、あなたは深くて暗くて強力なチェストプレートを身に付けます。',
      sv: 'Smidd av okända magiker, har du en mörk och kraftfull bröstkorg.',
      ko: '알려지지 않은 마술사에 의해 위조 된, 당신은 깊고 어둡고 강력한 가슴 판을 착용합니다.',
      ro: 'Făurită de magicieni necunoscuți, porți o armură toracică întunecată și puternică.',
      da: 'Smedet af ukendte tryllekunstnere, har du en mørk og kraftig brystplade.'
    }
  },

  {
    name       : {$$: 'Hellfire Fullplate' },
    description: {
      en: 'Forged in unknown valleys, it provides protection for your weak, fleshy body.',
      ru: 'Выкованный в неизвестных долинах, он обеспечивает защиту вашему слабому, мясистому телу.',
      es: 'Forjada desde las valles desconocidos, proporciona protección para tu cuerpo débil y carnoso.',
      de: 'In unbekannten Tälern geschmiedet, bietet es Schutz für Ihren schwachen, fleischigen Körper.',
      fr: 'Forgé dans des vallées inconnues, il protège votre corps faible et charnu.',
      pt: 'Forjado em vales desconhecidos, ela fornece proteção para seu corpo fraco e carnudo.',
      nl: 'Gesmeed uit de onbekende valleien, biedt het bescherming voor je zwakke, vlezige lichaam.',
      hi: 'अज्ञात घाटियों में जाली, यह आपके कमजोर, मांसल शरीर के लिए सुरक्षा प्रदान करती है।',
      el: 'Σφυρηλατημένο σε άγνωστες κοιλάδες, παρέχει προστασία για το αδύναμο, σαρκώδες σώμα σας.',
      bg: 'Кован в неизвестни долини, той осигурява защита за вашето слабо, месесто тяло.',
      tl: 'Peke sa di-kilalang mga lambak, nagbibigay ito ng proteksyon para sa iyong mahina, mataba na katawan.',
      pl: 'Wykuty w nieznanych dolinach, zapewnia ochronę twojemu słabemu, mięsistemu ciału.',
      it: 'Forgiato in valli sconosciute, protegge il tuo corpo debole e carnoso.',
      ht: 'Fòje nan fon enkoni, li bay pwoteksyon pou kò fèb ou, charnèl.',
      tr: 'Bilinmeyen vadilerde yapılan bu zayıf, etli bedeniniz için koruma sağlar.',
      cs: 'Kovaná v neznámých údolích poskytuje ochranu pro vaše slabé, masité tělo.',
      ja: '未知の渓谷で鍛造され、それはあなたの弱い、肉質の体を保護します。',
      sv: 'Smidd i okända dalar, det ger skydd för din svaga köttiga kropp.',
      ko: '미지의 계곡에서 위조되어있어 약한 육체를 보호합니다.',
      ro: 'Forjată în văi necunoscute, îți oferă protecție pentru corpul tău slab, cărnos.',
      da: 'Smedet i ukendte dale, det giver beskyttelse for din svage, kødelige krop.'
    }
  },

  {
    name       : {$$: 'Soulkeeper' },
    description: {
      en: 'When enemies are slain, their souls are added to the wielder\'s collection.',
      ru: 'Когда враги убиты, их души добавляются в коллекцию владельца.',
      es: 'Cuando los enemigos son asesinados, sus almas se añaden a la colección del poseedor.',
      de: 'Wenn Feinde getötet werden, werden ihre Seelen der Sammlung des Führers hinzugefügt.',
      fr: 'Quand des ennemis sont tués, leurs âmes sont ajoutées à la collection du porteur.',
      pt: 'Quando os inimigos são mortos,as suas almas são adicionadas à coleção do portador.',
      nl: 'Wanneer vijanden worden gedood, worden hun zielen toegevoegd aan de collectie van de drager.',
      tl: 'Kapag ang mga kaaway ay pinatay ang kanilang mga kaluluwa ay idinagdag sa koleksyon ng mga gumagamit.',
      hi: 'जब दुश्मन मारे गए हैं, अपनी आत्मा wielder के संग्रह करने के लिए जोड़ रहे हैं।',
      pl: 'Kiedy wrogowie są zabijani, ich dusze są dodawane do kolekcji władcy.',
      it: 'Quando i nemici vengono uccisi, le loro anime vengono aggiunte alla collezione del detenuto.',
      ht: 'Lè lènmi yo te mouri, nanm yo te ajoute nan koleksyon wielder la.',
      el: 'Όταν οι εχθροί σκοτώνονται, οι ψυχές τους προστίθενται στη συλλογή των wielders.',
      bg: 'Когато враговете се убиват, душите им се прибавят към колекцията на владетелите.',
      tr: 'Düşmanlar katledildiğinde, ruhlarını koleksiyonuna ekler.',
      cs: 'Když jsou nepřátelé zabiti, jejich duše jsou přidány do sbírky držitele.',
      ja: '敵が殺害されたとき、彼らの魂は野郎のコレクションに追加されます。',
      sv: 'När fiender slås, läggs deras själar till wielderens samling.',
      ko: '적들이 살해 당하면 그들의 영혼이 수비수의 소장품에 추가됩니다.',
      ro: 'Când dușmanii sunt uciși, sufletele lor sunt adăugate la colecția posesorului.',
      da: 'Når fjender slås, bliver deres sjæle tilføjet til wielderens samling.'
    }
  },

  {
    name       : {$$: 'Deathless' },
    description: {
      en: 'Rumours say that the wearer is immortal. Unfortunately this armour can only be found on corpses of the slain.',
      ru: 'Слухи говорят, что носитель брони бессмертен. К сожалению, эту броню можно найти только на трупах.',
      es: 'Los rumores dicen que el portador es inmortal. Desafortunadamente, esta armadura sólo se encuentra en los cadáveres de los muertos.',
      de: 'Gerüchten zufolge ist der Träger unsterblich. Leider ist diese Rüstung nur auf den Leichen der Erschlagenen zu finden.',
      fr: 'Les rumeurs disent que le porteur de cette armure est immortel. Malheureusement, elle ne peut être trouvée que sur les cadavres des victimes.',
      pt: 'Rumores dizem que o portador é imortal. Infelizmente esta armadura só pode ser encontrada nos cadáveres dos mortos.',
      tl: 'Sinasabi ng mga alingawngaw na ang tagapagsuot ay walang kamatayan. Sa kasamaang palad ang armor na ito ay matatagpuan lamang sa mga bangkay ng mga napatay.',
      nl: 'Er gaan geruchten dat de drager onsterfelijk is. Helaas is dit harnas alleen te vinden op lijken van de gedode personen.',
      hi: 'अफवाहें का कहना है कि पहनने वाला अमर है। दुर्भाग्य से इस कवच केवल मारे हुए की लाशों पर पाया जा सकता।',
      pl: 'Plotki mówią, że noszący jest nieśmiertelny. Niestety ta zbroja znajduje się tylko na zwłokach zabitych.',
      el: 'Φήμες λένε ότι ο φορέας είναι αθάνατος. Δυστυχώς αυτή η πανοπλία μπορεί να βρεθεί μόνο στα πτώματα των σκοτωμένων.',
      bg: 'Слуховете казват, че носителят е безсмъртен. За съжаление тази броня може да бъде намерена само на трупове на убитите.',
      it: 'Si dice che chi lo indossa è immortale. Purtroppo questa armatura si trova solo sui cadaveri degli uccisi.',
      ht: 'Rimè ki di ke moun nan se imòtèl. Malerezman zam sa a ka jwenn sèlman sou kadav moun ki mouri yo.',
      tr: 'Dedikodulara göre bunu giyen ölümsüzmüş. Ne yazık ki bu zırh sadece öldürülen cesetlerinde bulunabilir.',
      cs: 'Pověsti říkají, že nositel je nesmrtelný. Bohužel toto brnění lze nalézt pouze na mrtvolách zabitých.',
      ja: '噂によると、着用者は不滅です。残念ながらこの装甲は殺人の死体にしか見られません。',
      sv: 'Rykten säger att bäraren är odödlig. Tyvärr kan denna rustning endast hittas på de dödas lik.',
      ko: '소문은 착용자가 불멸하다고 말한다. 불행히도이 갑옷은 살해 된 시체에서만 발견 할 수 있습니다.',
      ro: 'Zvonurile spun că purtătorul este nemuritor. Din păcate, această armură poate fi găsită doar pe cadavrele celor uciși.',
      da: 'Rygerne siger, at bæreren er udødelig. Desværre er denne rustning kun fundet på lig af de dræbte.'
    }
  }

]
