export default [
  {
    name       : {$$: 'Sandals' },
    description: {
      en: 'At least you\'re wearing something on those feet.',
      ru: 'По крайней мере, вы хоть что-то носите на своих ногах.',
      de: 'Zumindest trägst du etwas auf diesen Füßen.',
      es: 'Al menos llevas algo en los pies.',
      fr: 'Au moins, tu portes quelque chose sur tes pieds.',
      it: 'Almeno tu indossi qualcosa su quei piedi.',
      pt: 'Pelo menos estás a usar algo nesses pés.',
      nl: 'Je draagt tenminste iets op die voeten.',
      tr: 'En azından ayağına bir şeyler giyiyorsun.',
      pl: 'Przynajmniej nosisz coś na tych stopach.',
      sv: 'Du har åtminstone nåt på fötterna.',
      tl: 'Hindi bababa sa ikaw ay may suot ng isang bagay sa mga paa.',
      ht: 'Omwen wap mete yon bagay sou pye sa yo.',
      cs: 'Přinejmenším máš na těch nohách něco.',
      ja: '少なくともあなたはそれらの足に何かを着ています。',
      el: 'Τουλάχιστον φοράτε κάτι σε αυτά τα πόδια.',
      bg: 'Поне ти носиш нещо на тези крака.',
      hi: 'काम से काम आप ने अपने पैरों पर कुछ तो पहना है।',
      ko: '적어도 너는 그 발에 무언가를 신었다.',
      ro: 'Cel puțin poți purta ceva în picioare.',
      da: 'I det mindste har du noget på disse fødder.'
    }
  },

  {
    name       : {$$: 'Cloth Footpads' },
    description: {
      en: 'Soles made from cloth, will probably tear after a few hours.',
      ru: 'Подошвы сделанные из ткани, вероятно, порвутся через несколько часов.',
      de: 'Sohlen aus Stoff, werden wahrscheinlich nach ein paar Stunden reißen.',
      es: 'Suelas hechas de tela, probalamente rasgarán después de unas horas.',
      fr: 'Des semelles en tissu, elles se déchireront probablement au bout de quelques heures.',
      it: 'Suole fatte di stoffa, probabilmente si strappano dopo qualche ora.',
      pt: 'Solas feitas de tecido, provavelmente rasgarão depois de algumas horas.',
      nl: 'Zolen van doek, zullen waarschijnlijk na een paar uur scheuren.',
      tr: 'Kumaştan yapılmış tabanlar, muhtemelen birkaç saat sonra yırtılacak.',
      pl: 'Podeszwy wykonane z tkaniny, prawdopodobnie rozerwą się po kilku godzinach.',
      tl: 'Ang mga solong gawa sa tela ay malamang na mapunit pagkatapos ng ilang oras.',
      sv: 'Tygsulor som det troligtvis kommer att gå hål i efter några timmar.',
      ht: 'Plant te fè soti nan twal, pwal pwobableman detache apre kèk èdtan.',
      cs: 'Podešve vyrobené z látky se po několika hodinách pravděpodobně roztrhnou.',
      ja: '布で作られた足の裏はおそらく数時間後に裂けるでしょう。',
      el: 'Τα πέλματα από ύφασμα πιθανόν να σχίσουν μετά από λίγες ώρες.',
      bg: 'Подметките, направени от плат, вероятно ще се разкъсат след няколко часа.',
      hi: 'इसके तले कपड़े के बने है, थोड़ी डर में फट जाएँगे।',
      ko: '옷감으로 만든 신, 몇 시간 후에 찢어 질 것입니다.',
      ro: 'Talpa din pânză, probabil se va rupe după câteva ore.',
      da: 'Soles lavet af klud vil sandsynligvis rive efter et par timer.'
    }
  },

  {
    name       : {$$: 'Leather Shoes' },
    description: {
      en: 'The soft leather is said to be stripped off wild boars roaming the eerie woods.',
      ru: 'Говорят, что мягкую кожу сняли с кабанов, бродящих по жутким лесам.',
      de: 'Das weiche Leder soll von Wildschweinen befreit worden sein, die durch die unheimlichen Wälder streifen.',
      es: 'Se dice que el cuero suave es despojado de los jabalíes que deambulan por los espeluznantes bosques.',
      it: 'Si dice che la morbida pelle sia stata rimossa dai cinghiali che vagano nei boschi inquietanti.',
      fr: 'On dit que le cuir souple est dépouillé des sangliers qui errent dans les bois étranges.',
      pt: 'Diz-se que o couro macio é arrancado dos javalis selvagens que vagueiam pelos bosques sinistros.',
      nl: 'Het zachte leer zou gestript zijn van wilde zwijnen die door de griezelige bossen zwerven.',
      tr: 'Bu yumuşak derinin, ürkütücü ormanda dolaşan yaban domuzlarından yüzüldüğü söyleniyor.',
      pl: 'Mówi się, że miękka skóra jest rozebrana z dzika wędrującego po przerażających lasach.',
      sv: 'Det mjuka läderet sägs vara avskilt från vildsvin som roaming de kusliga skogen.',
      tl: 'Ang malambot na katad ay sinasabing hinubaran ng mga ligaw na baboy na nakasisilaw sa nakatatakot na mga kahoy.',
      ht: 'li te di kwi mou yo dwe wete nan sangliye sovaj vagan bwa yo etranj.',
      el: 'Το μαλακό δέρμα λέγεται ότι απογυμνώνεται από αγριόχοιρους περιαγώνοντας το απόκοσμο δάσος.',
      bg: 'За меката кожа се казва, че е съблечена от диви свине, прекосяващи зловещите гори.',
      cs: 'Říká se, že měkká kůže je zbavena divokých prasat roamingu děsivých lesů.',
      ja: '柔らかい革は不気味な森を歩き回っているイノシシを剥ぎ取られると言われています。',
      hi: 'इसका नरम चमड़े को डरावने जंगलो में रहने वाले जंगली सूअरो से लिए गया है।',
      ko: '부드러운 가죽은 섬뜩한 숲을 돌아 다니는 야생 멧돼지에서 벗겨졌다.',
      ro: 'Se zvonește că pielea moale a fost dezbrăcată de mistreții ce se plimbau prin pădurea stranie.',
      da: 'Det bløde læder siges at være fjernet fra vildsvin, der roaming de uhyggelige skove.'
    }
  },

  {
    name       : {$$: 'Bone Brogans' },
    description: {
      en: 'Clearly lacking in imagination, the maker made boots from the bones of a very large creature...',
      ru: 'Очевидно, у создателя не хватает воображения, ведь он сделал сапоги из костей очень крупного существа ...',
      de: 'Offensichtlich fantasielos machte der Hersteller Stiefel aus den Knochen einer sehr großen Kreatur...',
      es: 'Claramente sin imaginación, el zapatero uso los huesos de una criatura grande...',
      fr: 'Manquant clairement d\'imagination, le confectionné a fabriqué des bottes à partir des os d\'une très grande créature....',
      it: 'Chiaramente privo di immaginazione, l\'autore ha realizzato stivali dalle ossa di una creatura molto grande...',
      pt: 'Claramente sem imaginação, o fabricante fez botas a partir dos ossos de uma criatura muito grande...',
      nl: 'Duidelijk niet verbeeldingsvol, de maker maakte laarzen van de botten van een zeer groot wezen...',
      tr: 'Hayal gücünden yoksun olduğu aşikâr, usta bu botları çok büyük bir yaratığın kemiklerinden yapmış...',
      pl: 'Wyraźnie pozbawiony wyobraźni, twórca wykonał buty z kości bardzo dużego stworzenia...',
      sv: 'Klart saknar fantasi gjorde tillverkaren stövlar från benen i en väldigt stor varelse...',
      ht: 'Klèman manke nan imajinasyon, Maker la te fè bòt soti nan zo yo nan yon bèt gwo anpil...',
      tl: 'Maliwanag na kulang sa imahinasyon ang gumagawa ay gumawa ng mga bota mula sa mga buto ng isang napakalaking nilalang ...',
      cs: 'Jasně chybí představivost a vyrábí boty z kostí velkého stvoření...',
      ja: '想像力に欠け、明らかに巨大な生き物の骨からブーツを作りました。',
      hi: 'जाहिर है कल्पना में कमी है, इसके निर्माता ने एक बहुत बड़ी प्राणी की हड्डियों से इसे बनाया...',
      el: 'Σαφώς λείπει από τη φαντασία ο κατασκευαστής έκανε μπότες από τα οστά ενός πολύ μεγάλου πλάσματος...',
      bg: 'Очевидно без въображение, производителят е направил ботуши от костите на много голямо същество...',
      ko: '분명히 상상력이 부족한이 제작자는 매우 큰 생물의 뼈에서 부츠를 만들었습니다...',
      ro: 'În mod evident lipsit de imaginație, producătorul a făcut cizmele din oasele unei creaturi foarte mari...',
      da: 'Klart mangler fantasi, skaberen lavede støvler fra knoglerne i et meget stort væsen...'
    }
  },

  {
    name       : {$$: 'Scaled Treads' },
    description: {
      en: 'Mysterious scales cover the outside of your footwear, catching glares in the sun.',
      ru: 'Загадочная чешуя покрывает внешнюю сторону обуви, улавливая блики на солнце.',
      de: 'Mysteriöse Schuppen bedecken die Außenseite Ihres Schuhwerks und fangen grelle Blicke in der Sonne auf.',
      es: 'Escamas misteriosas cubren la parte exterior del calzado, atrapando los reflejos del sol.',
      it: 'Scaglie misteriose coprono l\'esterno delle vostre calzature, catturando i riflessi del sole.',
      fr: 'De mystérieuses écailles recouvrent l\'extérieur de vos chaussures et attirent les regards au soleil.',
      pt: 'Escalas misteriosas cobrem o exterior do seu calçado, pegando olhares ao sol.',
      nl: 'Mysterieuze weegschalen bedekken de buitenkant van je schoeisel en vangen de blikken in de zon.',
      tr: 'Gizemli pullar ayakkabınızın dışını örtüyor ve güneşten gelen ışıkları yansıtarak göz kamaştırıyor.',
      pl: 'The mysterious scale covers the outside of the shoe, capturing reflections in the sun.',
      sv: 'Mystiska vågar täcker utsidan av dina skor, fångar glares i solen.',
      tl: 'Ang mga mahiwagang kaliskis ay sumasaklaw sa labas ng iyong kasuotan sa paa nakahahalina glares sa araw.',
      el: 'Μυστηριώδεις κλίμακες καλύπτουν το εξωτερικό των υποδημάτων σας που τραβάνε τις γεύσεις στον ήλιο.',
      bg: 'Тайнствените люспи покриват външността на обувките ви, хванали погледите на слънцето.',
      ht: 'Balans misterye kouvri deyò a nan soulye ou a, pwan fikse nan solèy la.',
      cs: 'Tajemství váhy pokrývají vnější stranu vaší obuvi, chytí do očí slunce.',
      ja: '神秘的な鱗があなたの履物の外側を覆い、太陽の光を捉えます。',
      hi: 'रहस्यमय शल्क आपके जूतों को ढकते है, जो धूप में प्रकाश को पकड़ते है।',
      ko: '신비한 비늘은 신발의 바깥을 덮고 태양 빛을 따라 잡습니다.',
      ro: 'Solzi misterioși acoperă exteriorul încălțămintelor tale, atrăgând priviri când stau în soare.',
      da: 'Mystiske skalaer dækker ydersiden af ​​dit fodtøj og fanger glares i solen.'
    }
  },

  {
    name       : {$$: 'Shadow Shoes' },
    description: {
      en: 'A pleasant pattern made to paralyze your foes... wonder if it works.',
      ru: 'Приятный узор, созданный, чтобы парализовать ваших врагов... интересно, работает ли он',
      de: 'Ein angenehmes Muster, das gemacht wurde, um deine Feinde zu lähmen... frage dich, ob es funktioniert.',
      es: 'Un diseño agradable para paralizar a sus enemigos... no sé si funciona.',
      fr: 'Un motif agréable fait pour paralyser vos ennemis... vous vous demandez si ça marche.',
      it: 'Un piacevole motivo fatto per paralizzare i tuoi nemici... chiedo se funziona',
      pt: 'Um padrão agradável feito para paralisar os teus inimigos... imagina se funciona.',
      nl: 'Een aangenaam patroon om je vijanden te verlammen... of het werkt.',
      tr: 'Düşmanlarınızı felç etmek için yapılan hoş bir desen... işe yarayıp yaramadığı merak konusu.',
      pl: 'Przyjemny wzór stworzony w celu sparaliżowania twoich wrogów... zastanawiam się, czy działa...',
      tl: 'Isang maayang pattern na ginawa upang maparalisa ang iyong mga kaaway ... magtaka kung ito gumagana.',
      sv: 'Ett trevligt mönster för att förlamna dina fiender ... undrar om det fungerar.',
      ht: 'Yon modèl bèl te fè nan paralize lènmi ou... mande si li fonksyone.',
      cs: 'Příjemný vzor, ​​který paralyzuje vaše nepřátele ... zajímá vás, jestli to funguje.',
      ja: 'あなたの敵を麻痺させるために作られた楽しいパターン... それがうまくいくかどうか疑問に思う',
      hi: 'एक सटीक प्रतिरूप आपके दुश्मनो को कमज़ोर करने के लिए... पता नहीं यह काम भी करता है या नहीं।',
      el: 'Ένα ευχάριστο σχέδιο για να παραλύσει τους εχθρούς σας ... αναρωτιέται αν λειτουργεί.',
      bg: 'Приятна картина, направена да парализира враговете ви ... чудя се дали работи.',
      ko: '적을 마비시키는 유쾌한 패턴이있다... 되는지는 모르겠다.',
      ro: 'Un model plăcut făcut pentru a paraliza inamicii... mă întreab dacă funcționează.',
      da: 'Et behageligt mønster lavet til at lamme dine fjender... spekulerer på, om det virker.'
    }
  },

  {
    name       : {$$: 'Wartorn Boots' },
    description: {
      en: 'Taken from war veterans who clearly didn\'t find enough protection from these greaves.',
      ru: 'Взято у ветеранов войны, которые явно не получили достаточной защиты от этих наголенников.',
      de: 'Entnommen von Kriegsveteranen, die offensichtlich nicht genug Schutz vor diesen Grieben gefunden haben.',
      es: 'Tomado de veteranos de guerra que obviamente no estaban protegido por estos chicharrones.',
      fr: 'Pris à des vétérans de guerre qui n\'ont clairement pas trouvé assez de protection dans ces bottes.',
      it: 'Preso da veterani di guerra che chiaramente non hanno trovato abbastanza protezione da questi ciccioli.',
      pt: 'Levados por veteranos de guerra que claramente não encontraram proteção suficiente contra estes torresmos.',
      nl: 'Genomen van oorlogsveteranen die duidelijk niet genoeg bescherming vonden tegen deze kanen.',
      tr: 'Dizçekleri yeterince korunaklı bulmayan savaş gazilerinden alınmış.',
      pl: 'Odebrane od weteranów wojennych, którzy najwyraźniej nie znaleźli wystarczającej ochrony przed tymi skwarkami.',
      sv: 'Hämtad från krigsveteraner som helt klart inte hitta tillräckligt med skydd från dessa greaves.',
      ht: 'Pran nan men veteran lagè ki klèman pa jwenn ase pwoteksyon soti nan greaves sa yo.',
      cs: 'Odvedeni od válečných veteránů, kteří zjevně nenalezli dostatečnou ochranu před těmito škvarky.',
      ja: '明らかにこれらの奴隷からの十分な保護を見つけることができなかった戦争のベテランから取られます。',
      tl: 'Kinuha mula sa mga beterano ng digmaan na malinaw na hindi nakahanap ng sapat na proteksyon mula sa mga ito.',
      hi: 'युद्ध के दिग्गजों से लिए हुए, जिन्हें इन जूतों से पर्याप्त संरक्षण नहीं मिला.',
      el: 'Λαμβανόταν από βετεράνους πολέμου που σαφώς δεν βρήκαν αρκετή προστασία από αυτά τα χοντρά σχοινιά.',
      bg: 'Взети от ветерани от войната, които очевидно не са намерили достатъчно защита от тези пръжки.',
      ko: '분명히이 부츠에서 충분한 보호를 찾지 못한 전쟁 참전 용사에게서 가져온 것입니다.',
      ro: 'Luate de la veterani de război care, evident, nu au găsit suficientă protecție în aceste cizme.',
      da: 'Taget fra krigsveteraner, der klart ikke fandt tilstrækkelig beskyttelse af disse greve.'
    }
  },

  {
    name       : {$$: 'Imbued Treads' },
    description: {
      en: 'Chunky in its looks, probably very uncomfortable.',
      ru: 'Состоят из блочных кусков, наверное, очень неудобные.',
      de: 'Grob in ihrem Aussehen, wahrscheinlich sehr unangenehm.',
      es: 'Aparece macizo y fornido, probablemente incómodo.',
      fr: 'Son design semble grossier, probablement très inconfortable.',
      it: 'Chunky nel suo aspetto, probabilmente molto scomodo.',
      pt: 'Aparentemente volumoso, provavelmente muito desconfortável.',
      nl: 'Mollig in zijn uiterlijk, waarschijnlijk erg ongemakkelijk.',
      tr: 'Görünüşte tıknaz, muhtemelen hiç rahat değil.',
      pl: 'W swoim wyglądzie, prawdopodobnie bardzo niewygodny.',
      sv: 'Chunky i sitt utseende, förmodligen mycket obekväma.',
      ht: 'Chunky nan sanble li yo, pwobableman trè alèz.',
      tl: 'Chunky sa kanyang hitsura marahil napaka hindi komportable.',
      cs: 'Chunky v jeho vzhledu, pravděpodobně velmi nepříjemné.',
      ja: '分厚いその外観はおそらく非常に不快です。',
      hi: 'दिखाने में लट्ठेदार, काफ़ी असहज होगे।',
      el: 'Χοντροκομμένο στην εμφάνισή του μάλλον πολύ άβολα.',
      bg: 'Корена си изглежда вероятно много неприятно.',
      ko: '그 모습이 거칠고, 아마도 매우 불편합니다.',
      ro: 'Arată îndesate, probabil foarte inconfortabile',
      da: 'Chunky i sit udseende, sandsynligvis meget ubehageligt.'
    }
  },

  {
    name       : {$$: 'Skyswift Boots' },
    description: {
      en: 'Run as quick as the wind... or close to it.',
      ru: 'Беги быстро, как ветер... ну почти.',
      de: 'Laufen Sie so schnell wie der Wind... oder in der Nähe davon.',
      es: 'Corre tan rápido como el viento... o cerca de el.',
      fr: 'Courir aussi vite que le vent... ou presque.',
      it: 'Corri veloce come il vento... o vicino ad esso',
      pt: 'Corra tão rápido como o vento... ou perto disso.',
      nl: 'Ren zo snel als de wind... of dichtbij.',
      tr: 'Rüzgar kadar hızlı koş... veya meltem kadar da olabilir.',
      pl: 'Biegnij tak szybko jak wiatr... lub blisko niego.',
      sv: 'Kör så fort som vinden... eller nära den.',
      ht: 'Kouri vit tankou van an... oswa tou pre li.',
      tl: 'Magpatakbo nang mabilis hangga\'t ang hangin... o malapit dito.',
      el: 'Εκτελέστε τον άνεμο... ή κοντά του.',
      bg: 'Бягайте по-бързо от вятъра... или близо до него.',
      cs: 'Jdi tak rychle jako vítr... nebo blízko k němu.',
      ja: '風と同じくらい速く走るか、またはそれに近づける。',
      hi: 'हवा के साथ चलिए... या उससे थोड़ा पीछे।',
      ko: '바람처럼 빨리 달릴 수 있습니다... 그것에 가깝습니다.',
      ro: 'Fugi rapid ca și vântul... sau aproape ca el.',
      da: 'Kør så hurtigt som vinden... eller tæt på den.'
    }
  },

  {
    name       : {$$: 'Coldforged Greaves' },
    description: {
      en: 'Icy cold boots forged without heat which allow you to run without stumbling.',
      ru: 'Холодные ботинки выкованы без тепла, которые позволяют бегать без спотыканий.',
      es: 'Botas frías forjadas sin calor que permiten correr sin tropezar.',
      fr: 'Bottes froides forgées sans chaleur qui vous permettent de courir sans trébucher',
      de: 'Kalte, ohne Hitze geschmiedete Stiefel, die es Ihnen ermöglichen, ohne Stolpern zu laufen.',
      pt: 'Botas frias forjadas sem calor que lhe permitem correr sem tropeçar',
      ko: '비틀 거리지 않고 달릴 수있는 열없이 단조 된 콜드 부츠',
      nl: 'Koude laarzen gesmeed zonder warmte waardoor u zonder struikelen kunt lopen',
      tr: 'Ateş kullanılmadan işlenmiş bu buz gibi soğuk botlar, tökezlemeden koşmanı sağlayacak.',
      pl: 'Zimne buty kute na gorąco, które umożliwiają bieganie bez potykania się.',
      sv: 'Kall stövlar smidda utan värme vilket gör att du kan springa utan att snubbla',
      ht: 'Bòt frèt fòje san chalè ki pèmèt ou kouri san yo pa bite',
      it: 'Stivali a freddo forgiati senza calore che permettono di correre senza inciampare.',
      hi: 'गर्मी के बिना ठंडे जूते जाली जो आपको ठोकर के बिना चलाने की अनुमति देते हैं',
      tl: 'Ang mga malamig na bota ay pinipigilan nang walang init na nagpapahintulot sa iyo na tumakbo nang walang katitisuran',
      el: 'Κρύες μπότες σφυρηλατημένες χωρίς θερμότητα που σας επιτρέπουν να τρέχετε χωρίς εμπόδια',
      bg: 'Студените ботуши изковани без топлина, които ви позволяват да бягате без препъване',
      cs: 'Studené boty kované bez tepla, které vám umožní běžet bez úrazu',
      ja: 'あなたはつまずくことなく実行することができます熱なしで鍛造コールドブーツ',
      ro: 'Cizmele reci ca gheața și forjate fără căldură îți permit să alergi fără să te împiedici.',
      da: 'Isnende kold støvler smedet uden varme, som giver dig mulighed for at løbe uden at snuble.'
    }
  },

  {
    name       : {$$: 'Cloudrunners' },
    description: {
      en: 'Some say you can run on clouds with these. The few that have tried have already ascended.',
      ru: 'Некоторые говорят, что с этими ботинками можно бегать по облакам. Те немногие, кто пытался, уже вознеслись.',
      de: 'Einige sagen, dass man damit auf Wolken laufen kann. Die wenigen, die es versucht haben, sind bereits aufgestiegen.',
      es: 'Se dice que puede correr en nubes con estos. Los pocos que trataban ya han ascendido.',
      fr: 'Certains disent qu\'on peut courir sur les nuages avec elles. Les quelques personnes qui ont essayé y sont déjà montés.',
      it: 'C\'è chi dice che con queste si può correre sulle nuvole. I pochi che hanno provato sono già saliti.',
      pt: 'Alguns dizem que se pode correr em nuvens com isto. Os poucos que tentaram já ascenderam.',
      nl: 'Sommigen zeggen dat je hiermee op wolken kunt lopen. De weinigen die het geprobeerd hebben zijn al opgestegen.',
      tr: 'İnsanlar bunlarla bulutların üzerinde koşabileceğinizi söylüyor. Denemiş olan birkaç kişi çoktan atmosfere ulaştı bile.',
      tl: 'Ang ilang mga sinasabi maaari kang tumakbo sa mga ulap sa mga ito. Ang ilang mga na sinubukan ay umakyat na.',
      pl: 'Niektórzy mówią, że możesz biegać z nimi po chmurach. Nieliczni, którzy próbowali, już się podnieśli.',
      sv: 'Vissa säger att du kan springa på moln med dessa. De få som har försökt har redan stigit upp.',
      cs: 'Někteří říkají, že s nimi můžete běžet na mraky. Těch několik, kteří se už pokusili vystoupit.',
      ja: 'あなたはこれらで雲の上を走ることができると言う人もいます。試みた少数の人はすでに上がっています。',
      hi: 'कहते है इनसे आप बादलों पे चल सकते है। जिन्होंने कोशिश की है वे तो पहले ही स्वर्ग पहुँच गए।',
      el: 'Κάποιοι λένε ότι μπορείτε να τρέξετε σε σύννεφα με αυτά. Οι λίγοι που έχουν δοκιμάσει έχουν ήδη ανέλθει.',
      bg: 'Някои казват, че с тях може да тичате на облаци. Малцината, които са се опитали, вече са се възнесли.',
      ht: 'Yon lòt ankò: ou ka kouri sou nwaj yo ak tout bagay sa. Twa ki te eseye fè deja est.',
      ko: '어떤 사람들은 이장화로 구름 위에서 뛰어 다닐 수 있다고 말한다. 시도한 몇명은 하늘나라로 갔다.',
      ro: 'Câțiva oameni spun că poți alerga pe nori cu acestea. Puținii care au incercat s-au înălțat deja.',
      da: 'Nogle siger, at du kan køre på skyer med disse. De få, der har forsøgt, har allerede steget op.'
    }
  },

  {
    name       : {$$: 'Talaria' },
    description: {
      en: 'Ancient boots rumoured to be stolen from the feet of a messenger god.',
      ru: 'По слухам, древние сапоги были украдены с ног бога-вестника.',
      de: 'Alte Stiefel sollen aus den Füßen des Kuriergottes gestohlen worden sein.',
      es: 'Se rumorea que las botas antiguas fueron robadas de los pies de un dios mensajero.',
      fr: 'Des bottes anciennes qui auraient été volées aux pieds d\'un dieu messager.',
      tl: 'Ang sinaunang bota na rumored na ninakaw mula sa mga paa ng diyos ng sugo ng.',
      it: 'Stivali antichi che si dice siano stati rubati dai piedi del dio messaggero.',
      pt: 'Dizem que estas botas antigas foram roubadas dos pés de um deus mensageiro.',
      nl: 'Eeuwenoude laarzen, waarvan wordt beweerd dat ze gestolen zijn uit de voeten van de boodschappergod.',
      tr: 'Haberci tanrının ayaklarından çalındığı söylenilen ilkel botlar.',
      pl: 'Starożytne buty, które podobno zostały skradzione z nóg posłańca bogów.',
      sv: 'Gamla stövlar ryktes för att bli stulna från fötterna till den budbärarens gud.',
      cs: 'Starověké boty, o nichž se říkalo, že jsou ukradeny z nohou posla boha.',
      ja: '古代のブーツは、メッセンジャーの神の足から盗まれたと噂されていました。',
      hi: 'प्राचीन जूते एक दूत भगवान के पैरों से चोरी होने की अफवाह थी।',
      el: 'Αρχαία μπότες που φημολογούνται ότι κλέβονται από τα πόδια του θεού του αγγελιοφόρου.',
      bg: 'Древните ботуши, за които се говори, че са откраднати от краката на бог-посланик.',
      ko: '고대의 부츠는 전령 신의 발에서 도난 당했다고 소문이났다.',
      ht: 'Bòt ansyen yo rimè yo dwe vòlè nan pye yo nan yon bondye mesaje.',
      ro: 'Bocanci antici, zvoniți a fi furați de la picioarele unui zeu mesager.',
      da: 'Gamle støvler rygter sig for at blive stjålet fra en messengerguds fødder.'
    }
  },

  {
    name       : {$$: 'Starshards' },
    description: {
      en: 'Stars were always considered to be almighty, now they\'re yours.',
      ru: 'Звезды всегда считались всемогущими, теперь они твои',
      de: 'Sterne wurden immer als allmächtig angesehen, jetzt gehören sie dir.',
      es: 'Las estrellas siempre fueron consideradas todopoderosas, y ahora son tuyas.',
      fr: 'Les étoiles ont toujours été considérées comme toutes-puissantes, maintenant elles t\'appartiennent.',
      it: 'Le stelle sono sempre state considerate onnipotenti, ora sono tue.',
      pt: 'As estrelas sempre foram consideradas poderosas, agora são tuas.',
      nl: 'Sterren werden altijd beschouwd als almachtig, nu zijn ze van jou.',
      tr: 'Yıldızlar her zaman kudretli olarak kabul edildi, şimdi onlar senin.',
      tl: 'Ang mga bituin ay palaging itinuturing na pinakamakapangyarihan ngayon sila ay iyo.',
      pl: 'Gwiazdy zawsze uważano za wszechmocne, teraz są twoje.',
      sv: 'Stjärnor anses alltid vara allsmäktiga, nu är de din.',
      cs: 'Hvězdy byly vždy považovány za všemohoucího, teď jsou vaše.',
      ja: '星は常に万能であると考えられてきました。',
      hi: 'सितारों को हमेशा सर्वशक्तिमान माना गया है, अब वे आपके हो गए।',
      el: 'Τα αστέρια πάντα θεωρούνταν παντοδύναμα τώρα που είναι δικά σας.',
      bg: 'Звездите винаги са били считани за всемогъщи, сега са ваши.',
      ht: 'Zetwal te toujou konsidere tout, koulye a, y\' ap ye.',
      ko: '별은 언제나 전능자로 여겨졌습니다, 이제 당신의 것입니다.',
      ro: 'Stelele au fost întotdeauna considerate a fi atotputernice, acum sunt ale tale.',
      da: 'Stjerner blev altid betragtet som almægtige, nu er de dine.'
    }
  }

]
