export default [
  { // Item name. Names are English only!
    name       : {$$: 'Driftwood Shortbow' },
    // Item description.
    description: {
      en: 'Almost lightweight. You can probably find something better around.',
      ru: 'Легкий лук. Скорее всего, вы сможете найти что-то получше .',
      fr: 'Un vrai poids plume. Il y en à sûrement de meilleurs dans le coin.',
      de: 'Fast leicht. Du kannst wahrscheinlich etwas Besseres finden.',
      es: 'Casi ligero. Probablemente puedas encontrar algo mejor por aquí.',
      pt: 'Quase leve. Você pode provavelmente encontrar algo melhor ao redor.',
      nl: 'Bijna lichtgewicht. Je kunt waarschijnlijk iets beters vinden.',
      pl: 'Prawie lekka. Prawdopodobnie znajdziesz tu coś lepszego.',
      it: 'Quasi leggero. Probabilmente si può trovare qualcosa di meglio in giro.',
      sv: 'Inte så tung. Du kan nog hitta nåt bättre.',
      tl: 'Halos magaan. Maaari mong mahanap ang isang bagay na mas mahusay sa paligid.',
      ht: 'Prèske lejè. Ou ka pwobableman jwenn yon bagay pi byen alantou.',
      tr: 'Neredeyse tüy kadar hafif. Muhtemelen etrafta daha iyi bir şeyler bulabilirsin.',
      hi: 'लगभग हल्का। आस पास आप इससे बहतर चीज़ धून्ध सकते हैं।',
      cs: 'Téměř lehká. Asi můžete najít něco lepšího.',
      el: 'Σχεδόν ελαφρύς. Μπορεί πιθανώς να βρείτε κάτι καλύτερο γύρω.',
      bg: 'Почти лек. Вероятно можете да намерите нещо по-добро наоколо.',
      ja: 'ほぼ軽量です。あなたはおそらくもっと良いものを見つけることができるでしょう。',
      ro: 'Ușor ca o pană. Probabil poți găsi ceva mai bun în jur.',
      ko: '거의 가볍다. 아마도 주위에 더 나은 것을 찾을 수 있습니다.',
      da: 'Næsten letvægt. Du kan sikkert finde noget bedre rundt.'
    }
  },

  {
    name       : {$$: 'Novice Shortbow' },
    description: {
      en: 'You feel less skilled just by holding this in your hands.',
      ru: 'Вы чувствуете себя менее опытным, просто держа его в своих руках',
      fr: 'On se sent moins doué rien qu\'en tenant cet arc.',
      de: 'Du fühlst dich weniger geschickt, nur weil du das in deinen Händen hältst.',
      es: 'Te sientes menos hábil con sólo sostener esto en tus manos.',
      pt: 'Sentes-te menos hábil só por teres isto nas mãos.',
      nl: 'Je voelt je minder bekwaam door dit in je handen te houden.',
      pl: 'Czujesz się mniej wykwalifikowany, trzymając to w swoich rękach.',
      it: 'Ti senti meno abile solo tenendoti questo tra le mani.',
      sv: 'Bara att hålla den i händerna får dig att känna dig oduglig.',
      ht: 'Ou santi ou mwens kalifye jis pa kenbe sa a nan men ou.',
      tr: 'Sadece tutmakla bile insan kendini yeteneksiz hissediyor, öyle bir yay.',
      hi: 'इसे हाथ में पकड़ते हीं आप नासमझ महसूस करेंगे।',
      tl: 'Ang pakiramdam mo ay hindi gaanong nangangailangan ng kasanayan sa pamamagitan ng pagpindot sa iyong mga kamay.',
      cs: 'Cítíš se méně zručně, když to držíš ve svých rukou.',
      el: 'Αισθάνεσαι λιγότερο εξειδικευμένο κρατώντας το στα χέρια σου.',
      bg: 'Чувствате се по-малко квалифицирани само ако държите това в ръцете си.',
      ja: 'これを手に持つだけでは、上手くいけないと感じます。',
      ro: 'Te simți mai puțin experimentat doar ținând acesta în mâinile tale.',
      ko: '이것을 손에 쥐기만해도 실력이 주는 겄갓습니다.',
      da: 'Du føler dig mindre dygtige bare ved at holde dette i dine hænder.'
    }
  },

  {
    name       : {$$: 'Curved Shortbow'},
    description: {
      en: 'This bow is curved to such an extent that it will probably snap at any moment.',
      ru: 'Лук настолько изогнут, что кажется будто он сейчас треснет.',
      hi: 'इतना मुड़ा हुआ कि किसी भी समय आधे में टूट सकता है।',
      nl: 'Het is zo gebogen dat het elk moment kan breken.',
      ro: 'A fost curbat atât de tare încât ar putea să cedeze în orice clipă.',
      pt: 'Este arco é curvado a tal ponto que provavelmente se partirá a qualquer momento.',
      fr: 'Cet arc est tellement courbé qu\'il pourrait se briser à tout moment.',
      de: 'Dieser Bogen ist so stark gebogen, dass er wahrscheinlich jeden Moment einrasten wird.',
      es: 'Este arco está curvado hasta tal punto que probablemente se romperá en cualquier momento.',
      pl: 'Ten łuk jest zakrzywiony do tego stopnia, że prawdopodobnie w każdej chwili pęknie.',
      it: 'Questo arco è curvo a tal punto che probabilmente si spezzerà in qualsiasi momento.',
      sv: 'Den här pilbågen är så krökt att den lär gå av när som helst.',
      ht: 'Se banza sa a koube nan yon limit ke li pral pwobableman menen nan nenpòt ki moman.',
      el: 'Αυτό το τόξο είναι καμπύλο σε τέτοιο βαθμό που πιθανότατα θα σπάσει ανά πάσα στιγμή.',
      tl: 'Ang busog na ito ay may kurbatang sa isang lawak na ito ay maaaring snap sa anumang sandali.',
      bg: 'Този лък е извит до такава степен, че вероятно ще се скъса във всеки момент.',
      tr: 'Bu yay, muhtemelen herhangi bir anda kopacak şekilde bükülmüş.',
      cs: 'Tento luk je zakřivený do takové míry, že se v každém okamžiku pravděpodobně zaklapne.',
      ja: 'この弓はそれがおそらくいつでもスナップするような程度に湾曲しています。',
      ko: '이 활은 언제나 스냅 될 정도까지 구부러져 있습니다.',
      da: 'Denne bue er buet i en sådan grad, at den sikkert vil snappe til enhver tid.'
    }
  },

  {
    name       : {$$: 'Adventurer\'s Shortbow' },
    description: {
      en: 'Whoever left this on the ground probably didn\'t meet a nice end.',
      ru: 'Тот кто оставил его на земле, вероятно, встретил не хороший конец',
      fr: 'Quiconque a laissé cet arc par terre n\'a sûrement pas eu droit à une fin heureuse.',
      de: 'Wer das auf dem Boden gelassen hat, hat wahrscheinlich kein schönes Ende gefunden.',
      es: 'Quienquiera que haya dejado esto en el suelo probablemente no tuvo un buen final.',
      pt: 'Quem quer que tenha deixado isto no chão, provavelmente não teve um final agradável.',
      nl: 'Wie dit op de grond liet liggen, kwam waarschijnlijk niet aan een mooi einde.',
      pl: 'Ktokolwiek zostawił to na ziemi, prawdopodobnie nie spotkał się z miłym końcem.',
      it: 'Chiunque l\'abbia lasciato a terra probabilmente non ha avuto una bella fine.',
      sv: 'Den som tappade den här på marken dog nog ingen trevlig död.',
      ht: 'Nenpòt moun ki te kite sa a sou tè a pwobableman pa satisfè yon fen bèl.',
      el: 'Όποιος έφυγε από αυτό στο έδαφος πιθανότατα δεν κατάλαβε ένα καλό τέλος.',
      tl: 'Ang sinumang nag-iwan dito sa lupa ay malamang na hindi natutugunan ang magandang dulo.',
      bg: 'Който е оставил това на земята, вероятно не е срещнал хубав край.',
      tr: 'Bunu kim yere düşürdüyse muhtemelen sonu iyi olmamıştır.',
      hi: 'जिस किसी ने भी इसे ज़मीन पर छोड़िया है, उसका अन्त अच्छा नहीं था।',
      cs: 'Ten, kdo tohle na zemi opustil, pravděpodobně neuskutečnil pěkný konec.',
      ja: 'これを地面に置いたままにしておいた人は誰もがうまく行かなかったでしょう。',
      ro: 'Oricine l-ar fi lăsat pe pământ, probabil că nu a avut un sfârșit frumos.',
      ko: '이것을 남긴 사람은 아마도 안좋은 끝을 만난 것 같습니다.',
      da: 'Den, der forlod dette på jorden, opfyldte sandsynligvis ikke en god ende.'
    }
  },

  {
    name       : {$$: 'Long Bow' },
    description: {
      en: 'A more advanced weapon. Quite nice to look at.',
      ru: 'Более продвинутое оружие. Довольно приятно смотреть на него.',
      de: 'Eine fortschrittlichere Waffe. Sehr schön anzusehen.',
      es: 'Un arma más avanzada. Bastante bonito de ver.',
      fr: 'Une arme plus travaillée. Plutôt agréable à regarder.',
      pt: 'Uma arma mais avançada. Bastante agradável de se ver.',
      nl: 'Een geavanceerder wapen. Leuk om naar te kijken.',
      pl: 'Bardziej zaawansowana broń. Całkiem nieźle się na nią patrzy.',
      it: 'Un\'arma più avanzata. Piuttosto bello da guardare.',
      sv: 'Ett mer avancerat vapen. Ganska trevligt att se på.',
      ht: 'Yon zam ki pi avanse. Byen bèl gade.',
      tr: 'Daha gelişmiş bir silah. Bakması bile oldukça güzel hissettiriyor.',
      tl: 'Isang mas advanced na armas. Masyadong maganda ang pagtingin.',
      hi: 'एक उन्नत हथियार। दिखने में काफी अच्छा।',
      cs: 'Pokročilejší zbraň. Docela hezké se na to podívat.',
      el: 'Ένα πιο προηγμένο όπλο. Πολύ ωραίο να το δούμε.',
      bg: 'По-напреднало оръжие. Много хубаво е да се погледне.',
      ja: 'より高度な武器見てとてもうれしいです。',
      ro: 'O armă mai avansată. Destul de frumoasă la înfățișare.',
      ko: '더 발전된 무기. 보기도 좃습니다.',
      da: 'Et mere avanceret våben. Ganske rart at se på.'
    }
  },

  {
    name       : {$$: 'Bone Bow' },
    description: {
      en: 'Put together with the bones of... somebody?',
      ru: 'Cобран из костей... кого-то?',
      fr: 'Assemblé avec les os de... quelqu\'un?',
      de: 'Zusammen mit den Knochen von... jemandem?',
      es: '¿Colocado con los huesos de... alguien?',
      pt: 'Feito com os ossos de... alguém?',
      nl: 'In elkaar gezet met de botten van... iemand?',
      tl: 'Isama ang mga buto ng ... isang tao?',
      pl: 'Złożone razem z kośćmi... kogoś?',
      it: 'Messo insieme alle ossa di... qualcuno?',
      sv: 'Gjord av... någons... ben',
      el: 'Συνδυάστε με τα οστά του... κάποιον;',
      bg: 'Заедно с костите на някой?',
      ht: 'Mete ansanm ak zo yo nan... yon moun?',
      tr: 'Şeylerin kemikleri birleştirilerek yapılmış... insanların?',
      hi: 'किस इनसान की हड्डीयो से बना है?',
      cs: 'Dej dohromady s kostmi... někoho?',
      ja: '〜誰かの骨と一緒に？',
      ro: 'Făcut din oasele... cuiva?',
      ko: '뼈로 만들어진 활... 누구의 뼈일가?',
      da: 'Sammen med knoglerne af... nogen?'
    }
  },

  {
    name       : {$$: 'Elven Bow' },
    description: {
      en: 'An expert bow of an elegant race.',
      ru: 'Искусный лук изящный расы',
      fr: 'Un arc d\'expert venant d\'une race élégante.',
      de: 'Ein erfahrener Bogen eines eleganten Rennens.',
      es: 'Un arco experto de una raza elegante.',
      pt: 'Um arco perito de uma raça elegante.',
      nl: 'Een deskundige boog van een verfijnd geslacht.',
      pl: 'Ekspercki łuk elegancki ród.',
      it: 'Un arco esperto di una gente signorile.',
      tl: 'Isang dalubhasang bow ng isang eleganteng lahi.',
      sv: 'En expertbuga av en sirlig ras.',
      ht: 'Yon banza ekspè nan yon ras ki elegan.',
      tr: 'Zarif bir ırkın uzman yayı.',
      hi: 'एक सुरुचिपूर्ण दौड़ का एक विशेषज्ञ धनुष।',
      el: 'Ένας ειδικός τόξο μιας κομψής φυλής.',
      bg: 'Един експертен поклон на елегантен раса.',
      cs: 'Odborný luk elegantní druh.',
      ja: '優雅なレースの巧妙な弓。',
      ro: 'Un arc expert al unei rasă elegante.',
      ko: '우아한 레이스의 전문가 활입니다.',
      da: 'En ekspertbue af en elegant race.'
    }
  },

  {
    name       : {$$: 'Ancient Bow' },
    description: {
      en: 'Crude, but effective. Draws its power from the tiny leaf attached to it.',
      ru: 'Грубый, но эффективный. Получает силу из крошечного листа, прикрепленного к нему.',
      de: 'Grob, aber effektiv. Seine Kraft bezieht er aus dem kleinen Blatt, das daran befestigt ist.',
      es: 'Crudo, pero efectivo. Extrae su poder de la diminuta hoja adherida a él.',
      fr: 'Grossier, mais efficace. Tire son énergie de la petite feuille qui lui est attachée.',
      pt: 'Bruto, mas eficaz. Retira o seu poder da pequena folha que lhe está ligada.',
      tl: 'Maliit ngunit epektibo. Gawin ang kapangyarihan nito mula sa maliit na dahon na nakalakip dito.',
      nl: 'Ruw, maar effectief. Trekt zijn kracht uit het kleine blaadje dat eraan vastzit.',
      pl: 'Surowe, ale skuteczne. Wyciąga swoją moc z dołączonego do niego malutkiego liścia.',
      it: 'Crudo, ma efficace. Trae il suo potere dalla minuscola foglia ad essa attaccata.',
      el: 'Ακατέργαστο αλλά αποτελεσματικό. Βγάζει τη δύναμή του από το μικροσκοπικό φύλλο που συνδέεται με αυτό.',
      bg: 'Сурови, но ефективни. Извлича силата си от малкия лист, прикрепен към него.',
      sv: 'Primitiv, men effektiv. Får sin kraft från ett litet fastsatt blad.',
      ht: 'Brut, men efikas. Trase pouvwa li soti nan fèy la ti tache ak li.',
      tr: 'İlkel, ama etkili. Gücünü, kendisine bağlı küçük yapraktan alıyor.',
      hi: 'अनगढ़, लेकिन प्रभावशाली। अपने उपर उगने वाली छोटी पत्ती इसे शक्ती देती हैं।',
      cs: 'Hrubý, ale účinný. Čerpá svou sílu z malého lístku, který je k němu připojen.',
      ja: '粗いが効果的。それに付いている小さな葉から力を引き出します。',
      ro: 'Crud, dar eficient. Își trage puterea din frunzulița atașată pe el.',
      ko: '조잡하지만 효과적입니다. 그것에 붙어있는 작은 잎에서 그것의 힘을 당긴다.',
      da: 'Rå, men effektiv. Træk sin kraft fra det lille blad fastgjort til det.'
    }
  },

  {
    name       : {$$: 'Iron Piercer' },
    description: {
      en: 'Burns away the enemy with the spiciest of red coloring.',
      ru: 'Сжигает противника своим ярко-красным окрасом.',
      de: 'Verbrennt den Feind mit der schärfsten roten Farbe.',
      es: 'Quema al enemigo con la coloración roja más picante.',
      fr: 'Brûle ses ennemis avec la coloration rouge la plus prononcée.',
      pt: 'Queima o inimigo com a mais picante das cores vermelhas.',
      nl: 'Verbrandt de vijand met de scherpste rode kleur.',
      pl: 'Wypala wroga z najostrzejszym czerwonym zabarwieniem.',
      it: 'Brucia il nemico con la più piccante colorazione rossa.',
      tl: 'Sinunog ang kaaway sa spiciest ng pulang kulay.',
      sv: 'Bränner bort fienden med den spiciest av röd färgning.',
      ht: 'Burns lwen lènmi an ak spiciest nan koloran wouj.',
      el: 'Εξαφανίζει τον εχθρό με το πιό spicyest του κόκκινου χρωματισμού.',
      bg: 'Изгаря врага с най-блестящия червен цвят.',
      hi: 'मसालेदार लाल रंग से दुश्मनों को राख कर देता है।',
      cs: 'Spálí nepřítele s nejjemnějším červeným zbarvením.',
      ja: '最も辛い赤色の着色で敵を焼き払います。',
      ro: 'Arde inamicul cu cea mai intensă culoare de roșu.',
      ko: '뜨거운 붉은 색으로 적을 태운다.',
      da: 'Brænder fjenden med den spicieste af rød farve.',
      tr: 'Düşmanlarını kırmızı parlak bir ışıkla yakar.'
    }
  },

  {
    name       : {$$: 'Silver Recurve' },
    description: {
      en: 'A bow commonly used by low ranked royal archers. Blends in well with vegetation.',
      ru: 'Лук, обычно используемый низкопоставленными королевскими лучниками. Хорошо сливается с растительностью.',
      de: 'Ein Bogen, der häufig von niederrangigen königlichen Bogenschützen verwendet wird. Passt sich gut der Vegetation an.',
      es: 'Un arco comúnmente usado por arqueros reales de bajo rango. Se integra bien con la vegetación.',
      fr: 'Un arc couramment utilisé par les archers royaux de bas rang. Se fond bien dans la végétation.',
      pt: 'Um arco normalmente usado por arqueiros reais de baixo escalão. Mistura-se bem com a vegetação.',
      tl: 'Isang busog na karaniwang ginagamit ng mababang ranggo na mga mamamana. Pinagsasama-sama ng mga halaman.',
      nl: 'Een boog die vaak gebruikt wordt door laaggeplaatste koninklijke boogschutters. Past goed in de vegetatie.',
      pl: 'Łuk powszechnie używany przez nisko sklasyfikowanych łuczników królewskich. Dobrze komponuje się z roślinnością.',
      it: 'Un arco comunemente usato dagli arcieri reali di basso rango. Si fonde bene con la vegetazione.',
      sv: 'En båge som vanligtvis används av lågrankade kungliga bågar. Blandar väl med vegetation.',
      ht: 'Yon banza souvan itilize pa banza klase wa archers. Melanje nan byen ak vejetasyon,',
      el: 'Ένα τόξο που χρησιμοποιείται συνήθως από τους χαμηλού βαθμού βασιλικούς τοξότες. Συνδυάζεται καλά με τη βλάστηση.',
      bg: 'Лук, който често се използва от ниско разположените кралски стрелци. Съчетава се добре с растителността.',
      tr: 'Genel olarak düşük rütbeli kraliyet okçuları tarafından kullanılan bir yay. Bitki örtüsü sayesinde iyi kamufle olur.',
      hi: 'राजकीय सिपाहियों द्वारा इस्तेमाल किए जाने वाला धनुष, पेड़ पत्तीयों में आसानी से छिप जाता है।',
      cs: 'Luk běžně používaný nízkohodnotnými královskými lukostřelci. Směsi ve vegetaci.',
      ja: '低位の王室弓兵によく使われる弓。植生とよく調和しています。',
      ro: 'Un arc folosit în mod obișnuit de arcașii regali de rang inferior. Se amestecă bine cu vegetația.',
      ko: '낮은 등급의 왕궁에 자주 사용되는 활. 식물과 잘 어울립니다.',
      da: 'En bue, der almindeligvis anvendes af lavrangerede kongelige bueskytter. Blander godt med vegetationen.'
    }
  },

  {
    name       : {$$: 'Assassin\'s Bow' },
    description: {
      en: 'Masterfully crafted by the bandits of the capitals.',
      ru: 'Мастерски созданный столичными бандитами.',
      de: 'Meisterhaft gefertigt von den Banditen der Hauptstädte.',
      es: 'Hecho con maestría por los bandidos de las capitales.',
      tl: 'Masterfully crafted sa pamamagitan ng mga pangkat ng mga capitals.',
      fr: 'Fabriqué avec brio par les bandits des capitales.',
      pt: 'Magistralmente trabalhado pelos bandidos das capitais.',
      nl: 'Op meesterlijke wijze gemaakt door de bandieten van de hoofdsteden.',
      pl: 'Mistrzowsko wykonane przez bandytów ze stolic.',
      it: 'Artigianato con maestria dai banditi delle capitali.',
      sv: 'Mästerligt framställd av banditerna i huvudstäderna.',
      ht: 'Metriz fabrike pa bandi kapital yo.',
      tr: 'Başkentlerin haydutları tarafından ustaca hazırlanmış.',
      hi: 'राज्य के डाकुओं द्वारा बनाया गया विशेष हथियार।',
      el: 'Χειροποίητα κατασκευασμένο από τους ληστές των πρωτευουσών.',
      bg: 'Майсторски изработени от бандитите на столиците.',
      cs: 'Mistrovsky vytvořený bandity z hlavních měst.',
      ja: '首都の盗賊によって巧妙に作られました。',
      ro: 'Meșteșugit de bandiții capitalelor.',
      ko: '도시 산적들에 의해 훌륭하게 제작되었습니다.',
      da: 'Mesterligt udformet af banditernes banditter.'
    }
  },

  {
    name       : {$$: 'Skyfire Warbow' },
    description: {
      en: 'A rare bow used in the greatest of wars. Shooting it makes you feel like the heavens will collapse.',
      ru: 'Редкий лук, используемый в величайших войнах. Стреляя, вы чуствуете, как будто упадут небеса.',
      fr: 'Un arc rare utilisé dans les plus grandes batailles. Tirer une flèche avec cet arme vous donne l\'impression que les cieux vont s\'effondrer.',
      de: 'Ein seltener Bogen, der in den größten Kriegen verwendet wird. Beim Schießen hat man das Gefühl, dass der Himmel zusammenbrechen wird.',
      es: 'Un arco raro usado en la mayor de las guerras. Disparar te hace sentir como si el cielo se fuera a derrumbar.',
      pt: 'Um arco raro usado na maior das guerras. Atirar nele faz você sentir que os céus vão entrar em colapso.',
      tl: 'Ang isang bihirang bow na ginagamit sa pinakadakilang ng mga digmaan. Ang pagbaril ay ginagawa mo ang pakiramdam tulad ng pagbagsak ng langit.',
      nl: 'Een zeldzame boog gebruikt in de grootste oorlogen. Door het schieten ervan krijg je het gevoel dat de hemel zal instorten.',
      pl: 'Rzadki łuk używany w największych wojnach. Strzelanie do niego sprawia, że czujesz się, jakby niebo się zawaliło.',
      it: 'Un arco raro usato nelle più grandi guerre. Sparare ti fa sentire come se il cielo crollerà.',
      sv: 'En sällsynt båge som används i störst krig. Skytte det gör att du känner att himlen kommer att kollapsa.',
      ht: 'Yon banza ra ki te itilize nan pi gran nan lagè. Fiziyad li fè ou santi ou tankou syèl la pral tonbe plat atè.',
      el: 'Ένα σπάνιο τόξο που χρησιμοποιείται στα μεγαλύτερα των πολέμων. Σκοποβολή σας κάνει να νιώσετε ότι οι ουρανοί θα καταρρεύσουν.',
      bg: 'Рядък лък, използван в най-великите войни. Стрелбата го кара да се чувстваш като небето ще се срути.',
      tr: 'En büyük savaşlarda kullanılan bu nadir yayı çekince sanki yer gök yıkılacak gibi hissettiriyor.',
      hi: 'सबसे महान युद्ध में इस्तेमाल किया गया दुर्लभ धनुष। इसे चलाने से लगता है कि स्वर्ग टूट कर गिर जाएगा।',
      cs: 'Vzácný luk používaný v největších válkách. Střelba z vás dělá pocit, že se nebe zhroutí.',
      ja: '最も偉大な戦争で使われる珍しい弓。それを撮影すると、天が崩壊するように感じるでしょう。',
      ro: 'Un arc rar, folosit în cele mai mari războaie. Să tragi te face să simți că cerurile se vor prăbuși.',
      ko: '가장 큰 전쟁에서 사용 된 희귀 한 활. 그것을 쏘면 하늘이 무너지는 것처럼 느껴집니다.',
      da: 'En sjælden bue, der bruges i de største krige. Skydning det får dig til at føle, at himlen vil kollapse.'
    }
  },

  {
    name       : {$$: 'Hellfire Warbow' },
    description: {
      en: 'What is it? Is it ice? The world may never know...',
      ru: 'Что это? Это лед? Мир может никогда не узнать...',
      fr: 'Qu\'est-ce que c\'est? De la glace? Le monde ne le saura peut-être jamais...',
      de: 'Was ist das? Was ist das? Ist es Eis? Die Welt wird es vielleicht nie erfahren...',
      tl: 'Ano ito? Yelo ba Ang mundo ay hindi maaaring malaman...',
      es: '¿Qué es esto? ¿Es hielo? El mundo tal vez nunca lo sepa...',
      pt: 'O que é isso? É gelo? O mundo pode nunca saber...',
      nl: 'Wat is het? Is het ijs? De wereld zal misschien nooit weten...',
      pl: 'Co to jest? Czy to lód? Świat może nigdy się nie dowiedzieć...',
      it: 'Cosa c\'è? È ghiaccio? Il mondo potrebbe non saperlo mai...',
      sv: 'Vad är det? Är det is? Världen kanske aldrig vet...',
      ht: 'Kisa li ye? Èske li glas? Mond lan pa janm ka konnen...',
      el: 'Τι είναι αυτό? Είναι πάγος; Ο κόσμος μπορεί ποτέ να μην ξέρει...',
      bg: 'Какво е? Лед ли е? Светът никога няма да знае...',
      tr: 'Bu ne? Buz mu bu? Dünya bunu asla bilemeyecek...',
      hi: 'यह क्या है? कहीं बर्फ़ तो नहीं? दुनिया को कभी पता नहीं चलेगा।',
      cs: 'Co je to? Je to led? Svět se nikdy nedozví...',
      ja: 'それは何ですか？氷ですか？世界は知らないかもしれません...',
      ro: 'Ce e asta? Gheață? Lumea s-ar putea să nu afle niciodată.',
      ko: '이게 뭐지? 얼음일까? 세상은 결코 알지 못할 것입니다...',
      da: 'Hvad er det? Er det is? Verden kan aldrig vide...'
    }
  },

  {
    name       : {$$: 'Widowmaker' },
    description: {
      en: 'Kills as beautifully as it looks.',
      ru: 'Убивает так же красиво, как и выглядит.',
      de: 'Tötet so schön, wie es aussieht.',
      es: 'Mata tan maravillosamente como parece.',
      fr: 'Tue aussi joliment que la beauté de cet arc.',
      pt: 'Mata tão bem como parece.',
      nl: 'Doodt net zo mooi als het eruit ziet.',
      pl: 'Zabija tak pięknie, jak wygląda.',
      it: 'Uccide tanto bene quanto sembra.',
      el: 'Σκοτώνει τόσο όμορφα όσο φαίνεται.',
      tl: 'Kills bilang maganda bilang hitsura nito.',
      bg: 'Убива толкова красиво, колкото изглежда.',
      sv: 'Dödar så vackert som det ser ut.',
      ht: 'Touye bèl jan li sanble.',
      tr: 'Güzel göründüğü kadar güzel öldürür de.',
      hi: 'जितना खूबसूरत दिखता है उतनी ही खूबसूरती से मारता है।',
      cs: 'Zabije tak krásně, jak to vypadá.',
      ja: '見た目と同じくらい美しく殺します。',
      ro: 'Ucide la fel de frumos cum și arată.',
      ko: '외형만큼 아름답게 적을 죽깁니다.'
    }
  },

  {
    name       : {$$: 'Stormsong' },
    description: {
      en: 'Surrounded by a ghastly aura. The wind blows in the direction you aim it.',
      ru: 'Окруженный аурой, наводящей ужас. Ветер дует в том направлении, куда вы нацеливаетесь.',
      de: 'Umgeben von einer grässlichen Aura. Der Wind weht in die Richtung, in die du ihn zielst.',
      es: 'Rodeado de un aura espantosa. El viento sopla en la dirección en que lo apuntas.',
      fr: 'Entouré d\'une aura horrible. Le vent souffle dans la direction où vous visez.',
      pt: 'Rodeado por uma aura medonha. O vento sopra na direção que você aponta.',
      nl: 'Omringd door een afschuwelijke aura. De wind waait in de richting waarin je hem richt.',
      pl: 'Otoczony upiorną aurą. Wiatr wieje w kierunku, w którym go celujesz.',
      it: 'Circondato da un\'aura spettrale. Il vento soffia nella direzione in cui lo si mira.',
      sv: 'Omgiven av en hemsk aura. Vinden blåser i riktning mot målet.',
      tl: 'Napalibutan ng isang malupit na aura. Humihihip ang hangin sa direksyon mo sa layunin nito.',
      ht: 'Antoure pa yon Aura efreyan. Van an soufle nan direksyon ou vize li.',
      el: 'Περιβάλλεται από μια φρικτή αύρα. Ο άνεμος φυσά προς την κατεύθυνση που εσείς σκοπεύετε.',
      bg: 'Заобиколен от ужасна аура. Вятърът духа в посоката, в която го насочвате.',
      tr: 'Kasvetli bir havayla çevrili. Rüzgar, bu yayı çevirdiğiniz yöne doğru eser.',
      hi: 'एक भयंकर आभा से घिरा। जिस दिशा में इसे चलाएंगे, हवा उस हि दिशा में चलती है।',
      cs: 'Obklopen hroznou aurou. Vítr fouká ve směru, kterým je zamíříte.',
      ja: 'ひどいオーラに囲まれています。風はあなたがそれを目指す方向に吹きます。',
      ro: 'Este înconjurat de o aură îngrozitoare. Vântul suflă în direcția în care țintești.',
      ko: '무시 무시한 분위기로 둘러싸여 있습니다. 바람은 당신이 정하는 방향으로 불어납니다.',
      da: 'Omgivet af en forfærdelig aura. Vinden blæser i retningen du målretter mod.'
    }
  },

  {
    name       : {$$: 'Scarebow' },
    description: {
      en: 'So scary that few have the guts to hold it.',
      ru: 'Настолько пугающий, что немногим хватает мужества держать его.',
      de: 'So beängstigend, dass nur wenige den Mut haben, es zu halten.',
      es: 'Tan aterrador que pocos tienen la coraje para sostenerlo.',
      fr: 'Un arc si effrayant que peu de gens ont le courage de le brandir.',
      pt: 'Tão assustador que poucos têm a coragem de o segurar.',
      nl: 'Zo eng dat weinigen het lef hebben om het vast te houden.',
      tl: 'Kaya nakakatakot na ilang may mga lakas ng loob upang i-hold ito.',
      pl: 'Tak przerażające, że niewielu ma odwagę, by to utrzymać.',
      it: 'Cosi\' spaventoso che pochi hanno il coraggio di trattenerlo.',
      sv: 'Så läskigt att få har mage att hålla den.',
      ht: 'Se konsa, pè ke kèk gen kouraz yo kenbe li.',
      el: 'Τόσο τρομακτικό που λίγοι έχουν τα κότσια να το κρατήσουν.',
      bg: 'Толкова страшно, че малцина имат смелостта да го държат.',
      tr: 'O kadar korkunç ki çok az kişi onu tutacak cesarete sahip.',
      hi: 'इतना डरावना की कुछ ही इसे उठाने की हिम्मत जुटा पाए हैं।',
      cs: 'Tak děsivé, že jen málokdo má odvahu držet to.',
      ja: 'それを保持するための勇気を持っている人はほとんどいないので怖い。',
      ro: 'Atât de înfricoșător că puțini au curajul să-l țină.',
      ko: '너무 무섭기 때문에 그것을 잡을 용기가 있는자는 거의 없습니다.',
      da: 'Så skræmmende, at få har modet til at holde det.'
    }
  },

  {
    name       : {$$: 'Fury' },
    description: {
      en: 'Embedded with a primal rage, your foes tremble at the sight of this weapon. Pew pew is the last thing they will ever hear.',
      ru: 'Насыщенный первобытной яростью, ваши противники дрожат при виде этого оружия. Пиу Пиу - последнее, что они услышат.',
      de: 'Eingebettet in eine urtümliche Wut, zittern deine Feinde beim Anblick dieser Waffe. Kirchenbank ist das Letzte, was sie je hören werden.',
      es: 'Envueltos en una furia primigenia, tus enemigos tiemblan al ver esta arma. Pew Pew es lo último que oirán.',
      fr: 'Enfermés dans une rage primitive, vos ennemis tremblent à la vue de cette arme. Pew pew pew est la dernière chose qu\'ils n\'entendront jamais.',
      pt: 'Embutido em uma raiva primária, seus inimigos tremem ao ver esta arma. O banco de bancos é a última coisa que eles vão ouvir.',
      nl: 'Ingebed in een oerwoede, beven je vijanden bij het zien van dit wapen. Pew pew is het laatste wat ze ooit zullen horen.',
      pl: 'Osadzeni w pierwotnej wściekłości, twoi wrogowie drżą na widok tej broni. Pew pewna ławka jest ostatnią rzeczą, jaką kiedykolwiek usłyszą.',
      it: 'Incastonati in una rabbia primordiale, i tuoi nemici tremano alla vista di quest\'arma. Pew pew pew è l\'ultima cosa che sentiranno mai.',
      el: 'Ενσωματωμένοι με μια πρωταρχική οργή οι εχθροί σας τρέμουν με την όραση αυτού του όπλου. Το pew pew είναι το τελευταίο πράγμα που θα ακούσουν ποτέ.',
      bg: 'Вкопчени в първична ярост, враговете ви треперят от това оръжие. Pew pew е последното нещо, което някога ще чуят.',
      tl: 'Naka-embed sa isang primal galit ang iyong mga foes panginginig sa paningin ng armas na ito. Pew bangko ay ang huling bagay na kanilang maririnig.',
      sv: 'Inbäddad med primitiv raseri, dina fiender darrar vid synen av detta vapen. Pew pew är det sista de någonsin kommer att höra.',
      ht: 'Embedded ak yon primal raj la, lènmi ou souke nan je a nan zam sa a. Pew pew pew la se bagay la dènye tout tan tout tan yo dwe tande.',
      tr: 'İlkel bir öfkeyle bezenmiş, düşmanların bu silahı görünce titriyor. Pew pew, duyacakları son şey.',
      hi: 'मौलिक क्रोध से बना, इसे देखकर आपके दुश्मन कांप उठेंगे। आख़री आवाज़ जो उन्हें सुनाई पड़ेगी वो होगी तेज़ तीरों की हवा कटने की आवाज।',
      cs: 'Vloženi s prvotním vztekem, vaši nepřátelé se třesou při pohledu na tuto zbraň. Pew je poslední věc, kterou kdy slyší.',
      ja: 'この武器を見てあなたの敵は震え上がります。ピューピューは彼らが今までに聞くことになる最後のものです。',
      ro: 'Cuprins de o furie primordială, dușmanii tăi tremură la vederea acestei arme. Pew pew e ultimul lucru pe care-l vor auzi vreodată.',
      ko: '원시적 인 분노덕분의, 적들은 이 무기를 보기만해도 겁의질려 떫니다. 이 활을 소는 것이 적들이 마지막으로 듣게될 소리입니다.',
      da: 'Embedet med et primært vrede, dine fjender ryster ved synet af dette våben. Pew pew er det sidste, de nogensinde vil høre.'
    }
  }

]
