export default [
  {
    name       : {$$: 'Splintered Club' },
    description: {
      en: 'It\'s already half broken and you are still using it?',
      ru: 'Он уже наполовину сломан, и вы все еще его используете?',
      hi: 'यह पहले से ही आधा टूट गया है और आप अभी भी इसका प्रयोग कर रहे हैं?',
      es: '¿Ya está medio roto y todavía lo estás usando?',
      de: 'Es ist bereits halb gebrochen und du benutzt es immer noch?',
      fr: 'Il est déjà à moitié cassé et vous l\'utilisez toujours?',
      pt: 'Já está meio partido e ainda estás a usá-lo?',
      nl: 'Het is al voor de helft gebroken en je gebruikt het nog steeds?',
      pl: 'Jest już w połowie zepsuty, a ty nadal go używasz?',
      el: 'Το ήδη μισό σπασμένο και εξακολουθείτε να το χρησιμοποιείτε;',
      bg: 'Вече е наполовина счупен и все още го използвате?',
      it: 'E\' gia\' mezzo rotto e tu lo stai ancora usando?',
      cs: 'Je to už napůl rozbité a stále to používáš?',
      ja: 'それはすでに半分壊れていて、あなたはまだそれを使っていますか？',
      ht: 'Li deja mwatye kase epi ou toujou ap itilize li?',
      sv: 'Det är redan halvbruten och du använder det fortfarande?',
      ko: '벌써 절반이 고장 났고 당신은 아직도 그것을 사용하고 있습니까?',
      ro: 'E deja pe jumătate rupt și tu încă îl mai folosești?',
      tl: 'Ito ay kalahati na sira at ginagamit mo pa rin ito?',
      tr: 'Zaten yarısı bozuk ve hala kullanıyor musun?',
      da: 'Det er allerede halvt brudt, og bruger du stadig det?',
      zh: '已经被打破了一半，而你还在使用?'
    }
  },

  {
    name       : {$$: 'Wooden Mallet' },
    description: {
      en: 'This should be hammering nails, not skulls.',
      ru: 'Это должны быть гвозди, а не черепа.',
      hi: 'इससे कील ठोकते है, खोपड़ी नहीं।',
      es: 'Esto debería estar clavando clavos, no cráneos.',
      de: 'Das sollten hämmernde Nägel sein, nicht Schädel.',
      el: 'Αυτό πρέπει να σφυρηλατεί τα νύχια και όχι τα κρανία.',
      bg: 'Това трябва да бъде чукане на нокти, а не черепи.',
      fr: 'Ça devrait enfoncer des clous, pas des crânes.',
      pt: 'Isto devia estar a martelar pregos, não caveiras.',
      nl: 'Dit zouden hamerende spijkers moeten zijn, geen schedels.',
      pl: 'To powinno być młotkowanie gwoździ, a nie czaszek.',
      it: 'Questo dovrebbe essere martellare le unghie, non i teschi.',
      cs: 'To by mělo být kladívko, ne lebky.',
      ja: '頭蓋骨ではなく、釘を打ってください。',
      ht: 'Sa a ta dwe rakle klou, pa kran.',
      sv: 'Detta bör hamra naglar, inte skallar.',
      ko: '이것은 두개골이 아니라 망치질하는 손톱이어야합니다.',
      ro: 'Acest lucru ar trebui să fie ciocan pentru cuie, nu cranii.',
      tl: 'Ito ay dapat na pagmamartilyo mga kuko, hindi skulls.',
      tr: 'Kafatasları değil, çivileri çekiçlemek için kullanılmalıdır.',
      da: 'Dette burde være hammering negle, ikke kranier.',
      zh: '这是锤钉子，不是锤头骨。'
    }
  },

  {
    name       : {$$: 'Primal Mace' },
    description: {
      en: 'Rusty old hammer, on the verge of breaking.',
      ru: 'Ржавый старый молот, на грани поломки.',
      hi: 'ज़ंग लगा पुराना हथौड़ा, बस टूटेने ही वाला है।',
      es: 'Un viejo martillo oxidado, a punto de romperse.',
      de: 'Rostiger alter Hammer, kurz davor, zu brechen.',
      el: 'Σκουριασμένο παλιό σφυρί στα πρόθυρα θραύσης.',
      bg: 'Ръстият чук на ръба на счупване.',
      fr: 'Un vieux marteau rouillé, sur le point de se briser.',
      pt: 'Um velho martelo enferrujado, prestes a partir-se.',
      nl: 'Roestige oude hamer, op het punt om te breken.',
      pl: 'Zardzewiały, stary młotek, na skraju załamania.',
      it: 'Un vecchio martello arrugginito, sull\'orlo della rottura.',
      cs: 'Rusty starý kladivo, na pokraji prasknutí.',
      ja: '壊れる寸前のさびた古いハンマー。',
      ht: 'Rusty martre fin vye granmoun, sou wout pou l kraze.',
      sv: 'Rustig gammal hammare, på gränsen till att bryta.',
      ko: '오래 된 녹슨 망치, 깨고 직전.',
      ro: 'Ciocan vechi și ruginit, pe punctul de a se rupe.',
      tl: 'Masungit na lumang martilyo, sa gilid ng paglabag.',
      tr: 'Paslı eski çekiç, kırma eşiğinde.',
      da: 'Rusten gammel hammer, på randen af ​​at bryde.',
      zh: '生锈的旧锤子，濒临破碎。'
    }
  },

  {
    name       : {$$: 'Orcish Bludgeon' },
    description: {
      en: 'An ancient weapon stolen from marauding orcs residing in hidden lairs.',
      ru: 'Древнее оружие, украденное у орков-мародеров, живущих в спрятанных логовах.',
      hi: 'छिपी हुई गलियों में निवास करने वाले मरुदलों से चुराया गया एक प्राचीन हथियार।',
      es: 'Un arma antigua robada de orcos merodeadores que residen en guaridas escondidas.',
      el: 'Ένα αρχαίο όπλο κλεμμένο από μαρατούντες ορκισμούς που κατοικούν σε κρυμμένες κούνιες.',
      de: 'Eine alte Waffe, die von marodierenden Orks gestohlen wurde, die sich in versteckten Höhlen aufhalten.',
      fr: 'Une arme ancienne volée à des orcs en maraude qui habitent des repaires cachés.',
      pt: 'Uma arma antiga roubada aos orcs saqueadores residentes em caves escondidas.',
      nl: 'Een oud wapen dat gestolen is van plunderende orks die in verborgen schuilplaatsen wonen.',
      pl: 'Starożytna broń skradziona z łupieżczych orków mieszkających w ukrytych legowiskach.',
      it: 'Un\'antica arma rubata agli orchi predoni che risiedono in nascondigli nascosti.',
      cs: 'Starověká zbraň ukradená z loupežných orků žijících ve skrytých doupětech.',
      ja: '隠れた隠れ家に住むオークを襲撃することで盗まれた古代の武器。',
      ht: 'Yon zam ansyen yo vòlè li soti nan mouton ork k ap viv nan kochon kache.',
      sv: 'Ett gammalt vapen som stulits från marauding orker bosatt i dolda lairs.',
      ko: '고대 무기는 숨겨진 의자에있는 오크들을 약탈하여 도난당했습니다.',
      tl: 'Isang sinaunang sandata na ninakaw mula sa mga mandarambong na mga orcs na naninirahan sa mga nakatagong lairs.',
      ro: 'O armă antică furată de la orcii jefuitori ce locuiesc în bârloguri ascunse.',
      tr: 'Gizli yerlerde gizlenmiş vahşi düşmanlardan alınan eski bir silah.',
      da: 'Et gammelt våben stjålet fra marauding orker bosiddende i skjulte lairs.',
      bg: 'Древно оръжие, откраднато от мародерски орки, живеещи в скрити леговища.'
    }
  },

  {
    name       : {$$: 'Heavy Mace' },
    description: {
      en: 'Large weapon used long ago to destroy skulls.',
      ru: 'Крупное оружие, использованное давным-давно для уничтожения черепов.',
      es: 'Un arma grande usada hace mucho tiempo para destruir cráneos.',
      fr: 'Grande arme utilisée il y a longtemps pour détruire des crânes.',
      de: 'Große Waffe, die vor langer Zeit benutzt wurde, um Schädel zu zerstören.',
      pt: 'Grande arma usada há muito tempo para destruir crânios.',
      ko: '오래전에 두개골을 파괴하는 데 사용 된 대형 무기.',
      nl: 'Groot wapen dat lang geleden gebruikt werd om schedels te vernietigen.',
      pl: 'Duża broń używana dawno temu do niszczenia czaszek.',
      sv: 'Stort vapen som använts för länge sedan för att förstöra skalle.',
      ht: 'Gwo zam yo itilize depi lontan pou detwi kran yo.',
      it: 'Grande arma usata molto tempo fa per distruggere i teschi.',
      hi: 'खोपड़ी को नष्ट करने के लिए बनाया गया पौराणिक हथियार।',
      tl: 'Malaking sandata na ginamit nang matagal na ang nakalipas upang sirain ang mga skull.',
      el: 'Μεγάλο όπλο που χρησιμοποιήθηκε εδώ και πολύ καιρό για να καταστρέψει τα κρανία.',
      bg: 'Голямо оръжие, използвано отдавна, за да унищожи черепите.',
      cs: 'Velká zbraň používaná již dávno k ničení lebek.',
      ja: '頭蓋骨を破壊するために昔使用されていた大きな武器。',
      ro: 'Armă uriașă folosită cu mult timp în urmă pentru a zdrobi capete.',
      tr: 'Eski zamanlarda düşman kafataslarını yok etmek için kullanılan harika bir silah.',
      da: 'Stort våben bruges for længe siden til at ødelægge kranier.'
    }
  },

  {
    name       : {$$: 'Iron Basher' },
    description: {
      en: 'Strange rod-like basher. Seems crude and emits a faint smell of druid oils...',
      ru: 'Странная стержнеобразная дубинка. Кажется грубой и источает слабый запах друидских масел...',
      hi: 'अजीब छड़ी जैसा हथौड़ा। अनगद लगता है और पवित्र पूरोतिहो के तेल की गंध छोड़ता है।',
      es: 'Extraño golpeador en forma de varilla. Parece crudo y emite un ligero olor a aceite de druida...',
      el: 'Παράξενη ράβδο τύπου basher. Φαίνεται ακατέργαστο και εκπέμπει μια αμυδρή μυρωδιά δευτεροπαθών ελαίων ...',
      bg: 'Странен барометър. Изглежда суров и излъчва слаб мирис на друидни масла ...',
      de: 'Seltsamer stabförmiger Schläger. Scheint roh zu sein und verströmt einen schwachen Geruch von Druidenölen...',
      fr: 'Étrange batteur en forme de baguette. Semble brut et émet une légère odeur d\'huile de druide...',
      pt: 'Martelo estranho em forma de bastão. Parece bruto e emite um ligeiro cheiro a óleos druidas...',
      nl: 'Vreemde staafvormige basher. Lijkt ruw en verspreidt een vage geur van druïdenoliën....',
      pl: 'Dziwny, podobny do pręta basher. Wydaje się surowy i wydziela słaby zapach olejków druidów...',
      it: 'Strano bastone simile a una canna da basher. Sembra grezzo ed emette un debole odore di olii druido...',
      cs: 'Podivný tyčovitý basher. Vypadá to surově a vydává slabý zápach druidských olejů ...',
      ja: '奇妙な棒状のバッシャー。原油らしく、ドルイド油のかすかな香りがする…',
      ht: 'Etranj baton ki tankou basher. Sanble brut ak emèt yon sant endispoze nan lwil drwid ...',
      sv: 'Konstigt stavliknande basher. Verkar rå och avger en svag lukt av druidoljor ...',
      ko: '이상한 막대기 같은 지하실. 원유처럼 보이고 드루이드 오일의 희미한 냄새를 풍깁니다 ...',
      ro: 'Ciudată bâtă. Pare brută și emite un miros slab de uleiuri druide...',
      tl: 'Kakaibang baras martilyo. Mukhang krudo at nagpapalabas ng isang malabong amoy ng mga langis na druga ...',
      tr: 'Garip çubuk benzeri silah. Cadı yağları gibi kokuyor.',
      da: 'Mærkelig rod-lignende basher. Synes rå og udsender en svag lugt af druidolier ...'
    }
  },

  {
    name       : {$$: 'Darkmetal Maul' },
    description: {
      en: 'Ancient dwarves forged this mighty structure. Dark and deadly.',
      ru: 'Древние дворфы создали эту могущественную булаву. Темная и смертельная.',
      hi: 'प्राचीन बौनो ने इस शक्तिशाली संरचना का निर्माण किया। काला और घातक।',
      es: 'Los enanos antiguos forjaron esta poderosa estructura. Oscura y mortal.',
      de: 'Alte Zwerge schmiedeten diese mächtige Struktur. Dunkel und tödlich.',
      fr: 'Les nains anciens ont forgé cette puissante structure. Sombre et mortel.',
      pt: 'Antigos anões forjaram esta poderosa estrutura. Escuros e mortais.',
      el: 'Οι αρχαίοι νάνοι σφυρηλατούσαν αυτήν την πανίσχυρη δομή. Σκούρο και θανατηφόρο.',
      bg: 'Древните джуджета изковали тази могъща структура. Тъмно и смъртоносно.',
      nl: 'Oude dwergen hebben deze machtige structuur gesmeed. Donker en dodelijk.',
      pl: 'Starożytne krasnoludy wykuły tę potężną strukturę. Ciemne i zabójcze.',
      it: 'Antichi nani hanno forgiato questa possente struttura. Scuro e mortale.',
      cs: 'Starověcí trpaslíci vytvořili tuto mocnou strukturu. Temné a smrtící.',
      ja: '古代の小人たちはこの力強い構造を鍛造しました。暗くて致命的です。',
      ht: 'Nen ansyen fòje estrikti sa a vanyan sòlda. Nwa ak trè danjere.',
      sv: 'Forntida dvärgar smidade denna mäktiga struktur. Mörk och dödlig.',
      ko: '고대의 드워프들은이 강력한 구조물을 만들었습니다. 어둡고 치명적입니다.',
      ro: 'Piticii antici au făcut această structură măreață. Întunecată și mortală.',
      tl: 'Inilaan ng mga sinaunang dwarf ang makapangyarihang istraktura na ito. Madilim at nakamamatay.',
      tr: 'Eski cüceler bu güçlü yapıyı yaptı. Karanlık ve ölümcül.',
      da: 'Gamle dværge smedet denne mægtige struktur. Mørk og dødelig.'
    }
  },

  {
    name       : {$$: 'Divine Gavel' },
    description: {
      en: 'It is said that the eyes of the gods follow the wielder, bringing fortune to the valiant and doom to the cowardly.',
      ru: 'Говорят, что глаза богов следуют за хозяином, принося удачу отважным, а трусливым - гибель.',
      hi: 'ऐसा कहा जाता है कि देवताओं की आँखें क्षेत्रपाल का अनुसरण करती हैं, वीरता के लिए भाग्य लाती हैं और कायरों को कयामत तक पहुंचाती हैं।',
      es: 'Se dice que los ojos de los dioses siguen al portador, trayendo fortuna a los valientes y condenación a los cobardes.',
      de: 'Es wird gesagt, dass die Augen der Götter folgen dem Verwalter und bringen den Mutigen Glück und den Feiglingen Verderben.',
      el: 'Λέγεται ότι τα μάτια των θεών ακολουθούν το wielder, φέρνοντας τύχη στον γενναίο και μοίρα προς το δειλό.',
      bg: 'Казано е, че очите на боговете следват водача, като донасят съдбата на храбрите и гибелите на страхливите.',
      fr: 'Il est dit que les yeux des dieux suivent le possesseur de ce marteau, apportant la fortune aux vaillants et la mort aux lâches.',
      pt: 'Diz-se que os olhos dos deuses seguem o portador, trazendo fortuna para o valente e a perdição para o covarde.',
      nl: 'Er wordt gezegd dat de ogen van de goden volgen de drager en brengen de dappere en laffe dappere mensen geluk en verdoemenis.',
      pl: 'Mówi się, że oczy bogów podążają za władcą, przynosząc majątek dzielnemu i skazanie tchórzliwego.',
      it: 'Si dice che gli occhi degli dei seguono il maneggiatore, portando la fortuna al valoroso e il destino al vile.',
      cs: 'To je říkal, že oči gods následují wielder, přinášet štěstí k statečnému a osudu k zbabělému.',
      ja: 'それは神々の目が野蛮人に運をもたらし、そして臆病者に運命をもたらして、野蛮人に続くと言われます。',
      ht: 'Li te di ke je bondye yo swiv wielder a, yo pote fòtin vanyan sòlda ak fayit la lachte la.',
      sv: 'Det sägs att gudarnas ögon följer wielderen och ger förmögenhet till tapperhet och döm till fegan.',
      ko: '신들의 눈은 주인을 따라 가며 비겁한 용감한 운명에 운을 가져다 준다고합니다.',
      tl: 'Sinasabi na ang mga mata ng mga diyos ay sumunod sa mangangalakal, nagdadala ng kapalaran sa magiting at kamatayan sa duwag.',
      ro: 'Se spune că zeii urmăresc cu privirea pe purtători, aducându noroc celor bravi și belsteme celor lași.',
      tr: 'Tanrıların gözlerinin bu silahın taşıyıcısını takip ettiği söylenir. Bu cesur için iyi bir servet getiriyor ve bir korkak için işkence.',
      da: 'Det siges, at gudernes øjne følger wielderen og bringer formue og domme til de fede.'
    }
  },

  {
    name       : {$$: 'Hallowed Hammer' },
    description: {
      en: 'Holy tool used by druids to make sacrifices to the ancient nature gods.',
      ru: 'Святой инструмент, используемый друидами, чтобы приносить жертвы древним богам природы.',
      hi: 'पवित्र पुरोहितो द्वारा प्रकृति देवताओं को बलिदान चढ़ाने के लिए प्रयोग किया जाने वाला प्राचीन उपकरण।',
      es: 'Herramienta sagrada usada por los druidas para hacer sacrificios al gran dios, Yggdrasil.',
      el: 'Άγιο εργαλείο που χρησιμοποιείται από druids για να κάνει θυσίες στους αρχαίους θεούς της φύσης.',
      bg: 'Свещен инструмент, използван от друидите за жертвоприношения на древните богове.',
      de: 'Heiliges Werkzeug, das von Druiden benutzt wird, um dem großen Gott Yggdrasil Opfer zu bringen.',
      fr: 'Outil sacré utilisé par les druides pour faire des sacrifices aux dieux anciens de la nature.',
      pt: 'Ferramenta sagrada usada pelos druidas para fazer sacrifícios aos deuses da natureza antiga.',
      nl: 'Heilig instrument gebruikt door druïden om offers te brengen aan de oude natuurgoden.',
      pl: 'Święte narzędzie używane przez druidów do składania ofiar starożytnym bogom natury.',
      it: 'Strumento sacro usato dai druidi per fare sacrifici agli dei della natura antica.',
      cs: 'Svatý nástroj, který druid používá k obětování starodávným bohům přírody.',
      ja: 'ドルイド僧が古代の性質の神々を犠牲にするために使用する聖なる道具。',
      ht: 'Zouti Sentespri itilize pa drwid yo fè sakrifis pou bondye yo nati ansyen.',
      sv: 'Heligt verktyg som används av druider för att göra offer till de gamla naturgudarna.',
      ko: '드루이드가 고대 성전의 희생 제물을 만들기 위해 사용한 거룩한 도구.',
      ro: 'Instrument sfânt folosit de druizi pentru a face sacrificii, oferite zeilor antici ai naturii.',
      tl: 'Ang Banal na tool na ginagamit ng mga druid upang gumawa ng mga sakripisyo sa sinaunang mga diyos ng kalikasan.',
      tr: 'Kutsal aracı antik doğa tanrılara kurban yapmak için druidler tarafından kullanılan.',
      da: 'Helligt værktøj, der bruges af druider til at ofre til de gamle naturgud.'
    }
  },

  {
    name       : {$$: 'Dwarven Maul' },
    description: {
      en: 'Heavy basher used by dwarven warriors. Made of an unknown metal, dark and heavy.',
      ru: 'Тяжелая дубинка, используемая дворфами-воинами. Изготовлена из неизвестного металла, темная и тяжелая.',
      hi: 'बौने योद्धाओं द्वारा इस्तमाल किया गया भारी हथौड़ा। अनजान धातु से बना हुआ, कला और भारी।',
      es: 'Golpeador pesado usado por los guerreros enanos. Hecho de un metal desconocido, oscuro y pesado.',
      de: 'Schwerer Schläger, der von Zwergenkrieger benutzt wird. Hergestellt aus einem unbekannten Metall, dunkel und schwer.',
      fr: 'Une arme lourde utilisée par les guerriers nains. Fait d\'un métal inconnu, sombre et lourd.',
      el: 'Βαρύ basher που χρησιμοποιείται από νάρκες πολεμιστές. Κατασκευασμένο από άγνωστο μεταλλικό σκούρο και βαρύ.',
      bg: 'Тежък башар, използван от джуджета. Изработен от неизвестен метал, тъмен и тежък.',
      pt: 'Um martelo pesado usado por guerreiros anões. Feito de um metal desconhecido, escuro e pesado.',
      nl: 'Zware basher gebruikt door dwergenkrijgers. Gemaakt van een onbekend metaal, donker en zwaar.',
      pl: 'Ciężki basher używany przez karłowatych wojowników. Wykonane z nieznanego metalu, ciemne i ciężkie.',
      it: 'Basher pesante usato dai guerrieri nani. Realizzato in un metallo sconosciuto, scuro e pesante.',
      cs: 'Těžký basher používaný trpaslíkovými válečníky. Vyrobeno z neznámého kovu, tmavé a těžké.',
      ja: 'ドワーフの戦士によって使用されるヘビーバッシャー。暗くて重い未知の金属製。',
      ht: 'Lou basher itilize pa enne vanyan sòlda. Te fè nan yon metal unknown, nwa ak lou.',
      sv: 'Tung hammare som används av dvärgkrigare. Tillverkad av en okänd metall, mörk och tung.',
      ko: '드워프 전사들이 사용하는 무거운 지하실. 알 수없는 금속으로 제작되었으며, 어둡고 무겁습니다.',
      ro: 'Bâtă greoaie folosită de către piticii râzboinici. Făcută dintr-un material necunoacut, întunecat și greu.',
      tl: 'Malakas na basher na ginagamit ng mga mandirigmang dwarven. Ginawa ng isang hindi kilalang metal, madilim at mabigat.',
      tr: 'Cüce savaşçılar tarafından kullanılan ağır silah. Bilinmeyen bir metalden yapılmış, karanlık ve ağır.',
      da: 'Kraftig hammer, der bruges af dværgkrigere. Lavet af et ukendt metal, mørkt og tungt.'
    }
  },

  {
    name       : {$$: 'Coldforged Gavel' },
    description: {
      en: 'A mighty hammer forged without heat killing anything it can without mercy.',
      ru: 'Могучий молоток, выкованный без тепла, убивает все, что может без пощады.',
      es: 'Un poderoso martillo forjado sin calor que mata todo lo que puede sin piedad.',
      fr: 'Un puissant marteau forgé sans chaleur tuant tout ce qu\'il peut sans pitié.',
      de: 'Ein mächtiger Hammer, geschmiedet, ohne Hitze, der alles zerstört, was er ohne Gnade kann.',
      pt: 'Um poderoso martelo forjado sem calor, matando tudo o que puder sem misericórdia.',
      ko: '힘없는 망치로 열을 가하지 않고 자존심없이 죽일 수 있습니다.',
      nl: 'Een machtige hamer gesmeed zonder hitte die alles wat het kan doden zonder genade.',
      pl: 'Potężny młotek kuty bez zabijania na gorąco wszystkiego, co może bez litości.',
      sv: 'En mäktig hammare smidd utan värme och dödar allt det kan utan barmhärtighet.',
      ht: 'Yon mato vanyan fòje san chalè touye anyen li kapab san pitye.',
      it: 'Un potente martello forgiato senza calore che uccide tutto ciò che può senza pietà.',
      hi: 'आग के बिना बनाया हुआ यह शक्तिशाली हथौड़ा बिना दया के सब ख़त्म कर देता है।',
      tl: 'Ang isang makapangyarihang martilyo na huwad na walang init na pagpatay sa anumang bagay na magagawa nito nang walang awa.',
      el: 'Ένα ισχυρό σφυρί σφυρήλατο χωρίς ζέστη να σκοτώνει οτιδήποτε μπορεί χωρίς έλεος.',
      bg: 'Мощен чук, изкован без топлина, убиващ всичко, което може, без милост.',
      cs: 'Mohutné kladivo kované bez ohně, zabíjejícího cokoliv, bez slitování.',
      ja: '強烈なハンマーは熱を加えずに鍛造され、容赦なくできることは何もしません。',
      ro: 'Un ciocan puternic forjat fără căldură, ce ucide orice poate fără milă.',
      tr: 'Isı olmadan yapılan güçlü bir çekiç. Merhamet olmadan her şeyi öldürür.',
      da: 'En mægtig hammer smedet uden varme at dræbe alt det kan uden barmhjertighed.'
    }
  },

  {
    name       : {$$: 'Amboss' },
    description: {
      en: 'Topped with the skull of a slain beast, this weapon inspires terror in all who stand against it.',
      ru: 'Это оружие, увенчанное черепом чудища, внушает ужас всем, кто противостоит ему.',
      hi: 'मारे गए राक्षस की खोपड़ी से बनाया गया, यह हथियार अपने विरोधिदो में आतंक को प्रेरित करता है।',
      es: 'Cubierta con el cráneo de una bestia muerte, esta arma inspira terror en todos los que se oponen.',
      de: 'Diese Waffe, die mit dem Schädel eines getöteten Tieres überzogen ist, weckt Schrecken bei allen, die sich dagegen stellen.',
      fr: 'Surmontée du crâne d\'une bête tuée, cette arme inspire la terreur à tous ceux qui s\'y confrontent.',
      pt: 'Coberta com o crânio de uma besta morta, esta arma inspira terror em todos os que estão contra ela.',
      ko: '죽은 짐승의 두개골을 얹은이 무기는 모든 사람에게 공포를 불러 일으킨다.',
      nl: 'Bovenop de schedel van een gedood beest, inspireert dit wapen terreur in iedereen die ertegen staat.',
      pl: 'Uwieńczona czaszką zabitej bestii, broń ta budzi przerażenie u wszystkich, którzy się jej sprzeciwiają.',
      sv: 'Toppat med skallen av ett slaktdjur, detta vapen inspirerar terror i alla som står emot det.',
      ht: 'Konpoze ak zo bwa tèt la nan yon bèt touye, zam sa a enspire pè nan tout moun ki kanpe kont li.',
      it: 'Con il cranio di una bestia uccisa, quest\'arma ispira terrore in tutti coloro che vi si oppongono.',
      tl: 'Nangunguna sa bungo ng isang slain beast, ang armas na ito ay nagbibigay inspirasyon sa lahat ng tumayo laban dito.',
      el: 'Με το κρανίο ενός δολοφονημένου θηρίου, αυτό το όπλο εμπνέει τρόμο σε όλους όσους τον κατακλύζουν.',
      bg: 'Оградено с черепа на убит звяр, това оръжие вдъхва терор на всички, които се изправят срещу него.',
      cs: 'Tato zbraň s lebkou zabitého zvířete vzbuzuje hrůzu ve všech, kteří proti ní stojí.',
      ja: '殺された獣の頭蓋骨をトッピングしたこの武器は、それに立ち向かうすべての人々に恐怖を呼び起こします。',
      ro: 'Acoperită cu craniul unei bestii ucise, această armă inspiră teroare în toți cei ce stau împotriva ei.',
      tr: 'Üstte ölü bir düşmanın kafatası olan bir silah. Buna karşı çıkan herkese terör getirir.',
      da: 'Topet med et slagtedyrs kraniet inspirerer dette våben terror i alle, der står imod det.'
    }
  },

  {
    name       : {$$: 'Skullshatterer' },
    description: {
      en: 'Can penetrate your feeble skull quite easily. Or your foes. Probably yours though.',
      ru: 'Может легко проникнуть в ваш слабый череп. Или в твоих врагов. Хотя вероятнее в ваш.',
      hi: 'आपके कमज़ोर खोपड़ी में बड़ी आसानी से घुस सकता है। या फिर दुश्मन की। शायद आपकी ही।',
      es: 'Puede penetrar su cráneo débil facilamente. O el cranéo de sus enemigos. Pero probalamente la suya.',
      de: 'Mit dem Schädel eines getöteten Riesenfeindes überzogen, inspiriert diese Waffe Schrecken bei allen, die sich dagegen stellen.',
      fr: 'Peut détruire votre faible crâne plutôt facilement. Ou celui de vos ennemis. Plutôt le vôtre, en fait.',
      bg: 'Може лесно да проникне във вашия слаб череп. Или вашите врагове. Вероятно е твой.',
      el: 'Μπορεί να διεισδύσει το αδύναμο κρανίο σας αρκετά εύκολα. Ή τους εχθρούς σου. Πιθανώς το δικό σου.',
      pt: 'Pode penetrar facilmente no seu crânio fraco. Ou seus inimigos. Provavelmente o seu, contudo.',
      nl: 'Kan vrij gemakkelijk in uw zwakke schedel doordringen. Of je vijanden. Waarschijnlijk wel de jouwe.',
      pl: 'Może przeniknąć twoją słabą czaszkę całkiem łatwo. Albo twoi wrogowie. Prawdopodobnie jednak twoja.',
      it: 'Può penetrare il tuo cranio debole abbastanza facilmente. O i tuoi nemici. Probabilmente il vostro però.',
      cs: 'Dokáže snadno proniknout do tvé slabé lebky. Nebo vaši nepřátelé. Pravděpodobně vaše.',
      ja: 'あなたの弱い頭蓋骨を非常に簡単に突き刺すことができます。またはあなたの敵おそらくあなたのもの。',
      ht: 'Ka rantre nan zo bwa tèt fèb ou byen fasil. Oswa lènmi ou yo. Pwobableman ou menm si.',
      sv: 'Kan lätt tränga in i din svaga skalle. Eller dina fiender. Förmodligen din men.',
      ko: '당신의 연약한 두개골에 아주 쉽게 침투 할 수 있습니다. 또는 당신의 원수. 아마 당신 것.',
      ro: 'Poate penetra craniul tău slab destul de ușor. Sau al dușmanilor tăi. Probabil al tău totuși.',
      tl: 'Maaari bang tumagos ang iyong mahinang bungo na medyo madali. O iyong mga kaaway. Marahil sa iyo kahit na.',
      tr: 'Bu kolayca kafatası veya düşmanın kafatası kırabilir. Muhtemelen önce senindir.',
      da: 'Kan let trænge ind i din svage kranium. Eller dine fjender. Sandsynligvis din selv.'
    }
  },

  {
    name       : {$$: 'Benevolence' },
    description: {
      en: 'Nothing kind about this cruel weapon.',
      ru: 'Ничего доброго в этом жестоком оружии.',
      hi: 'इस निर्दयी हथियार में कोई मेहरबानी नहीं है।',
      es: 'Esta arma cruel no tiene nada de amable.',
      bg: 'Нищо подобно за това жестоко оръжие.',
      de: 'Nichts Besonderes an dieser grausamen Waffe.',
      el: 'Τίποτα δεν είναι καλό για αυτό το σκληρό όπλο.',
      fr: 'Cette arme cruelle n\'a rien de bon.',
      pt: 'Não há nada de bom nesta arma cruel.',
      nl: 'Niets aardigs aan dit wrede wapen.',
      pl: 'Nic miłego w tej okrutnej broni.',
      it: 'Non c\'e\' niente di che vedere con quest\'arma crudele.',
      cs: 'Na této kruté zbrani není nic zvláštního.',
      ja: 'この残酷な武器については何もない。',
      ht: 'Pa gen anyen sou zam mechan sa a.',
      sv: 'Inget snällt om det här grymma vapnet.',
      ko: '이 잔인한 무기에 대한 어떤 것도.',
      ro: 'Nimic bun despre această armă crudă.',
      tl: 'Wala nang uri tungkol sa malupit na sandata na ito.',
      tr: 'Bu zalim silah hakkında güzel bir şey yok.',
      da: 'Intet venligt om dette grusomme våben.'
    }
  },

  {
    name       : {$$: 'Hammer of Gaia' },
    description: {
      en: 'Deadly and uncontrollable, this celestial hammer etches terror in its purest form into those unfortunate ones who have caught sight of it.',
      ru: 'Смертоносный и неконтролируемый, этот небесный молот в чистейшей форме протравливает ужас в тех несчастных, кто его увидел.',
      hi: 'घातक और बेकाबू, यह स्वर्गीय हथौड़ा आतंक के सबसे शुद्द रूप को उन दुर्भाग्य लोगों के बसा देता है जिन्होंने इसे देख लिया।',
      es: 'Mortal e incontrolable, este martillo celestial graba el terror en su forma más pura en aquellos desafortunados que lo han visto.',
      el: 'Κάποιοι λένε ότι από τους νάνοι οι άλλοι λένε από τους ξωτικούς ... η αλήθεια δεν έχει αποκαλυφθεί ακόμα.',
      bg: 'Някои казват, че направените от джуджета други казват от елфи ... истината все още не е разкрита.',
      de: 'Tödlich und unkontrollierbar, ritzt dieser himmlische Hammer den Schrecken in seiner reinsten Form in die Unglücklichen, die ihn aus den Augen verloren haben.',
      fr: 'Mortel et incontrôlable, ce marteau céleste grave la terreur dans sa forme la plus pure sur les malheureux qui l\'ont vue.',
      pt: 'Mortal e incontrolável, este martelo celestial grava o terror na sua forma mais pura naqueles infelizes que o viram.',
      nl: 'Dodelijk en oncontroleerbaar, deze hemelse hamer ets terreur in zijn puurste vorm in de ongelukkigen die hem in het vizier hebben gekregen.',
      pl: 'Śmiertelnie i niekontrolowanie, ów niebiański młotek w swojej najczystszej formie wprawia w przerażenie tych nieszczęsnych którzy go złapali.',
      it: 'Mortale e incontrollabile, questo martello celeste incide il terrore nella sua forma più pura in quegli sfortunati che l\'hanno scoperto.',
      cs: 'Smrtící a nekontrolovatelné, toto nebeské kladivo leptá hrůzu v nejčistší podobě do těch nešťastných, kteří si to všimli.',
      ja: '致命的で手に負えない、この天体ハンマーはその純粋な形でそれを見ていたそれらの不幸なものにテロを蝕みます。',
      ht: 'Mòtèl ak enkontwolab, mato sa a selès pè atè nan fòm pur li yo nan sa yo malere ki te wè nan li.',
      sv: 'Dödlig och okontrollabel, den här himmelska hammaren etsar terror i sin renaste form till de olyckliga som har sett det.',
      ko: '치명적이고 통제 할 수없는이 천체 망치는 그 가장 순수한 형태의 공포를 그 광경을 포착 한 불행한 사람들에게 뿌린다.',
      ro: 'Mortal și incontrolabil, acest ciocan ceresc gravează teroarea în cea mai pură formă în acei nefericiți ce l-au văzut.',
      tl: 'Nakamamatay at hindi mapigilan, ang makalangit na martilyo na ito ay nagtatakot ng malaking takot sa pinakadalisay na anyo nito sa mga kapus-palad na nakakakita dito.',
      tr: 'Ölümcül ve kontrol edilemez bu göksel çekiç, terörü en saf haliyle, onu gören talihsiz olanlara dağıtır',
      da: 'Døde og ukontrollable, æsler denne himmelske hammer terror i sin reneste form til de uheldige, der har set det til syne.'
    }
  },

  {
    name       : {$$: 'Worldender' },
    description: {
      en: 'Does it have the power to end worlds? Few can say. If it does, we will not live long enough to learn of it.',
      ru: 'Есть ли у него сила, чтобы положить конец мирам? Мало кто может сказать. Если это произойдет, нас уже не будет в живых, чтобы узнать об этом.',
      hi: 'क्या इसमें दुनिया ख़त्म करने की शक्ति है? कुछ ही कह सकते है। यदि है, तो हम इसके बारे में जानने लायक़ लम्बा नहीं जिएँगे।',
      es: '¿Tiene el poder de acabar con los mundos? Pocos pueden decirlo. Si lo hace, no viviremos lo suficiente para aprenderlo.',
      de: 'Hat sie die Macht, Welten zu beenden? Nur wenige können das sagen. Wenn dies der Fall ist, werden wir nicht lange genug leben, um davon zu erfahren.',
      el: 'Έχει τη δύναμη να τερματίσει τους κόσμους; Λίγοι μπορούν να πουν. Αν το κάνει, δεν θα ζήσουμε αρκετά για να μάθουμε γι \'αυτό.',
      bg: 'Има ли силата да прекратява светове? Малцина могат да кажат. Ако го направи, няма да живеем достатъчно дълго, за да научим за него.',
      fr: 'A-t-il le pouvoir de mettre fin aux mondes ? Peu de gens peuvent le dire. Si c\'est le cas, nous ne vivrons pas assez longtemps pour l\'apprendre.',
      pt: 'Tem o poder de acabar com mundos? Poucos podem dizer. Se o tiver, não viveremos tempo suficiente para aprender com ele.',
      nl: 'Heeft het de kracht om werelden te beëindigen? Weinigen kunnen dat zeggen. Als dat zo is, zullen we niet lang genoeg leven om ervan te leren.',
      pl: 'Czy ma moc kończenia świata? Niewielu może powiedzieć. Jeśli tak się stanie, nie będziemy żyli wystarczająco długo, aby się o tym nauczyć.',
      it: 'Ha il potere di porre fine ai mondi? Pochi possono dire. Se lo fa, non vivremo abbastanza a lungo per impararlo.',
      cs: 'Má moc ukončit světy? Málokdo může říct. Pokud ano, nebudeme žít tak dlouho, abychom se o tom dozvěděli.',
      ja: 'それは世界を終わらせる力を持っていますか？言うことはできません。もしそうなら、私たちはそれを学ぶのに十分なほど長くは生きません。',
      ht: 'Li gen pouvwa pou fini mond lan? Kèk ka di. Si li fè sa, nou p ap viv lontan ase pou aprann li.',
      sv: 'Har det befogenhet att sluta världar? Få kan säga. Om det gör kommer vi inte leva tillräckligt länge för att lära oss av det.',
      ko: '그것은 세상을 끝낼 힘이 있습니까? 거의 말할 수 없습니다. 그렇다면 우리는 그 사실을 알기에 충분히 오래 살지 않을 것입니다.',
      ro: 'Are puterea de a pune capăt lumilor? Puțini pot spune. Dacă o face, nu vom trăi suficient de mult pentru a afla asta.',
      tl: 'Mayroon ba itong kapangyarihan upang tapusin ang mga mundo? Ang ilang mga maaaring sabihin. Kung gagawin nito, hindi tayo mabubuhay nang matagal upang malaman ito.',
      tr: 'Dünyaları sona erdirme gücü var mı? Sadece birkaç kişi söyleyebilir. Eğer yaparsa, bunu öğrenmek için yeterince uzun yaşamayacağız.',
      da: 'Har den magt til at ende verdener? Få kan sige. Hvis det gør det, vil vi ikke leve længe nok for at lære af det.'
    }
  },

  {
    name       : {$$: 'Nightmare' },
    description: {
      en: 'A mysterious magician soaked many intricate charms into this weapon, bringing ghastly thoughts and dreams to its wielder.',
      ru: 'Таинственный волшебник впитал множество замысловатых чар на этом оружии, принося ужасные мысли и мечты его обладателю.',
      hi: 'एक रहस्यमयी जादूगर ने इस हथियार में ऐसे जटिल जादू निचोड़े के इसे चलने वाले को भयंकर ख़याल और ख़्वाब आते है।',
      es: 'Un mago misterioso empapó muchos encantos intrincados en esta arma, trayendo pensamientos y sueños espantosos a su portador.',
      el: 'Ένας μυστηριώδης μάγος μουσκεύει πολλές πολύπλοκες γοητείες σε αυτό το όπλο που φέρνει φρικιαστικές σκέψεις και όνειρα στο πονηρό του.',
      bg: 'Тайнственият магьосник накисна много сложни прелести в това оръжие, довеждайки ужасни мисли и мечти до неговия водач.',
      de: 'Mysteriöser Magier, der mit vielen komplizierten Reizen auf dieser Waffe getränkt ist und schreckliche Gedanken und Träume zu seinem Verwalter bringt.',
      fr: 'Un mystérieux magicien a versé sur cette arme de nombreux charmes complexes, apportant des pensées et des rêves épouvantables à celui qui l\'utilise.',
      pt: 'Um mágico misterioso colocou muitos encantos intrincados nesta arma, trazendo pensamentos e sonhos horríveis ao seu portador.',
      nl: 'Een mysterieuze goochelaar heeft vele ingewikkelde charmes in dit wapen gedrenkt, daardoor het drager van terrible gedachten en dromen.',
      pl: 'Tajemniczy magik nasączył tę broń wieloma zawiłymi wdziękami, przynosząc okropne myśli i marzenia władcy.',
      it: 'Un misterioso mago ha inzuppato in quest\'arma molti fascino intricato, portando pensieri e sogni orribili al suo manipolatore.',
      cs: 'Tajemný kouzelník nasákl do této zbraně mnoho složitých kouzel a přivedl k jeho držiteli strašlivé myšlenky a sny.',
      ja: '神秘的な魔術師がこの武器に多くの複雑な魅力を染み込ませ、その手に恐ろしい考えや夢をもたらしました。',
      ht: 'Yon majisyen misterye tranpe anpil cham konplike nan zam sa a, pote panse efreyan ak rèv gonflan li yo.',
      sv: 'En mystisk trollkarl blötläggde många invecklade charmar i detta vapen, vilket medför grymma tankar och drömmar till sin wielder.',
      ko: '신비한 마술사가 많은 무기를이 무기에 담아 무시 무시한 생각과 꿈을 그 사람에게 가져다줍니다.',
      ro: 'Un magician misterios a înmuiat această armă în multe farmece complicate, aducând gânduri și vise îngrozitoare deținătorului său.',
      tl: 'Isang misteryosong salamangkero ang sumipsip ng maraming masalimuot na mga kagandahan sa armas na ito, na nagdadala ng malupit na mga kaisipan at mga pangarap sa tagahanga nito.',
      tr: 'Gizemli bir sihirbaz bu silahın içine birçok şey ekledi. Taşıyıcıya korkunç düşünceler ve rüyalar getiriyor.',
      da: 'En mystisk tryllekunstner gennemblødt mange indviklede charme i dette våben og brækkede forfærdelige tanker og drømme til sin ejer.'
    }
  }

]
