export default [
  {
    name       : {$$: 'Woven Band' },
    description: {
      en: 'Don\'t look at it or it will fall apart.',
      ru: 'Не смотрите на него, а то оно развалится.',
      es: 'No lo mires o se caerá a pedazos.',
      de: 'Sieh es dir nicht an, sonst fällt es auseinander.',
      hi: 'इसकी तरफ़ देखना मत। टूट जाएगा।',
      fr: 'Ne la regarde pas ou elle va tomber en morceaux.',
      pt: 'Não olhes para ele ou vai desmoronar-se.',
      nl: 'Kijk er niet naar, anders valt het uit elkaar.',
      tl: 'Huwag tumingin sa ito o ito ay mahulog bukod.',
      bg: 'Не го гледайте или ще се разпадне.',
      el: 'Δεν το εξετάζετε ή θα καταρρεύσει.',
      pl: 'Nie patrz na to, bo się rozpadnie.',
      it: 'Non guardarlo o cadrà a pezzi.',
      cs: 'Nedívej se na to, nebo se rozpadne.',
      ja: 'それを見てはいけないか、それはバラバラになります。',
      ht: 'Pa gade li oswa li pral tonbe apa.',
      sv: 'Om du så mycket som sneglar på det här bandet så lär det falla i bitar.',
      ko: '그것을 보지 않거나 떨어져 나옵니다.',
      ro: 'Nu te uita la el sau se va destrăma.',
      tr: 'O kadar narin ki baktığın zaman bile paramparça olur.',
      da: 'Kig ikke på det, eller det vil falde fra hinanden.'
    }
  },

  {
    name       : {$$: 'Ironbark Loop' },
    description: {
      en: 'Not sure about the bark, but it\'s definitely made of iron.',
      ru: 'Не уверен насчет коры, но оно определенно сделано из железа.',
      es: 'No estoy seguro de la corteza, pero definitivamente es de hierro.',
      de: 'Nicht sicher über die Rinde, aber sно оно определена зделана из железы.',
      hi: 'चाल का तो पता नहीं पर ये लोहे का ज़रूर बना है।',
      fr: 'Pas convaincu que ça soit de l\'écorce, par contre c\'est sûr que c\'est fait de fer.',
      pt: 'Não tenho a certeza sobre a casca, mas é definitivamente feita de ferro.',
      nl: 'Niet zeker van de schors, maar het is zeker van ijzer.',
      tl: 'Hindi sigurado ang tungkol sa bark ngunit tiyak na ginawa ito ng bakal.',
      bg: 'Не съм сигурен за кората, но определено от желязо.',
      el: 'Δεν είναι σίγουρος για τον φλοιό, αλλά σίγουρα φτιαγμένος από σίδηρο.',
      pl: 'Nie jestem pewien co do kory, ale na pewno jest zrobiona z żelaza.',
      it: 'Non sono sicuro della corteccia, ma è sicuramente di ferro.',
      cs: 'Nejste si jisti o kůře, ale rozhodně ze železa.',
      ja: '樹皮についてはわからないが、それは確かに鉄でできている。',
      ht: 'Pa sèten sou jape la, men li la definitivman te fè nan fè.',
      sv: 'Osäker när det gäller barken, men den är helt klart gjord av järn.',
      ko: '나무 껍질에 대해서는 잘 모르겠지만 철분으로 만들어졌습니다.',
      ro: 'Nu sunt sigur despre coajă, dar este cu sigurață făcut din fier.',
      tr: 'Kabuk hakkında emin değilim ama kesinlikle demirden yapılmış.',
      da: 'Ikke sikker på barken, men det er helt klart lavet af jern.'
    }
  },

  {
    name       : {$$: 'Brass Unity' },
    description: {
      en: 'Finally, a ring that is shiny.',
      ru: 'Наконец-то блестящее кольцо.',
      es: 'Finalmente, un anillo que brilla.',
      de: 'Endlich ein Ring, der glänzt.',
      fr: 'Enfin, un anneau qui brille.',
      hi: 'एक चमकीली अँगूठी।',
      tl: 'Sa wakas isang ring na makintab.',
      bg: 'Накрая пръстен, който е лъскав.',
      el: 'Τέλος ένα δαχτυλίδι που είναι λαμπερό.',
      pt: 'Finalmente, um anel que é brilhante.',
      nl: 'Eindelijk, een ring die glanst.',
      pl: 'W końcu pierścionek, który jest błyszczący.',
      it: 'Finalmente, un anello che è lucido.',
      cs: 'Konečně, prsten, který je lesklý.',
      ja: 'つやのあるリング。',
      ht: 'Finalman, yon bag ki klere.',
      sv: 'Äntligen, en skinande ring.',
      ko: '마지막으로, 빛나는 반지.',
      ro: 'În sfârșit, un inel care strălucește.',
      tr: 'Sonunda, parlayan bir yüzük.',
      da: 'Endelig en ring, der er skinnende.'
    }
  },

  {
    name       : {$$: 'Hollowed Bone' },
    description: {
      en: 'A ring made of last night\'s leftovers.',
      ru: 'Кольцо из остатков прошлого ужина.',
      es: 'Un anillo hecho con las sobras de anoche.',
      de: 'Ein Ring aus den Überresten der letzten Nächte.',
      hi: 'कल के बचे खुचे खाने से बनी अँगूठी।',
      fr: 'Une vertèbre de monstre aurait servit à sa fabrication.',
      pt: 'Um anel feito dos restos da noite passada.',
      nl: 'Een ring gemaakt van de restjes van gisteravond.',
      tl: 'Isang singsing na ginawa ng mga tira sa huling gabi.',
      bg: 'Пръстен от остатъци от последните нощи.',
      el: 'Ένα δαχτυλίδι από τα υπόλοιπα βράδια.',
      pl: 'Pierścionek wykonany z resztek z ostatniej nocy.',
      it: 'Un anello fatto con gli avanzi di ieri sera.',
      cs: 'Prsten ze zbytků minulé noci.',
      ja: '最後の夜の残り物で作られた指輪。',
      sv: 'En ring gjord av matresterna från igår kväll.',
      ko: '어젯밤의 남은 음식으로 만든 반지.',
      ht: 'Yon bag te fè nan rès rezèv yè swa a.',
      ro: 'Un inel făcut din resturile de aseară.',
      tr: 'Dün akşamki yemeğin artıklarından yapılmış bir yüzük.',
      da: 'En ring lavet fra sidste natrester.'
    }
  },

  {
    name       : {$$: 'Elven Heirloom' },
    description: {
      en: 'A race of elegant elves constructed this fine ring to protect themselves from danger.',
      ru: 'Раса элегантных эльфов сделала это прекрасное кольцо, чтобы защитить их от опасностей.',
      es: 'Una raza de elfos elegantes construyó este anillo fino para protegerse del peligro.',
      fr: 'Une race d\'elfes élégants a construit cette belle bague pour se protéger du danger',
      de: 'Eine Rasse von eleganten Elfen konstruierte diesen feinen Ring, um sich vor Gefahren zu schützen.',
      pt: 'Uma raça de elfos elegantes construiu este requintado anel para se protegerem do perigo.',
      ko: '우아한 엘프들의 경주가이 미세한 고리를 만들어 위험으로부터 자신을 보호합니다.',
      nl: 'Een ras van elegante elfen bouwde deze mooie ring om zichzelf te beschermen tegen gevaar.',
      pl: 'Rasa eleganckich elfów zbudowała ten piękny pierścionek, aby chronić się przed niebezpieczeństwem.',
      sv: 'En ras av praktfulla alver lät tillverka denna ring för att värja sig mot faror.',
      ht: 'Yon ras nan luten elegant konstwi sa a bag amann pwoteje tèt yo kont danje.',
      it: 'Una razza di eleganti elfi ha costruito questo raffinato anello per proteggersi dal pericolo.',
      hi: 'सुरुचिपूर्ण कल्पित बौनों की एक दौड़ ने खतरे से खुद को बचाने के लिए इस बढ़िया अंगूठी का निर्माण किया।',
      tl: 'Ang isang lahi ng mga eleganteng elves ay nagtayo ng pinong singsing upang protektahan ang kanilang sarili mula sa panganib.',
      el: 'Μια φυλή κομψών ξωτικών κατασκευάζει αυτό το ωραίο δαχτυλίδι για να προστατευθεί από τον κίνδυνο.',
      bg: 'Състезание от елегантни елфи изгради този фин пръстен, за да се предпази от опасност.',
      cs: 'Druh elegantních elfů vytvořil tento jemný prsten, aby se chránil před nebezpečím.',
      ja: '優雅なエルフのレースは危険から身を守るためにこの素晴らしい指輪を作りました。',
      ro: 'O rasă de elfi eleganți a construit acest inel frumos pentru a se proteja de pericole.',
      tr: 'Zarif elflerden bir ırk, kendilerini tehlikeden korumak için bu güzel yüzüğü işledi.',
      da: 'En rave af elegante alver konstruerede denne fine ring for at beskytte sig mod fare'
    }
  },

  {
    name       : {$$: 'Imbued Union' },
    description: {
      en: 'Fits nicely, although the effects it gives are marginal.',
      ru: 'На руке сидит хорошо, хотя эффекты, которые он дает, незначительны.',
      es: 'Encaja bien, aunque los efectos que produce son marginales.',
      de: 'Passt gut, auch wenn die Wirkung gering ist.',
      hi: 'सही बैठती है, भले ही इसकी शक्तियाँ कुछ ख़ास नहीं।',
      fr: 'S\'ajuste convenablement au doigt, bien que ses pouvoirs soient limités.',
      tl: 'Tama ang sukat bagaman ang mga epekto ay nagbibigay ng marginal.',
      bg: 'Приляга добре, въпреки че ефектите, които дава, са незначителни.',
      el: 'Ταιριάζει ωραία, αν και τα αποτελέσματα που δίνει είναι περιθωριακά.',
      pt: 'Adapta-se muito bem, embora os efeitos que dá sejam marginais.',
      nl: 'Past mooi, maar de effecten zijn marginaal.',
      pl: 'Pasuje ładnie, chociaż efekty, jakie daje, są marginalne.',
      it: 'Si adatta bene, anche se gli effetti che dà sono marginali.',
      cs: 'Dobře padne, i když účinky, které dává, jsou okrajové.',
      ja: 'それが与える効果はわずかですが、うまく収まります。',
      ht: 'Adapte joliman, byen ke efè li bay yo majinal.',
      sv: 'Passar fint, även om effekterna är marginella.',
      ko: '멋지게 잘 맞습니다. 효과는 거의 없습니다.',
      ro: 'Se potrivește bine, cu toate că efectele pe care le dă sunt marginale.',
      tr: 'Parmağına tam uyuyor ama sağladığı efektler marjinal.',
      da: 'Passer pænt, selvom de effekter det giver er marginale'
    }
  },

  {
    name       : {$$: 'Arcane Ring' },
    description: {
      en: 'No one knows if it is worth putting on.',
      ru: 'Никто не знает, стоит ли его надевать.',
      es: 'Nadie sabe si vale la pena ponerse esto.',
      de: 'Niemand weiß, ob es sich lohnt, sie anzuziehen.',
      hi: 'इसे पहना या ना पहना, कोई नहीं जानते।',
      fr: 'Personne ne sait si elle vaut la peine d\'être portée.',
      tl: 'Walang nakakaalam kung ito ay nagkakahalaga ng paglagay.',
      bg: 'Никой не знае дали си струва да се облече.',
      el: 'Κανείς δεν ξέρει αν αξίζει να το κάνουμε.',
      pt: 'Ninguém sabe se vale a pena vesti-lo.',
      nl: 'Niemand weet of het de moeite waard is om aan te trekken.',
      pl: 'Nikt nie wie, czy warto to założyć.',
      it: 'Nessuno sa se vale la pena di indossarlo.',
      cs: 'Nikdo neví, jestli to stojí za to.',
      ja: 'それを着る価値があるかどうか誰も知りません。',
      ht: 'Pa gen moun ki konnen si li vo mete.',
      sv: 'Ingen vet om den är värd att ta på sig.',
      ko: '아무 가치도 없다면 아무도 몰라요.',
      ro: 'Nimeni nu știe dacă merită să-l pui pe deget.',
      tr: 'Kimse parmağına takmaya değer olup olmadığını bilmiyor.',
      da: 'Ingen ved, om det er værd at sætte på.'
    }
  },

  {
    name       : {$$: 'Emerald Band' },
    description: {
      en: 'Emeralds on all sides to make you feel rich.',
      ru: 'Изумруды со всех сторон, чтобы вы чувствовали себя богатым.',
      es: 'Esmeraldas por todos lados para que te sientas rico.',
      de: 'Smaragde auf allen Seiten, damit Sie sich reich fühlen.',
      hi: 'इसके चारों ओर क़ीमती पत्थर जड़े है, जिनसे आप धनी महसूस करे।',
      fr: 'Incrustée d\'émeraudes pour vous faire vous sentir riche.',
      pt: 'Esmeraldas em todos os lados para te fazer sentir rico.',
      nl: 'Smaragden aan alle kanten om je rijk te laten voelen.',
      tl: 'Ang mga esmeralda sa lahat ng panig ay nagpapasaya sa iyo.',
      bg: 'Изумруди от всички страни, за да се почувствате богати.',
      el: 'Σμαράγδια σε όλες τις πλευρές για να σας κάνουν να αισθάνεστε πλούσιοι.',
      pl: 'Szmaragdy po wszystkich stronach, żebyś poczuł się bogaty.',
      it: 'Nessuno sa se vale la pena di indossarlo.',
      cs: 'Smaragdy ze všech stran, abys se cítil bohatý.',
      ja: 'あなたを豊かな気分にさせるためのあらゆる面のエメラルド。',
      ht: 'Emrod sou tout kote yo fè ou santi ou rich.',
      sv: 'Smaragder på alla sidor för att få dig att känna dig rik.',
      ko: '너를 부자로 만드는 에메랄드.',
      ro: 'Are smaralde în toate părțile pentru a te face să te simți bogat.',
      tr: 'Etrafındaki zümrütler sizi zengin hissettirecek.',
      da: 'Smaragder på alle sider for at få dig til at føle dig rig.'
    }
  },

  {
    name       : {$$: 'Infernal Ring' },
    description: {
      en: 'If it could speak, it would probably complain about being triangular.',
      es: 'Si pudiera hablar, probablemente se quejaría de ser triangular.',
      de: 'Gefühl zu geben, wenn es sprechen könnte, würde es sich wahrscheinlich darüber beschweren, dreieckig zu sein.',
      fr: 'Si elle pouvait parler, elle se plaindrait probablement d\'être triangulaire.',
      ru: 'Если б оно могло говорить, оно вероятно, пожаловалось бы на то, что оно треугольное.',
      hi: 'अगर ये अँगूठी बोल पति तो अपने त्रिकोण होने की शिकायत करती।',
      pt: 'Se pudesse falar, provavelmente queixar-se-ia de ser triangular.',
      nl: 'Als het kon spreken, zou het waarschijnlijk klagen over het feit dat het driehoekig is.',
      tl: 'Kung maaari itong magsalita malamang ay magreklamo tungkol sa pagiging triangular.',
      bg: 'Ако можеше да говори, вероятно щеше да се оплаче, че е триъгълна.',
      el: 'Εάν μπόρεσε να μιλήσει, θα διαμαρτυρόταν πιθανώς να είναι τριγωνικό.',
      pl: 'Gdyby mógł mówić, prawdopodobnie skarżyłby się na bycie trójkątnym.',
      it: 'Se potesse parlare, probabilmente si lamenterebbe di essere triangolare.',
      cs: 'Kdyby mohla mluvit, pravděpodobně by si stěžovala na to, že je trojúhelníková.',
      ja: 'それが話すことができればそれはおそらく三角形であることについて不平を言うでしょう。',
      ht: 'Si li te kapab pale, li ta pwobableman pote plent pou yo te triyangilè.',
      sv: 'Kunde den tala så skulle det troligen klaga över att vara triangulär.',
      ko: '말할 수 있다면 아마도 삼각형에 대해 불평 할 것입니다.',
      ro: 'Dacă ar putea vorbi, probabil s-ar plânge că e triunghiular.',
      tr: 'Bu yüzük konuşabilseydi, muhtemelen üçgen şekli hakkında şikayet ederdi.',
      da: 'Hvis det kunne tale, ville det nok klage over at være trekantet.'
    }
  },

  {
    name       : {$$: 'Ancient Signet' },
    description: {
      en: 'No written records exist to tell us about its origin...',
      ru: 'Не существует никаких письменных отчетов о его происхождении ...',
      es: 'No existen registros escritos que nos indiquen su origen...',
      de: 'Es gibt keine schriftlichen Aufzeichnungen, um uns über die Herkunft zu informieren...',
      fr: 'Il n\'existe aucune trace écrite de son origine...',
      hi: 'इसके बारे में कोई जानकारी उपलब्ध नहीं है।',
      pt: 'Não existem registos escritos que nos falem da sua origem...',
      nl: 'Er bestaan geen schriftelijke gegevens om ons te vertellen over de oorsprong ervan...',
      tl: 'Walang umiiral na nakasulat na tala upang sabihin sa amin ang tungkol sa pinagmulan nito...',
      bg: 'Не съществуват писмени записи, които да ни кажат за неговия произход.',
      el: 'Δεν υπάρχουν γραπτά αρχεία για να μας πουν για την προέλευσή του ....',
      pl: 'Nie ma żadnych pisemnych zapisów, które powiedziałyby nam o jego pochodzeniu...',
      it: 'Non esistono documenti scritti che ci dicono la sua origine...',
      cs: 'Neexistují žádné písemné záznamy, které by nám sdělily svůj původ ...',
      ja: 'その起源について私たちに伝えるための書面による記録はありません。',
      ht: 'Pa gen okenn dosye ekri ki egziste di nou sou orijin li yo ...',
      sv: 'Dess ursprung är höljt i dunkel',
      ko: '원산지에 대해 알려주는 기록이 없습니다 ...',
      ro: 'Nu există înregistrări scrise care să ne spună despre originea lui...',
      tr: 'Kökeni hakkında bilgi veren yazılı bir kaynak yok...',
      da: 'Der findes ingen skriftlige optegnelser for at fortælle os om dets oprindelse ...'
    }
  },

  {
    name       : {$$: 'Reverence' },
    description: {
      en: 'Sacred artifact lost by holy druids.',
      ru: 'Священный артефакт, потерянный святыми друидами.',
      es: 'Artefacto sagrado perdido por druidas sagrados.',
      de: 'Heiliges Artefakt, das von heiligen Druiden verloren wurde.',
      hi: 'पवित्र द्रुइड ने इस धार्मिक अँगूठी को खो दिया था।',
      fr: 'Artefact sacré perdu par des druides saints.',
      pt: 'Artefacto sagrado perdido pelos druidas sagrados.',
      tl: 'Banal na artepakto nawala sa pamamagitan ng banal druids.',
      bg: 'Свещен артефакт, изгубен от светите друиди.',
      el: 'Ιερό τεχνούργημα που χάθηκε από ιερά τυράνια.',
      nl: 'Heilig artefact verloren door heilige druïden.',
      pl: 'Święty artefakt utracony przez świętych druidów.',
      it: 'Artefatto sacro perso dai santi druidi.',
      cs: 'Posvátný artefakt ztracený svatými druidy.',
      ja: '聖ドルイドによって失われた神聖なアーティファクト。',
      ht: 'Sakrifis sakre pèdi pa druid apa pou Bondye.',
      sv: 'Helgad artefakt mist av heliga druider.',
      ko: '거룩한 드루이드가 잃어버린 신성한 유물.',
      ro: 'Artefact sacru, pierdut de sfinții druizii.',
      tr: 'Kutsal druidlerin kayıp kutsal eseri.',
      da: 'Sacred artefact tabt af hellige druider'
    }
  },

  {
    name       : {$$: 'Gyges' },
    description: {
      en: 'A ring said to be capable of turning its wearer invisible and motivate them for everlasting glory.',
      ru: 'Кольцо, которое, как говорят, способно сделать его владельца невидимым и мотивировать его на вечную славу.',
      es: 'Un anillo que se dice es capaz de volver invisible a su portador y los motiva para la gloria eterna.',
      de: 'Ein Ring soll in der Lage sein, seinen Träger unsichtbar zu machen und ihn zu ewigem Ruhm zu motivieren.',
      hi: 'एक अंगूठी ने अपने पहनने वाले को अदृश्य करने में सक्षम होने के लिए कहा और उन्हें हमेशा की महिमा के लिए प्रेरित किया।',
      fr: 'Un anneau dit être capable de rendre son porteur invisible et de le motiver pour la gloire éternelle.',
      pt: 'Um anel dito ser capaz de transformar seu portador invisível e motivá-los para a glória eterna.',
      nl: 'Een ring die naar verluidt in staat is om de drager onzichtbaar te maken en hen te motiveren voor eeuwige glorie.',
      tl: 'Ang isang singsing ay nagsabi na may kakayahang gawing hindi nakikita ang tagapagsuot nito at mag-udyok sa kanila para sa walang hanggang kaluwalhatian.',
      bg: 'Пръстен, за който се казва, че е способен да превърне своя невидим и да ги мотивира за вечна слава.',
      el: 'Ένα δαχτυλίδι λέγεται ότι είναι ικανό να μετατρέψει τον φορέα του αόρατο και να τον παρακινήσει για αιώνια δόξα.',
      pl: 'Pierścień, o którym mówi się, że potrafi zmienić swojego noszącego w niewidzialny i zmotywować go do wiecznej chwały.',
      it: 'Un anello che si dice sia in grado di rendere invisibile chi lo indossa e motivarlo per la gloria eterna.',
      cs: 'Prsten řekl, že je schopný otočit svého nositele neviditelným a motivovat je k věčné slávě.',
      ja: '指輪は身に着けている人を見えなくし、永遠の栄光に動機付けることができると言われています。',
      ht: 'Yon bag te di yo dwe kapab vire utilisateurs li yo envizib ak motive yo pou tout bèl pouvwa p\'ap janm fini an.',
      sv: 'En ring sa att kunna ändra sin bärare osynlig och motivera dem för evigt ära.',
      ko: '반지는 착용자를 보이지 않게하고 영원한 영광을 위해 그들을 자극 할 수 있다고 말했습니다.',
      da: 'En ring sagde at være i stand til at vende sin bærer usynlig og motivere dem til evig herlighed.',
      ro: 'Se spune că inelul este capabil să-și facă purtătorul invizibil și să-l motiveze pentru glorie veșnică.',
      tr: 'Söylenilene göre takan kişiyi görünmez yapabilen ve sonsuz zafer için motive edebilen bir yüzük.'
    }
  },

  {
    name       : {$$: 'Peacekeeper' },
    description: {
      en: 'Keeper of peace...not sure about that, but it might keep you alive...',
      ru: 'Хранитель мира... не уверен в этом, но оно может помочь остаться в живых...',
      es: 'Guardián de la paz... no estoy seguro de eso, pero podría mantenerte vivo.',
      de: 'Hüter des Friedens... nicht sicher, aber vielleicht hält dich das am Leben.',
      hi: 'शांति की रखवाली...इसकी गैरंटी तो नहीं, पर आपको ज़िंदा रख पाएगी शायद...',
      fr: 'Gardien de la paix... pas sûr de cela, mais elle saura sûrement vous garder en vie.',
      pt: 'Guardião da paz... não tenho a certeza disso, mas pode mantê-lo vivo...',
      nl: 'Bewaarder van de vrede... niet zeker, maar het kan je in leven houden...',
      tl: 'Tagapangalaga ng kapayapaan... hindi sigurado tungkol sa bagay na iyon ngunit maaaring panatilihing buhay ka...',
      bg: 'Пазител на мира... не съм сигурен в това, но може да те запази жив...',
      el: 'Φύλακας της ειρήνης... δεν είμαι σίγουρος γι \'αυτό αλλά μπορεί να σας κρατήσει ζωντανό ...',
      pl: 'Strażnik spokoju... nie jestem tego pewien, ale może to utrzyma cię przy życiu...',
      it: 'Custode di pace... non ne sono sicuro, ma potrebbe tenervi in vita...',
      cs: 'Strážce míru ... není si tím jistý, ale může vás udržet naživu.',
      ja: '平和の番人... それについてはよくわからないが、それはあなたを生かし続けるかもしれない...',
      ht: 'Gadyen lapè... pa sèten sou sa, men li ta ka kenbe ou vivan...',
      sv: 'Fredsbevarare... inte så säker på det, men den kan hålla dig vid liv...',
      ko: '평화를 지키기 위해... 확실하지는 않지만, 당신을 살릴 수 있습니다.',
      ro: 'Păstrător al păcii... nu sunt sigur de asta, dar s-ar putea să te țină în viață...',
      tr: 'Barış bekçisi... bundan emin değilim ama seni hayatta tutabilir.',
      da: 'Fredens bevogter ... ikke sikker på det, men det kan holde dig i live'
    }
  }

]
