export default [
  {
    name       : {$$: 'Lucid' },
    description: {
      en: 'Small and sharp, this pendant leaves shallow scrapes on your skin during battle.',
      ru: 'Маленький и острый, этот кулон оставляет мелкие царапины на коже во время боя.',
      es: 'Pequeño y afilado, este colgante deja rasguños superficiales en la piel durante la batalla.',
      de: 'Klein und scharf, hinterlässt dieser Anhänger im Kampf flache Kratzer auf der Haut.',
      fr: 'Petit et pointu, ce pendentif laisse des éraflures peu profondes sur votre peau pendant le combat.',
      nl: 'Klein en scherp, deze hanger laat ondiepe schrammen achter op je huid tijdens een gevecht.',
      tl: 'Maliit at matalim ang palawit na ito ay umalis sa mababaw na mga scrapes sa iyong balat sa panahon ng labanan.',
      pl: 'Mały i ostry wisior pozostawia płytkie zadrapania na skórze podczas walki.',
      pt: 'Pequeno e afiado, este pingente deixa marcas rasas na sua pele durante a batalha.',
      el: 'Μικρό και αιχμηρό αυτό το κρεμαστό κόσμημα αφήνει ρηχό ξύσιμο στο δέρμα σας κατά τη διάρκεια της μάχης.',
      bg: 'Малък и остър този висулка оставя плитки ожулвания по кожата ви по време на битка.',
      it: 'Piccolo e appuntito, questo ciondolo lascia dei graffi poco profondi sulla pelle durante la battaglia.',
      hi: 'छोटे और तेज, यह मणि लड़ाई के दौरान आपकी त्वचा पर उथले खरोंच छोड़ा देती है।',
      cs: 'Malý a ostrý, tento přívěsek zanechává mělké škrábance na kůži během bitvy.',
      ja: '小さくて鋭いこのペンダントは戦いの間にあなたの肌に浅い擦り傷を残します。',
      tr: 'Küçük ve keskin, bu kolye savaş sırasında cildinize küçük sıyrıklar bırakır.',
      ht: 'Ti ak byen file, sa a pandye fèy bwa grate ti kras sou po ou pandan batay.',
      sv: 'Liten och skarp, denna hängsmycke lämnar grunda skrapar på din hud under striden.',
      ko: '작고 날카로운이 펜던트는 전투 중에 피부에 얕은 긁힌 자국을 남깁니다.',
      ro: 'Mic și ascuțit, acest pandantiv lasă zgârieturi superficiale pe piele în timpul luptei.',
      da: 'Lille og skarp, dette vedhæng efterlader overfladisk skraber på din hud under kamp.'
    }
  },

  {
    name       : {$$: 'Melant' },
    description: {
      en: 'Rough disc-shaped gray stone with strange druidic engravings encasing it.',
      ru: 'Серый камень грубой дисковой формы со странной друидной гравюрой на его поверхности.',
      es: 'Rugoso con forma de disco gris pierda con extraños inscripción druídicos que lo cerrar.',
      de: 'Grober scheibenförmiger grauer Stein mit seltsamen druidischen Gravuren, die ihn umgeben.',
      fr: 'Pierre grise brute en forme de disque avec d\'étranges gravures druidiques tout autour.',
      nl: 'Ruwe schijf-vormige grijze steen met vreemde druïdische gravures die het omhullen.',
      el: 'Σκληρή πέτρινη γκρίζα πέτρα, με περίεργες δεξιοτεχνικές χαρακτικές, που την περιβάλλουν.',
      bg: 'Груб сив ​​камък с форма на диск, в който са разположени странни друидични гравюри.',
      pl: 'Szary kamień w kształcie dysku z dziwnymi druidycznymi rycinami, które go otaczają.',
      pt: 'Pedra cinzenta em forma de disco rugoso com estranhas gravuras druídicas que a rodeiam',
      it: 'Pietra grigia a forma di disco grezzo con strane incisioni druidiche che lo avvolgono.',
      hi: 'गोलकर और कठोर पत्थर जिस पर अजीब पवित्र नक़्क़ाशी है।',
      cs: 'Hrubý šedý kámen ve tvaru disku s podivnými rytmickými druidickými rytinami, které ho obklopují.',
      tl: 'Magaspang na hugis-disc na kulay abong bato na may mga kakaibang druidical na ukit na ito.',
      ja: 'それを包んでいる奇妙なドルイドの彫刻が付いている粗い円盤形の灰色の石。',
      tr: 'Kaba disk şeklindeki gri taş, onu saran garip rahibesel işlemeler.',
      ht: 'Wouj disk ki gen fòm wòch gri ak etranj grave ekri dris encasing li.',
      sv: 'Grov skivformad grå sten med konstiga druidiska gravyrer som omsluter den.',
      ko: '거친 디스크 모양의 회색 돌에 이상한 사제 조각이 들어 있습니다.',
      ro: 'Piatră cenușie în formă de disc, ce are niște gravuri druidice ciudate încrustate în ea.',
      da: 'Grov skiveformet grå sten med mærkelige druidiske graveringer, der omslutter den.'
    }
  },

  {
    name       : {$$: 'Turim' },
    description: {
      en: 'Powerful transparent glass talisman with a faint purple tint showing you the world in a melancholic light.',
      es: 'Poderoso talismán de cristal transparente, de color púrpura pálido que muestra el mundo en una luz melancólica.',
      ru: 'Мощный прозрачный стеклянный талисман. Его бледно-фиолетовый оттенок показывает мир в меланхолическом свете.',
      de: 'Kraftvoller transparenter Glas-Talisman, schwacher Violett-Ton zeigt Ihnen die Welt in einem melancholischen Licht.',
      fr: 'Puissant talisman en verre transparent, légèrement teinté de violet, qui montre le monde dans une lumière mélancolique.',
      nl: 'Krachtige transparante glazen talisman, een vage paarse tint laat je de wereld zien in een melancholisch licht.',
      pl: 'Mocny przezroczysty szklany talizman z lekkim fioletowym zabarwieniem ukazującym świat w melancholijnym świetle.',
      bg: 'Мощен прозрачен стъклен талисман със слаб лилав оттенък, който ви показва света в меланхолична светлина.',
      el: 'Ισχυρός διαφανής γυαλιστερός γυαλιστερός με μια απαλή μοβ απόχρωση που σας δείχνει τον κόσμο σε ένα μελαγχολικό φως.',
      tl: 'Makapangyarihang transparent na salamin na anting-anting na may malabong lilang tint na nagpapakita sa iyo ng mundo sa isang mapanglaw na liwanag.',
      pt: 'Poderoso talismã de vidro transparente com uma leve tonalidade púrpura que mostra o mundo numa luz melancólica.',
      it: 'Potente talismano in vetro trasparente con una tenue tinta viola che mostra il mondo in una luce malinconica.',
      hi: 'एक आकर्षक बैंगनी रंग के साथ शक्तिशाली और पारदर्शी ग्लास तावीज़ आपको एक उदास रोशनी में दुनिया दिखा रहा है।',
      cs: 'Výkonný transparentní skleněný talisman se slabým fialovým odstínem, který vám ukazuje svět v melancholickém světle.',
      ja: '憂鬱な光の中であなたに世界を見せるかすかな紫の色合いを持つ強力な透明なガラスお守り。',
      tr: 'Melankolik ışıkta dünyayı gösteren soluk mor renk tonu ile güçlü şeffaf cam tılsım.',
      ht: 'Pwisan Talisman transparan an vè ak yon tenti koulè wouj violèt endispoze ki montre ou mond lan nan yon limyè trist.',
      sv: 'Kraftfull transparent glas talisman med en svag lila nyans som visar dig världen i ett melankolskt ljus.',
      ko: '우울한 보라색 색조와 함께 강력한 투명 유리 부적은 당신에게 우울한 빛으로 세계를 보여줍니다.',
      ro: 'Talismanul puternic din sticlă transparentă, cu nuanță violet slabă, îți arată lumea într-o lumină melancolică.',
      da: 'Kraftig gennemsigtig glas talisman med en svag lilla farvetone, der viser dig verden i et melankolsk lys.'
    }
  },

  {
    name       : {$$: 'Fundo' },
    description: {
      en: 'Brown desaturated gem, emitting putrid scents as you wear it around your neck.',
      ru: 'Драгоценный камень коричневого цвета, испускающий гнилой аромат, когда вы носите его на шее.',
      es: 'Gema desaturada marrón, que emite olores pútridos al llevarlo alrededor del cuello.',
      de: 'Brauner, entsättigter Edelstein, der faulige Gerüche abgibt, wenn man ihn um den Hals trägt.',
      fr: 'Bijou brun désaturé, émettant des senteurs putrides lorsque vous le portez autour de votre cou.',
      nl: 'Bruine desaturated edelsteen, die rottende geuren afgeeft terwijl je het om je nek draagt.',
      el: 'Καφέ αποκορεσμένο κόσμημα που εκπέμπει ξεθωριασμένα αρώματα καθώς το φοράτε γύρω από το λαιμό σας.',
      bg: 'Кафяво денатуриран скъпоценен камък, излъчващ гнилови миризми, докато го носите около врата си.',
      pl: 'Brązowy, mniej nasycony klejnot, wydzielający zgniłe zapachy, gdy nosisz go na szyi.',
      pt: 'Jóia marrom desaturada, emitindo cheiros fétidos ao usá-la ao redor do pescoço.',
      tl: 'Brown desaturated gem ang nagpapalabas ng malaswang amoy habang isinusuot mo ito sa iyong leeg.',
      it: 'Una gemma marrone desatura, che emette profumi putridi quando la si indossa intorno al collo.',
      hi: 'ब्राउन मणि, सड़ा हुआ सुगंधों उत्सर्जन के रूप में आप इसे अपने गले में पहनते हैं।',
      cs: 'Hnědý desaturovaný drahokam, vyzařující hnijící vůně, když ho nosíte kolem krku.',
      ja: '腐敗した香りを放つ茶色の彩度の低い宝石',
      tr: 'Kahverengi doygunluğu azaltılmış mücevher, boynunuza taktığınız gibi kokuşmuş kokular yayar.',
      ht: 'Gwo lous desaturasyon, emèt sant odè ou mete li nan kou ou.',
      sv: 'Brun desaturerad pärla som ger utspända dofter när du bär den runt nacken.',
      ko: '당신의 목에 착용하면 부패한 냄새가 나는 갈색 불포화 보석.',
      ro: 'Bijuterie maro desaturată, emite mirosuri putrede în timp ce o porți la gât.',
      da: 'Brun desatureret perle, der udsender uhyggelige dufte som du bærer den rundt om halsen.'
    }
  },

  {
    name       : {$$: 'Amari' },
    description: {
      en: 'Lustrous blue artifact, exposed wispy white veins running along its spherical surface.',
      ru: 'Блестящий синий артефакт с белоснежными венами, протекающими по его сферической поверхности.',
      es: 'Lustroso artefacto azul, vetas blancas y delgadas expuestas que corren a lo largo de su superficie esférica.',
      de: 'Glänzend blaues Artefakt, freiliegende, wischig weiße Adern, die entlang seiner kugelförmigen Oberfläche verlaufen.',
      fr: 'Artefact bleu lustré, avec des veines blanches et brillantes le long de sa surface sphérique.',
      tl: 'Ang matingkad na asul na artifact ay nakalantad na wispy white veins na tumatakbo kasama ang spherical na ibabaw nito.',
      nl: 'Lustrous blue artefact, blootgestelde wispy witte aders die langs zijn bolvormige oppervlak lopen.',
      el: 'Το λαμπερό μπλε τεχνούργημα εκθέτει τις άσπρες φλέβες που τρέχουν κατά μήκος της σφαιρικής επιφάνειας.',
      bg: 'Блестящ син артефакт разкриваше тънки бели вени, движещи се по сферичната му повърхност.',
      pl: 'Świecący artefakt w kolorze niebieskim, odsłonięte białe żyły biegnące wzdłuż jego kulistej powierzchni.',
      pt: 'Artefacto azul lustroso, veias brancas expostas e esbranquiçadas ao longo da sua superfície esférica.',
      it: 'Lustrous artefatto blu brillante, esposte venature bianche e sottili che corrono lungo la sua superficie sferica.',
      hi: 'चमकदार नीली विरूपण साक्ष्य, सफेद नसों की उजागर कणों का अपनी गोलाकार सतह के साथ चल रहा है।',
      cs: 'Lesklý modrý artefakt, odkryté chlupaté bílé žíly podél jeho kulového povrchu.',
      ja: '光沢のある青いアーティファクトは、その球面に沿って走る白っぽく白い静脈を露出させました。',
      tr: 'Parlak mavi eser, küresel yüzeyi boyunca akan incecik beyaz damarlarla bezenmiş.',
      ht: 'Lustrous asosye ble, ekspoze wispy venn blan kouri ansanm sifas esferik li yo.',
      sv: 'Ljusblå artefakt, exponerade vita vita vener som löper längs sin sfäriska yta.',
      ko: '광택있는 푸른 유물, 구형 표면을 따라 달려 드는 희미한 흰 정맥.',
      ro: 'Artefactul albastru lucios, expune vene albe subțiri aflate de-a lungul suprafeței sale sferice.',
      da: 'Strålende blå artefakt, eksponerede, hvide hvide årer, der løber langs sin sfæriske overflade.'
    }
  },

  {
    name       : {$$: 'Purum' },
    description: {
      en: 'Radiant titian glass-like gem revealing your foe\'s hidden secrets.',
      es: 'Luminoso gema en forma de vidrio que revela los secretos ocultos de tus enemigos.',
      ru: 'Сияющий титьяновый, похожий на стекло драгоценный камень, раскрывающий секреты ваших врагов.',
      de: 'Strahlender titianischer glasartiger Edelstein, der die verborgenen Geheimnisse deiner Feinde enthüllt.',
      fr: 'Gemme de verre titien rayonnante révélant les secrets cachés de vos ennemis.',
      nl: 'Stralend Titiaans-achtig glasachtig juweel dat verborgen geheimen van je vijanden onthult.',
      pl: 'Wspaniałe tytan figura szklana gem ujawniający ukryte sekrety twoich wrogów.',
      pt: 'Uma jóia radiante de vidro ticiano que revela os segredos escondidos dos teus inimigos.',
      tl: 'Mapang-akit na salamin na salamin tulad ng salamin na nagpapakita ng iyong mga kaaway na nakatago ng mga lihim.',
      bg: 'Излъчващ скъпоценен камък от тициан, който разкрива вашите врагове скрити тайни.',
      el: 'Radiant titian γυαλί-όπως κόσμημα αποκαλύπτοντας τους εχθρούς σας κρυμμένα μυστικά.',
      it: 'Una radiosa gemma di vetro tiziano che rivela i segreti nascosti dei tuoi nemici.',
      hi: 'उज्ज्वल नारंगी कांच की तरह मणि अपने शत्रु के छिपे रहस्यों को प्रकट करती है।',
      cs: 'Zářivý titánový skleněný drahokam, který odhaluje tvé nepřátele skrytá tajemství.',
      ja: 'あなたの敵に隠された秘密を明らかにした輝くティティアングラスのような宝石。',
      tr: 'Düşmanlarının gizli sırlarını açığa çıkaran parlayan ışıltılı titian cam benzeri mücevher.',
      ht: 'Radyan jeyan tankou vè ki tankou revele sekrè kache lenmi ou.',
      sv: 'Strål ande Titian glasliknande pärla avslöjar din fiende gömda hemligheter.',
      ko: '적의 숨겨진 비밀을 드러내는 빛나는 타이탄 유리 같은 보석.',
      ro: 'O bijuterie strălucitoare de titian care dezvăluie secretele ascunse ale dușmanului tău.',
      da: 'Strålende titian glasagtige perle afslørende din fjende er skjulte hemmeligheder.'
    }
  },

  {
    name       : {$$: 'Royal' },
    description: {
      en: 'This grand red gem enclosed in abyss dark fissures grants your foes a sense of jealousy.',
      ru: 'Этот большой красный драгоценный камень, заключенный в бездну темных трещин, дарит врагам чувство ревности.',
      es: 'Esta gran gema roja encerrada en las oscuras fisuras del abismo, dando a tus enemigos una sensación de celos.',
      de: 'Dieser großartiges rotes Juwel, umgeben von dunklen Rissen im Abgrund, das deinen Feinden ein Gefühl der Eifersucht verleiht.',
      fr: 'Ce grand joyau rouge enfermé dans des fissures sombres de l\'abîme donne à vos ennemis un sentiment de jalousie.',
      nl: 'Deze een groot rood juweel, ingesloten in donkere kloven in de afgrond, waardoor je vijanden een gevoel van jaloezie krijgen.',
      tl: 'Ang engrandeng pulang perlas na ito na nakapaloob sa kalaliman ng madilim na mga fissures ay nagbibigay sa iyong mga kaaway ng pag-iisip ng paninibugho.',
      el: 'Αυτό το μεγάλο κόκκινο στολίδι που περικλείεται σε άβυσες σκοτεινές σχισμές δίνει στους εχθρούς σας μια αίσθηση ζήλια.',
      bg: 'Този велик червен скъпоценен камък, затворен в бездната на тъмните пукнатини, дава на вашите врагове усещане за ревност.',
      pl: 'Ten wielki czerwony klejnot zamknięty w otchłani ciemnych szczelinach daje wrogom poczucie zazdrości.',
      pt: 'Esta grande jóia vermelha encerrada em fissuras escuras no abismo, dando aos seus inimigos uma sensação de ciúmes',
      it: 'Questa grande gemma rossa racchiusa in fenditure scure dell\'abisso che dona ai tuoi nemici un senso di gelosia.',
      hi: 'यह गहरे लाल रंग के गहरे नीले रंग के मणि में जड़ा हुआ रत्न आपके दुश्मनों को ईर्ष्या की भावना देता है।',
      cs: 'Tento velký červený drahokam uzavřený v propasti temných trhlin dává svým nepřátelům pocit žárlivosti.',
      ja: '深みのある暗い割れ目に囲まれたこの真っ赤な宝石は、あなたの敵に嫉妬の感覚を与えます。',
      ht: 'Gwo wòch sa a wouj ki fèmen nan gwo twou san fon fant nwa bay lènmi ou yo yon sans jalouzi.',
      sv: 'Denna stora röda sten som är innesluten i avgrunds mörka sprickor ger dina fiender en känsla av svartsjuka.',
      ko: '어두운 붉은 균열에 둘러싸인 웅장한 빨간 돌은 당신의 원수에게 질투심을 부여합니다.',
      ro: 'Această enormă piatră roșie înconjurată de fisuri negre abisale, oferă dușmanilor tăi un sentiment de gelozie.',
      da: 'Denne store røde perle indesluttet i afgrund mørke fissurer giver dine fjender en følelse af jalousi.',
      tr: 'Bu etrafı karanlık hiçlik çatlakları ile çevrelenmiş büyük kırmızı mücevher düşmanlarını kıskandırır.'
    }
  },

  {
    name       : {$$: 'Tara' },
    description: {
      en: 'The sharp green edges catch sparkling light in the sun, making a beautiful and deadly sight.',
      ru: 'Острые зеленые края улавливают блики на солнце, создавая прекрасный и смертоносный вид.',
      es: 'Los bordes afilados de color verde captan una luz brillante en el sol, lo que hace que la vista sea hermosa y mortal.',
      de: 'Die scharfen grünen Kanten fangen funkelndes Licht in der Sonne ein und machen einen schönen und tödlichen Anblick.',
      fr: 'Les bords vert vif captent la lumière étincelante du soleil, ce qui en fait un spectacle aussi magnifique que mortel.',
      nl: 'De scherpe groene randen vangen het sprankelende licht op in de zon, waardoor een mooi en dodelijk zicht ontstaat.',
      el: 'Τα αιχμηρά πράσινα άκρα πιάζουν το φως του ήλιου στον ήλιο κάνοντας ένα όμορφο και θανατηφόρο θέαμα.',
      tl: 'Ang matalim berdeng mga gilid mahuli ang sparkling light sa araw na gumagawa ng magandang at nakamamatay na paningin.',
      bg: 'Острите зелени ръбове улавят искряща светлина на слънцето, правейки красива и смъртоносна гледка.',
      pl: 'Ostre zielone krawędzie łapią błyszczące światło w słońcu, tworząc piękny i zabójczy widok.',
      pt: 'As bordas verdes afiadas captam luz cintilante no sol, fazendo uma visão bela e mortal.',
      it: 'I taglienti bordi verdi catturano la luce scintillante al sole, rendendo la vista bella e mortale.',
      hi: 'तेज हरी किनारों धूप में स्पार्कलिंग प्रकाश को पकड़ने, एक सुंदर और घातक दृष्टि बना रही है।',
      cs: 'Ostré zelené okraje zachycují na slunci zářivé světlo, které vytváří krásný a smrtící pohled.',
      ja: '鋭い緑色の縁が太陽の下で輝く光を捉え、美しく致命的な光景を作ります。',
      tr: 'Keskin yeşil kenarlar güneşte parlayan ışıklar saçar, güzel ve ölümcül bir manzara sunar.',
      ht: 'Byen file lizyè vèt trape mousseux limyè nan solèy, li fè yon bèl ak vi trè danjere.',
      sv: 'De skarpa gröna kanterna får glittrande ljus i solen, vilket gör en vacker och dödlig syn.',
      ko: '날카로운 초록색 가장자리가 태양 빛을 반사하여 아름답고 치명적인 시력을 선사합니다.',
      ro: 'Marginile verzi ascuțite prind o lumină strălucitoare în soare, făcând o priveliște frumoasă și mortală.',
      da: 'De skarpe grønne kanter får glittende lys i solen, hvilket gør et smukt og dødeligt syn.'
    }
  },

  {
    name       : {$$: 'Gloom' },
    description: {
      en: 'Small, smooth and dark, this gem possesses treacherous traits as it slips from its wielders hands...',
      ru: 'Маленький, гладкий и темный, этот драгоценный камень обладает коварными чертами характера, как он выскальзывает из рук своих владельцев....',
      es: 'Pequeña, lisa y oscura, esta gema posee rasgos traicioneros ya que se desliza de las manos de sus dueños...',
      de: 'Klein, glatt und dunkel, besitzt dieses Juwel tückische Eigenschaften, während es aus den Händen seiner Besitzer rutscht...',
      fr: 'Petit, lisse et sombre, ce joyau possède des traits traîtres lorsqu\'il glisse des mains de son possesseur..',
      nl: 'Klein, glad en donker, dit juweel heeft verraderlijke eigenschappen als het uit zijn handen glijdt...',
      tl: 'Maliit na makinis at madilim ang mamahaling bato na ito ay nagtataglay ng mga taksil na katangian tulad ng mga ito mula sa mga kamay ng mga kamay nito...',
      el: 'Μικρό ομαλό και σκοτεινό αυτό το κόσμημα έχει προδοτικά χαρακτηριστικά, καθώς γλιστρά από τα χέρια του χειριστή...',
      bg: 'Малък гладък и тъмен този скъпоценен камък притежава коварните черти, тъй като се изплъзва от ръцете си...',
      pl: 'Mały, gładki i ciemny, ten klejnot posiada zdradzieckie cechy, ponieważ zsuwa się z rąk władców...',
      pt: 'Pequena, suave e escura, esta jóia possui traços traiçoeiros enquanto escorrega das mãos dos que a empunham...',
      it: 'Piccola, liscia e scura, questa gemma possiede tratti infidi mentre scivola dalle mani dei suoi manipolatori...',
      hi: 'छोटे चिकनी और अंधेरे, इस मणि विश्वासघाती लक्षण पास के रूप में यह अपनी wielders हाथ से निकल जाता है ...',
      cs: 'Malý, hladký a temný, tento drahokam má zrádné rysy, když se vyklouzne z rukou držitelů ...',
      ja: '小さくて滑らかで暗いこの宝石は、その手の手の手から外れると危険な特徴を持っています...',
      tr: 'Küçük, pürüzsüz ve karanlık, bu mücevher kaynakçıların ellerinden kaydığı için hain özelliklere sahip...',
      ht: 'Ti, dous ak fènwa, gem sa a possède trè perfides ke li bons anba men wielders li...',
      sv: 'Små, släta och mörka, den här pärlan har förrädiska egenskaper som den glider ut från sina handtagshänder...',
      ko: '작고 매끄럽고 어두운이 보석은 손에 들고있는 손에서 미끄러지 듯 위험한 특성을 가지고 있습니다...',
      ro: 'Mică, netedă și întunecată, această nestemată are trăsături înșelătoare ce o fac să alunece din mâinile proprietarilor săi...',
      da: 'Små, glatte og mørke, denne perle besidder forræderiske træk, da det glider fra sine håndtagers hænder ...'
    }
  },

  {
    name       : {$$: 'Plurae' },
    description: {
      en: 'Spectacular saturated pink plumes rise from this faceted prismical gem. Your foes to stare at you with awe...',
      ru: 'Из этого граненого призматического камня поднимаются впечатляющие насыщенные розовые шлейфы. Твои враги с восхищением смотрят на тебя...',
      es: 'Espectaculares plumas rosas saturadas surgen de esta gema prismática facetada. Tus enemigos te mirarán con asombro...',
      de: 'Spektakuläre, gesättigte rosa Federn erheben sich aus diesem facettierten prismatischen Juwel. Deine Feinde, die dich mit Ehrfurcht anstarren...',
      el: 'Κομψά κοκκινωπά κοκκώδη κεράσια ανεβαίνουν από αυτό το πολύπλευρο πρισματικό κόσμημα. Οι εχθροί σου να σε κοιτάζουν με δέος ...',
      bg: 'Впечатляващите наситени розови перки се издигат от тази грапава призматична перла. Твоите врагове да те гледат с благоговение ...',
      fr: 'Des panaches roses spectaculaires s\'élèvent de ce joyau prismatique à facettes. Vos ennemis vous regardent avec crainte...',
      nl: 'Spectaculaire verzadigde roze pluimen rijzen op uit deze gefacetteerde prismatische parel. Uw vijanden om u met ontzag aan te staren.....',
      tl: 'Ang mga nakamamanghang puspos ng mga kulay-rosas na mga plume ay tumaas mula sa faceted prismical gem na ito. Ang iyong mga kaaway upang tumitig sa iyo sa sindak ...',
      pl: 'Z tego fasetowanego klejnotu pryzmatycznego wyrastają spektakularne, nasycone różowe smugi. Twoi wrogowie, którzy będą się na ciebie gapić z podziwem...',
      pt: 'Espectaculares plumas cor-de-rosa saturadas emergem desta gema prismática facetada. Os teus inimigos olham para ti com admiração...',
      it: 'Spettacolari pennacchi rosa saturi sorgono da questa gemma prismatica sfaccettata. I tuoi nemici a fissarti con stupore ...',
      hi: 'बेमिसाल गुलाबी ज़ुल्फ़ें ',
      cs: 'Z tohoto fasetového hranolového drahokamu vyčnívají velkolepé nasycené růžové švestky. Vaši nepřátelé na tebe zírají s úžasem ...',
      ja: '壮観な飽和ピンクプルームは、このファセットプリズム宝石から発生します。あなたの敵は畏敬の念を持ってあなたを見つめています...',
      tr: 'Muhteşem pembe tüyler bu prizmatik cevherden çıkar. Huşu ile sana bakar...',
      ht: 'Gwo saturée plumes penk monte soti nan prismical gem à sa a. Lènmi ou gade nan je ou ak eskente...',
      sv: 'Spektakulära mättade rosa plumes stiger från denna fasetterade prismiska pärla. Dina fiender att stirra på dig med vördnad ...',
      ko: '환상적인 포화 분홍색 깃털은이 면면체의 보석으로 유명합니다. 너의 대적이 경외심으로 너를 응시하는 ...',
      ro: 'Pene roz spectaculos saturate se ridică din această bijuterie prismică. Dușmanii tăi să se holbeze la tine cu venerație...',
      da: 'Spektakulære mættede lyserøde plumer stiger fra denne facetterede prismiske perle. Dine fjender til at stirre på dig med ærefrygt ...'
    }
  },

  {
    name       : {$$: 'Aeter' },
    description: {
      en: 'Bright green lights occasionally span out of this glass gem, casting projections of the wearer\'s future.',
      ru: 'Яркий зеленый свет иногда проливается из этого стеклянного камня, бросая проекции будущего для его владельца.',
      es: 'Las luces verdes vivo extienden a veces fuera de esta gema de cristal, proyecciones de fundición del futuro de los usuarios.',
      de: 'Strahlend grüne Lichter ragen gelegentlich aus diesem Glasjuwel heraus und werfen Projektionen der Zukunft der Träger hervor.',
      fr: 'De brillantes lumières vertes s\'étendent parfois à l\'extérieur de ce joyau de verre, montrant les projections de l\'avenir de ceux qui le portent.',
      el: 'Φωτεινά πράσινα φώτα περιστασιακά εκτείνονται από αυτό το γυάλινο κόσμημα χυτεύοντας προβολές του μέλλοντος των χρηστών.',
      bg: 'Ярко зелени светлини понякога се разпростират от прожекциите за оцветяване на бъдещето на носителите.',
      tl: 'Ang mga maliliwanag na berdeng ilaw ay paminsan-minsang lumalabas sa mga ito sa pag-iimbak ng salamin na ito ng mga projection ng mga nagsuot ng hinaharap',
      nl: 'Heldere groene lichten af en toe overspannen van deze glazen juweel, het gieten van projecties van de dragers de toekomst.',
      pl: 'Jasnozielone światło czasami rozprzestrzenia się z tego szklanego klejnotu, odlewając projekcje przyszłości użytkowników.',
      pt: 'Luzes verdes brilhantes ocasionalmente se estendem para fora desta jóia de vidro, projetando projeções de fundição do futuro dos usuários.',
      it: 'Le luci verdi brillanti di tanto in tanto si estendono da questa gemma di vetro, proiettando le proiezioni del futuro di chi la indossa.',
      hi: 'कभी कभी इस काँच की मणि से तेज़ हरी रोशनी निकलती है, जो धारक के भविष्य के बारे में बताती है।',
      cs: 'Z tohoto skleněného klenotu se občas rozprostírají jasně zelená světla.',
      ja: '鮮やかな緑色の光が時折着用者の将来のこのガラス宝石の鋳造物の投影から広がっています。',
      tr: 'Parlak yeşil ışıklar ara sıra, bu cam mücevherin dışına çıkmakta ve kullanıcıların gelecekteki hallerini yansıtmaktadır.',
      ht: 'Tenyen dènye limyè green Okazyonèlman pon nan gem vè sa a, al depoze vòt pwojèksyon yo nan pwochen porteurs.',
      sv: 'Ljusgröna lampor spänner ibland ut ur den här glasstenen, framkallning av bärarens framtid.',
      ko: '밝은 녹색 불빛이 때때로이 유리 쥬얼리에서 튀어 나와 착용자의 미래를 예측합니다.',
      ro: 'Lumini verzi strălucitoare ies ocazional din această bijuterie de sticlă, arătând proiecții despre viitorul purtătorilor.',
      da: 'Lys grønne lys spænder lejlighedsvist ud af denne glas perle, støber fremskrivninger af wearers fremtid.'
    }
  }
]
