export default [
  {
    name       : {$$: 'Broken Twig' },
    description: {
      en: 'Weapon forged by the greatest blacksmith of all the land. At least that\'s what we told little Timmy.',
      hi: 'क्षेत्र के सबसे महान लोहार द्वारा बनाया गया हथियार। नन्हें टिम्मी से तो हमने यही कहा।',
      ru: 'Оружие, выкованное величайшим кузнецом из всей земли. По крайней мере, так мы сказали маленькому Тимми.',
      es: 'Una arma forjado por el más grande herrero de la tierra. Al menos, eso es lo que dijimos a pequeño Timmy.',
      de: 'Die Waffe wurde vom größten Schmied des Landes geschmiedet. Zumindest haben wir dem kleinen Timmy das gesagt.',
      fr: 'Une arme forgée par le plus grand forgeron du pays. Du moins, c\'est ce qu\'on a dit au petit Timmy.',
      pt: 'Arma forjada pelo maior ferreiro de toda a terra. Pelo menos foi o que dissemos ao pequeno Timmy.',
      nl: 'Wapen gesmeed door de grootste smid van het land. Althans, dat is wat we kleine Timmy hebben verteld.',
      tl: 'Ang sandata ay hinubog ng pinakadakilang panday ng lahat ng lupain. Hindi bababa sa na kung ano ang sinabi namin maliit Timmy.',
      bg: 'Оръжие, изковано от най-големия ковач на цялата земя. Поне това каза на малко Тими.',
      el: 'Όπλο σφυρηλατημένο από τον μεγαλύτερο σιδηρουργό όλης της γης. Τουλάχιστον αυτό είναι αυτό που είπαμε λίγο Timmy.',
      pl: 'Broń wykuta przez największego kowala ze wszystkich ziem. Przynajmniej to samo powiedzieliśmy małemu Timmyemu.',
      it: 'Arma forgiata dal miglior fabbro di tutta la terra. Almeno questo è quello che abbiamo detto al piccolo Timmy.',
      cs: 'Zbraň kovaná největším kovářem celé země. Aspoň to jsme řekli málo Timmymu.',
      ja: 'すべての土地の最大の鍛冶屋によって作られた武器少なくともそれが私たちがトムに言ったことです。',
      ht: 'Zam fabrike pa pi fò forj nan tout peyi a. Omwen se sa ki nou te di ti Timmy.',
      sv: 'Vapen smidd av den största smeden av hela landet. Det var åtminstone det vi sa till Timmy.',
      ko: '모든 땅의 가장 큰 대장장이가 만든 무기. 적어도 우리가 티미에게 말한 것입니다.',
      ro: 'Armă făurită de cel mai bun fierar din țară. Cel puțin asta i-am spus micuțului Timmy.',
      tr: 'Bu topraklarda en iyi Demirci tarafından yapılan bir silah. En azından küçük Timmy\'ye böyle söyledik.',
      da: 'Våben smedet af den største smed af hele landet. Det var i hvert fald det, vi fortalte lille Timmy.'
    }
  },

  {
    name       : {$$: 'Cracked Stick' },
    description: {
      en: 'Desperate situations call for desperate measures.',
      hi: 'मुश्किल स्थितियों में मुश्किल फ़ैसले लेने पड़ते है।',
      ru: 'Отчаянные ситуации требуют отчаянных мер.',
      es: 'Las situaciones desesperadas requieren acciones desesperadas.',
      de: 'Verzweifelte Situationen erfordern verzweifelte Maßnahmen.',
      fr: 'Les situations désespérées exigent des mesures désespérées.',
      pt: 'Situações desesperadas exigem medidas desesperadas.',
      nl: 'Wanhopige situaties vragen om wanhopige maatregelen.',
      tl: 'Ang mga desperadong sitwasyon ay tumatawag para sa desperado na mga hakbang.',
      bg: 'Отчаяни ситуации изискват отчаяни мерки.',
      el: 'Οι απεγνωσμένες καταστάσεις απαιτούν απελπισμένα μέτρα.',
      pl: 'Zdesperowane sytuacje wymagają desperackich działań.',
      it: 'Situazioni disperate richiedono misure disperate.',
      cs: 'Zoufalé situace vyžadují zoufalá opatření.',
      ja: '絶望的な状況では、絶望的な対策が必要です。',
      ht: 'Sanzespwa sitiyasyon rele pou mezi dezespere.',
      sv: 'Desperata situationer kräver desperata åtgärder.',
      ko: '필사적 인 상황에서는 필사적 인 조치가 필요합니다.',
      ro: 'Situațiile disperate cer măsuri disperate.',
      tr: 'Umutsuz durumlar umutsuz önlemler için çağrı.',
      da: 'Desperate situationer kræver desperate foranstaltninger.'
    }
  },

  {
    name       : {$$: 'Gnarled Broomstick' },
    description: {
      en: 'Scruffy broomstick stolen from a mage. Gnarled and bony.',
      ru: 'Потрепанная метла украдена у мага. Корявая и костлявая.',
      hi: 'एक जादूगर से चुराया हुआ झाड़ू। हद्दीदार और गाँठिला।',
      es: 'Un palo de escoba desaliñado robado de un mago. Nudoso y huesudo.',
      de: 'Dreckiger Besenstiel, der einem Magier gestohlen wurde. Knurrig und knöchern.',
      fr: 'Un balai négligé volé à un mage. Noueux et osseux.',
      pt: 'Vassoura de vassoura roubada de um mago. Gnarradas e ossudas.',
      nl: 'Schrobbelige bezemsteel gestolen van een magiër. Knoestig en benig.',
      tl: 'Nakakagambala na tangkay ng walis na ninakaw mula sa isang salamangkero. Gnarled at bony.',
      bg: 'Мрачна метла, открадната от магьосник. Кокалест и кокалест.',
      el: 'Σκουρόχρωμη σκούπα που κλαπεί από έναν μάγο. Σκονισμένο και οστεώδες.',
      pl: 'Miotła skradziona z maga. Gnarled and bony.',
      it: 'Una robaccia trasandata rubata da un mago. Masticato e ossuto.',
      cs: 'Šupinatý košťátko ukradené z mága. Pokroucený a kostnatý.',
      ja: '魔術師から盗まれただらしないほうきぎざぎざと骨。',
      ht: 'Vakabon bale vòlè nan men yon maj. Gnarled ak zo.',
      sv: 'Smutsig kvast stulen från en mage. Gnarled och benig.',
      ko: '지저분한 빗자루가 마법사에게서 도난당했습니다. 뼈 아프다.',
      ro: 'Coadă de Mătură uzată furată de la un mag. Noduros și osos.',
      tr: 'Bir büyücüden çalınan çok yıpranmış bir süpürge çubuğu. kaba ve kemikli.',
      da: 'Beskidt pind af en kost, stjålet fra en mage. Gnarled og benet.'
    }
  },

  {
    name       : {$$: 'Oak Stave' },
    description: {
      en: 'A wand cut from the branches of an ancient oak. Infused with deep power.',
      hi: 'प्राचीन पेड की डाल से बनी छड़ी। विचित्र ताक़त से भारी हुई।',
      ru: 'Палочка, вырезанная из ветки древнего дуба. Обладает глубокой силой.',
      es: 'Una varita cortada de las ramas de un arce anciano. Tiene gran poder canadiense.',
      de: 'Ein Zauberstab, der aus den Zweigen einer kastanienbraunen Eiche geschnitten wurde. Durchdrungen von tiefer Kraft.',
      fr: 'Baguette coupée dans les branches d\'un chêne d\'ancien. Doté d\'une puissance profonde.',
      pt: 'Uma varinha cortada dos ramos de um antigo carvalho. Infundido com um poder profundo.',
      nl: 'Een toverstaf die uit de takken van een oude eik is gesneden. Doordrenkt met diepe kracht.',
      tl: 'Ang isang wand ay pinutol mula sa mga sanga ng isang sinaunang owk. Pinagsama sa malalim na kapangyarihan.',
      bg: 'Жезъл, отрязан от клоните на древен дъб. Влива се с дълбока сила.',
      el: 'Ένα ραβδί κομμένο από τα κλαδιά μιας αρχαίας βελανιδιάς. Εγχυθεί με βαθιά δύναμη.',
      pl: 'Rózga wycięta z gałęzi starożytnego dębu. Przepełniona głęboką mocą.',
      it: 'Una bacchetta ricavata dai rami di un\'antica quercia. Infuso di potinza profonda.',
      cs: 'Z větví starobylého dubu se vyřízne hůlka. Naplněný hlubokou silou.',
      ja: '古代のオークの枝から切り取った杖。深い力を注ぎ込んだ。',
      ht: 'Yon ralonj koupe soti nan branch yo nan yon pye bwadchenn ansyen. Enfuze ak pouvwa gwo twou san fon.',
      sv: 'En trollstav som klipps från en gammal eks grenar. Infunderad med djup kraft.',
      ko: '고대 참나무의 가지에서 잘라 지팡이. 깊은 힘이 스며 들었습니다',
      ro: 'O baghetă tăiată din ramurile unui stejar antic. Infuzată cu o putere profundă.',
      tr: 'Eski bir meşe dalından kesilmiş bir değnek. Bu asanın derin gücü var.',
      da: 'En tavle skåret fra grene af en gammel eg. Infunderet med dyb magt.'
    }
  },

  {
    name       : {$$: 'Mystic Wand' },
    description: {
      en: 'Mystical weapon glowing with a mysterious essence.',
      ru: 'Мистическое оружие, светящееся загадочной сущностью.',
      hi: 'रहस्यमयी संसार से चमकाने वाला रहस्यमयी हथियार।',
      es: 'Arma mística que brilla con una esencia misteriosa.',
      de: 'Mystische Waffe, die mit einer mysteriösen Essenz angestrahlt wird.',
      fr: 'Une arme mystique qui brille d\'une essence mystérieuse.',
      pt: 'Uma arma mística que brilha com uma essência misteriosa.',
      nl: 'Mystiek wapen dat gloeit met een mysterieuze essentie.',
      tl: 'Mystical na armas na kumikinang na may mahiwagang kakanyahan.',
      bg: 'Мистично оръжие, светещо с тайнствена същност.',
      el: 'Μυστικό όπλο που λάμπει με μια μυστηριώδη ουσία.',
      pl: 'Mistyczna broń świecąca tajemniczą esencją.',
      it: 'Un\'arma mistica che brilla di un\'essenza misteriosa.',
      cs: 'Mystická zbraň zářící tajemnou podstatou.',
      ja: '神秘的な武器が神秘的なエッセンスで輝いています。',
      ht: 'Zam mistik lumineux ak yon sans misterye.',
      sv: 'Mystiskt vapen glödande med en mystisk väsen.',
      ko: '신비한 본질로 빛나는 신비한 무기',
      ro: 'Armă mistică ce strălucește cu o esență misterioasă.',
      tr: 'Gizemli bir özü ile parlayan mistik silah.',
      da: 'Mystisk våben glødende med en mystisk essens.'
    }
  },

  {
    name       : {$$: 'Bone Stave' },
    description: {
      en: 'Nothing fancy about this weapon, just the femur of a lich.',
      ru: 'Ничего особенного в этом оружии, только бедро лича.',
      hi: 'कुछ ख़ास नहीं, बस एक लाश की हड्डी है।',
      es: 'Esta arma no tiene nada lujosa, sólo es el fémur de un liche',
      de: 'Nichts Besonderes an dieser Waffe, nur der Oberschenkelknochen eines Lichs.',
      fr: 'Cette arme n\'a rien d\'extravagant, c\'est juste le fémur d\'une liche.',
      pt: 'Nada de especial nesta arma, apenas o fémur de um líquen.',
      nl: 'Niets bijzonders aan dit wapen, slechts het dijbeen van een lich.',
      tl: 'Walang magarbong tungkol sa sandata na ito ang femur ng isang lich.',
      bg: 'Нищо необичайно за това оръжие, само за бедрената кост на лич.',
      el: 'Τίποτα δεν φαντάζεται γι \'αυτό το όπλο μόνο το μηριαίο υγρό.',
      pl: 'Nie ma nic ciekawego w tej broni, tylko kość udowa licha.',
      it: 'Non c\'e\' niente di speciale in quest\'arma, solo il femore di una lich.',
      cs: 'Na této zbrani není nic zajímavého, jen femur licha.',
      ja: 'この武器についての何も空想の大腿骨だけで空想はない。',
      ht: 'Pa gen anyen anpenpan sou sa a zam, jis femèl la nan yon lich.',
      sv: 'Inget fancy om det här vapnet, bara lårbenets lår.',
      ko: '이 무기에 대해 환상적인 것은 없으며, 리치의 대퇴골에 불과합니다.',
      ro: 'Nimic extravagant la această armă, doar femurul unui lich.',
      tr: 'Bu silah hakkında hiçbir şey fantezi. Sadece ölü bir canavardan bir kemik.',
      da: 'Intet fancy om dette våben, bare lårbenenes lår.'
    }
  },

  {
    name       : {$$: 'Encrusted Rod' },
    description: {
      en: 'Long rod with a shimmering blue gem on its crown.',
      ru: 'Длинная палочка с синим мерцающим драгоценным камнем на короне.',
      hi: 'नीले रंग के चमकीले सिरे वाली लम्बी छड़ी।',
      es: 'Varita larga, con una joya azul brillante en su corona.',
      de: 'Langer Stab, mit einem blau schimmernden Edelstein an der Krone.',
      fr: 'Longue baguette, avec une gemme bleue chatoyante à sa couronne.',
      pt: 'Vara comprida com uma gema azul cintilante na sua coroa.',
      nl: 'Lange staaf met een glinsterende blauwe edelsteen op zijn kroon.',
      tl: 'Long rod na may isang shimmering asul na mamahaling bato sa kanyang korona.',
      bg: 'Дълъг прът с блестящ син камък на короната си.',
      el: 'Μεγάλη ράβδος με ένα λαμπερό γαλάζιο κόσμημα στο στέμμα της.',
      pl: 'Długi kij z mieniącym się niebieskim klejnotem na koronie.',
      it: 'Asta lunga con una gemma blu scintillante sulla corona.',
      cs: 'Dlouhá tyč s třpytivým modrým drahokamem na korunce.',
      ja: 'その冠にきらめく青い宝石と長い棒。',
      ht: 'Long baton ak yon vè chatwi ble sou kouwòn li yo.',
      sv: 'Lång stång med en skimrande blå pärla på kronan.',
      ko: '그것의 크라운에 반짝임 파란 보석을 가진 긴 막대.',
      ro: 'Un toiag lung cu o bijuterie albastră sclipitoare pusă pe coroană.',
      tr: 'Taç üzerinde parıldayan mavi bir mücevher ile uzun çubuk.',
      da: 'Intet fancy om dette våben, bare lårbenenes lår.'
    }
  },

  {
    name       : {$$: 'Imbued Staff' },
    description: {
      en: 'Dark purple staff. Quite mysterious in its making, yet nice to look at.',
      ru: 'Темно-фиолетовый посох. Совершенно таинственного происхождения, но приятно смотреть на него.',
      hi: 'गहरी बैंगनी छड़ी। इसकी बनावट रहस्यमयी है, पर छड़ी बड़ी ख़ूबसूरत है।',
      es: 'Varita morado oscuro. Bastante misteriosa en su fabricación, pero agradable para ver.',
      de: 'Dunkelvioletter Stab. Ziemlich mysteriös in seiner Entstehung, aber schön anzusehen.',
      fr: 'Bâton violet foncé. Assez mystérieux dans sa fabrication, mais agréable à regarder.',
      pt: 'Cajado roxo escuro. Bastante misterioso na sua criação, mas agradável de se ver.',
      nl: 'Donkerpaarse toverstaf. Vrij mysterieus in hoe het gemaakt is, maar leuk om naar te kijken.',
      tl: 'Madilim na lilang staff. Masyadong mahiwaga sa paggawa nito pa maganda upang tumingin sa.',
      bg: 'Тъмно лилав персонал. Съвсем загадъчна в създаването й, но е хубаво да се погледне.',
      el: 'Σκούρο μωβ προσωπικό. Πολύ μυστηριώδης στο να κάνει ακόμα ωραίο να κοιτάξει κανείς.',
      pl: 'Ciemnofioletowa laska. Całkiem tajemnicza w tworzeniu, ale miła w spojrzeniu.',
      it: 'Bacchetta viola scuro. Piuttosto misterioso nella sua struttura, ma bello da vedere',
      cs: 'Tmavě fialový štáb. Zcela záhadné v jeho tvorbě, ale pěkné na to dívat.',
      ja: '濃い紫色のスタッフ。その作り方はとても不思議ですが、見るのはいいですね。',
      ht: 'Anplwaye twal koulè wouj violèt. Byen misterye nan fè li yo, men bèl gade.',
      sv: 'Mörk lila personal. Ganska mystisk när det gäller att göra, men ändå trevligt att titta på.',
      ko: '어두운 보라색 직원. 그것의 만드는 것에있는 확실히 신비한, 그러나 보는 것은 좋다.',
      ro: 'Toiag purpuriu închis. Destul de misterios în fabricare, dar e frumos să te uiți la el.',
      tr: 'Koyu mor. Yapımında oldukça gizemli, henüz bakmak güzel.',
      da: 'Mørk lilla personale. Helt mystisk i sin fremstilling, men godt at se på.'
    }
  },

  {
    name       : {$$: 'Emerald Staff' },
    description: {
      en: 'Constructed from emeralds stolen from the mountain dwarves.',
      ru: 'Создан из изумрудов украденных у горных дворфов.',
      hi: 'पहाड़ बौने से चोरी किए पन्नो से रची।',
      es: 'Construido de esmeraldas robadas de los enanos de las montañas.',
      de: 'Gebaut aus Smaragden, die den Bergweibchen gestohlen wurden.',
      fr: 'Construit à partir d\'émeraudes volées aux nains des montagnes.',
      pt: 'Construído a partir de esmeraldas roubadas dos anões das montanhas.',
      nl: 'Gemaakt van gestolen smaragden van de bergdwergen.',
      tl: 'Itinayo mula sa mga emeralds na ninakaw mula sa mga dwarve ng bundok.',
      bg: 'Построен от изумруди, откраднати от планинските джуджета.',
      el: 'Κατασκευασμένο από σμαράγδια κλεμμένα από τους νάνους των βουνών.',
      pl: 'Zbudowany z szmaragdów skradzionych z krasnali górskich.',
      it: 'Costruito con smeraldi rubati ai nani di montagna.',
      cs: 'Vyrobeno ze smaragdů ukradených z horských trpaslíků.',
      ja: '山の小人から盗まれたエメラルドから作られました。',
      ht: 'Konstwi soti nan emrod yo vòlè li soti nan nen yo mòn.',
      sv: 'Konstruerad från smaragder som stulits från bergsdvärgarna.',
      ko: '산 드워프에서 도난당한 에메랄드로 만들어졌습니다.',
      ro: 'Construit din smaralde furate de la piticii de munte.',
      tr: 'Dağ cücelerinden çalınan zümrütlerden inşa edilmiştir.',
      da: 'Konstrueret fra smaragder stjålet fra bjergdværgerne.'
    }
  },

  {
    name       : {$$: 'Sapphire Staff' },
    description: {
      en: 'Strange... the staff seems... triangular...',
      ru: 'Странно... посох кажется... треугольным...',
      hi: 'अजीब... छड़ी लगती है... त्रिकोणीय...',
      es: 'Extraño... el bastón parece... triangular...',
      de: 'Seltsam... der Stab scheint... dreieckig...',
      fr: 'Bizarre... le bâton semble... triangulaire...',
      pt: 'Estranho... o bastão parece... triangular...',
      nl: 'Vreemd... de toverstaf lijkt... driehoekig...',
      tl: 'Kakaiba ... tila ang kawani ... tatsulok ...',
      bg: 'Странно ... персоналът изглежда ... триъгълна ...',
      el: 'Παράξενη ... το προσωπικό φαίνεται ... τριγωνικό ...',
      pl: 'Dziwne... personel wydaje się... trójkątny...',
      it: 'Strano... il personale sembra... triangolare...',
      cs: 'Podivné ... personál se zdá ... trojúhelníkový ...',
      ja: '奇妙な...スタッフは...三角形のようです...',
      ht: 'Etranj ... anplwaye a sanble... triyangilè...',
      sv: 'Konstigt ... personalen verkar... triangulär...',
      ko: '이상합니다 ... 직원들은 ... 삼각형 인 것 같습니다...',
      ro: 'Straniu... toiagul pare... triunghiular...',
      tr: 'Garip... bu görünüyor... üçgen şeklinde...',
      da: 'Mærkeligt ... personalet synes ... trekantede ...'
    }
  },

  {
    name       : {$$: 'Frozen Greatstaff' },
    description: {
      en: 'Eccentric rod with a pale blue stone embedded inside...',
      ru: 'Эксцентриковый стержень с бледно-голубым камнем, встроенным внутрь...',
      hi: 'फ़िके नीले पत्थर से जड़ी अजीबो-ग़रीब छड़ी।',
      es: 'Vara excéntrica con una piedra azul pálido incrustado al interior...',
      de: 'Exzentrische Stange mit einem hellblauen Stein, der innen eingebettet ist...',
      fr: 'Tige excentrique avec une pierre bleu pâle incrustée à l\'intérieur...',
      pt: 'Vara excêntrica com uma pedra azul pálida embutida no interior...',
      nl: 'Excentrieke staaf met een lichtblauwe steen ingebed in de kern...',
      tl: 'Eccentric rod na may isang maputla asul na bato na naka-embed sa loob ng ...',
      bg: 'Ексцентричен прът с бледосин камък, вграден вътре ...',
      el: 'Εκκεντρική ράβδος με μπλε μπλε πέτρα ενσωματωμένη μέσα ...',
      pl: 'Ekscentryczny pręt z jasnoniebieskim kamieniem osadzonym w środku...',
      it: 'Asta eccentrica con una pietra azzurra incastonata all\'interno...',
      cs: 'Výstředná tyč s bledě modrým kamenem vloženým dovnitř ...',
      ja: '内側に淡いブルーの石が埋め込まれた偏心ロッド',
      ht: 'Inik baton ak yon wòch ble pal anndan ...',
      sv: 'Excentrisk stång med en ljusblå sten inbäddad inuti ...',
      ko: '내부에 옅은 푸른 색 돌이 달린 괴상한 막대가 ...',
      ro: 'Un toiag excentric cu o piatră albastră pală încorporată înăuntru...',
      tr: 'İçinde gömülü soluk mavi taşlı eksantrik çubuk.',
      da: 'Ekscentrisk stang med en lyseblå sten indlejret indeni ...'
    }
  },

  {
    name       : {$$: 'Infernal Staff' },
    description: {
      en: 'Constructed by unknown blacksmiths residing in fabled valleys.',
      ru: 'Сконструирован неизвестными кузнецами, живущими в сказочных долинах.',
      hi: 'पौराणिक घाटियों में रहने वाले गुप्त लोहारो द्वारा निर्मित।',
      es: 'Construido por herreros desconocidos que residen en valles legendarios.',
      de: 'Erbaut von unbekannten Schmieden, die in sagenumwobenen Tälern leben.',
      fr: 'Confectionné par des forgerons inconnus résidant dans des vallées légendaires.',
      pt: 'Construído por ferreiros desconhecidos que residem em vales lendários.',
      nl: 'Gebouwd door onbekende smeden gevestigd in fabelachtige valleien.',
      tl: 'Itinayo ng mga di-kilalang mga panday na naninirahan sa mga kambal na mga lambak.',
      bg: 'Изградени от неизвестни ковачи, пребиваващи в легендарни долини.',
      el: 'Κατασκευάστηκε από άγνωστους σιδεράδες που κατοικούν σε γνωστές κοιλάδες.',
      pl: 'Zbudowany przez nieznanych kowali mieszkających w legendarnych dolinach.',
      it: 'Costruito da fabbri sconosciuti che risiedono in valli favolose.',
      cs: 'Postaveny neznámými kováři sídlícími v legendárních údolích.',
      ja: '伝説の谷間に住む未知の鍛冶屋によって造られました。',
      ht: 'Konstwi pa fòjere unknown ki abite nan vale ladann.',
      sv: 'Konstruerad av okända smeden som bor i fableda dalar.',
      ko: '전설적인 계곡에 거주하는 알려지지 않은 대장장이들에 의해 건축되었습니다.',
      ro: 'Construit de fierari necunoscuți ce locuiesc în văi legendare.',
      tr: 'Efsanevi vadilerde yaşayan bilinmeyen demirciler tarafından inşa edilmiştir.',
      da: 'Konstrueret af ukendte smedere, der bor i fabelagtige dale.'
    }
  },

  {
    name       : {$$: 'Hellfire Greatstaff' },
    description: {
      en: 'Its beauty calls out to you... to kill... to conquer...',
      ru: 'Его красота призывает тебя... убивать... побеждать...',
      hi: 'इतनी सुंदर... आपको बुलाती है... मरने के लिए... जीतने के लिए...',
      es: 'Su belleza te llama... a matar... a conquistar...',
      de: 'Seine Schönheit ruft nach dir, zu töten, zu erobern...',
      fr: 'Sa beauté vous ordonne... de tuer... de conquérir...',
      pt: 'A sua beleza chama-te... para matar... para conquistar...',
      nl: 'Haar schoonheid roept om jou.... om te doden... om te overwinnen...',
      pl: 'Jego piękno wzywa do ciebie... zabić... podbić...',
      tl: 'Ang kagandahan nito ay tumatawag sa iyo ... upang patayin ... upang masakop ...',
      bg: 'Нейната красота ви призовава ... да убива ... да завладее ...',
      el: 'Η ομορφιά της καλεί σε σας ... να σκοτώσει ... για να κατακτήσει ...',
      it: 'La sua bellezza vi invita ad uccidere... a conquistare...',
      cs: 'Její krása vás volá ... zabít ... dobýt ...',
      ja: 'その美しさはあなたに声をかけます...殺すために...征服するために...',
      ht: 'Bote li apèl soti nan ou ... yo touye ... konkeri ...',
      sv: 'Dess skönhet kallar till dig ... att döda ... för att erövra ...',
      ko: '그 아름다움은 당신을 부른다 ... 죽이기 위해서 ... 정복하기 위해 ...',
      ro: 'Frumusețea lui te cheamă... pentru a ucide... pentru a cuceri...',
      tr: 'Güzelliği size sesleniyor...öldürmek...fethetmek...',
      da: 'Dens skønhed opfordrer til dig ... at dræbe ... for at erobre ...'
    }
  },

  {
    name       : {$$: 'Divine Staff' },
    description: {
      en: 'A staff stolen from the angels. They\'re still hunting for it.',
      ru: 'Посох, украденный у ангелов. Они все еще охотятся за ним.',
      hi: 'फ़रिश्तों से चुराई छड़ी। वे इसे अभी भी ढूँढ रहे है।',
      es: 'Un bastón robado de los ángeles. Ellos todavía lo están buscándolo.',
      de: 'Ein Stab, der von den Engeln gestohlen wurde. Sie sind immer noch auf der Jagd danach.',
      fr: 'Un bâton volé aux anges. Ils sont toujours à sa recherche.',
      pt: 'Um bastão roubado aos anjos. Eles ainda estão caçando por isso.',
      nl: 'Een staf gestolen van de engelen. Ze zijn er nog steeds naar op zoek.',
      tl: 'Isang kawani na ninakaw mula sa mga anghel. Sila pa rin ang hunting para dito.',
      bg: 'Персонал, откраднат от ангелите. Те все още го търсят.',
      el: 'Ένα προσωπικό κλεμμένο από τους αγγέλους. Είναι ακόμα το κυνήγι για αυτό.',
      pl: 'Personel skradziony aniołom. Nadal na niego polują.',
      it: 'Uno staff rubato dagli angeli. Sono ancora a caccia di esso.',
      cs: 'Zaměstnanci ukradli anděly. Stále na to hledají.',
      ja: 'スタッフが天使たちから盗まれました。彼らはまだそれを探しています。',
      ht: 'Yon anplwaye yo vòlè li nan men zanj Bondye yo. Yo ap toujou lachas pou li.',
      sv: 'En personal som stulits från änglarna. De letar fortfarande efter det.',
      ko: '직원이 천사들로부터 도난당했습니다. 그들은 아직도 그것을 찾고 있습니다.',
      ro: 'Un toiag furat de la îngeri. Încă îl mai caută.',
      tr: 'Meleklerden çalındı. Hala onu arıyorlar.',
      da: 'Et personale stjålet fra englene. De er stadig på jagt efter det.'
    }
  },

  {
    name       : {$$: 'Crystal Core' },
    description: {
      en: 'Crude in its looks, yet mighty at its heart...',
      ru: 'Грубая внешность, но могущественная в глубине его сердца...',
      hi: 'दिखने में कच्चा पर दिल से महान...',
      es: 'Crudo en su aspecto, pero poderoso en su corazón...',
      de: 'Grob in seinem Aussehen, aber mächtig in seinem Herzen...',
      fr: 'Brut dans son apparence, mais puissant dans son cœur...',
      pt: 'Cruéis na sua aparência, mas poderosos no seu coração...',
      nl: 'Ruw in zijn uiterlijk, maar machtig in zijn hart...',
      tl: 'Crude sa kanyang hitsura pa makapangyarihan sa kanyang puso ...',
      bg: 'Сурови по вид, все още силен в сърцето си ...',
      el: 'Ακατέργαστο στα βλέμματά του, ακόμα ισχυρό στην καρδιά του ...',
      pl: 'Surowy w swoim wyglądzie, ale potężny w swoim sercu...',
      it: 'Raw in his appearance, but powerful in his heart...',
      cs: 'Surový v jeho vzhledu, ale mocný v srdci ...',
      ja: 'その見た目は粗いが、その中心部は強大な...',
      ht: 'Brut nan sanble li yo, men vanyan sòlda nan kè li ...',
      sv: 'Rå i sitt utseende, men mäktigt i sitt hjärta ...',
      ko: '그것의보기에있는 조잡한, 그러나 그것의 심혼에 강 대한 ...',
      ro: 'Crud în aspectul său, dar puternic în inima sa...',
      tr: 'İlkel görünüyor, ama güçlü bir kalbi var.',
      da: 'Rå i sit udseende, men alligevel mægtig i sit hjerte ...'
    }
  },

  {
    name       : {$$: 'Witch\'s Heart' },
    description: {
      en: 'We are told it\'s core is from the heart of a witch. No one has found the corpse. Or the staff itself.',
      ru: 'Нам говорят, что его ядро взято из сердца ведьмы​. Но никто не нашел труп. Или сам посох.',
      hi: 'कहते है इसका मूल एक दायाँ के दिल से बना है। उसकी लाश आज तक नहीं मिली। ना ही ये छड़ी मिली।',
      es: 'Se nos dice que su núcleo es del corazón de una bruja. Nadie ha encontrado el cadáver. O el varita sí mismo.',
      de: 'Uns wurde gesagt, dass sein Kern aus dem Herzen einer Hexe stammt. Niemand hat die Leiche gefunden. Oder das Personal selbst.',
      fr: 'On nous dit que son coeur est celui d\'une sorcière. Personne n\'en a retrouvé le cadavre. Ou la baguette elle-même.',
      pt: 'Dizem-nos que o seu núcleo é do coração de uma bruxa. Ninguém encontrou o cadáver. Ou o próprio cajado.',
      nl: 'Ons is verteld dat de kern uit het hart van een heks komt. Niemand heeft het lijk gevonden. Of het toverstaf zelf.',
      tl: 'Sinabihan kami na ang core nito ay mula sa puso ng isang bruha. Walang nasumpungan ang bangkay. O ang kawani mismo.',
      bg: 'Казва ни се, че ядрото му е от сърцето на вещица. Никой не е намерил трупа. Или самият персонал.',
      el: 'Μας λένε ότι ο πυρήνας της είναι από την καρδιά μάγισσας. Κανείς δεν βρήκε το πτώμα. Ή το ίδιο το προσωπικό.',
      pl: 'Powiedziano nam, że jego rdzeń pochodzi z serca czarownicy. Nikt nie znalazł zwłok. Albo sam personel.',
      it: 'Ci hanno detto che il cuore di una strega è il cuore di una strega. Nessuno ha trovato il cadavere. O il personale stesso.',
      cs: 'Říká se, že jádro je ze srdce čarodějnice. Nikdo nenašel mrtvolu. Nebo samotný personál.',
      ja: 'その核心は魔女の心に由来すると言われています。誰も死体を見つけたことがない。またはスタッフ自身。',
      ht: 'Nou te di nwayo li se soti nan kè a nan yon sòsyè. Pa gen moun ki jwenn kadav la. Oswa pèsonèl la tèt li.',
      sv: 'Vi får höra det är kärnan är från hjärtat av en häxa. Ingen har hittat liket. Eller personalen själv.',
      ko: '우리는 그것이 핵심이 마녀의 심장에서 온 것이라고 말합니다. 아무도 시체를 발견하지 못했습니다. 또는 직원 자체.',
      ro: 'Ni s-a spus că nucleul provine din inima unei vrăjitoare. Nimeni nu a găsit cadavrul. Sau toiagul în sine.',
      tr: 'Çekirdeğin bir cadının kalbinden geldiğini söylüyorlar. Cesedi kimse bulamadı.',
      da: 'Vi får at vide, at kernen er fra hjertet af en heks. Ingen har fundet liget. Eller personalet selv.'
    }
  },

  {
    name       : {$$: 'Deathweaver' },
    description: {
      en: 'This weapon is so secretive that the few who wield it have killed all that know of it.',
      ru: 'Это оружие настолько скрытно, что те, кто владеют им, убили всех, кто о нем знает.',
      hi: 'एक हथियार, इतना गुप्त की जिन गिने चुने लोगों ने इसे धारण किया है, उन्होंने सब कुछ तबाह कर दिया।',
      es: 'Esta arma es tan reservado que los pocos que empuña han matado todas que saber de su existencia.',
      de: 'Diese Waffe ist so geheimnisvoll, dass die wenigen, die sie führen, alle getötet haben, die von ihr wissen.',
      fr: 'Cette arme est si secrète que les quelques personnes qui la manient ont tué tous ceux qui étaient au courant de son existence.',
      pt: 'Esta arma é tão secreta que os poucos que a empunham mataram todos os que a conhecem.',
      nl: 'Dit wapen is zo geheimzinnig dat de paar die het dragen iedereen gedood hebben die er vanaf weten.',
      tl: 'Ang sandata na ito ay sobrang lihim na ang ilan na gumagamit nito ay pumatay ng lahat ng alam nito.',
      bg: 'Това оръжие е толкова потаен, че малцината, които я притежават, са убили всички, които знаят за него.',
      el: 'Αυτό το όπλο είναι τόσο μυστικοπαθές που οι λίγοι που τον χειρίζονται σκότωσαν όλα όσα το γνωρίζουν.',
      pl: 'Ta broń jest tak tajemnicza, że ci, którzy nią rządzą, zabili wszystko, co o niej wiedzą.',
      it: 'Quest\'arma è così segreta che i pochi che la maneggiano hanno ucciso tutti coloro che ne sono a conoscenza.',
      cs: 'Tato zbraň je tak utajená, že těch pár, kteří ji ovládají, zabila všechny, kdo o ní vědí.',
      ja: 'この武器は非常に秘密主義であるため、それを使用した少数の人々はそれを知っているすべての人を殺した。',
      ht: 'Sa a zam se konsa sekrè ke kèk nan yo ki ègzamen li te touye tout moun ki konnen li.',
      sv: 'Detta vapen är så hemligt att de få som använder det har dödat allt som känner till det.',
      ko: '이 무기는 너무 비밀 스럽기 때문에 그것을 사용하는 소수만이 알고있는 모든 것을 죽였습니다.',
      ro: 'Această armă este atât de secretoasă încât puținii care o posedă au ucis tot ce se știa despre ea.',
      tr: 'Çok gizli. Bunu çok az kişi kullandı ve onu kullananlar, yolundaki her şeyi öldürdüler.',
      da: 'Dette våben er så hemmelighedsfuldt, at de få, der bruger det, har dræbt alt, hvad der kender til det.'
    }
  }

]
