export default [
  { // T1 item name. names are english only!
    name       : {$$: 'Wooden Sword' },
    // Item description
    description: {
      en: 'Name says it all. Careful of the splinters.',
      ru: 'Имя говорит само за себя. Остерегайтесь заноз.',
      es: 'El nombre lo dice todo. Ten cuidado de las astillas.',
      de: 'Der Name sagt alles. Vorsicht mit den Splittern.',
      fr: 'Le nom en dit long. Attention aux échardes.',
      hi: 'नाम ही काफ़ी है। छितरों से बचे।',
      tl: 'Sinasabi ng lahat ng pangalan. Mag-ingat sa mga splinters.',
      bg: 'Името казва всичко. Внимавайте с трески.',
      el: 'Το όνομα λέει όλα. Προσέξτε τα θραύσματα.',
      pt: 'O nome diz tudo. Cuidado com as lascas.',
      nl: 'De naam zegt het allemaal. Voorzichtig met de splinters.',
      pl: 'Imię mówi wszystko. Uważaj na drzazgi.',
      ht: 'Non di li tout. Atansyon ak ekla yo.',
      it: 'Il nome dice tutto. Attento alle schegge.',
      cs: 'Jméno říká všechno. Pozor na třísky.',
      ja: '名前はそれをすべて言います。破片の注意が必要です。',
      sv: 'Namnet säger allt. Var försiktig med splinterna.',
      ko: '이름은 그것을 모두 말한다. 파편을 조심하십시오.',
      ro: 'Numele spune totul. Ai grijă la așchii.',
      tr: 'Adı her şeyi söylüyor. Dikkatli olun yoksa kıymık batabilir.',
      da: 'Navnet siger alt. Pas på splinterne.'
    }
  },

  {
    name       : {$$: 'Rusty Ironsword' },
    description: {
      en: 'Not much better than a blunt piece of wood in my opinion.',
      ru: 'Не намного лучше, чем тупой кусок дерева, на мой взгляд.',
      fr: 'À peine meilleure qu\'un morceau de bois émoussé, à mon humble avis.',
      es: 'No es mucho mejor que un trozo de madera en mi opinión.',
      de: 'Nicht viel besser als ein stumpfes Stück Holz, denke ich.',
      hi: 'मरी राय में यह लकड़ी के कुंद टुकड़े से बेहतर नहीं है।',
      pt: 'Não é muito melhor do que um pedaço de madeira na minha opinião.',
      nl: 'Niet veel beter dan een stomp stuk hout naar mijn mening.',
      tl: 'Hindi mas mahusay kaysa sa isang mapurol piraso ng kahoy sa aking opinyon.',
      bg: 'По мое мнение не е много по-добре от едно парче дърво.',
      el: 'Όχι πολύ καλύτερα από ένα αμβλύ κομμάτι ξύλου κατά τη γνώμη μου.',
      pl: 'Niewiele lepiej niż tępy kawałek drewna, moim zdaniem.',
      ht: 'Pa pi bon pase yon moso bwa ki pa bay tèt ou pwoblèm nan opinyon mwen.',
      it: 'Secondo me non molto meglio di un pezzo di legno smussato.',
      cs: 'Podle mého názoru není o moc lepší než tupý kus dřeva.',
      ja: '私の意見では鈍い木の部分よりもずっと良くはありません。',
      sv: 'Inte mycket bättre än ett trubbigt träslag enligt min åsikt.',
      ko: '내 의견으로는 뭉툭한 나무 조각보다 낫지 않습니다.',
      ro: 'Nu cu mult mai bun decât o bucată de lemn tocit, în opinia mea.',
      tr: 'Bence körelmiş bir ahşap parçasından çok da iyi değil.',
      da: 'Ikke meget bedre end et stumt stykke træ efter min mening.'
    }
  },

  {
    name       : {$$: 'Troll Blade' },
    description: {
      en: 'Am I being pranked?',
      ru: 'Меня тролят?',
      es: '¿Estoy siendo bromado?',
      de: 'Werde ich verarscht?',
      fr: 'Suis-je victime d\'une farce?',
      hi: 'मज़ाक़ कर रहो हो?',
      pt: 'Estou a ser enganado?',
      nl: 'Word ik voor de gek gehouden?',
      pl: 'Czy jestem żartobliwy?',
      tl: 'Ako ba ay pranked?',
      bg: 'Някой да не ме троли?',
      el: 'Είμαι φάρσα;',
      ht: 'Èske mwen te pranked?',
      it: 'Sono stato fregato?',
      cs: 'Jsem zmatený?',
      ja: '私はいたずらですか？',
      sv: 'Blir jag lurad?',
      ko: '내가 장난하는거야?',
      ro: 'Asta e o glumă?',
      tr: 'Trolleniyor muyum?',
      da: 'Bliver jeg trollet?'
    }
  },

  {
    name       : {$$: 'Broadsword' },
    description: {
      en: 'Some knight dropped this. Probably unintentionally.',
      ru: 'Какой-то рыцарь бросил это. Вероятно, непреднамеренно.',
      fr: 'Un chevalier a lâché cette épée. Probablement par accident.',
      es: 'Un caballero la dejó caer. Probablemente por accidente',
      de: 'Ein Ritter hat das fallen lassen. Wahrscheinlich unbeabsichtigt.',
      hi: 'किसी शूरवीर से गिर गयी। ग़लती से।',
      pt: 'Um cavaleiro qualquer deixou cair isto. Provavelmente não intencionalmente.',
      nl: 'Een of andere ridder heeft dit laten vallen. Waarschijnlijk onbedoeld.',
      tl: 'Bumagsak ito ng ilang kabalyero. Marahil hindi sinasadya.',
      bg: 'Някой рицар се е отказал от това. Вероятно неволно.',
      el: 'Κάποιος ιππότης έπεσε αυτό. Πιθανώς ακούσια.',
      pl: 'Jakiś rycerz to upuścił. Prawdopodobnie nieumyślnie.',
      ht: 'Gen kèk Knight tonbe sa a. Pwobableman san entansyon',
      it: 'Qualche cavaliere ha lasciato cadere questo. Probabilmente non intenzionalmente.',
      cs: 'Někteří rytíři to upustili. Pravděpodobně neúmyslně.',
      ja: 'いくつかの騎士はこれを落としました。意図的ではないと思われます。',
      sv: 'En del riddare släppte detta. Förmodligen oavsiktligt.',
      ko: '어떤 기사가 이것을 떨어 뜨 렸습니다. 아마도 우연히.',
      ro: 'Un cavaler a scăpat asta. Probabil neintenționat.',
      tr: 'Bir şövalye bunu düşürdü. Muhtemelen bilerek değil.',
      da: 'Nogle ridder faldt dette. Sandsynligvis utilsigtet.'
    }
  },

  {
    name       : {$$: 'Longsword' },
    description: {
      en: 'Long? Yes. Deadly? Maybe. Just don\'t cut yourself.',
      ru: 'длинный? да. Смертельный? Может быть. Только не порежься.',
      fr: 'Longue? Oui. Mortelle? Peut-être. Évite de te couper pas avec.',
      es: '¿Largo? Sí. ¿Mortal? Tal vez. No te cortes.',
      de: 'Lang? Ja. Tödlich? Vielleicht. Schneidet euch nur nicht selbst.',
      hi: 'लम्बी? हाँ। जानलेवा? शायद। बस ख़ुद को मत काट लेना।',
      pt: 'Longo? Sim. Mortal? Talvez. Apenas não se corte.',
      nl: 'Lang? Ja. Dodelijk? Misschien. Gewoon jezelf niet snijden.',
      tl: 'Matagal? Oo. Nakamamatay? Siguro. Huwag lamang i-cut ang iyong sarili.',
      bg: 'Дълъг? Да. Смъртоносен? Може би. Просто не се порязвайте.',
      el: 'Μακρύς? Ναί. Θανάσιμα? Μπορεί. Απλά δεν κόβετε τον εαυτό σας.',
      pl: 'Długo? Tak. Śmiertelnie? Może. Tylko się nie skalecz.',
      ht: 'Lontan? Wi. Mòtèl? Petèt. Jis pa koupe tèt ou.',
      it: 'Lungo? Sì. Mortale? Può essere. Non ti tagliare.',
      cs: 'Dlouho? Ano. Smrtící? Možná. Prostě se neřízni.',
      ja: '長いです？はい。致命的？多分。ただ自分を切らないでください。',
      sv: 'Lång? Ja. Dödligt? Kanske. Skär inte dig själv.',
      ko: '긴? 예. 치명적인? 아마도. 그냥 자르지 마.',
      ro: 'Lungă? Da. Mortală? Poate. Doar ai grijă să nu te tai.',
      tr: 'Uzun? Evet. Ölümcül? Belki. Sadece kendini kesme.',
      da: 'Lang? Ja. Dødelig? Måske. Skær bare ikke dig selv.'
    }
  },
  {
    name       : {$$: 'Gladius' },
    description: {
      en: 'Crudely carved from the bones of an ancient behemoth.',
      ru: 'Грубо вырезанный из кости древнего чудища',
      es: 'Crudamente tallado de los huesos de un antiguo gigante.',
      de: 'Grob geschnitten aus den Knochen eines alten Riesen.',
      fr: 'Sculptée grossièrement dans les os d\'un monstre ancien.',
      hi: 'प्राचीन बेहेमोथ की हड्डियों से तराशी हुई।',
      pt: 'Esculpido grosseiramente nos ossos de um antigo beemote.',
      nl: 'Ruw gesneden uit de botten van een oude kolos.',
      tl: 'Crudely inukit mula sa mga buto ng isang sinaunang behemoth.',
      bg: 'Грубо издълбани от костите на древен гигант.',
      el: 'Σκουριασμένο από τα οστά ενός αρχαίου μεγαθήρου.',
      pl: 'Wycięte z kości starożytnego olbrzyma.',
      ht: 'Crudely so soti nan zo yo nan yon behemoth ansyen.',
      it: 'Crudamente scolpito dalle ossa di un antico behemoth.',
      cs: 'Krutě vyřezaný z kostí starověkého monstra.',
      ja: '古代の巨獣の骨から粗く彫られています。',
      sv: 'Bruten skuren från benen av en gammal behemoth.',
      ko: '고대 거물의 뼈에서 날카롭게 새겨 져있다.',
      ro: 'Sculptată grosolan din oasele unui monstru behemoth.',
      tr: 'Antik bir yaratığın kemiğinden kabaca oyulmuş.',
      da: 'Grovt skåret ud af knoglerne i en gammel behemoth.'
    }
  },
  {
    name       : {$$: 'Greatsword' },
    description: {
      en: 'A sword so mighty that few can handle it. It\'s pretty heavy.',
      ru: 'Меч такой могущественный, что немногие могут с ним справиться. Довольно тяжелый.',
      es: 'Una espada tan grande que la mayoría no puede usarla. Es muy pesada',
      de: 'Ein Schwert, das so mächtig ist, dass nur wenige damit umgehen können. Es ist ziemlich schwer.',
      fr: 'Une épée si puissante que peu de gens peuvent la manier. Elle est assez lourde.',
      hi: 'एक तलवार इतनी महान, कुछ ही लोग इसे नियंत्रित कर सकते है। काफ़ी भारी है।',
      pt: 'Uma espada tão poderosa que poucos conseguem lidar com ela. É muito pesada.',
      nl: 'Een zwaard dat zo machtig is dat weinigen het aankunnen. Het is behoorlijk zwaar.',
      tl: 'Isang tabak kaya makapangyarihan na ilang maaaring hawakan ito. Napakaganda nito.',
      bg: 'Толкова могъщ меч, че малцина могат да се справят с него. Доста тежи.',
      el: 'Ένα τόσο ισχυρό σπαθί που ελάχιστοι μπορούν να το χειριστούν. Είναι πολύ βαρύ.',
      pl: 'Miecz tak potężny, że niewielu zdoła sobie z nim poradzić. Jest dość ciężki.',
      ht: 'Yon epe konsa vanyan sòlda ke kèk ka okipe li. Li trè lou',
      it: 'Una spada così potente che pochi riescono a gestirlo. È piuttosto pesante.',
      cs: 'Meč tak mocný, že to zvládne jen málo. Je to dost těžké.',
      ja: '刀はとても強力で、それを扱うことができる人はほとんどいない。そのかなり重いです。',
      sv: 'Ett svärd så mäktigt att få kan hantera det. Det är ganska tungt.',
      ko: '몇 명만이 그것을 처리 할 수있는 강력한 칼. 꽤 무거워.',
      ro: 'O sabie atât de puternică încât puțini o pot mânui. E destul de grea.',
      tr: 'O kadar güçlü bir kılıç ki, sadece bazı kişiler kullanabilir. Oldukça ağır.',
      da: 'Et sværd så mægtigt, at få kan klare det. Det er ret tungt.'
    }
  },
  {
    name       : {$$: 'Nullfire Sword' },
    description: {
      en: 'Diabolical curved blade. Even holding it makes you feel its dark essence.',
      ru: 'Дьявольское изогнутое лезвие. Когда вы его держите, вы чувствуете его темную сущность.',
      es: 'Es una diabla curva. Incluso sostenerlo te hace sentir su oscura esencia.',
      de: 'Diabolisch geschwungene Klinge. Schon beim Halten spürt man seine dunkle Essenz.',
      fr: 'Lame diabolique incurvée. Juste la tenir vous fait sentir son aura sombre.',
      hi: 'दुष्ट टेढ़ी तलवार। पकड़ने से ही इसकी दुष्टता का एहसास होता है।',
      pt: 'Lâmina curva diabólica. Mesmo segurando-a faz você sentir a sua essência escura.',
      nl: 'Duivels gebogen zwaard. Zelfs het vasthouden ervan maakt dat je de donkere essentie voelt.',
      tl: 'Diabolical curved blade. Kahit na humahawak ito ginagawang pakiramdam mo ang madilim na kakanyahan.',
      bg: 'Дяволски извито острие. Дори само да го подържите, ще почувствате неговата тъмна същност.',
      el: 'Διαβολική καμπύλη λεπίδα. Ακόμη και η κατοχή σας κάνει να νιώσετε τη σκοτεινή ουσία της.',
      pl: 'Diabolicznie zakrzywione ostrze. Nawet trzymanie go sprawia, że czujesz jego ciemną esencję.',
      ht: 'Lam dyabolik koube. Menm kenbe li fè ou santi ou li nan sans fè nwa.',
      it: 'Lama diabolica curva. Anche tenerlo ti fa sentire la sua essenza oscura.',
      cs: 'Diabolská zakřivená čepel. I když to držíte, cítíte jeho temnou podstatu.',
      ja: '悪魔のような湾曲した刃。それを持っていてもあなたはその暗い本質を感じさせます。',
      sv: 'Djävulskt krökt blad. Även hålla det får dig att känna sin mörka kärna.',
      ko: '악마 모양의 곡선 칼날. 그것을 들고 있어도 당신은 어둠의 본질을 느낄 수 있습니다.',
      ro: 'Lamă curbată diabolic. Doar ținând-o poți să-i simți esența întunecată.',
      tr: 'Kavisli şeytani kılıç. Karanlık özünü sadece tutarak bile hissedebilirsiniz.',
      da: 'Diabolisk buet blad. Selv at holde det får dig til at føle sin mørke essens.'
    }
  },

  {
    name       : {$$: 'Ghastly Scimitar' },
    description: {
      en: 'A cold-looking blade with a burning hot edge.',
      ru: 'Холодный клинок с горячим краем',
      es: 'Una espada que parece helada con un borde caliente y feroz.',
      de: 'Eine kalt aussehende Klinge mit einer brennend heißen Scheibe.',
      fr: 'Une lame qui semble froide, mais avec un bord brûlant.',
      hi: 'जलती हुई गर्म धार के साथ ठंडा दिखने वाला ब्लेड',
      pt: 'Uma lâmina de aspecto frio com uma borda quente a arder.',
      nl: 'Een koud uitziend mes met een brandende hete rand.',
      tl: 'Isang malamig na nakikitang talim na may mainit na gilid',
      bg: 'Студено острие с горещ ръб',
      el: 'Μια λεπίδα με κρύα εμφάνιση με καυτή καυτή άκρη',
      pl: 'Zimno wyglądające ostrze z palącą się krawędzią.',
      ht: 'Yon lam frèt kap ak yon boule kwen cho',
      it: 'Una lama dall\'aspetto freddo con un bordo caldo che brucia.',
      cs: 'Chladně vypadající čepel s hořící horkou hranou',
      ja: '燃えるようなホットエッジを備えた寒さに見えるブレード',
      sv: 'Ett kallt blad med en brinnande het kant',
      ko: '불타는 뜨거운 가장자리가있는 차가운 모양의 날',
      ro: 'O lamă cu aspect rece și o margine ce arde fierbinte.',
      tr: 'Yanan, sıcak kenarlı, soğuk görünümlü bir kılıç.',
      da: 'Et koldt klinge med en brændende varm kant.'
    }
  },

  {
    name       : {$$: 'Knight\'s Greatsword'},
    description: {
      en: 'Cylindrical sword stolen from an ancient king. Cutting capability is questionable.',
      ru: 'Цилиндрический меч украден у древнего короля. Возможность разрезки сомнительна.',
      fr: 'Epée cylindrique volée à un ancien roi. Sa capacité à trancher reste à débattre.',
      es: 'Espada cilíndrica robada a un antiguo rey. La capacidad de corte es cuestionable.',
      de: 'Zylindrisches Schwert, das einem alten König gestohlen wurde. Die Schneidfähigkeit ist fragwürdig.',
      hi: 'एक प्राचीन राजा से चुरायी हुई गोल तलवार। काटने की क्षमता पर संदेह है।',
      pt: 'Espada cilíndrica roubada de um antigo rei. A capacidade de corte é questionável.',
      nl: 'Cilindrisch zwaard gestolen van een oude koning. Het snijvermogen is twijfelachtig.',
      tl: 'Ninakaw na tabak na ninakaw mula sa isang sinaunang hari. Ang pagputol ng kakayahan ay kaduda-dudang.',
      bg: 'Цилиндричен меч, откраднат от древен цар. Способността за рязане е под въпрос.',
      el: 'Κυλινδρικό σπαθί κλεμμένο από αρχαίο βασιλιά. Η ικανότητα κοπής είναι αμφισβητήσιμη.',
      pl: 'Cylindryczny miecz skradziony starożytnemu królowi. Zdolność cięcia jest wątpliwa.',
      ht: 'Silendrik nepe yo vòlè li soti nan yon wa ansyen. Koupe kapasite se dout.',
      it: 'Spada cilindrica rubata da un antico re. La capacità di taglio è discutibile.',
      cs: 'Válcový meč ukradl starému králi. Schopnost řezání je sporná.',
      ja: '古代の王から盗まれた円筒形の刀。切断能力は疑問です。',
      sv: 'Cylindriskt svärd stulet från en gammal kung. Klippkapacitet är ifrågasättande.',
      ko: '고대의 왕이 원통형 칼을 훔쳤다. 절단 능력에 의문의 여지가 있습니다.',
      ro: 'Sabie cilindrică furată de la un rege antic. Capabilitatea de tăiere este discutabilă.',
      tr: 'Eski bir kraldan çalınan silindirik kılıç. Keskinliği tartışılabilir.',
      da: 'Cylindrisk sværd stjålet fra en gammel konge. Klippeevne er tvivlsom.'
    }
  },

  {
    name       : {$$: 'King\'s Rapier' },
    description: {
      en: 'A blade wielded by only the most skillful knights.',
      ru: 'Клинок, которым владеют только самые умелые рыцари',
      es: 'Una espada blandida sólo por los caballeros más hábiles.',
      fr: 'Une lame maniée par les plus grands chevaliers.',
      de: 'Eine Klinge, die nur von den geschicktesten Rittern geführt wird.',
      hi: 'सबसे कुशल योद्धा ही इसे चला सकते है।',
      pt: 'Uma lâmina empunhada apenas pelos cavaleiros mais habilidosos.',
      nl: 'Een zwaard dat alleen door de meest bekwame ridders wordt gedragen.',
      tl: 'Ang isang talim na ginagamit lamang ng mga pinaka-mahusay na Knights.',
      bg: 'Острие, притежавано само от най-умелите рицари.',
      el: 'Μια λεπίδα που κυριαρχεί μόνο από τους πιο επιδέξιους ιππότες.',
      pl: 'Ostrze, którym posługują się tylko najbardziej uzdolnieni rycerze.',
      ht: 'Yon lam itilize nan sèlman kavalye yo ki pi abil.',
      it: 'Una lama impugnata solo dai cavalieri più abili.',
      cs: 'Čepel ovládaná jen nejkvalifikovanějšími rytíři.',
      ja: '最も熟練した騎士だけが装備した刀身。',
      sv: 'Ett blad som varar av endast de mest skickliga riddarna.',
      ko: '가장 숙련 된 기사들만이 휘두르는 칼날.',
      ro: 'O lamă mânuită doar de cei mai pricepuți cavaleri.',
      tr: 'Sadece en yetenekli şövalyeler tarafından kullanılan bir kılıç.',
      da: 'Et kniv varet af kun de mest dygtige riddere.'
    }
  },

  {
    name       : {$$: 'Void Blade' },
    description: {
      en: 'Powerful masterpiece brought from the abysses of the underworld.',
      ru: 'Мощный шедевр, принесенный из бездны подземного мира.',
      es: 'Una poderosa obra maestra traída de los abismos del inframundo.',
      fr: 'Puissant chef-d\'oeuvre apporté des abysses du monde souterrain.',
      de: 'Ein kraftvolles Meisterwerk aus den Abgründen der Unterwelt.',
      hi: 'पाताल से लायी गयी शक्तिशाली श्रेष्ठ रचना।',
      pt: 'Poderosa obra-prima trazida dos abismos do submundo.',
      nl: 'Krachtig meesterwerk verkregen uit de afgronden van de onderwereld.',
      tl: 'Makapangyarihang obra maestra na dinala mula sa abysses ng underworld.',
      bg: 'Мощен шедьовър, донесен от пропастите на подземния свят.',
      el: 'Ισχυρό αριστούργημα από τις άβυσσες του κάτω κόσμου.',
      pl: 'Potężne arcydzieło przywiezione z otchłani podziemnego świata.',
      ht: 'Pwisan chèf pote soti nan abis yo nan mò yo ye a.',
      it: 'Potente capolavoro portato dagli abissi degli inferi.',
      cs: 'Mocné mistrovské dílo přinesené z propastí podsvětí.',
      ja: '強力な傑作は、暗黒街の窮地からもたらされました。',
      sv: 'Kraftfullt mästerverk som tagits från underjordens avgrundar.',
      ko: '지하 세계의 무덤에서 가져온 강력한 걸작.',
      ro: 'O capodoperă puternică adusă din abisurile lumii de dincolo.',
      tr: 'Yeraltı dünyasının çatlaklarından getirilen güçlü bir başyapıt.',
      da: 'Kraftigt mesterværk bragt fra undergrundens afgrund.'
    }
  },

  {
    name       : {$$: 'Zerstörer' },
    description: {
      en: 'Mysterious pink sword. Engravings say "Mächtig Zerstörer".',
      ru: 'Таинственный розовый меч. Гравюры говорят "Mächtig Zerstörer".',
      fr: 'Une mystérieuse épée rose. Sur les gravures, nous pouvons lire: «Mächtig Zerstörer».',
      es: 'Una misteriosa espada rosa. Los grabados dicen "Mächtig Zerstörer".',
      de: 'Ein mysteriöses rosa Schwert. Gravuren sagen "Mächtig Zerstörer".',
      hi: 'रहस्यमयी गुलाबी तलवार। इस पर की गयी नक्काशी कहती है "मैशतिग ज़ेर्सटोरर। "',
      pt: 'Espada rosa misteriosa. As gravuras dizem "Mächtig Zerstörer".',
      nl: 'Mysterieus roze zwaard. Gravures lezen "Mächtig Zerstörer".',
      tl: 'Mahiwagang pink na tabak. Engravings sabihin "Mächtig Zerstörer".',
      bg: 'Тайнственият розов меч. Гравюрите казват "Mächtig Zerstörer".',
      el: 'Μυστηριώδες ροζ σπαθί. Χαρακτικά λένε "Mächtig Zerstörer".',
      pl: 'Tajemniczy różowy miecz. Ryciny mówią, że "Mächtig Zerstörer".',
      ht: 'Misterye nepe woz. Gravure di "Mächtig Zerstörer".',
      it: 'Misteriosa spada rosa. Incisioni di "Mächtig Zerstörer".',
      cs: 'Tajemný růžový meč. Rytiny říkají "Mächtig Zerstörer".',
      ja: '不思議なピンクの刀彫刻は「MächtigZerstörer」と言います。',
      sv: 'Mystiskt rosa svärd. Graveringar säger "Mächtig Zerstörer".',
      ko: '신비한 핑크색 칼. 조각은 "Mächtig Zerstörer""라고합니다.',
      ro: 'Misterioasa sabie roz. Gravurile spun "Mächtig Zerstorer".',
      tr: 'Gizemli, pembe bir kılıç. Kazınmış kelimeler: "Mächtig Zerstörer".',
      da: 'Mystisk rosa sværd. Graveringer siger "Mächtig Zerstörer".'
    }
  },

  {
    name       : {$$: 'Hearteater' },
    description: {
      en: 'Devours living tissue as it plunges its way into the thick muscle of your foes beating heart.',
      ru: 'Пожирает живую ткань, проникая через бьющиеся сердца ваших врагов',
      es: 'Devora el tejido vivo a medida que se adentra en el grueso músculo del corazón de tus enemigos.',
      de: 'Verschlingt lebendes Gewebe, während es sich in den dicken Muskel deiner Feinde stürzt und das Herz schlägt.',
      fr: 'Dévore les tissus vivants alors qu\'elle plonge dans les muscles épais du cœur battant de vos ennemis.',
      hi: 'दुश्मनों के धड़कते दिल की मोटी मांसपेशियों में घुसते घुसते मांस-तंतुओं को खाते जाती है।',
      pt: 'Devora o tecido vivo à medida que mergulha no músculo espesso dos seus inimigos que batem no coração.',
      nl: 'Verslindt levend weefsel als het zich een weg baant in de dikke spier van het kloppende hart van je vijanden.',
      tl: 'Nagmumula ng tisyu na nabubuhay habang nilusob nito ang makapal na kalamnan ng iyong mga kaaway na matalo ang puso.',
      bg: 'Поглъща жива тъкан, тъй като потъва в гъстата мускулатура на биещото сърце на враговете ви.',
      el: 'Καταβρέχει ζωντανό ιστό, καθώς βυθίζει το δρόμο του στο παχύ μυ των εχθρών σας που κτυπά την καρδιά.',
      pl: 'Pożera żywą tkankę, która zagłębia się w gęste mięśnie bijącego serca przeciwnika.',
      ht: 'Devore tisi vivan jan li plonje fason li nan nan misk epè nan lènmi ou bat kè.',
      it: 'Divora il tessuto vivente mentre si insinua nel muscolo spesso dei tuoi nemici che battono il cuore.',
      cs: 'Pohlcuje živou tkáň, když se vrhá do tlustého svalu vašich nepřátel, jak bije srdce.',
      ja: 'それは心臓を鼓動させるあなたの敵の厚い筋肉にその道を突入するにつれて生きている組織を貪ります。',
      sv: 'Förhinder levande vävnad som det pungar sig in i den tjocka muskeln av dina fiender som slår hjärta.',
      ko: '심장을 때리는 적의 두꺼운 근육 속으로 빠져들면서 조직을 파괴합니다.',
      ro: 'Devorează țesutul viu în timp ce-și face loc în mușchiul gros al inimii bătânde a dușmanilor tăi.',
      tr: 'Bu kılıç düşmanın kalbine girerken dokuları yok eder.',
      da: 'Uddanner levende væv, da det plunges vej ind i dine fjenders tykke muskel, der slår hjerte.'
    }
  },

  {
    name       : {$$: 'Demonedge' },
    description: {
      en: 'A blade said to be broken in the past and forged anew by the fabled demons of these magnificent lands.',
      de: 'Der die Klinge in der Vergangenheit gebrochen werden und von den sagenumwobenen Dämonen mag diese Länder geschmiedet aufs Neue.',
      ru: 'Поговаривают, этот клинок был сломан в прошлом и создан вновь легендарными демонами этих великолепных земель.',
      pt: 'Uma lâmina que foi quebrada no passado e forjada de novo pelos demónios lendários destas magníficas terras.',
      it: 'Una lama che si diceva essere rotta in passato e forgiata di nuovo dai demoni leggendari di queste magnifiche terre.',
      nl: 'Een lemmet zou in het verleden gebroken zijn en opnieuw gesmeed zijn door de legendarische demonen van dit prachtige aanlanden.',
      pl: 'Ostrze, które podobno zostało złamane w przeszłości i wykute na nowo przez legendarne demony tych wspaniałych ziem.',
      fr: 'Une lame que l\'on disait cassée dans le passé et forgée à nouveau par les légendaires démons de ces terres magnifiques.',
      es: 'Una espada que se dice que fue rota en el pasado y forjada de nuevo por los demonios legendarios de estas magníficas tierras.',
      bg: 'Острие, което се казвало, че е било разрушено в миналото и изковано отново от легендарните демони на тези великолепни земи.',
      tl: 'Ang isang talim ay sinabi na pinaghiwa-hiwalay sa nakaraan at hinubog muli ng mga masayang demonyo ng mga kahanga-hangang lupain na ito',
      cs: 'Čepel, která měla být v minulosti zlomena a znovu zformována legendárními démony těchto nádherných zemí.',
      el: 'Μια λεπίδα που λέγεται ότι έχει σπάσει στο παρελθόν και σφυρηλατηθεί εκ νέου από τους θρυλικούς δαίμονες αυτών των μαγευτικών χωρών.',
      ht: 'Yon lam te di ke yo dwe kase nan tan lontan an ak fòje yon lòt fwa pa move lespri yo selèb nan peyi sa yo manyifik.',
      hi: 'एक तलवार जो अतीत में कभी टूट गई थी, उसे इस महान धरती के मायावी राक्षसों ने नये से बनाया।',
      ko: '블레이드는 과거에 부서지고이 장엄한 땅의 전설적인 악마에 의해 새롭게 단련되었다고 말했습니다.',
      ja: '刃は過去に壊れたと言われて、これらの壮大な土地の伝説的な悪魔によって新しく鍛造されました。',
      da: 'Et blad sagde at være brudt i fortiden og smedet på ny af de fantastiske dommere i disse storslåede lande.',
      sv: 'Ett blad sägs vara brutet i det förflutna och smidda igen av de fantastiska demonerna i dessa magnifika länder.',
      ro: 'O lamă ce se spune că ar fi fost ruptă în trecut și făurită din nou de către demonii legendari ai acestor tărâmuri magnifice.',
      tr: 'Söylenilene göre bu kılıç geçmişte kırılmış ve bu görkemli diyarların efsanelerinde adı geçen iblisler tarafından tekrar dövülmüş.'
    }
  },

  {
    name       : {$$: 'Excalibur' },
    description: {
      en: 'We were told it was pulled from stone. Still can\'t find the stone.',
      ru: 'Нам сказали, что он был извлечен из камня. Все еще не можем найти камень.',
      es: 'Se dice que era tomado de una roca. ¿Dónde está la roca?',
      de: 'Es kann Dämonen besiegen, aber keine Engel.',
      fr: 'La légende nous raconte qu\'elle fut extraite d\'une pierre. On n\'a toujours pas trouvé la pierre.',
      hi: 'कहते है इसे एक पत्थर से निकला गया था। वो पत्थर आज तक नहीं मिला।',
      pt: 'Disseram-nos que foi tirada da pedra. Ainda não conseguimos encontrar a pedra.',
      nl: 'Ons werd verteld dat het uit steen werd getrokken. Kan de steen nog steeds niet vinden.',
      tl: 'Sinabihan kami na mahila ito mula sa bato. Hindi pa rin mahanap ang bato.',
      bg: 'Казаха ни, че е изтеглен от камък. Все още не мога да открия камъка.',
      el: 'Μας είπαν ότι τραβήχτηκε από πέτρα. Ακόμα δεν μπορείς να βρεις την πέτρα.',
      pl: 'Powiedziano nam, że został wycišgnięty z kamienia. Wciąż nie można znaleźć kamienia.',
      ht: 'Nou te di li te rale nan wòch. Toujou kapab jwenn wòch la.',
      it: 'Ci è stato detto che è stato estratto dalla pietra. Ancora non riesco a trovare la pietra.',
      cs: 'Bylo nám řečeno, že to bylo vytaženo z kamene. Stále nemůžu najít kámen.',
      ja: 'それは石から引き出されたと言われました。それでも、その石を見つけることはできません。',
      sv: 'Vi fick höra att det drogs från sten. Fortfarande kan inte hitta stenen.',
      ko: '우리는 돌에서 꺼냈다 고 들었다. 아직도 돌을 찾을 수 없습니다.',
      ro: 'Ni s-a spus că a fost scoasă din piatră. Piatra încă nu a fost găsită.',
      tr: 'Bu kılıcın bir taştan çekildiği söylendi. Ama taşı bulamıyoruz.',
      da: 'Vi fik at vide, at det blev trukket fra sten. Stadig kan ikke finde stenen.'
    }
  },

  {
    name       : {$$: 'Harbinger' },
    description: {
      en: 'This weapon brings about the coming of a new age.',
      ru: 'Это оружие вызывает наступление новой эры.',
      es: 'Esta espada trae la llegada de una nueva era.',
      de: 'Diese Waffe bringt das Kommen eines neuen Zeitalters mit sich.',
      fr: 'Cette arme provoque l\'avènement d\'une nouvelle ère.',
      hi: 'होने वाली है नए युग की शुरुआत।',
      pt: 'Esta arma traz o advento de uma nova era.',
      nl: 'Dit wapen brengt de komst van een nieuw tijdperk met zich mee.',
      tl: 'Ang armas na ito ay nagdudulot ng pagdating ng isang bagong edad.',
      bg: 'Това оръжие води до идването на нова епоха.',
      el: 'Αυτό το όπλο επιφέρει την έλευση μιας νέας εποχής.',
      pl: 'Ta broń powoduje nadejście nowej ery.',
      ht: 'Sa a zam pote sou vini nan yon nouvo laj.',
      it: 'Quest\'arma porta all\'avvento di una nuova era.',
      cs: 'Tato zbraň přináší příchod nového věku.',
      ja: 'この武器は新しい時代の到来をもたらします。',
      sv: 'Detta vapen ger upphov till en ny ålder.',
      ko: '이 무기는 새로운 시대를 열어줍니다.',
      ro: 'Această armă aduce începutul unei noi ere.',
      tr: 'Bu silah yeni bir çağın şafağını getiriyor.',
      da: 'Dette våben giver anledning til en ny tids alder.'
    }
  }

]
