export default {
  // The class name
  name: {
    en: 'Archer',
    sv: 'Bågskytt',
    ru: 'Лучник',
    ko: '궁수',
    es: 'Arquero',
    fr: 'Archer',
    pt: 'Arqueiro',
    de: 'Bogenschütze',
    tr: 'Okçu',
    nl: 'Boogschutter',
    hi: 'धनुरधारी',
    it: 'Arciere',
    ht: 'Archer',
    tl: 'Archer',
    pl: 'Łucznik',
    ro: 'Arcaș',
    cs: 'Lukostřelec',
    el: 'Τοξότης',
    bg: 'Стрелец',
    ja: '射手',
    da: 'Bueskytte',
    zh: '弓箭手',
    hu: 'Vadász'
  },

  // Class description, visible during character creation
  description: {
    en: 'Archers deal high single target damage and bursty Area of Effect damage. A good archer will always keep their distance and snipe enemies from afar.',
    sv: 'Bågskytten gör stor skada på enskilda enheter, och även stor areell skada. En god bågskytt prickskjuter alltid sina fiender på avstånd.',
    ru: 'Лучники наносят высокий урон по одиночной цели и взрывной урон по области. Хороший лучник всегда будет держать дистанцию и отстреливать врагов издалека.',
    ko: '궁수는 높은 단일 타겟 데미지와 버스트 에어리어 피해를줍니다. 좋은 궁수는 먼 거리에서 항상 적을 도일 당합니다.',
    es: 'Los arqueros hacen daño increíble con sus flechas y pueden disparar muchos flechos a una vez con daño explosivo. La estregia mejor es evitar los enemigos y atacar a lo lejos.',
    fr: 'Les archers peuvent infliger des dégâts élevés sur une cible précise et des dégâts de zone importants. Un bon archer garde toujours ses distances et élimine ses ennemis de loin.',
    pt: 'Arqueiros causam danos altos a um único alvo e danos na sua Área de Efeito. Um bom arqueiro sempre manterá sua distância e dispara sobre os inimigos de longe.',
    de: 'Bogenschützen verursachen hohen Einzelzielschaden und Berstenden Wirkungsbereich. Ein guter Bogenschütze wird immer Abstand halten und Feinde aus der Ferne bekämpfen.',
    nl: 'Boogschutters veroorzaken hoge schade op een enkel doelwit en op een groter gebied middels frequente schoten. Een goede boogschutter zal altijd zijn afstand bewaren en vijanden vanuit de verte beschieten.',
    tr: 'Okçular tekli hedefe yüksek zarar verir ve aralıklı alan etkili hasar verir. İyi bir okçu her zaman mesafesini korur ve hedeflerini uzaktan avlar.',
    hi: 'धनुरधारी उच्च एकल लक्ष्य क्षति और प्रभाव क्षति के त्वरित क्षत्रुऔ से निपटते हैं। एक अच्छा धनुरधारी हमेशा अपनी दूरी बनाए रखेगा और दुश्मनों को दूर से ही मार देगा।',
    tl: 'Ang mga mamamana ay nakikitungo sa mataas na solong target na pinsala at pagkalanta ng Area of Effect na pinsala. Ang isang mahusay na mamamana ay palaging panatilihin ang kanilang distansya at labuyo kaaway mula sa kalayuan.',
    it: 'Gli arcieri infliggono danni da bersaglio singolo e danno da area di effetto. Un buon arciere manterrà sempre le distanze e tirerà i nemici da lontano.',
    ht: 'Banza kontra segondè sib domaj segondè ak pete Zòn domaj nan efè. Yon bon Archer ap toujou kenbe distans yo ak kritike lènmi soti byen lwen.',
    pl: 'Łucznicy zadają wysokie obrażenia pojedynczego celu i zadają duże obrażenia obszarowe. Dobry łucznik zawsze będzie trzymał dystans i ostrzeliwuje wrogów z daleka.',
    ro: 'Arcașii cauzează daune mari unei ținte unice și au o arie de acțiune largă. Un arcaș bun va menține mereu o distanță considerabilă față de inamici și îi va ataca de la distanță.',
    cs: 'Lukostřelci se vypořádávají s vysokým poškozením jediného cíle a zničením. Dobrý lukostřelec bude vždy držet jejich vzdálenost a ostřelovat nepřátele z dálky.',
    el: 'Οι τοξότες ασχολούνται με υψηλές ζημιές στο στόχο και τις ζημιές που προκαλούν την περιοχή της επίδρασης. Ένας καλός τοξότης θα κρατήσει πάντα την απόσταση τους και θα καταστρέψει τους εχθρούς από μακριά.',
    bg: 'Стрелците нанасят високи щети на единични цели и разрушаващи атаки на голяма площ. Добрият стрелец винаги ще се държи на дистанция от врагове си.',
    ja: '射手は高い単一ターゲットダメージと突発的なエリアダメージを与えます優れた射手は常に距離を保ち、遠くから敵を狙撃します。',
    da: 'Bueskytter beskæftiger sig med højt enkelt målsskader og burste områder med effekt skader. En god bueskytter vil altid holde afstanden og snipe fjender langt væk.',
    zh: '弓箭手會對單一目標造成高額傷害而且也有著爆發區域傷害。 一個專業的弓箭手會與敵人保持距離，並在遠處進行狙擊。',
    hu: 'A vadászok kiválóan képesek koncentrálni erejüket egyetlen célpontra, és darabosan több ellenfélre is kifejthetik hatásukat. Egy jó lövész mindig távolságot tart, és a nyilait a távolból zúdítja áldozatára.'
  }
}
