export default {
  // The class name
  name: {
    en: 'Mage',
    ru: 'Маг',
    de: 'Magier',
    sv: 'Magiker',
    es: 'Mago',
    hi: 'जादूगर',
    fr: 'Mage',
    ko: '마법사',
    pt: 'Mago',
    tr: 'Büyücü',
    nl: 'Magiër',
    it: 'Mago',
    ht: 'Mage',
    tl: 'Mage',
    pl: 'Mag',
    cs: 'Kouzelník',
    el: 'Mage',
    bg: 'Магьосник',
    ja: 'メイジ',
    ro: 'Magician',
    da: 'Troldmand',
    zh: '魔法師',
    hu: 'Mágus'
  },

  // Class description, visible during character creation
  description: {
    en: 'Mages deal very heavy large scale Area of Effect damage, while also providing utility through slowing targets with their ice based magic.',
    ru: 'Маги наносят большой урон по области, а так же приносят пользу благодаря замедлению целей своей магией льда.',
    sv: 'Magiker åsamkar förödande areell skada och kan även sakta ned motståndare med sin ismagi.',
    de: 'Magier verursachen sehr großen Flächenschaden und sind gleichzeitig nützlich, da sie Ziele mit ihrer auf Eis basierenden Magie verlangsamen.',
    es: 'Los magos usan los poderes del invierno para ralentizar y hacer daño massivo a los enemigos.',
    hi: 'जादूगर बड़े स्तर पर एक गोल ईलाके में ज़ोरदार क्षति पहुँचा सकते है और साथ ही साथ अपने बर्फ़ीले जादू से दुश्मनो को धीमे भी कर सकते है।',
    fr: 'Les Mages infligent de très lourds dégâts à grande échelle grâce à leurs dégâts de zone tout en pouvant être utiles en ralentissant les cibles grâce à leur magie de glace.',
    ko: '마법사는 매우 큰 무거운 대 면적의 효과 피해를 처리하는 동시에 얼음 기반의 마법으로 대상의 속도를 늦추어 유틸리티를 제공합니다.',
    pt: 'Os magos causam danos muito pesados em grande escala na sua Área de Efeito, ao mesmo tempo que também fornecem utilidade através da diminuição da velocidade dos alvos com a sua magia baseada em gelo.',
    nl: 'Magiërs geven zeer zware, grootschalige schade op een groot oppervlak, terwijl ze ook tegenstanders kunnen bevriezen met hun ijs gebaseerde magie.',
    tr: 'Büyücüler ağır alan etkili hasar verirken buz büyüleriyle hedeflerini yavaşlatır.',
    it: 'I maghi infliggono danni di Area of Effect molto pesanti su larga scala, fornendo anche utilità attraverso il rallentamento degli obiettivi con la loro magia basata sul ghiaccio.',
    ht: 'Maj kontra gwo echèl gwo Zòn domaj nan efè, pandan y ap tou bay sèvis piblik nan ralanti sib ak majik ki baze sou glas yo.',
    tl: 'Mages makitungo ng napakabigat na malaking sukat ng Area of Effect na pinsala, habang nagbibigay din ng utility sa pamamagitan ng pagbagal ng mga target sa kanilang yelo batay magic.',
    pl: 'Magowie zadają bardzo duże obrażenia obszarowe na dużą skalę, dostarczając jednocześnie narzędzia poprzez spowalnianie celów za pomocą magii opartej na lodzie.',
    cs: 'Mágové se zabývají velmi těžkým rozsahem škod způsobených rozsáhlým rozsahem a zároveň poskytují pomůcku prostřednictvím zpomalení cílů s jejich kouzlem založeným na ledu.',
    el: 'Οι Mages ασχολούνται με πολύ βαρύς μεγάλης κλίμακας ζημιές Περιοχή Εφέ ενώ παράλληλα παρέχουν χρησιμότητα μέσω της επιβράδυνσης των στόχων με τη μαγεία που βασίζεται στον πάγο.',
    bg: 'Маговете се занимават с много силни магии за щета по многобройни цели, като същевременно осигуряват помощ чрез забавяне на целите с помощта на ледената си магия.',
    ja: '魔術師は、非常に重い大規模な効果領域ダメージを与えながら、氷をベースにした魔法でターゲットを減速させることで有用性も提供します。',
    ro: 'Magicienii cauzează daune considerabile la scară largă, fiind în același timp folositori prin încetinirea țintelor cu ajutorul magiei lor pe bază de gheață.',
    da: 'Troldmænd skader i stor grad meget areal skade mens de også gør nytte ved at sænke farten på monstre ved at bruge is-baseret magi.',
    zh: '魔法師會釋放大範圍的區域傷害，同時還會利用冰屬性魔法減慢目標。',
    hu: 'A Mágusok tudnak egy nagy területen belül pusztítani, de támogatást is nyújthatnak, ha ellenségeiket fagymágiával lelassítják.'
  }
}
