export default {
  // The class name
  name: {
    en: 'Warrior',
    de: 'Krieger',
    sv: 'Krigare',
    ru: 'Воин',
    es: 'Guerrero',
    fr: 'Guerrier',
    hi: 'योधा',
    ko: '전사',
    pt: 'Guerreiro',
    tr: 'Savaşçı',
    nl: 'Krijger',
    it: 'Guerriero',
    ht: 'Gèrye',
    pl: 'Wojownik',
    cs: 'Bojovník',
    tl: 'Mandirigma',
    ja: '戦士',
    el: 'Πολεμιστής',
    bg: 'Войн',
    ro: 'Războinic',
    da: 'Kriger',
    zh: '戰士',
    hu: 'Harcos'
  },
  // Class description, visible during character creation
  description: {
    en: 'Warriors are built to tank more monsters than any other class by having high defense through equipment (Shields) and strong defensive buffs.',
    sv: 'Krigarnas stryktåliga utrustning (Sköldar) och starka försvarsbuffar gör att de tål mer än någon annan klass.',
    ru: 'Воины построены для того, чтобы танковать больше монстров чем любой другой класс, имея хорошую защиту с помощью снаряжения (Щита) и сильных защитных усилений.',
    de: 'Krieger sind so gebaut, dass sie mehrere Monster auf einmal aushalten können, da sie eine hohe Verteidigungrate durch Ausrüstung (Schilde) und starke defensive Buffs haben.',
    es: 'Guerreros son los tanques de la guerra, Guerreros luchan para el honor y gloria de la batalla. Ellos pueden aguantar una gran cantidad de daño de todas las otras clases con sus escudos y buffs de defensa.',
    fr: 'Les guerriers sont conçus pour encaisser plus de monstres que n\'importe quelle autre classe en ayant une défense élevée grâce à leurs équipements (Boucliers) et des buffs défensifs puissants.',
    hi: 'सर्वश्रेष्ठ रक्षा उपकरण और ताक़तवर कवच के उपयोग से सारी श्रेणियो में योधा सबसे अधिक मार रोक सकते हैं।',
    ko: '전사들은 장비 (방패)와 강력한 방어 숙련자를 통해 높은 방어력을 가짐으로써 다른 클래스보다 더 많은 몬스터를 견딜수 있습니다.',
    pt: 'Os guerreiros são feitos de forma a resistir a mais monstros do que qualquer outra classe, tendo alta defesa através de equipamentos (Escudos) e fortes buffs defensivos.',
    nl: 'Krijgers zijn bedoeld om meer schade op te vangen dan enig andere klasse via middel van bepaalde verdedigingsuitrusting (Schilden) en sterke defensieve betoveringen.',
    tl: 'Ang mga Warrior ay binuo upang tangke ng higit pang mga monsters kaysa sa anumang iba pang mga klase sa pamamagitan ng pagkakaroon ng mataas na pagtatanggol sa pamamagitan ng kagamitan (Shields) at malakas na defensive buffs.',
    tr: 'Savaşçılar güçlü defansif ekipmanları (Kalkanlar) ve defansif güçlendirmeleri ile canavarları diğer sınıflardan daha çok üstüne çeker.',
    it: 'I Guerrieri sono costruiti per accumulare più mostri di qualsiasi altra classe, avendo un\'alta difesa tramite equipaggiamento (Scudi) e forti abilità difensive.',
    ht: 'Gèrye yo bati kenbe tèt avè plis domaj pase tout lòt klas yo atravè defans segondè nan ekipman yo (Sköld) ak tan defans fò.',
    pl: 'Wojownicy są w stanie walczyć z większą ilością potworów niż jakakolwiek inna klasa poprzez posiadanie wysokiego poziomu obrony dzięki wyposażeniu (Tarcze) i silnych buforów obronnych.',
    cs: 'Bojovníci jsou stavěni k tanku více monster než nějaká jiná třída tím, že má vysokou obranu přes vybavení (Štíty) a silné obranné nadšence.',
    ja: '戦士は装備品（盾）と強力な防御バフを通して高い防御力を持つことによって他のどのクラスよりも多くのモンスターを戦うために建てられました。',
    el: 'Οι πολεμιστές είναι κατασκευασμένοι για να δεξαμενώνουν περισσότερα τέρατα από οποιαδήποτε άλλη τάξη έχοντας υψηλή άμυνα μέσω εξοπλισμού (Ασπίδες) και ισχυρών αμυντικών buffs.',
    bg: 'Воините са построени да задържат повече чудовища от всеки друг клас, като имат висока защита чрез оборудване (Щитове) и силни защитни способности.',
    ro: 'Războinicii sunt făcuți pentru a atrage mai mulți monștrii decât orice altă clasă, având o defensivă foarte ridicată datorită echipamentului (Scuturi) și buff-uri defensive puternice.',
    da: 'Krigere er bygget til at tanke flere monstre end nogen anden klasse ved at have højt forsvar via udstyr (Skjolde) og stærke defensive buffs.',
    zh: '通過裝備（盾牌）和強大的防守增益效果，戰士可以打敗比其他角色更多的怪物。',
    hu: 'A harcosok hatalmas védekező képességükre és erejükre támaszkodva magukra vállalhatják a közelharcot számos ellenséggel, hogy a csapatjuk többi tagja zavartalanul használhassa mágiáját.'
  }
}
